### ISSUE TITLE
Fix UI typo for setting the logger level

### ISSUE THREAD

**Issue by Tzahi12345** [Tzahi12345/YoutubeDL-Material#100]
**Prelude:** I'd like to get people more involved with this project coding-wise. The suggestions are great! But long-term, having multiple people with some codebase knowledge would be ideal (and helpful in getting the list of issues down, this one included)

**Problem:** In the `Advanced` tab in the settings, there's a dropdown to select the logger level. The dropdown is mislabeled, though. Instead of saying "Select a logger level", it says "Select a downloader" which is not good!

To fix it, you have to change the label for the dropdown. You can find this in the `settings` component, particularly in the `settings.component.html` file. The rest is fairly easy to figure out, if you have any issues trying to solve it feel free to ask!

Screenshot of the problem:
![](https://i.imgur.com/xeL57FW.png)

If no one gets to this in the next month or so (about how long I expect 4.1 to take until release), I'll go ahead and do it myself. But I really do want your help on this! Again, let me know if any issues come up trying to fix it.

**Comment by arrudaricardo** [comment]
@Tzahi12345 can I work on that?

**Comment by Tzahi12345** [comment]
Yes! I'll have it assigned.
