### ISSUE TITLE
[FEATURE] user management

### ISSUE THREAD

**Issue by sinawic** [Tzahi12345/YoutubeDL-Material#1005]
hey,
great tool.
+ can we have a user management option in the app. like we define the admin user through env vars
++ also admin can create and manage users who can only view their own downloaded files and stuff
+++ user registeration would be a great option to have which can be an option that can be switched on/off like with env vars.

thanks btw

**Comment by Tzahi12345** [comment]
There is some basic user management if you enable multi-user mode in the settings. Does everything you're talking about, is there something I'm missing?

If you enable it, the Users tab will become available where you can edit/add users, enable/disable registration, create roles, etc: 
![image](https://github.com/Tzahi12345/YoutubeDL-Material/assets/707413/26170d38-7e61-43dc-bd9c-6c9ba7003200)
