### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sreeram-ravi** [Tzahi12345/YoutubeDL-Material#1011]
**Describe the bug**
i get "ERROR: Unable to extract uploader id" whenever i try to download any video from youtube

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
- YoutubeDL-Material version
- Docker tag: <tag> (optional)

Ideally you'd copy the info as presented on the "About" dialogue
in YoutubeDL-Material.
Error while retrieving info on video with URL https://youtu.be/SA-toN0eXM4 with the following message: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -i -o users/ravi/audio/%(title)s.%(ext)s --write-info-json --print-json --audio-quality 0 -x --audio-format mp3 --write-thumbnail --dump-json https://youtu.be/SA-toN0eXM4

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Additional context**
Add any other context about the problem here. For example, a YouTube link.

**Comment by GlassedSilver** [comment]
Please fill out the template correctly.

You're at least lacking a descriptive title (can be the error message that you get for example), the environment details like the version and if you're using docker and if so which branch and the error message actually goes into the first section.

Sorry to trouble you with the formality, but the repo is managed in an on-off manner with limited time and only few hands helping out. Putting bug reports as tidy as possible helps those who help out use their time as efficiently as possible.

**Comment by Tzahi12345** [comment]
It sounds like you're using youtube-dl, switch to yt-dlp and it should work.
