### ISSUE TITLE
[BUG] "Users" greyed out?! 

### ISSUE THREAD

**Issue by RoccoRakete** [Tzahi12345/YoutubeDL-Material#1014]
**Describe the bug**
On the web interface, the option "Users" is greyed out. Do I have to setup something different for this? 

**To Reproduce**
Go to the Web interface 

**Environment**
- YoutubeDL-Material version v4.3.2 (Docker)

Installation details:

Installed version: v4.3.2 -

  You are up to date.

Installation type: docker
Docker tag: latest
Commit hash: 13a03a7
Build date: 2023-05-27

**Comment by amenolo** [comment]
In order to enable authentication and users feature you have to first flag `Multi-user mode` option under Setting/Main:

![immagine](https://github.com/Tzahi12345/YoutubeDL-Material/assets/29974944/b6a778fd-9b38-40c5-a992-4dd43dd8889c)
