### ISSUE TITLE
Feature Idea - ability to view logs from UI

### ISSUE THREAD

**Issue by CountParadox** [Tzahi12345/YoutubeDL-Material#102]
Can we get a log section in the settings to make submitting these reports a little easier ? :D

**Comment by Tzahi12345** [comment]
Haha yes great idea! A simple "view logs" button with a dialog should do. It won't be auto updating or anything fancy like that but it will help with debugging so you don't have to go into the appdata folder.

**Comment by Tzahi12345** [comment]
This is done! See [latest commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/2998562655cdda2ccc6d5d33c227b6b5a61e53cf). You can use this feature in the latest `nightly`, or wait until the next update.

Note that the logs viewer does not periodically check for new logs, you will need to switch tabs for it to properly reload (though this can be added in quite easily if desired). Cheers!

**Preview:**
![image](https://user-images.githubusercontent.com/707413/85357087-985a1000-b4de-11ea-829f-9a6f44d7df2a.png)
