### ISSUE TITLE
[BUG]Cannot download / test download

### ISSUE THREAD

**Issue by Plex-FireWire** [Tzahi12345/YoutubeDL-Material#1021]
**Describe the bug**
I added the channels to the subscription area; I currently have 3. I do everything that seems like it would download everything or at least show some sort of check of what is missing.
(running everything in the task area, resetting the docker, adding a brand new channel, and searching for a way to trigger it)

I am unsure if this is a bug or if I'm requesting a refresh button on the subscriptions page.

**Expected behavior**
A process is being started to check the recent additions/changes to the subscription(s)

**Environment**
- YoutubeDL-Material version
- Docker tag: <tag> (optional)
- 
**Additional context**
Add any other context about the problem here. For example, a YouTube link.
I must be doing something wrong, or this is a hard-to-explain bug.

**Comment by Tzahi12345** [comment]
Can you try on the latest nightly?
