### ISSUE TITLE
[BUG] reverse proxy with nginx proxy manager

### ISSUE THREAD

**Issue by JalenMak6** [Tzahi12345/YoutubeDL-Material#1024]
I try to set up the proxy host for the page with Nginx proxy manager along with Cloudflare DNS. I do disable the HTST nosniff feature and add the all the methods mentioned like adding header for 
X-Content-Type-Options: none

  in the open issue. but when I use Safari to access it with my subdomain, it just downloaded the whole page. On Chrome, it showed me the HTML text only.

May I know how to fix this issue?

**Comment by D34DC3N73R** [comment]
This [PR](https://github.com/Tzahi12345/YoutubeDL-Material/pull/1004) should fix it. I'm guessing if you check headers, something is still adding the X-Content-Type-Options nosniff header. The PR is a single line fix, so you could try manually patching the file if you want to test it out.

**Comment by Tzahi12345** [comment]
Closing as this should be resolved.
