### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by danielstorch** [Tzahi12345/YoutubeDL-Material#1025]
Nothing more to say. Its not getting updated and doesn't work anymore?

Anyone else having this problem?

**Comment by Tzahi12345** [comment]
Not dead, just hibernating. Apologies that I haven't done any updates recently, life has gotten in the way one way or another.

I hope to get back to it soon but no guarantees. So sorry you're having issues running it, at least on my end I've used the latest tag on Docker without issues so maybe you'll have better luck there.

**Comment by Tzahi12345** [comment]
I think the latest nightly solves that problem. Also closing as I've started working on this again :)
