### ISSUE TITLE
[BUG] Retrieving info error when download any video, please help to resolve, thanks!

### ISSUE THREAD

**Issue by tokyoqiang** [Tzahi12345/YoutubeDL-Material#1028]
Recently when I download any video, it fail to download and show below error.
Then I re-installed docker, but error still exist.
Can help to check how to resolve it? Thanks a lot!

My System: Synology DSM 7.2
Installation Method: Docker

Reproduce Step
Step1. whatever youtube link I input, it doesn't search as usual, but directly show Best in Quality, like the wrong text I input;
![image](https://github.com/Tzahi12345/YoutubeDL-Material/assets/99979431/971b31e7-bf41-4520-b4f0-2f6b8831f798)

Step2. once click download, it throw out below error in 1 second
Error while retrieving info on video with URL https://www.youtube.com/watch?v=DuY-Dql_A_U with the following message: Error: Command failed with EACCES: node_modules/youtube-dl/bin/youtube-dl -o video/%(title)s.mp4 --write-info-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail --no-clean-info-json -j --dump-json http://www.youtube.com/watch?v=DuY-Dql_A_U
spawn node_modules/youtube-dl/bin/youtube-dl EACCES

**Comment by outbound** [comment]
How did you resolve this?

I'm still getting this error. I've rebuilt the stack, done the chmod that was suggested and verified that I'm using yt-dlp. 
Running 4.3.2 on Synology NAS via Docker and Portainer

**Comment by Tzahi12345** [comment]
Can you try the latest nightly? I think this is related to permissions but I could be wrong.

**Comment by outbound** [comment]
Hi there,

So I wiped the container clean, and then used Nightly. On the second try,
it's working again.

Thanks for that suggestion.

Cheers

**Comment by punkidow** [comment]
`2023-12-03T15:57:18.051Z ERROR: Failed to retrieve available formats for url: https://www.youtube.com/watch?v=RJbo2DRWXr4`

**Comment by Tzahi12345** [comment]
Figured out what's happening, put up and merged a PR which fixes this. Thanks @punkidow!

https://github.com/Tzahi12345/YoutubeDL-Material/pull/1039
