### ISSUE TITLE
Multi-user mode allows you to go 'home' instead of logging in

### ISSUE THREAD

**Issue by suckerfish** [Tzahi12345/YoutubeDL-Material#104]
If you turn on multi-user mode and attempt to access the homepage, it rightly asks you to log in. But you can get the hamburger menu on the left and go 'home' which then gives you the screen that looks like it lets you download a video. But if you try to download a video, it throws an error, likely because you aren't logged in.

**Comment by Tzahi12345** [comment]
If you use the `nightly` tag on Docker, you should see this fixed (someone addressed this exact problem [here](https://github.com/Tzahi12345/YoutubeDL-Material/issues/98) among some other issues).

Let me know if that helps!

**Comment by suckerfish** [comment]
Looks like it indeed will. Thank you!
