### ISSUE TITLE
Help: how to find back admin password?

### ISSUE THREAD

**Issue by tokyoqiang** [Tzahi12345/YoutubeDL-Material#1052]
I turned on multi-user model, and forgot the admin password, how can I find it back or reset it? Thanks!

**Comment by Tzahi12345** [comment]
Just delete the admin account and recreate it. All your videos will remain. If you're not using MongoDB, just delete this:

![image](https://github.com/Tzahi12345/YoutubeDL-Material/assets/707413/7a180de3-8d85-4177-bc9e-3d45358550fa)

If you're using MongoDB, you'll have to use a tool like MongoDBCompass, connect to your database, and delete the `admin` record in the `users` table. Hope this helps!

**Comment by tokyoqiang** [comment]
thank you so much!
