### ISSUE TITLE
Support for newer npm/node?

### ISSUE THREAD

**Issue by tunloop** [Tzahi12345/YoutubeDL-Material#1076]
On Debian 12, I was going to install manually but ran into issues with npm install. This breaks all further installation steps listed in instructions.

```
# /opt/youtubedl-material# npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'backend@1.0.0',
npm WARN EBADENGINE   required: { node: '^16', npm: '6.14.4' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
```

Is downgrade the only way to use this?

**Comment by martadinata666** [comment]
It only `WARN` and not blocking installation.

**Comment by tunloop** [comment]
> It only `WARN` and not blocking installation.

Oh, it appears that I used the zip file from the releases page instead of the repo itself. 
Why is the backend folder put out in releases?

Using the whole repo works now, thanks.

**Comment by martadinata666** [comment]
Afaik, the release zip is frontend copied to backend then the backend zipped out. *cmiiw
