### ISSUE TITLE
Can't download Reddit video

### ISSUE THREAD

**Issue by suckerfish** [Tzahi12345/YoutubeDL-Material#108]
Tried at least twice using different videos. URL = https://www.reddit.com/r/nextfuckinglevel/comments/gr72ih/cats_run_on_solar_power/

my CLI version of youtube-dl gets this fine. I just get a 'download failed' using YTDLM.

**Comment by Tzahi12345** [comment]
Good catch! I seriously thought this was fixed the last time I fixed reddit videos, but oh well. Anyways, I've updated the args for non-YT videos, and this time it seems like it's the best across the board. I'll be doing tons of testing for this next update to make sure it's in a good state when that drops.

[Here's the relevant commit.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/80f214fdde096e788f04bfef1495d06868efbfd0)

The latest `nightly` image on Docker should have this already included. Let me know if this doesn't work or if you find any other issues, thanks!
