### ISSUE TITLE
Custom args for subscriptions

### ISSUE THREAD

**Issue by magnusv0s** [Tzahi12345/YoutubeDL-Material#110]
Is this possible right now?  If not, any plans for this in the future? Love the program otherwise, have been testing it and is very nice to have a GUI to go along with youtube-dl, thanks for creating it.

**Comment by Tzahi12345** [comment]
Not possible currently, but functionality to support this is in the works. [This issue](https://github.com/Tzahi12345/YoutubeDL-Material/issues/84) has some related features, which will also be in 4.1. Since this is quite related, I can include that as part of the update. Thanks for the suggestion!

**Comment by Tzahi12345** [comment]
Done! Check out the [PR here](https://github.com/Tzahi12345/YoutubeDL-Material/pull/136) for more details. You can use the `nightly` tag on the Docker image to start using this immediately, otherwise you can wait until the next update drops. Thanks!
