### ISSUE TITLE
YoutubeDl material doesnt download a subscription.

### ISSUE THREAD

**Issue by RobustMarker** [Tzahi12345/YoutubeDL-Material#1109]
**issue**
YoutubeDl material refuses to download one channel (Linustechtips). 
The subscription feature works flawlessly for other channels (including other channels from the linustechtips group) but it is unable to download anything from linustechtips.
If I paste a video url from the channel in the download section it will download it fine in full quality but when I add the channel
to the subscription tab and set my parameters it does nothing.

Here is my config for linustechtips, the file output is the same for all the other channels its formatted for a jellyfin youtube metadata plugin.
<img width="607" alt="Screenshot 2024-04-01 at 15 50 46" src="https://github.com/Tzahi12345/YoutubeDL-Material/assets/74292007/abd080ad-824b-4688-933c-0dd94298fef8">

and in the logs it just states subscription check is incomplete for the channel, even if it has been running for days.
im lost.

**Comment by RobustMarker** [comment]
<img width="1665" alt="Screenshot 2024-04-03 at 16 48 25" src="https://github.com/Tzahi12345/YoutubeDL-Material/assets/74292007/ddf5e482-8feb-4c59-8af5-bf1354e22d6a">
Attempting this on a different machine returns similar results, just in the logs now it is stating that the wrong ID is being returned.......

**Comment by olig89** [comment]
Does the URL you're trying to import/sub to have an @ before the name? The URL should work without it, and I think removing it helped with a similar situation I was having - at least it got me past the forever-checking stage.

**Comment by RobustMarker** [comment]
Seemed to fix itself. Coudnt figure out how to reproduce it or find the problem.

**Comment by RobustMarker** [comment]
Seemed to fix itself. Coudnt figure out how to reproduce it or find the problem.

**Comment by Patriot2407** [comment]
I am having the same exact issue

**Comment by RobustMarker** [comment]
> I am having the same exact issue

I just switched to a application called tubearchivist. So much better. Otherwise never figured it out
