### ISSUE TITLE
[DEPENDENCIES <very low priority>] Use more advanced youtube-dl library

### ISSUE THREAD

**Issue by Tzahi12345** [Tzahi12345/YoutubeDL-Material#111]
We're starting to reach the limitations for [node-youtube-dl](https://github.com/przemyslawpluta/node-youtube-dl) as we begin to add more features/functionality. Tradeoffs are constantly being made (video progress only for *some* downloads, archiving only works for *some* downloads), so it would be a good idea to pick a new library that will better fit our needs.

There are promising alternatives like [node-ytdl-core](https://github.com/fent/node-ytdl-core) which might fit our needs. I'm not sure when I want to make this change (I'll put it on 4.2 for now), as it requires 3 important functions to be modified:

* app.js:tomp3 (where audio downloads go)
* app.js:tomp4 (where video downloads go)
* subscriptions.js:getVideosForSub (where subscription downloads go)

The existing functionality in all 3 functions need to be ported over to the new library. It's not a crazy amount of work, but it's important that we get it right the first time.

**Comment by Tzahi12345** [comment]
Just to update this, we haven't switched off of [node-youtube-dl](https://github.com/przemyslawpluta/node-youtube-dl) despite the fact that it's been deprecated for a little bit.

The reason is, I haven't been able to find an alternative that gives us the flexibility we need. Since creating this issue, we have totally refactored the way we do downloads. We have all the features we need (archiving works everywhere now, download progress works everywhere). We're using the absolute basics: just the executable and args.

node-youtube-dl was deprecated in favor of [youtube-dl-exec](https://github.com/microlinkhq/youtube-dl-exec). There's a couple issues with switching:
* Args are not strings, rather properties in an object that gets passed to a download function
* No access to the binary!

On the plus side it supports different repos for youtube-dl (e.g. yt-dlp), but we support that too (just in a weird workaround way, but still).

I'm not even sure this needs to be kept open anymore. I've use node-youtube-dl enough that I could even fork it and maintain our own version of it. For now I'll leave it up as node-youtube-dl is deprecated so long-term we should find a new library, but it's not a priority by any means.

**Comment by GlassedSilver** [comment]
I guess we can keep it open and change the title to reflect that this is not urgent and more like a long-term aspect we may need to re-consider if other factors change that necessitate this.

**Comment by Tzahi12345** [comment]
Just to update this, I think it's best we move onto managing the binary ourself. This is still low priority but what annoys me is by default, node-youtube-dl auto install youtube-dl, but we don't want/need that. In either system we have to pull in yt-dlp initially so it's not a major deal, just a minor annoyance.

Also our method of modifying the `details` json that sites in `node_modules/youtube-dl` to keep track of which youtube-dl fork & version we use is a bit janky.
