### ISSUE TITLE
Question about file naming

### ISSUE THREAD

**Issue by Drazzilb08** [Tzahi12345/YoutubeDL-Material#112]
Hello,
Love the program its got to be one of the best interfaces for YouTube-dl that I've worked with. However, I have one small thing I cant quite figure out or seem to know how to change. I'm looking to add the YouTube video ID to the end of the file name. I'm basically looking to have the YouTube video meet the naming requirements for this agent for Plex.
https://github.com/ZeroQI/YouTube-Agent.bundle
This does everything I need to do but allowing me to change the naming. 

Any assistance or possibly a feature would be great.

Oh edit: This is for a subscription

**Comment by Tzahi12345** [comment]
>Oh edit: This is for a subscription

Ok, there's good news and bad news: for subscriptions, this isn't possible yet, the good news is it's coming up soon! Check out the [issue here](https://github.com/Tzahi12345/YoutubeDL-Material/issues/73) to keep track of it.

For normal downloads (non-subscription), you can set a custom output using youtube-dl's [output template](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template) if you enable "Allow advanced download" in the `Advanced` tab in the settings. I know it's not what you're looking for, but this feature will be brought to subscriptions soon.
