### ISSUE TITLE
[BUG] Nightly does not start - error: exec: "npm": executable file not found in $PATH

### ISSUE THREAD

**Issue by razordynamics** [Tzahi12345/YoutubeDL-Material#1131]
**Describe the bug**
The nightly Docker image does not start properly on Docker on Synology DSM 7.2.

Logs produce the following:
[entrypoint] setup permission, this may take a while
error: exec: "npm": executable file not found in $PATH

And just repeats. The container fails to start properly and loops those two lines in the log.

**To Reproduce**
Using Container Manager to set up and pull the most current Nightly build, updating from Latest stable build. All Environment variables are stock/default.

**Expected behavior**
I expect the container to properly launch and YTDL-M to launch minutes later

**Screenshots**

**Environment**
- YoutubeDL-Material version - nightly
- Docker tag: nightly (optional)

**Comment by razordynamics** [comment]
![Screenshot 2024-08-08 at 10-53-58 Portainer local](https://github.com/user-attachments/assets/784bee8e-7e06-40a7-98f1-d03430c152f1)

**Comment by GldRush98** [comment]
I am seeing a similar but slightly different error running Nightly on DSM 7.2...

`error: exec: "pm2-runtime": executable file not found in $PATH`

**Comment by GldRush98** [comment]
Download pm2, added its extracted folder as a volume, added that to the path. I no longer get the pm2-runtime error, but now I am getting a new error on start:

`/usr/bin/env: 'node': No such file or directory`

**Comment by razordynamics** [comment]
I resolved it by shortening the NVM_DIR to just /usr/local/nvm.
