### ISSUE TITLE
Can't share links publicly - Asks you to log in

### ISSUE THREAD

**Issue by suckerfish** [Tzahi12345/YoutubeDL-Material#114]
Trying to share with multi-user mode enabled doesn't work. It prompts you to login/authenticate. Tested using incognito mode.

Ideally, sharing out a video link would let anyone with the link view that one video and nothing else.

**Comment by Tzahi12345** [comment]
This is a known bug, unfortunately. I'll try to get it fixed for 4.1 (I thought an issue existed for it already -- I guess not).

I'll let you know when that's fixed! I think the infrastructure is mostly there to support it anyways.

**Comment by Tzahi12345** [comment]
Good news, this is fixed! You should be able to share videos with non-users in the latest `nightly` Docker build :) [Relevant commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/abfe0dad032b0df6c7b437edaae8a64b3dc7f4b7)

Thanks for the bug report!

**Comment by suckerfish** [comment]
Dumb question, but how do I confirm what build I'm running? I updated my repository so it looks like this: "tzahi12345/youtubedl-material:nightly" but I am not sure that's actually working, so wanted to know how to confirm the build.

**Comment by Tzahi12345** [comment]
That looks good! Yeah, the tag at the end (after the colon) is correctly set to `nightly`. You just have to pull the latest version each time it's updated to get the latest features. If you're on the command line, `docker-compose pull` will do, or `docker pull tzahi12345/youtubedl-material:nightly` should do the job as well.
