### ISSUE TITLE
TextBox instead of Input

### ISSUE THREAD

**Issue by jobrien2001** [Tzahi12345/YoutubeDL-Material#119]
Hi, 

I have a suggestion.

If i have a list of urls, I do not want to paste them 1 by 1.

Would be cool to paste an entire list into the webui.

**Comment by Tzahi12345** [comment]
Not a bad idea, one way you can get around this is by making a playlist of the videos before, but it's an ugly workaround.

This may or may not be possible with the current library, I'll do some more investigating to see the viability of something like this.

**Comment by Tzahi12345** [comment]
Done! Check out the latest `nightly`, [see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/c5f7cd1874b12e35b7731fb712f7926299f180c6).

Screenshot:

![image](https://user-images.githubusercontent.com/707413/135199126-6047fdca-7943-4494-8678-870a7f4ff285.png)

**Comment by GlassedSilver** [comment]
Maybe disable scrollbars in this field? Auto-expand with line wrapping seems like a better way.

Maybe make URLs chiplets to visuallly separate multiple URLs more easily.
