### ISSUE TITLE
Static resources not loaded behind nginx reverse proxy

### ISSUE THREAD

**Issue by vfauth** [Tzahi12345/YoutubeDL-Material#125]
Hi,

I have an issue which may be related to #54 or #96. When using a nginx reverse proxy (using your Docker image), static resources are not loaded, so the webpage looks like this:
![image](https://user-images.githubusercontent.com/32266846/84359051-54a30480-abc8-11ea-8616-828b84af98dc.png)

I get no error in the console, but the only request the browser does are for the main html file and favicon.ico. So I assume the issue may have to do with headers.
When accessing the service directly, it works fine. I tried using Vivaldi and Firefox, and disabling my adblocker.

My nginx configuration (I tried removing the proxy_set_header lines, did not change anything):

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name download.domainname.tld;

    ssl_certificate           /etc/letsencrypt/live/default/fullchain.pem;
    ssl_certificate_key       /etc/letsencrypt/live/default/privkey.pem;

    access_log /var/log/nginx/youtubedl.access.log compression_logging;
    error_log /var/log/nginx/youtubedl.error.log;

    # This is the internal Docker DNS, cache only for 30s
    # Required to set define upstreams with variables
    # See https://sandro-keil.de/blog/let-nginx-start-if-upstream-host-is-unavailable-or-down/
    resolver 127.0.0.11 valid=30s;

    location / {
        set $upstream http://container_name:80;
        proxy_pass $upstream;
        proxy_redirect $upstream https://download.domainname.tld;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $server_name:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

And the headers:
`>> curl https://download.domainname.tld -I
HTTP/2 200 
server: nginx/1.17.8
date: Thu, 11 Jun 2020 07:53:54 GMT
x-powered-by: Express
access-control-allow-headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
access-control-allow-origin: https://download.domainname.tld
strict-transport-security: max-age=63072000; includeSubdomains;
x-frame-options: sameorigin
x-content-type-options: nosniff
x-xss-protection: 1; mode=block`

**Comment by suckerfish** [comment]
I am not an Nginx expert by any means. But my current implementation works fine as far as I can tell. 

https://pastebin.com/bwP1FqDz

**Comment by Tzahi12345** [comment]
I'm not sure what the fundamental reason behind this bug is or what configuration is *really* necessary. My guess is it's related to the fact that we're serving the HTML from Node.js (unlike before, where apache2 and nginx was required)

One possible workaround might be to use `try_files` and serve the HTML that way (therefore bypassing Node.js, this is faster too), but you'll need to download [this directory](https://github.com/Tzahi12345/YoutubeDL-Material/tree/master/backend/public) and add this line to your location block:

```
try_files /path/to/public/dir/ $uri
```
I *think* `$uri` should be at the end. You can find more details on `try_files` at [this link](https://www.nginx.com/blog/creating-nginx-rewrite-rules/).

Alternative, you can test out using a non-root path and see if that configuration works (just for debug purposes). This is the general setup for that:

```
location ~/ytdl(.*)$ {
	rewrite /ytdl/(.*) /  break;
	proxy_pass http://example.com:8998;
}
	
location /api/ {
	proxy_pass http://example.com:8998;
}
```

That's all I can think of in terms of possible workarounds. Let me know if this helps!

**Comment by vfauth** [comment]
Thank you for your answers!

@suckerfish I tried changing my configuration based on yours, didn't work :/

@Tzahi12345 I don't think that is the issue:
- When trying to access the script files directly, it works (e.g. trying `curl https://download.domain.tld/runtime-es2015.adce6980ecb528c465bb.js` works fine), so the files are served correctly by nginx.
- I tried with a non-root path already, didn't work either :/
- The issue there is that my browser does not even request these files. That's the reason I suspect security headers or something like that.

**Comment by vfauth** [comment]
I was able to make some progress. By adding `add_header Access-Control-Allow-Origin *`, most resources are loaded. However, I don't know why CORS would be an issue with a reverse proxy but not without.
Furthermore, that causes another issue:
![image](https://user-images.githubusercontent.com/32266846/84479404-2fc79380-ac93-11ea-8d0a-484d2b723f8d.png)

**Comment by vfauth** [comment]
Okay, so this issue was resolved by tweaking nginx config:

- I added `add_header Access-Control-Allow-Origin *;`, which is not very good security-wise
- I removed `add_header X-Content-Type-Options nosniff;` (thanks to #96)

However, these steps should not be necessary. Moreover, judging by #96, many people have that kind of issues.

Why not include a nginx server in the Docker image instead of using Node? That would probably resolve everything.

**Comment by Tzahi12345** [comment]
>Why not include a nginx server in the Docker image instead of using Node? That would probably resolve everything.

Is it possible to include an nginx server inside of a container? The way I've seen this done is where a `docker-compose.yml` will have an nginx container alongside the app's container, and they interface with each other. But I always saw this as messy and undesirable.

If it's possible to have nginx in the container without a huge hit to memory/performance, that would be great. Static resources would load a lot faster because after all, Node.js wasn't built to serve static files.

Can you walk me through why the nginx server built into the image would resolve the loading of the static files? That part isn't making 100% sense to me.

Also, thanks for including a stopgap solution! Hopefully it helps people until we get a more permanent solution out there.

**Comment by vfauth** [comment]
> Is it possible to include an nginx server inside of a container? The way I've seen this done is where a `docker-compose.yml` will have an nginx container alongside the app's container, and they interface with each other. But I always saw this as messy and undesirable.

Well, most users will use a reverse proxy, so in the end they have exactly the same setup: one "app" container, and one "reverse proxy/nginx/apache/traefik/etc" container.

But yes, it is possible to include a web server inside a Docker image. It may also be a way to reduce the image's size. You may take a look at this article, which is quite good: https://medium.com/@chemidy/create-a-small-and-secure-angular-docker-image-based-on-nginx-93452cb08aa2

> If it's possible to have nginx in the container without a huge hit to memory/performance, that would be great. Static resources would load a lot faster because after all, Node.js wasn't built to serve static files.
As you say, I expect to have a *positive* hit on performance. Not sure about memory, but worst case, it should not be a huge impact.

> Can you walk me through why the nginx server built into the image would resolve the loading of the static files? That part isn't making 100% sense to me.
Well, I am still not sure why that issue is happening, and I don't want to say things which are probably wrong.

I just think these issues *seem* to be caused by bad headers, which *may* be set by Node. I don't know anything about node, to be honest.

**Comment by dovy6** [comment]
I'm not sure if this helps, but here's a proxy-conf that works for Swag (formerly letsencrypt)
Save this file as youtube-dl.subfolder.conf

```
## Version 2020/12/23
# Works with this youtube-dl-material Fork: https://github.com/Tzahi12345/YoutubeDL-Material


location /youtube {
    return 301 $scheme://$host/youtube/;
}

location ^~ /youtube/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app  youtube-dl-material;
    set $upstream_port 17442;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    proxy_redirect  off;
    proxy_set_header Referer '';
    proxy_set_header Host $upstream_app:17442;
    rewrite /youtube(.*) $1 break;
}

location ^~ /youtube/api/ {
     include /config/nginx/proxy.conf;
     resolver 127.0.0.11 valid=30s;
     set $upstream_app youtube-dl-material;
     set $upstream_port 17442;
     set $upstream_proto http;
     proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
location ^~ /api/ {
     include /config/nginx/proxy.conf;
     resolver 127.0.0.11 valid=30s;
     set $upstream_app youtube-dl-material;
     set $upstream_port 17442;
     set $upstream_proto http;
     proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}

**Comment by GlassedSilver** [comment]
Coming just from issue #122 and hence looking at the whole web-server topic here again and seeing how it seems to help people with performance I'm curious if we could target looking into this for a 4.5 milestone, @Tzahi12345?

**Comment by D34DC3N73R** [comment]
I get this problem when `X-Content-Type-Options "nosniff" always` security header is enabled.
