### ISSUE TITLE
Quality selection

### ISSUE THREAD

**Issue by hjyoung1** [Tzahi12345/YoutubeDL-Material#13]
I'm having some problems with latest version.
No matter what quality i select but ytdl-m ignores it and download highest quality video.
![Screenshot_20200301-154021](https://user-images.githubusercontent.com/45882061/75624584-aefcf400-5bdb-11ea-87fe-59de50452f46.jpg)
Here i select 144p but it's still downloading 1080p 
![Screenshot_20200301-154148](https://user-images.githubusercontent.com/45882061/75624593-c3d98780-5bdb-11ea-8de8-1812b643af9d.jpg)

I also tried using custom args to fetch different resolution 
` -f bestvideo[height=360][ext=mp4]+bestaudio `
Or 
`-o "%(title)s.%(ext)s"  -f bestvideo[height=360][ext=mp4]+bestaudio`

But this causes download failed and shows error in terminal.
`ERROR: u'' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:" ) to search YouTube
(node:1) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl -i -o "%(title)s"  -f bestvideo[height=360][ext=mp4]+bestaudio[ext=m4a] https://youtu.be/992OYXQY18w
    at makeError (/app/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/app/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)`

**Comment by Tzahi12345** [comment]
Ah, this bug is my fault. I just updated the 3.3 docker image, so it's fixed there. I'll push out a fix on the non-Docker deployments later today. Thanks so much for pointing it out!

I'll play around more with custom args, and maybe make a guide on what works and what doesn't with YTDL-Material.
