### ISSUE TITLE
Update Readme: Translations How-To

### ISSUE THREAD

**Issue by web-connect** [Tzahi12345/YoutubeDL-Material#131]
Its not clear how to edit translations for the app.

**Comment by Tzahi12345** [comment]
Yup, this should probably be mentioned outside of the [Translate wiki page](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Translate), which is a bit hard to find.

**Comment by web-connect** [comment]
Whoops. I should have looked harder. Point still stands but thanks for the doc!

**Comment by web-connect** [comment]
Closed, WIKi page is fine.
