### ISSUE TITLE
[FEATURE] Limit number concurrent downloads

### ISSUE THREAD

**Issue by projx** [Tzahi12345/YoutubeDL-Material#135]
Hi

Rather than just Yes or No, could this feature be enhanced, to specify the max number of videos to download simultaneously.

Thanks

**Comment by Tzahi12345** [comment]
Not currently possible without building on our current downloads setup. There's no queuing system built in (all downloads are simultaneous), the multi-download mode is more of a UI feature.

But having one would be cool and it has been requested before! So once that is done I will 100% include a limit on concurrent downloads.

**Comment by Tzahi12345** [comment]
Going to close this as I'm consolidating some of the downloader-related feature requests. See #411 and #379, the latter shouldn't take too long to be implemented!
