### ISSUE TITLE
[Feature] User Management: Ability to disallow signup

### ISSUE THREAD

**Issue by UnlimitedCookies** [Tzahi12345/YoutubeDL-Material#142]
As seen in the title.

If this option is activated, only admins should be able to create new user accounts.

This would enable me to be able to open my instance to the public, so that no randoms can signup and download videos on my bandwidth.

Regards.

**Comment by Tzahi12345** [comment]
Have you tried unchecking `Enable user registration` in the Users tab in the settings? This should disable it for you, let me know if this doesn't work!

**Comment by UnlimitedCookies** [comment]
My bad... yep I didn't find it beforehand.
