### ISSUE TITLE
[Docker] Restructure Docker/Docker-Compose setup

### ISSUE THREAD

**Issue by UnlimitedCookies** [Tzahi12345/YoutubeDL-Material#143]
I find it really weird that you have to download a zip file with a structure of empty folders and some files.
Usually the needed files are within the image and the folders would be created by the program itself.

This means that `auth.js` ; `default.json` and `encrypted.json` should be created upon the first container start if they don't exist.

`encrypted.json` and `default.json` seem to serve the same purpose.

Or is there a specific reason that auth.js needs to be mounted outside the container?

It's best practice to just show what volumes to map, what ports to forward and which environment variables to set in the Readme file, so there shouldn't be the need to download an entire zip with file structure.

Furthermore, executables and zip files should be removed from the github repo long term.

Despite my suggestions, I really enjoy the work you have put into it :)

Best regards.

**Comment by Tzahi12345** [comment]
A couple things here:

1. Just noticed auth.js is in the zip, this is really not needed (it doesn't even get mapped, it's just unused). I'll remove this in the next update, good catch!

2. The folders packaged in the zip are automapped to their corresponding folders in the image. Without this mapping, the app would work perfectly fine. But every time you re-pull the image, your videos and settings might get overwritten. Having them automapped means they persist, no matter which image/version is used. I want this functionality to be built-in, maybe this can be done from the Dockerfile? All that needs to be done is empty folders get created, maybe with an ENV var switch in case a user doesn't want that

Anyways, good points overall! I just pushed [a commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/3abb29eee4065e979daedf0ac2974c881bc8b6d8) to get rid of some straggling exe's from the repo. I'll make sure to avoid binaries in the future.

**Comment by SuperSandro2000** [comment]
> All that needs to be done is empty folders get created

Just check if they exist and if not create them.

```
if [ -d /path/to/dir ]; then
  mkdir -p /path/to/dir
fi
```

> maybe with an ENV var switch in case a user doesn't want that

This is just a useless setting which clutters the image. A few directories won't hurt anyone and if one person does not want them they can always edit the script and built the image themself.

**Comment by Tzahi12345** [comment]
@SuperSandro2000 Thanks for the example snippet! We can stick something like that in the entrypoint.sh (apparently [arrays](https://opensource.com/article/18/5/you-dont-know-bash-intro-bash-arrays) are possible in bash, so we can loop through the  needed folders and make each if they're nonexistent)

**Comment by UnlimitedCookies** [comment]
This is a little cleaner than using an if statement:
```bash
[ -d /path/to/dir ] && mkdir -p /path/to/dir
```

**Comment by UnlimitedCookies** [comment]
Actually if you only want to `mkdir` if the directory does not exist you need to put an `!` in front of the -d flag.
Like this:
```bash
[ ! -d /path/to/dir ] && mkdir -p /path/to/dir
```

**Comment by UnlimitedCookies** [comment]
May I ask why we even want to check for the existence of the folder?

Because if we just run `mkdir -p /path/to/folder` and the folder already exists (so is mounted with contents), mkdir does not do anything and will exit with no error. So why do we need to check in the first place?
See in the [mkdir manpage](https://linux.die.net/man/1/mkdir).

**Comment by Tzahi12345** [comment]
I was thinking about this yesterday, and I realized we don't actually need to make any modifications *anywhere* to have the automatic folder creation work (so no mkdirs necessary).

Basically, if you set up a mount in the docker-compose.yml and the host-side folder doesn't exist, it will autocreate one -- this is the exact functionality we need! The container then correctly handles the empty folders (meaning config and db files get rightly made).

So for the next release (coming up in the next day or so) I'll just have users use the docker-compose and nothing else. Once that's done, I think everything else in this issue is addressed, so I'll close this issue then.

**Comment by Tzahi12345** [comment]
All done! Check out the [4.1 release here](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v4.1), now we just use a simple docker-compose.yml, no more zips :)

Thanks everyone for the help!
