### ISSUE TITLE
Indicate to user that the session/authorization has expired

### ISSUE THREAD

**Issue by UnlimitedCookies** [Tzahi12345/YoutubeDL-Material#150]
When I leave an ytdl-material tab open for some time and my auth token expires the fields and options usually just don't show any data. 
The site continues to show all contents until I press `f5` to reload the page.

Maybe there could be a check implemented that sends the user to the login page automatically when the token expires (or something else).

Best regards.

**Comment by Tzahi12345** [comment]
Good catch!

Looks like I can use HttpInterceptor to [capture all the 401 unauthorized errors](https://stackoverflow.com/a/46019852). If any of these errors are found, it will route the user to the login screen.

**Comment by Tzahi12345** [comment]
This is done! It's not merged yet, but it will be once v4.2 is released, which should happen in a week or two.

See the [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/pull/290/commits/7e06d30205ec81deb970af37c09e52430b441d60), and you can follow the [v4.2 PR here](https://github.com/Tzahi12345/YoutubeDL-Material/pull/290)

Thanks for the suggestions as always!
