### ISSUE TITLE
password change of non-default admin account changes the password of the default admin account

### ISSUE THREAD

**Issue by UnlimitedCookies** [Tzahi12345/YoutubeDL-Material#151]
While I wanted to send you the credentials for bug #144 I found out that I did change the password for the uid: admin instead of uid: Isaac even though I was editing uid: Isaac.

**Comment by Tzahi12345** [comment]
That's an ancient bug that's been there for a while, oh my!

Found where it happened, see this code snippet:

```
app.post('/api/auth/changePassword', optionalJwt, async (req, res) => {
    let user_uid = req.user.uid;
    // ^^ error is here! req.user.uid is the requester's user uid (admin usually),
    // while req.body.user_uid is the target's user uid
    let password = req.body.new_password;
    let success = await auth_api.changeUserPassword(user_uid, password);
    res.send({success: success});
});
```

Anyways, my latest [commit to master](https://github.com/Tzahi12345/YoutubeDL-Material/commit/e81d0cab42c4472c6662073c6b1e79c2de45c075) fixes this. The nightly should autobuild shortly, so you can pull that and get the bug fix (and then email me working credentials :P )

Thanks for catching that one!

**Comment by UnlimitedCookies** [comment]
Thanks for fixing this! I've already re-sent you working credentials :P
