### ISSUE TITLE
[Enhancement] Indicate to user that the credentials are wrong

### ISSUE THREAD

**Issue by UnlimitedCookies** [Tzahi12345/YoutubeDL-Material#152]
Currently, there's no feedback to the user that the entered credentials are wrong.
This is bad from a UX standpoint because the user might think that there's something wrong with the server, their webbrowser etc.

**Comment by Tzahi12345** [comment]
You're 100% correct, this is something that should be addressed rather soon. Thanks for the suggestion!

**Comment by SuperSandro2000** [comment]
This should not tell the user if their username or password ist wrong. This can be used to enumerate users.

**Comment by Tzahi12345** [comment]
@SuperSandro2000 good point, so just say "username or password incorrect" without specifying which one. Easy enough!

Some large orgs do have username/email checking during login, but maybe they have special security mechanisms to prevent bots from abusing it.

**Comment by UnlimitedCookies** [comment]
Yea, I was assuming you guys would implement it like that. :)

**Comment by Tzahi12345** [comment]
All done! [See commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/3732d1356290c293419b64c9862e3dcd0baf1b4c) As always, thanks for the suggestion! v4.1 is now feature complete, should drop in the next day or so. Cheers!
