### ISSUE TITLE
Wording error

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#154]
In the Settings tab for "Downloader" the wording is: `Note: This setting only applies to downloads on the Home page. If you would like to use youtube-dl archive functionality in subscriptions, head down to the Subscriptions section.`

However it should reflect that we don't have a settings panel anymore that is just one big list of settings laid out vertically, but tabbed, so I propose:

`[...] archive functionality in subscriptions, head to the Main tab and activate this option there.`

Or similar wording.

**Comment by Tzahi12345** [comment]
Good catch, fixed! [See commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/2e7b1c2d53ef172f2919abf8a58d03d120faf3e0)

Note that a rebuild of the frontend will be required for this change to appear. Thanks!!
