### ISSUE TITLE
Small UI improvements to the Settings Panel (not necessarily the big overhaul that's planned, but intermediary improvement)

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#155]
Whilst creating the issue #154 I noticed that the tabs in the Settings panel aren't always visible when scrolling the options unlike the window title bar. (the thing that reads "Settings")

I'd suggest we fix this! And two other Settings panel UI improvements I would like to suggest:

1) can we please have a settings panel that is 1.5 times taller and about half as wide? There is a LOT of unnecessary white space and in the areas where we actually do fill the width, it's a long line of text and one reason newspapers have multiple narrower columns instead of one wide block of text is improved readability. (both speed and tracking your position in the text) Recently I also found out that apparently in original manual typesetting it was also technically easier to make narrower columns, but I frequently find myself preferring the narrower text in any kind of scenario from a readability point of view as well. So whatever the original real reason, it's better practice. :)

2) Additionally, I would love to have a "Clear logs" button in the Logs tab. When debugging a bug it's easier to start off with a clean sheet and then just log the one workflow that throws an error rather than dealing with looking for the timestamps. Bonus points if we can display the log in rich text, e.g. color code the time stamps and type of event (ERROR, INFO, WARN, ...)

___
**A word about the Settings Layout future (as only I imagine it, of course)**

Truth be told though, long term it's probably best to have settings be accessed on a separate page where all settings and their tabs and descriptions can utilize the space better, especially when we add more customized toggles and buttons to set args in a more approachable way.

___
**Edit:** Styling fixed (I mixed HTML with MD styling? :/ )

**Comment by Tzahi12345** [comment]
>I noticed that the tabs in the Settings panel aren't always visible when scrolling the options unlike the window title bar.

Just tried messing around, I'll have to do some CSS magic to get it working but it shouldn't be so difficult. At the end you mentioned something that has crossed my mind: why have settings be a dialog? If it's made to be a dedicated page, I think making the header "sticky" will be easier. And there will be more room, especially for mobile users who are tight on width regardless.

I think this solves your main issue in this thread, but also subpoint 1 (settings menu will be a lot more wide/tall).

>Additionally, I would love to have a "Clear logs" button in the Logs tab. When debugging a bug it's easier to start off with a clean sheet and then just log the one workflow that throws an error rather than dealing with looking for the timestamps.

Good call, at first I imagined it as a "logs viewer", but extending it to be a "logs manager" with clearing functionality (and anything else we realize is useful) would be nice.

>Bonus points if we can display the log in rich text, e.g. color code the time stamps and type of event (ERROR, INFO, WARN, ...)

I like this idea too. It'll require a tiny refactor of the current setup but doesn't really need much more beyond that.

**Comment by Tzahi12345** [comment]
Check out the [latest commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/e97e9ec7174dbaf91ecd90fc3980a98dfd89b314)! Got inspired and updated the logs viewer: added ability to clear logs and log messages are color coded based on type (error, info, warn, etc.)

Update to the latest nightly to see these changes. That's all for now :)

**Comment by GlassedSilver** [comment]
> 
> 
> Check out the [latest commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/e97e9ec7174dbaf91ecd90fc3980a98dfd89b314)! Got inspired and updated the logs viewer: added ability to clear logs and log messages are color coded based on type (error, info, warn, etc.)
> 
> Update to the latest nightly to see these changes. That's all for now :)

Cool! Will check it out and report back! 👍

**Comment by GlassedSilver** [comment]
Loving it!
