### ISSUE TITLE
Twitch VOD (and possibly YouTube Live) Chat Replay

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#156]
So recently I captured a few Twitch videos as well to see how YTDL-M handles this and it's still a solid experience (so far only tested for streams with 1080p or less, so I don't know if issue #76 is affected here as well)

However I noticed that watching Twitch VODs (or any kind of live format that has audience chat on the side) is WEIRD without chat. I mean I'm still mighty glad I can capture and save footage that way that otherwise will FOR SURE be lost very soon as well, but man... Twitch Chat really is 30% of the experience, you really feel it.

I know there are a few open-source projects out there that can pull Twitch chats and even pull Twitch emotes and display them as well, don't know of any example that is using the same languages as YTDL-M though.

Any thoughts?

___
**Edit:** For Twitch chat maybe this could work? https://github.com/d-fischer/twitch

**Comment by Tzahi12345** [comment]
This looks surprisingly easy to implement. We have the original URL so it's easy to know if the video was from Twitch. At that point we can use a JS library like the one you mentioned, or here's an alternative: https://tmijs.com/

Either way, looks (relatively) simple from the backend. On the frontend, we could either have it replace the video description (I'm planning on putting that directly under the video), or have it be a sidebar on the right, like how it's done on Twitch.

**Comment by Tzahi12345** [comment]
Progress!

![image](https://user-images.githubusercontent.com/707413/100533874-45942b00-31d7-11eb-921d-3d2557869cbe.png)

**Comment by GlassedSilver** [comment]
Wow, that's amazing news!
Is the chat saved alongside the video and is that done at download time or at play time?

Thank you so much! Will check it out asap!

**Comment by Tzahi12345** [comment]
>Thank you so much! Will check it out asap!

It's not in yet, it's almost done!

For Twitch VODs, a new icon will appear in the player, once you click that a sidebar is revealed where there's a download button (that's the part I'm finalizing now). So it's not downloaded at download-time, rather it's done after. It's a bit of a hefty process (take's a minute or two for 20k chat messages), so that's why I decided to make it so users can do it after. You just click download, wait until it finishes, and then the chat log appears :)

**Comment by GlassedSilver** [comment]
Can you make automating it opt-in, please?

Bonus question: are twitch emotes and Better Twitch TV emotes/FrankerFacez emotes downloaded as well?

Cheers!

**Comment by Tzahi12345** [comment]
>Can you make automating it opt-in, please?

Will do!

>Bonus question: are twitch emotes and Better Twitch TV emotes/FrankerFacez emotes downloaded as well?

Unfortunately not! Looks like it *should* [be possible](https://discuss.dev.twitch.tv/t/how-to-get-emotes-badges-object/18916) but I'd rather leave it up to the next iteration of this feature (maybe get YT chat working as well)

**Comment by Tzahi12345** [comment]
Feature has been pushed! In about an hour the `nightly` should have this included. Just enable the Twitch API in the Extra tab in the settings and generate a key by following the "Setup" instructions at this link: https://dev.twitch.tv/docs/api/

**Comment by GlassedSilver** [comment]
Works! Wonderful! Thank you so much!

Any possibility we can get syncing of video play position with the chat?

Secondly it'd be cool to have an option to auto-display the chat if there is chat downloaded for it. :)

**Comment by GlassedSilver** [comment]
Another cool thing could be to have the chat colors enabled, because they REALLY make it a lot easier to follow along?

**Comment by Tzahi12345** [comment]
>Any possibility we can get syncing of video play position with the chat?

It should follow where you are. As in, if you skip to 30 minutes in, the chat will clear and show you the messages from then on.

>Secondly it'd be cool to have an option to auto-display the chat if there is chat downloaded for it. :)

Technically possible, shouldn't be *too* difficult. We don't know whether the chat exists or not from the player component, but finding out is pretty straightforward.

>Another cool thing could be to have the chat colors enabled, because they REALLY make it a lot easier to follow along?

Hm, I don't think we get the info for the colors, or do you mean to color it ourselves arbitrarily?

**Comment by GlassedSilver** [comment]
> > Any possibility we can get syncing of video play position with the chat?
> 
> It should follow where you are. As in, if you skip to 30 minutes in, the chat will clear and show you the messages from then on.
It does!
I don't know why it didn't when I first tried it (maybe chat was slow in that moment and there was nothing to load), but a second try revealed that it works as expected. LOVELY!

> > Secondly it'd be cool to have an option to auto-display the chat if there is chat downloaded for it. :)
> 
> Technically possible, shouldn't be _too_ difficult. We don't know whether the chat exists or not from the player component, but finding out is pretty straightforward.
Possibly add "chat logged" as a metadata field to the db file?
Also probably nice to keep track of this so we could make that a searchable tag?

> > Another cool thing could be to have the chat colors enabled, because they REALLY make it a lot easier to follow along?
> 
> Hm, I don't think we get the info for the colors, or do you mean to color it ourselves arbitrarily?
Hmm, how do tools like OBS that can pull in Twitch chat load the chat messages along with colors though?
I mean in the worst case I guess we'd be better off generating per-user color profiles for their messages on our end, it should be possible somehow, no?

Maybe the library that YTDL-M uses doesn't read it. I guess I can look into it as well if there are other libraries that support it.

OBS might just HTML-iframe the publicly available chat viewer that you can pop out, but couldn't one read the HTML color codes from there? Just an idea.

**Comment by Tzahi12345** [comment]
>Possibly add "chat logged" as a metadata field to the db file?

Basically what I was thinking. I went ahead and made it so that when a twitch video is retrieved, we check if the twitch chat file exists. If so, we add an additional field before sending the DB data to the UI, indicating whether the chat exists or not.

So you won't see it in the DB, it'll just be checked when the video is retrieved (it's simple and low cost performance-wise)

>Maybe the library that YTDL-M uses doesn't read it. I guess I can look into it as well if there are other libraries that support it.

It actually does! The way I implemented the chat downloading functionality was by using the Twitch API directly (someone already did this so I "stole" their code). I simply wasn't noticing that it includes a `user_color` field which we now leverage. Pull the latest nightly and you should see the auto-open and user-color functionality there, but you will have to redownload your chats for those to appear.

[Here's the commit.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/f425b9842f9e20282218331099ef6a07094a5f71) Check out the latest nightly!

**Comment by GlassedSilver** [comment]
Dude, you're a legend! I'll check it out as soon as I get the chance!

**Comment by Tzahi12345** [comment]
Haha always a pleasure, hope you enjoy the new feature :)

**Comment by GlassedSilver** [comment]
Ok so the color downloading works, but the chat doesn't auto-slide out.
(tested in incognito window, so fresh cache as always)

**Comment by GlassedSilver** [comment]
No auto-download either so far. Other than that still a top notch feature to have! Really happy!

**Comment by Tzahi12345** [comment]
Actually subscriptions aren't supported yet, it'll be an easy add and I probably should've done it already, but I wanted the core functionality in and tested. I'll re-open this issue as a reminder but maybe today I'll be able to get that in, as well as some player improvements!

**Comment by Tzahi12345** [comment]
Done! Check out the latest `nightly` in about an hour, should be deployed by then :)
