### ISSUE TITLE
Edit subscriptions?

### ISSUE THREAD

**Issue by tophee** [Tzahi12345/YoutubeDL-Material#163]
I'm sorry if I missed this, but I just seem to be able to figure out how I can edit a subscription once I hit "subscribe". It must be possible, right?

It it's not currently possible to edit the settings for a subscription, please treat this as a feature request.

**Comment by Tzahi12345** [comment]
It isn't! It's a high priority item, I intended to get it in for v4.1 but I never got around to it. Will make sure this functionality is added by v4.2. Thanks for the request!

**Comment by Tzahi12345** [comment]
Added! See [PR here.](https://github.com/Tzahi12345/YoutubeDL-Material/pull/184)
