### ISSUE TITLE
Please don't log me out or do it properly

### ISSUE THREAD

**Issue by tophee** [Tzahi12345/YoutubeDL-Material#165]
I have been struggling to get a download to work, playing around with various arguments but nothing worked. The download just kept failing. And what was even weirder was that the log didn't show anything about he failures.

It turns out: I had been logged out during a period of inactivity (multi-user mode) and that's why the download kept failing.

The main problem with that is, of course, that there was nothing to tell me that I had been automatically logged out. The whole interface kept working as usual (or so it seemed), so please, if the user is trying to use the interface without being logged in, tell them so.

But then I'm also wondering why I was logged out at all. The period of inactivity can hardly have been more than an hour and I don't see any point in automatically logging users out at all. But if you need to do it for some reason, I think a period of a day might be more adequate than an hour...

**Comment by Tzahi12345** [comment]
Here's a [related issue](https://github.com/Tzahi12345/YoutubeDL-Material/issues/150). The way your login is saved through a session is using an auth token (JWT), which have an inherent expiration time (see [line 32 in auth.js](https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/backend/authentication/auth.js#L32)). You can theoretically set this as high as you'd like, so we can do one of two things (or both):

* Make the expiration time configurable
* Have the frontend seamlessly request a new token before the previous one expires

I like option 2 better than option 1 (tokens never expiring is [bad practice](https://gist.github.com/soulmachine/b368ce7292ddd7f91c15accccc02b8df#1-how-to-hadle-jwt-expiration)), but if the browser fails to request a token before logout, you still will be logged out. But I don't mind implementing both, and even setting the default higher than an hour (1 day) sounds good.

Thanks for the suggestion, it's a good idea to prevent these unnecessary logouts.

**Comment by Tzahi12345** [comment]
Done! Added the ability to change login expiration time, the options go from 1 Hour to 1 Year. If you don't want to be logged out, just set it to 1 Year and you'll be good until the pandemic's over :) See [commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/c9b615c659f9e26da9742d74c59389e6bb85c824)

I'll eventually add seamless token generation when the expiration is coming up, but it requires additional overhead (like constantly checking) which I'm not so excited to add right now.

Check out the latest `nightly` to get this feature!
