### ISSUE TITLE
how downlaod Playlist or channel video with subtitle?

### ISSUE THREAD

**Issue by cyberskycat** [Tzahi12345/YoutubeDL-Material#172]
there is option there?

**Comment by Tzahi12345** [comment]
Yes! You'll have the use the custom args in your settings menu to do that.

Add `--write-sub` there and you'll be good to go. [Here](https://github.com/ytdl-org/youtube-dl#subtitle-options) are some other subtitle-related args, check it out! Let me know if you have trouble inputting them or run into any errors.

**Comment by cyberskycat** [comment]
ok i will try this option

**Comment by Tzahi12345** [comment]
I'm gonna to assume the arg worked out and close this issue. Let me know if you have issues with downloading subtitles, and I'll re-open!
