### ISSUE TITLE
Download thumbnails to directory?

### ISSUE THREAD

**Issue by CoreyVidal** [Tzahi12345/YoutubeDL-Material#175]
I'm using YoutubeDL-Material in Docker (docker-compose) on Ubuntu 20.04.

I've noticed that over time, some thumbnails break. This might be because some ID information changes somewhere (looking at you, TikTok) or maybe the video isn't actually available online anymore. Regardless, looking into the .json files, it looks like it links to thumbnails externally? At their original URL?

Could there be an option to download and/or generate thumbnails locally, so I keep a permanent copy? I'd like my YoutubeDL-Material library to look nice, on a long-term basis. :)

**Comment by Tzahi12345** [comment]
This is 100% possible! Just add `--write-thumbnail` to your custom args in the settings menu.

Caveat: This won't use the downloaded thumbnail as the thumbnail in the file manager, though I can add this feature in the next update once the homepage redesign comes along. I'll have it so the downloaded thumbnail will be used by default, and if it doesn't exist, the cached (url) one will be used instead.

Either way, if you add the `--write-thumbnail` arg, they will be downloaded alongside the video in the same directory. Let me know if you run into any issues on this front!

**Comment by CoreyVidal** [comment]
That's awesome and brilliant and thank you.

**Comment by Tzahi12345** [comment]
Glad I could help, I'll go ahead and close this issue. I added a reminder for using the cached thumbnail if it's available in the [v4.2 project page](https://github.com/Tzahi12345/YoutubeDL-Material/projects/4), so that will get done before the next update. Cheers!
