### ISSUE TITLE
Error: listen EACCES: permission denied 0.0.0.0:443

### ISSUE THREAD

**Issue by Romanmir** [Tzahi12345/YoutubeDL-Material#178]
I'm getting an error when I try to start/restart/rebuild the docker image.
Here is a brief history of time:
>root@ceres:/data/global/project/docker# mkdir ytdl
root@ceres:/data/global/project/docker# cd ytdl/
root@ceres:/data/global/project/docker/ytdl# ls
root@ceres:/data/global/project/docker/ytdl# curl -L https://github.com/Tzahi12345/YoutubeDL-Material/releases/latest/download/docker-compose.yml -o docker-compose.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   156  100   156    0     0    764      0 --:--:-- --:--:-- --:--:--   764
100   631  100   631    0     0   1464      0 --:--:-- --:--:-- --:--:--  1464
100   440  100   440    0     0    501      0 --:--:-- --:--:-- --:--:--   997
root@ceres:/data/global/project/docker/ytdl# vim docker-compose.yml
root@ceres:/data/global/project/docker/ytdl# docker-compose pull
Pulling ytdl_material ... done
root@ceres:/data/global/project/docker/ytdl# docker-compose up
Creating network "ytdl_default" with the default driver
Creating ytdl_ytdl_material_1 ... done
Attaching to ytdl_ytdl_material_1
ytdl_material_1  | events.js:292
ytdl_material_1  |       throw er; // Unhandled 'error' event
ytdl_material_1  |       ^
ytdl_material_1  |
ytdl_material_1  | Error: listen EACCES: permission denied 0.0.0.0:443
ytdl_material_1  |     at Server.setupListenHandle [as _listen2] (net.js:1296:21)
ytdl_material_1  |     at listenInCluster (net.js:1361:12)
ytdl_material_1  |     at Server.listen (net.js:1447:7)
ytdl_material_1  |     at Function.listen (/app/node_modules/express/lib/application.js:618:24)
ytdl_material_1  |     at startServer (/app/app.js:267:13)
ytdl_material_1  |     at /app/app.js:558:9
ytdl_material_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
ytdl_material_1  | Emitted 'error' event on Server instance at:
ytdl_material_1  |     at emitErrorNT (net.js:1340:8)
ytdl_material_1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
ytdl_material_1  |   code: 'EACCES',
ytdl_material_1  |   errno: 'EACCES',
ytdl_material_1  |   syscall: 'listen',
ytdl_material_1  |   address: '0.0.0.0',
ytdl_material_1  |   port: 443
ytdl_material_1  | }

Here is the relevant docker-compose.yml:
>version: "2"
services:
    ytdl_material:
        environment: 
            ALLOW_CONFIG_MUTATIONS: 'true'
        restart: always
        volumes:
            - /data/dockerdata/ytdl-mat:/app/appdata
            - /data/multimedia/audio:/app/audio
            - /data/multimedia/youtube_subs:/app/video
            - /data/multimedia/users:/app/subscriptions
            - /data/multimedia/Shorts:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:latest

What am I doing wrong?

**Comment by Tzahi12345** [comment]
Mind sharing your default.json file in the `appdata` folder?

It looks like it's trying to start on port 443 for some reason. This isn't possible unless you [run as root](https://stackoverflow.com/a/50112455/8088021).

**Comment by Romanmir** [comment]
Sorry for the delay. Here is the default.json: 
>/app/appdata # cat default.json
{
  "YoutubeDLMaterial": {
    "Host": {
      "url": "http://example.com",
      "port": "17442"
    },
    "Encryption": {
      "use-encryption": false,
      "cert-file-path": "/etc/letsencrypt/live/example.com/fullchain.pem",
      "key-file-path": "/etc/letsencrypt/live/example.com/privkey.pem"
    },
    "Downloader": {
      "path-audio": "audio/",
      "path-video": "video/",
      "use_youtubedl_archive": false,
      "custom_args": "",
      "safe_download_override": false
    },
    "Extra": {
      "title_top": "YoutubeDL-Material",
      "file_manager_enabled": true,
      "allow_quality_select": true,
      "download_only_mode": false,
      "allow_multi_download_mode": true,
      "settings_pin_required": false,
      "enable_downloads_manager": true
    },
    "API": {
      "use_API_key": false,
      "API_key": "",
      "use_youtube_API": false,
      "youtube_API_key": ""
    },
    "Themes": {
      "default_theme": "default",
      "allow_theme_change": true
    },
    "Subscriptions": {
      "allow_subscriptions": true,
      "subscriptions_base_path": "subscriptions/",
      "subscriptions_check_interval": "300",
      "subscriptions_use_youtubedl_archive": true
    },
    "Users": {
      "base_path": "users/",
      "allow_registration": true
    },
    "Advanced": {
      "use_default_downloading_agent": true,
      "custom_downloading_agent": "",
      "multi_user_mode": false,
      "allow_advanced_download": false,
      "use_cookies": false,
      "logger_level": "info"
    }
  }
}

**Comment by Romanmir** [comment]
So.. Interestingly enough, when I run "docker run -ti tzahi12345/youtubedl-material". it seems to run just fine. It shows up as an automatically named container in portainer. I am, apparently, able to start successfully start this container, inside of portainer as well as outside. I'm not sure what changed. I will close this ticket.

**Comment by Tzahi12345** [comment]
Ok! Weird stuff, glad it resolved itself.

**Comment by Romanmir** [comment]
Epilogue: It turns out I had a bind mount that pointed to an empty folder. Everything in the appdata folder didn't exist. I think that's why it was choking and dying every time I tried setting up mount points and labels. Anyhoo. I appreciate when people fix stuff on their own and then share. So here's what I think happened here.
