### ISSUE TITLE
Add password

### ISSUE THREAD

**Issue by maltokyo** [Tzahi12345/YoutubeDL-Material#18]
Just realised that anyone on the internet could use my server.  Any ideas to add a simple htpasswd?

**Comment by Tzahi12345** [comment]
If you're using a reverse-proxy, this should be easy to set up:

[nginx guide](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/) guide
[Apache2 guide](https://stackoverflow.com/questions/5011102/apache-reverse-proxy-with-basic-authentication)

Basically, I would suggest you use a reverse-proxy and one of these above solutions. I've been thinking about adding some native auth system, but I'd prefer not having that responsibility.

**Comment by maltokyo** [comment]
Yes thanks! I just enabled it on Nginx reverse proxy. All good. Will close.
