### ISSUE TITLE
Deprecate "use encryption" setting

### ISSUE THREAD

**Issue by GiantFrog** [Tzahi12345/YoutubeDL-Material#180]
In my configuration, I left 17442 as the port. When I run `npm start` (more specifically, I use pm2 for this) the command `lsof -i:17442`  yields no output. I cannot find anything node-related when combing through all the ports my server is listening to. The appdata/logs folder contains two empty files.

I'm not sure if this is a bug, my configuration file is wrong, or I'm just missing something... I'm not using docker, just a normal installation with all the dependencies and whatnot.

**Comment by Tzahi12345** [comment]
Interesting, can you try running `node app.js` with pm2 instead?

**Comment by GiantFrog** [comment]
Nope! Still nothing. Perhaps I should give the docker version a go? I would rather not if I don't have to, though.

**Comment by Tzahi12345** [comment]
You shouldn't have to, maybe it's a bug in the encryption logic? Try setting `use-encryption` to false and your URL to `http://dl.cooldomain.aaa` just to see if it works.

If it does work without encryption, you can use a reverse proxy to enable it. [Here's the wiki](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Reverse-Proxy-Setup) for that.

**Comment by GiantFrog** [comment]
Yes, that was it. Only made those two changes, I didn't change my reverse proxy at all, used npm start, and now I have a site at normal web ports using ssl, somehow. Through nginx I assume? I typed http:// but it redirected to https and everything.

**Comment by Tzahi12345** [comment]
>Through nginx I assume?

You have to get an SSL cert from LetsEncrypt using certbot, see [instructions here.](https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx.html) TLDR is install certbot and then run it like so: `certbot`. Pretty easy! And then it'll go through a self-explanatory prompt where you select which nginx domain you want to use SSL with.

If you try to run a reverse proxy with https without using certbot, browsers will get angry.

I would suggest using the above method and disabling encryption in the YoutubeDL-Material settings. Should work without issue! Make sure your URL has https in it: `https://dl.cooldomain.aaa`

**Comment by GiantFrog** [comment]
Nono I have all that, I've been renewing certs form there for years now. Nginx is using it properly, making the site look like it's encrypted, yet I can't enable encryption from your control panel. Maybe I don't need to? I'm thinking that maybe your program doesn't have access to those files because they're locked down or something.

**Comment by Tzahi12345** [comment]
Ah I see what you're saying. You should be good! If the webpage loads you're all set :)

Lmk if any other issues pop up. If not, I'll go ahead and rename the issue "deprecate use encryption" since it's been more trouble than it's worth.

**Comment by GiantFrog** [comment]
Sure sure, sounds good to me! I'm happy with the result, I just hope there's no hole along the line somewhere. Thanks for the help, your hunch was right on!

**Comment by GiantFrog** [comment]
Um sorry about that, I'm trying out the Github app and accidentally tapped the button. You open or close this when you're done with it. My bad.

**Comment by Tzahi12345** [comment]
Fixed! See PR #196 for more details.

Thanks for the help @GiantFrog!
