### ISSUE TITLE
Document custom UID/GID for Docker

### ISSUE THREAD

**Issue by tam481** [Tzahi12345/YoutubeDL-Material#181]
Hello,
Would it be  possible to support user mapping so that the docker container can be started with a specific user with restricted permissions on the host system to just that account?

I tried adding user: "uid:gid" but it complains about permissions

Thank you in advance

**Comment by Tzahi12345** [comment]
It should be UID instead of USER_ID and GID instead of GROUP_ID. Let me know if that fixes it for you!

**Comment by tam481** [comment]
Thank you. Works beautifully. 
Any chance you can update the documentation to show this. I think a few users could benefit from this :-)

Thank you so much

**Comment by Tzahi12345** [comment]
Awesome, I'll go ahead and convert this issue into a docs update request.

**Comment by Tzahi12345** [comment]
Done! [Check it out here](https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/README.md#custom-uidgid).
