### ISSUE TITLE
Container fails due to missing chown permissions on NFS share

### ISSUE THREAD

**Issue by slaecker** [Tzahi12345/YoutubeDL-Material#185]
I'm running the container in Kubernetes and the download directories (/app/audio, /app/video, /app/subscriptions, /app/users) on an NFS share. NFS doesn't allow chown so I manage the permissions in an init container before the main container is started.

But the main container fails to run when chown fails.

Container log:

```
chown: ./users: Operation not permitted
chown: ./users: Operation not permitted
chown: ./audio: Operation not permitted
chown: ./audio: Operation not permitted
chown: ./subscriptions: Operation not permitted
chown: ./subscriptions: Operation not permitted
chown: ./video: Operation not permitted
chown: ./video: Operation not permitted
```

Please change this so the failing chown only throws warnings instead of completely blocking the container from running.

**Comment by Tzahi12345** [comment]
Related issue: #146

Will try to add `|| true` tonight and see how that goes! But it might have implications down the road so I may have to ask for some testing help from you (nothing crazy, just downloading/deleting videos)

**Comment by Tzahi12345** [comment]
Pushed a potential fix! Can you try out the latest nightly using the `nightly` tag and seeing if it works? If you can, also try downloading/deleting a video to see if any downstream permissions issues crop up.

**Comment by slaecker** [comment]
Yep that fixes the issue.
As long as permissions are managed externally there is no problem downloading and deleting videos.

Maybe replace the `|| true` with something like `|| echo "WARNING! Could not change directory ownership. If you manage permissions externally this is fine, otherwise you may experience issues when downloading or deleting videos."`.

**Comment by Tzahi12345** [comment]
Done, check out the [latest commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/ee169cd7ce66242729f8afae35885099a6f35d35).

Thanks for the help fixing this bug! Will close.
