### ISSUE TITLE
OSError: [Errno 13] Permission denied: '/.cache'

### ISSUE THREAD

**Issue by powerdude** [Tzahi12345/YoutubeDL-Material#186]
i see this error a lot when i look in the logs.  Can you identify why it's happening?  This folder is in the docker container, so shouldn't it have access?

```
WARNING: Writing cache to u'/.cache/youtube-dl/youtube-sigfuncs/js_e49bfb00_107.json' failed: Traceback (most recent call last):
today at 11:05 PM File "/app/node_modules/youtube-dl/bin/youtube-dl/youtube_dl/cache.py", line 49, in store
today at 11:05 PM os.makedirs(os.path.dirname(fn))
today at 11:05 PM File "/usr/lib/python2.7/os.py", line 150, in makedirs
today at 11:05 PM makedirs(head, mode)
today at 11:05 PM File "/usr/lib/python2.7/os.py", line 150, in makedirs
today at 11:05 PM makedirs(head, mode)
today at 11:05 PM File "/usr/lib/python2.7/os.py", line 157, in makedirs
today at 11:05 PM mkdir(name, mode)
today at 11:05 PM OSError: [Errno 13] Permission denied: '/.cache'
```

**Comment by Tzahi12345** [comment]
Which Docker tag are you on? I pushed changes to the latest `nightly` today regarding permissions (chown is now skipped if it fails). Wondering if it's related.

**Comment by powerdude** [comment]
nightly

**Comment by Tzahi12345** [comment]
Ok! Yeah try pulling the latest nightly and see if that fixes it. Otherwise you can try recreating your container, and seeing if that fixes it.

Keep me updated if any of the above solutions work/don't.

**Comment by marcjmiller** [comment]
I know his hasn't seen any comments in awhile, but I ran into this spinning up an instance of `tzahi12345/youtubedl-material:nightly` install just now while my data exists on an NFS share (so chmod/chown is a no-go):

`Internal Server Error: error while creating mount source path '/mnt/appdata/config/Youtube/Video': chmod /mnt/appdata/config/Youtube/Video: operation not permitted`

It looks like during `RUN /bin/sh -c npm install && chown -R $UID:$GID ./ # buildkit` is causing the issue, and I'm not sure it is necessary?

**Comment by Tzahi12345** [comment]
@marcjmiller Have you tried setting the UID/GID to match that of the owner of the NFS share?

**Comment by marcjmiller** [comment]
Yes, I'm 99% sure it was deployed with pgid/puid 1000 which is the owner of the nfs share, but I will verify. The share is from TrueNAS with the setting to map all to user 1000 for all the other devices that use the share.

**Comment by tehniemer** [comment]
Same problem here, and the share is mounted with the same user and group as the container.

**Comment by Tzahi12345** [comment]
Maybe a temporary (bad) solution is to chmod 777 the entire node_modules folder through `docker exec -t /bin/sh`

**Comment by ninjachamp** [comment]
I am getting this error as well. I'm running it on Unraid which I downloaded from community applications. I believe my docker settings are default in terms of permissions:

YTDL_UMASK: 000
UID: 99
GID: 100

When I do ls -la from the docker's console I noticed that the user is 99 and group is users. All my other dockers have the same umasks setup but permissions seem to be root:root inside those dockers and I have no permissions issues with them. 

I chmod 777'd the download and appdata directories that this docker uses but it doesn't seem to have made a difference. This is the only docker I have this issue with. Thank you for any help and thank you for your work on this docker!

**Comment by GlassedSilver** [comment]
Try adding this to your docker template

![image](https://user-images.githubusercontent.com/1912133/135749624-3ac7874b-f3ef-46d7-a4e6-5b6e09cc4c1b.png)

sample:

![image](https://user-images.githubusercontent.com/1912133/135749628-13acfe02-80ac-49b5-bb80-1b59c3934349.png)

Maybe it's about time I add the template that I use to the CAs. :P

**Comment by GlassedSilver** [comment]
I think this is resolved by now?

I'll add the response needed label to this issue, so if there is no reply by the original author of the issue it will auto-close, however anyone is welcome to point out they still experience this issue and I will re-open. :)

Certainly permissions handling has received some attention by now, so I take it, it's safe to assume we consider this done, but I'll not close right away as I said.

Thank you everyone for your feedback! 👍
