### ISSUE TITLE
Add option to download both audio and video in one go

### ISSUE THREAD

**Issue by CountParadox** [Tzahi12345/YoutubeDL-Material#187]
Hello, 

I added a playlist to the subscription section, and I checked audio only. 

I then added the same playlist again intending to this time get the video as well, but an error is thrown that says the playlist with that URL already exists.

Perhaps rather than just 'audio only' an option such as 'include audio' can also be included, and if checked, it will download the audio separately to the video (extract it seperate?) and if audio only is checked, it behaves as now.

Just an idea

**Comment by Tzahi12345** [comment]
I should drop the URL restriction and simply force them to have different names. Then you can have "PewDiePie" and "PewDiePie - Audio" or something like that.

Making it download both in one go isn't trivial -- I'd have to run two downloads (or ffmpeg all the downloads to extract). I think what's more important (short term at least) is allowing a channel/playlist to allow both audio and video downloads. I'll look into it this weekend!

**Comment by CountParadox** [comment]
Yeah! That would work great tooOn 8 Aug 2020 3:55 pm, Tzahi12345 <notifications@github.com> wrote:
I should drop the URL restriction and simply force them to have different names. Then you can have "PewDiePie" and "PewDiePie - Audio" or something like that.
Making it download both in one go isn't trivial -- I'd have to run two downloads (or ffmpeg all the downloads to extract). I think what's more important (short term at least) is allowing a channel/playlist to allow both audio and video downloads. I'll look into it this weekend!

**Comment by Tzahi12345** [comment]
Fixed! [Here's the relevant commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/52bee8b280fe6df5ead1b164106f9b235dea5f42). Basically, you can now add a subscription with the same URL, but the new subscription must contain a custom name. Make sense?

I think this is a decent workaround, use the latest `nightly` to get this ability!
