### ISSUE TITLE
Trim the final output to the desired length

### ISSUE THREAD

**Issue by RashiqAzhan** [Tzahi12345/YoutubeDL-Material#189]
Maybe a feature that cuts the last/first x seconds of the video, audio from subscription or manual download. Also the ability to adjust the value after a subscription has been made without deleting the entry and making a new one.

It could allow for selecting the segments that is desired. E.g. For a 3 hour video I want the first and last 30 minutes of the entire video into a single 1 hour video.

**Comment by RashiqAzhan** [comment]
Love your work Mr.12345 by the way.

**Comment by Tzahi12345** [comment]
Glad you like it :)

This is certainly possible with [ffmpeg](https://superuser.com/a/682534/1032603), but things can get very messy as we can't necessarily predict the length of videos in a subscription. Of course we can figure it out after the fact (once it's downloaded), but a problem still exists: what if you want to cut out the first and last 30 mins of a subscription's video, but the video is only 45 minutes long? What about 15 minutes? Do we want to just not trim those videos?

Regarding being able to edit this without unsubscribing and resubscribing, I have already added a modify subscriptions dialog in the latest `nightly` tag on Docker, so we can just use that!

**Comment by RashiqAzhan** [comment]
I wonder if something straight forward exists that can handle most situations? Say,
x = total length
ht = head trim length
et = end trim length
if x < ht + et : don't trim
Would this work in most cases?

One caveat is that maybe someone doesn't want the intro, or outro, of the video, so they would be able to select whichever one makes the most sense but what if they select both that results in the playtime of the video in the negative?
E.g. Video of 30 minutes exists. Someone one puts in the data to trim the first 10 minutes and the last 25 minutes. Obviously the total trimmed amount that exceeds the total playback time (10+25)35 > 30. But the individual trims don't however exceed the total amount. Maybe someone can choose to prioritize the trims in an order where the content is chopped up according to the priority?
So either the 10 or 25 is applied but not both. If priority is not stated then don't apply anything. Or am I overthinking this.

**Comment by GlassedSilver** [comment]
Maybe instead of trimming the file we could offer to set play markers?
Similar to how this works:
https://github.com/ajayyy/SponsorBlock/wiki/Android

**Comment by Tzahi12345** [comment]
This has been implemented for quite a while, in advanced download mode you can crop a file to its desired length!
