### ISSUE TITLE
Add links from a file

### ISSUE THREAD

**Issue by RashiqAzhan** [Tzahi12345/YoutubeDL-Material#190]
Like import all the download links from a csv. The multi download feature requires adding the links one by one as far as I can see.

**Comment by Tzahi12345** [comment]
Related issue: #119 

Looks like youtube-dl (the underlying youtube downloading library) [already supports](https://superuser.com/a/1411838/1032603) downloading videos straight from a text file using the `-a` parameter. I'll have to play around with this to see how I could best integrate that feature with this app (file uploader?). There's currently a home page redesign in the works (#106) so I'll see if I can add this in with the redesign.

Thanks for the suggestion!

**Comment by RashiqAzhan** [comment]
It does. It was my go to till I found [youtube-dl-gui](https://github.com/MrS0m30n3/youtube-dl-gui) whenever 4k Video Downloader inevitably failed.
I'm sure a drag-n-drop feature should suffice for the file uploader as you say. Would it be possible to make it accept multiple files in a single dran-n-drop movement, much like how Google drives do it? That should make life easier for people with hundreds of .csv files without having to concatenate them.

[youtube-dl-gui](https://github.com/MrS0m30n3/youtube-dl-gui) had a window where you could paste all the links from clipboard that you had taken from a notepad or from tabs open in a web browser and it would go from there. It's quire old and written in Python 2 so doesn't really translate to this project directly. Could be something for the home screen.
It works something like this.
![youtube-dl-gui multi file download](https://user-images.githubusercontent.com/7370540/89720709-7c2d0800-d992-11ea-8a9b-5dd599ce9a86.gif)

**Comment by jimbobcraig** [comment]
would importing subscriptions from a file be a possible addition too?

i have a file from another youtube-dl container (jeeaaasustest/youtube-dl) with no gui and would like to migrate.

for me, this would be a one off process, so I could cope with some text-wrangling in the process. (list of channel ids ...etc)

perhaps there is already a way to fudge these into the db?

**Comment by GlassedSilver** [comment]
> would importing subscriptions from a file be a possible addition too?
> 
> i have a file from another youtube-dl container (jeeaaasustest/youtube-dl) with no gui and would like to migrate.
> 
> for me, this would be a one off process, so I could cope with some text-wrangling in the process. (list of channel ids ...etc)
> 
> perhaps there is already a way to fudge these into the db?

This is a bit of a separate issue and since YoutubeDL-Material supports downloading a list of videos by URL in the text box on the home page now I'll close the issue. (IDK why it never got closed, probably we forgot to mark as solved)

Feel free to create a new issue from your suggestion, although not gonna lie, implementations of new features right now will attract my humble request to submit PRs, since I'm mostly dealing with support, ideas, taking care of keeping dependencies running (shared props to Dependabot lol), because quite frankly, I'm not much of a coder.
