### ISSUE TITLE
Unable to subscribe to a channel with Cyrillic in the url

### ISSUE THREAD

**Issue by RashiqAzhan** [Tzahi12345/YoutubeDL-Material#191]
[The channel in question](https://www.youtube.com/c/%D0%9A%D0%A0%D0%98%D0%A7%D0%90%D0%A9%D0%98%D0%99%D0%9D%D0%90%D0%93%D0%9B%D0%9E%D0%91%D0%A3%D0%A1/videos?disable_polymer=1).

It seems the Cyrillic is throwing it off somehow as nothing else is standing out to me.
![image](https://user-images.githubusercontent.com/7370540/89721176-8c93b180-d997-11ea-8d93-936b9806d515.png)
It stays like this even after a half a day. It doesn't parse the channel name automatically either.
I tried manually naming it but that doesn't help. (Not that it would but just trying things here)
The folder never gets created in …\youtubedl-material\subscriptions\channels
Quite perplexing.

**Comment by Tzahi12345** [comment]
This might be a [related issue](https://github.com/ytdl-org/youtube-dl/issues/26248) for the bug in the youtube-dl code. I even tried decoding the encoded URL and got the same error (404). Will keep an eye on this, hopefully someone from youtube-dl gives a proper response/workaround.

**Comment by GlassedSilver** [comment]
Marked as resolved over at youtube-dl in the linked issue and should also be fixed in any of the forks we use (yt-dlc and yt-dlp).

Hence, I'll close this issue. If a similar issue occurs again, please write a new one, because then it'll probably related to something else being off.

Cheers!
