### ISSUE TITLE
Add Date Uploaded to file name

### ISSUE THREAD

**Issue by Adarack** [Tzahi12345/YoutubeDL-Material#193]
Would it be possible to add the option to add the date uploaded to YouTube to the front of the filename? Preferably in Year-Month-Day format?

It would help a fair bit with Subscriptions and archive downloads of various channels.

Thank you.

**Comment by Tzahi12345** [comment]
This is quite easy to add yourself if you're running the latest `nightly`. Simply edit your subscription (or create a new one), and put this as your "Custom file output":

`%(upload_date)s - %(title)s`

Your videos will then have the upload date in YYYYMMDD format prior to the file name. You can view all the possible variables for the output name [here](https://github.com/ytdl-org/youtube-dl#output-template) (called "output template"). Let me know if this helps!

**Comment by Adarack** [comment]
Thank you so much!

I hadn't looked at subscriptions, I was just downloading a few selected videos.  Would probably be much easier to setup a playlist and use the subscriptions.

Thank you for all your hard work.

**Comment by Tzahi12345** [comment]
Good news is you can still use this feature outside of subscriptions, just enable "Allow advanced download" in the `Advanced` tab in the settings, and you'll have a new expandable menu on the home screen where you can input your "Custom output" for regular downloads.
