### ISSUE TITLE
Subscription videos downloaded, but not showing in Web UI

### ISSUE THREAD

**Issue by adan89lion** [Tzahi12345/YoutubeDL-Material#194]
Steps to reproduce:
1. Subscribe to a channel.
![스크린샷 2020-08-13 오후 8 00 06](https://user-images.githubusercontent.com/6585644/90131949-89396500-dd9f-11ea-8ca9-fede6aacae94.png)

2. I can see the videos are being downloaded (in host machine), but the YoutubeDL-Material Web UI doesn't update the list.
![스크린샷 2020-08-13 오후 8 01 18](https://user-images.githubusercontent.com/6585644/90132049-b259f580-dd9f-11ea-9e86-bef7a846d1de.png)

3. Restart the container and the list isn't being refreshed (still empty).

Addition notes:
In the ``users.json`` file, I can see that the subscription link is registered in the file, but the ``videos`` section is empty
![스크린샷 2020-08-13 오후 8 03 32](https://user-images.githubusercontent.com/6585644/90132228-02d15300-dda0-11ea-8a7b-41f4cef68ded.png)

Possible solution:
- Create a method to recheck the filesystem periodically to refresh internal database and remove deleted videos from the database)?

**Comment by Tzahi12345** [comment]
Looks like it was in the middle of checking the subscription (at least before it was stopped).

A little backstory: beforehand we would get subscription videos by checking the directory every time to find videos and their associated JSON files. This changed in v4.1 where we now store the downloaded videos in the `videos` array in the `users.json` file (in the case of multi-user mode).

So why didn't the downloaded videos appear in the `videos` array? Well, they are only added to the array after the entire subscription is checked. So if you want to download every video, you'll have to wait until all of them are done to see them show up. I wish I could do it piecemeal (i.e. one by one as they are downloaded) but this is not currently possible.

Here's my suggestion: wait until the entire subscription is done downloading, and avoid restarting the container. If it's taking an insane amount of time, this may either point to a bug, throttling, or poor internet connection, so let me know if you experience this.

>Create a method to recheck the filesystem periodically to refresh internal database and remove deleted videos from the database)?

This is a great solution which would solve this problem pretty well. Not sure whether I'd want to do this periodically or just on startup, as I don't want to interfere with the normal downloading process and potentially create duplicate entries (what if the import and the download happens at the same time?)

Anyways, I appreciate the report! I'll label this as an enhancement for now until we get a solid workaround.

**Comment by Tzahi12345** [comment]
Fix implemented! See PR #195. Pull the latest `nightly` and restart your container, your files should be there A-OK!
