### ISSUE TITLE
Not working on pi4

### ISSUE THREAD

**Issue by frezeen** [Tzahi12345/YoutubeDL-Material#199]
this is error from logs
standard_init_linux.go:211: exec user process caused "exec format error"

installed with docker compose latest

**Comment by frezeen** [comment]
solved , my error , i have to pull arm arch
zahi12345/youtubedl-material:nightly-arm

**Comment by Tzahi12345** [comment]
The master branch currently has issues building with ARM (should be resolved within the next couple days). In the meantime the `nightly-arm` is up to date and should work without issue!

**Comment by SuperSandro2000** [comment]
@Tzahi12345 The problem is probably caused by the buildtime of the armhf Image. I tried it locally with a not to bad machine and it took 35 minutes. The Docker HUB infrastructure is an order of magnitude slower than my machine and probably would take 1 to 3 hours and the build is canceled.
