### ISSUE TITLE
No player is shown

### ISSUE THREAD

**Issue by mzch** [Tzahi12345/YoutubeDL-Material#20]
I download 3.3 release and run `node app.js` but once finished downloads, no player was shown.
Why?

![Shot005](https://user-images.githubusercontent.com/621178/75945229-f980b800-5edc-11ea-90e9-cef33ee62b15.png)

Server: Debian 10.3, ffmpeg 4.2.2
Client: Google Chrome  80.0.3987.122

**Comment by mzch** [comment]
p.s.
Please add necessary of ffmpeg installation to README.

**Comment by Tzahi12345** [comment]
I've experienced this issue once on chrome, I haven't been able to figure out what's wrong. Can you try using Firefox and see if the issue persists? I believe it's chrome-only but I just want to be sure.

Regarding ffmpeg, it was my understanding that youtube-dl depended on it. As a result, I assumed it would be grabbed along with it.

**Comment by mzch** [comment]
Hi @Tzahi12345 I tried Firefox and it works well.
Safari and Vivaldi don't show no player.

**Comment by Tzahi12345** [comment]
Tracked down the bug! I'll release a hotfix ASAP (will be travelling shortly so that may interfere) that fixes this. Thanks for helping me track it down!

**Comment by Tzahi12345** [comment]
Issue has been fixed in the latest update, check it out [here!](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v3.4)
