### ISSUE TITLE
Traduction [FR]

### ISSUE THREAD

**Issue by Halfayd** [Tzahi12345/YoutubeDL-Material#204]
Bonjour tout le monde,
Pour améliorer l'interface utilisateur, voici la traduction officielle [FR] pour "YoutubeDL-Material" par Tzahi12345.
L'auteur l'intégrera dans une prochaine version.

lien du fichier .xlf : [https://github.com/Halfayd/YoutubeDL-Material-FR/blob/master/messages.fr.xlf](https://github.com/Halfayd/YoutubeDL-Material-FR/blob/master/messages.fr.xlf)

**Comment by Tzahi12345** [comment]
Merci! I tested it and it looks great. Awesome work!

Do you by any chance have the original XLIFF file? The file that's provided is actually in JSON format which is actually all we *really* need, but the XLIFF includes the original text and is easy to use with other translation tools.

Also if you'd like, you can open up a PR, but we can do it this way if you're more comfortable with that.

**Comment by Tzahi12345** [comment]
French translations have now been added! Use the latest `nightly` to check it out.

It's not complete though, if you'd like to do that you can do so at this link: https://hosted.weblate.org/projects/youtubedl-material/ytdl-material/fr/
