### ISSUE TITLE
add kodi support

### ISSUE THREAD

**Issue by frezeen** [Tzahi12345/YoutubeDL-Material#207]
please can u add this routine in your program?
https://github.com/tmechen/youtube-dl2kodi
its a py script that create a .nfo used from kodi to localscan metadata, its use youtubedl output datas

the big world of kodi dont have a youtube metadata scraper.. if u implement this fuction its the only way to manage downloaded video with yputubedl on kodi with metadata and images.

**Comment by Tzahi12345** [comment]
Great suggestion! I'd prefer reimplementing the python script in JavaScript than using the python directly (if something goes wrong while generating the `.nfo` we'll have a better idea why).

Seems like a simple task, generate an XML which looks like this:

```
<episodedetails>
	<title>
		json['fulltitle']
	</title>
	<episode>
		json['playlist_index']
	</episode>
	<premiered>
		json['upload_date']
	</premiered>
	<plot>
		json['uploader_url']
		json['description']
		json['playlist_title']
	</plot>
</episodedetails>
```

There can be a setting to enable autogeneration of .nfo files in the `Extra` tab in the settings. If that setting is enabled, we can use [xmlbuilder2](https://github.com/oozcitak/xmlbuilder2) to generate the XML in the backend when each download finishes.

This would make it so every download would have a `.nfo` file. Would this be annoying, and so you would prefer doing it on a file by file basis?

Let me know what you think!

**Comment by frezeen** [comment]
To have a choice Is Better Always , i think a on/off Button Is Better ☺️ thanks for your Great support

**Comment by frezeen** [comment]
hi, i see u add the .nfo creation, now video music liberary of kodi detect the videos downloaded with youtubedl,work perfect for metadata. u are great, thanks
One question only, i use --write-thumbnail for to download thumbnail but kodi dont detect it, use a screen grabbed from video.
can u add in ,nfo the use of downloaded image from youtubedl with --write-thumbnail ?

**Comment by Tzahi12345** [comment]
Done! [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/562eaa1b9b5c15ac2052eaf953d24b5e58156c5f).

You can begin using this with the latest `nightly`.

Sorry for the delay! It's been a busy year :P
