### ISSUE TITLE
[CC] download along with videos

### ISSUE THREAD

**Issue by carb0nxl** [Tzahi12345/YoutubeDL-Material#211]
Hello - Apologies if this is not the proper way to ask this. I am new at github / setting up my containers in unRAID.

I have youtube-dl material running in a container on my unRAID machine. I've experienced the CLI version on macOS and I like this container because the webpage (and the browser plugin) just makes it such a snap.

However - I am Deaf so I depend on pulling the [CC] files from the videos and I know the command line version can do it, but how do I enable this feature in docker? More specifically for unRAID.

**Comment by Tzahi12345** [comment]
You're in the right place!

Is there any difference between CC and regular old subtitles? If not, then this should be quite easy! Go into the settings and add the following to the custom args in the Downloader tab: `--write-sub`. Subs should be downloaded alongside the video. Let me know if you need any help getting that set up.

[Here's a short list](https://superuser.com/questions/927523/how-to-download-only-subtitles-of-videos-using-youtube-dl/927532#927532) of some additional subtitle-related args. Hope this helps! If not, feel free to reach out.

**Comment by carb0nxl** [comment]
> You're in the right place!
> 
> Is there any difference between CC and regular old subtitles? If not, then this should be quite easy! Go into the settings and add the following to the custom args in the Downloader tab: `--write-sub`. Subs should be downloaded alongside the video. Let me know if you need any help getting that set up.
> 
> [Here's a short list](https://superuser.com/questions/927523/how-to-download-only-subtitles-of-videos-using-youtube-dl/927532#927532) of some additional subtitle-related args. Hope this helps! If not, feel free to reach out.

Thank you so much! I had no idea that was where we could add more arguments (I didn't consider "arg" as argument).
That did the trick - I now can download videos with subs attached. Cheers!

**Comment by Tzahi12345** [comment]
Awesome, great to hear! Perhaps I need to make "arg" a bit more explicit, otherwise it sounds like we're a bunch of pirates haha

Glad I could help, feel free to open up another issue if you encounter any other issues
