### ISSUE TITLE
Link to API docs dead

### ISSUE THREAD

**Issue by dugite-code** [Tzahi12345/YoutubeDL-Material#213]
The direct link to:
https://stoplight.io/p/docs/gh/tzahi12345/youtubedl-material?group=master&utm_campaign=publish_dialog&utm_source=studio is 

in Readme is re-directing to:
https://stoplight.io/welcome

There dosn't appear to be any way to reach the API docs. Tested in both Firefox and Chrome so might be a change with stoplight.io?

**Comment by Tzahi12345** [comment]
Fixed! Looks like spotlight's old system got deprecated, I moved the repo over to the new one and updated the link. Thanks for the heads up!
