### ISSUE TITLE
Not downloading best quality?

### ISSUE THREAD

**Issue by mikestecker** [Tzahi12345/YoutubeDL-Material#217]
First off - awesome project, thanks for putting this together! I'm running in docker.

Is there a limit to what quality this can download? I've tried a few different videos and they all seem to download sub-par quality (compared to my Homebrew's command-line `youtube-dl`) even though I've tried the "Max" and 1080 settings.

For example, this video (just random one I chose to test): https://www.youtube.com/watch?v=sj9J2ecsSpo

with YoutubeDL-Material, the file is 7.4mb:
<img width="334" alt="Screen Shot 2020-09-21 at 11 21 46 AM" src="https://user-images.githubusercontent.com/407465/93805493-af52f000-fbfc-11ea-8595-bc8b2aeb585a.png">

but when I use my Mac's homebrew CLI `youtube-dl`, I get a much larger, higher-quality file at 19.2mb:
<img width="345" alt="Screen Shot 2020-09-21 at 11 21 53 AM" src="https://user-images.githubusercontent.com/407465/93805512-b548d100-fbfc-11ea-88b7-6ec29dcb2496.png">

I'm using all the default settings with the project. Is there something I might have missed in the config possibly?

**Comment by Tzahi12345** [comment]
There used to be a limit, it was a bug though. Actually in 4.1 even this problem exists, but it has since been fixed :) See #76. 

Can you try using the `nightly` tag on Docker? It has the fix included among other improvements since v4.1.

**Comment by mikestecker** [comment]
@Tzahi12345 that fixed it! I was running the `latest` tag, but switching to `nightly` fixed it.

**Comment by Tzahi12345** [comment]
Awesome, great to hear. If you have any other problems or suggestions feel free to create another issue!
