### ISSUE TITLE
Multiple page view for main page.

### ISSUE THREAD

**Issue by jonathanm-ur** [Tzahi12345/YoutubeDL-Material#225]
Since I have thousands of videos indexed, it takes a very long time to populate the main page.

Could you add a limit, perhaps display 20 or 50 per page, so rendering doesn't take forever?

Maybe have a dropdown with options to show X per page or all, depending on user preference?

**Comment by Tzahi12345** [comment]
That is a great point, I did not consider what would happen if a user has hundreds or thousands of videos! What you're referring to is called "pagination." This is pretty easy to add as the UI library we use already has a [pagnitor component](https://material.angular.io/components/paginator/overview).

Will look into this, thanks for the suggestion!

**Comment by Tzahi12345** [comment]
This is done, check out the latest `nightly`!
