### ISSUE TITLE
Delete Videos from Subscriptions

### ISSUE THREAD

**Issue by chall32** [Tzahi12345/YoutubeDL-Material#227]
There is an option to delete individually downloaded videos using the 3 dot button on the top right of the video, however the delete option doesn't appear on videos from subscriptions. 

Options listed are:
- Info
- Go to subcription
- Delete and redownload

Any chance of adding a delete option to videos from subscriptions?

Unless I'm missing something? (Definitely possible!!)

**Comment by Tzahi12345** [comment]
It is possible! But it requires enabling the youtube-dl archive feature in the settings (I think the Downloader tab but don't quite me on that)

The reason for this is that the "delete and redownload" button actually only deletes the video. It's simply assumed the video will be redownloaded once the subscription is checked again.

With the youtube-dl archive feature, the ID of the video is added to a txt file which is used to ignore previously downloaded videos. The "delete and blacklist" option should appear after enabling it, and I assume this is what you're looking for.

One caveat here is that if you download a video and try redownloading it, the download will fail (as the file already exists in the archive). I could probably do some intelligent error checking here. Anyways, let me know if you have any other questions/suggestions!
