### ISSUE TITLE
Failed retrieving video info

### ISSUE THREAD

**Issue by adan89lion** [Tzahi12345/YoutubeDL-Material#228]
Here is the logs
``2020-10-09T12:11:37.807Z ERROR: Error while retrieving info on video with URL https://www.youtube.com/watch?v=yfH5H2oO8i0 with the following message: Error: Command failed with exit code 2: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -o users/seohyeon/video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --cookies appdata/cookies.txt --write-thumbnail  http://www.youtube.com/watch?v=yfH5H2oO8i0``

I tested in my local terminal and found out that the ``-o`` flag's argument ``users/seohyeon/video/%(title)s.mp4`` needs to be quoted, otherwise will cause ``syntax error near unexpected token `('`` output.

**Comment by Tzahi12345** [comment]
Can you try reloading your cookies or disabling it entirely? I've noticed that the error when retrieving info can happen with outdated cookies.

**Comment by adan89lion** [comment]
After disabling cookies, the video still can't be retrieved. The following is logs produced when pharsing a video.
``
2020-10-11T11:50:42.069Z ERROR: Error during parsing:Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json http://www.youtube.com/watch?v=9aDEq3u5huA
2020-10-11T11:50:42.069Z ERROR: failed to parse for urls starting with https://www.youtube.com/watch?v=9aDEq3u5huA
``

**Comment by GlassedSilver** [comment]
Hey, sorry for getting back to you so late, but can you see if this still occurs on the latest nightly build of YTDL-M?

Thank you for helping to make YTDL-M a better app.

**Comment by adan89lion** [comment]
Hi, after using `yt-dlp` a while ago solves this issue since it's better at restriction bypassing.
