### ISSUE TITLE
Resubscribe to unsubscribed channel not possible

### ISSUE THREAD

**Issue by colbach** [Tzahi12345/YoutubeDL-Material#229]
If an previously unsubscribed channel is readded the channel shows of in the list but there are no actual videos downloaded and there is no folder recreated.

**Comment by Tzahi12345** [comment]
Hm do you have any other details, such as logs or errors that came up?

This might be an obscure bug that only happens in edge cases. Or the channel could just be taking a while to download, but that seems unlikely (the directory would be created in that instance)

**Comment by colbach** [comment]
It basically happens on all resubscribed channel. There is nothing obscure in the logs. Can you test with a random channel of your choice if this works in your instance?

**Comment by GlassedSilver** [comment]
I have a sneaky suspicion what may have caused this: a dangling subscription archive causing the instance to believe everything had already been downloaded. But I may be off. I can investigate this soon if you like, but you can also tell me if this should have ever resolved on your end.

In any case, I checked our API and the function to delete the archive should have been there by the time you created this issue.

Maybe you try the latest nightly build and report back, if you don't mind @colbach?

Thank you for your issue in any case, and sorry for getting back to you so late, I'm currently going through old issues that got pushed out of sight by an influx of activity on this repo around the time you created this issue at.

**Comment by Tzahi12345** [comment]
Closing as this is very old, likely not an issue anymore.
