### ISSUE TITLE
volumes

### ISSUE THREAD

**Issue by tborychowski** [Tzahi12345/YoutubeDL-Material#23]
Hi,

Firstly - thank you so much for this tool.
I tested many and this is the only one that worked for me!

I'm using the docker version and was wondering why it's not possible to mount a volume, so I can have the files downloaded to the docker host.
I added sth like this:
```
        volumes:
            - ./video:/video
```
but it doesn't work.
The videos are downloaded and when I check inside the docker container - it is there in the `/video` folder, but the folder outside of the container is empty...

Also - should the `ytdl_download_only_mode` mode (when it's set to true) provide a way for the user to download the video in the browser somehow?
Because when I set this to true (and the `ytdl_file_manager_enabled` to false) - nothing happens after the video is downloaded...

**Comment by hjyoung1** [comment]
> I'm using the docker version and was wondering why it's not possible to mount a volume, so I can have the files downloaded to the docker host.
> I added sth like this:
> 
> ```
>         volumes:
>             - ./video:/video
> ```
> 
> but it doesn't work.
> The videos are downloaded and when I check inside the docker container - it is there in the `/video` folder, but the folder outside of the container is empty...

Change volume to 
```
-  ./video:/app/video
```

**Comment by tborychowski** [comment]
@hjyoung1 thanks for that!
