### ISSUE TITLE
Option to change date format on homepage

### ISSUE THREAD

**Issue by trinsic** [Tzahi12345/YoutubeDL-Material#232]
Would be nice to be able to change the date format in settings e.g MM/DD/YY, DD/MM/YY, YY/MM/DD etc. Because most countries outside of North America use DD/MM/YY.

From the individual json file I see that youtube/yt-dl puts it in the format of YYYYMMDD.
From the db.json file I see YYYY-MM-DD.
On the homepage it changes to MM/DD/YY. This one would be nice to change.

**Comment by Tzahi12345** [comment]
Just implemented! Check out #235. Sorry for the delay in responding, been crazy busy lately :P
