### ISSUE TITLE
Nightly - Running on Proxmox with Share on Synology

### ISSUE THREAD

**Issue by hankman13** [Tzahi12345/YoutubeDL-Material#233]
I had great days running this application (nightly) in Docker, but now it stops working.
I removed old images and run again, I get this error message

`...
ytdl_material_1  | chown: ./video/Make a Realistic Flamethrower in Blender - Iridesium.mp4: Operation not permitted
ytdl_material_1  | WARNING! Could not change directory ownership. If you manage permissions externally this is fine, otherwise you may experience issues when downloading or deleting videos.
ytdl_material_1  | /app/node_modules/lowdb/adapters/FileSync.js:42
ytdl_material_1  |           throw e;
ytdl_material_1  |           ^
ytdl_material_1  | 
ytdl_material_1  | SyntaxError: Malformed JSON in file: ./appdata/db.json
ytdl_material_1  | Unexpected end of JSON input
ytdl_material_1  |     at FileSync.parse [as deserialize] (<anonymous>)
ytdl_material_1  |     at FileSync.read (/app/node_modules/lowdb/adapters/FileSync.js:37:30)
ytdl_material_1  |     at LodashWrapper.db.read (/app/node_modules/lowdb/lib/main.js:32:21)
ytdl_material_1  |     at module.exports (/app/node_modules/lowdb/lib/main.js:51:13)
ytdl_material_1  |     at Object.<anonymous> (/app/app.js:42:12)
ytdl_material_1  |     at Module._compile (internal/modules/cjs/loader.js:1137:30)
ytdl_material_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
ytdl_material_1  |     at Module.load (internal/modules/cjs/loader.js:985:32)
ytdl_material_1  |     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
ytdl_material_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
ytdl_material_1  |     at internal/main/run_main_module.js:17:47`

Any idea what I have to change?

**Comment by Tzahi12345** [comment]
It sounds like a permissions issue, I thought the patch for #185 fixed this but I guess not. I think running the container with the root UID/GID ([see here](https://github.com/Tzahi12345/YoutubeDL-Material#custom-uidgid)) should solve this issue. Can you try that and see if the chown succeeds?

**Comment by hankman13** [comment]
Meanwhile I tried to delete the db.json and rerun the docker up command. This already solved the issue.
