### ISSUE TITLE
Allows to register a new empty user with an empty password

### ISSUE THREAD

**Issue by theRAGEhero** [Tzahi12345/YoutubeDL-Material#239]
Hello, I love your software!
I saw that is possibile to register a new empty user with an empty password that can't actually login and cannot be deleted.
Thank you!
Alessandro

**Comment by Tzahi12345** [comment]
Weird that it can't be deleted, I just tested out creating an account with no password and deleting was possible. BUT I did get the issue where I couldn't log in with that account.

Do you see an error pop up in the browser or server console when you try to delete?

The solution here might be to prevent users from creating accounts with empty passwords.

**Comment by theRAGEhero** [comment]
Oh, you are riht. I just checked now and I don't see anymore the 'empty' user.

**Comment by Tzahi12345** [comment]
>The solution here might be to prevent users from creating accounts with empty passwords.

Done! See the [latest commit.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/1542436e967676a6861986b86bdde04f971517a9)

**Comment by frakman1** [comment]
I don't understand what is meant by user? I've used the docker version of this webapp and it works without ny user knowledge.

**Comment by Tzahi12345** [comment]
If you enable multi-user mode and register a new user without a password, it's impossible to log in with that user. It's more preventing user error than a feature.
