### ISSUE TITLE
Add possibility to set ID3 tag of audio file

### ISSUE THREAD

**Issue by LukasK13** [Tzahi12345/YoutubeDL-Material#24]
It would be great to have the possibility to set the ID3 tag of the audio file before creating it, as can get pretty messy in software like iTunes which uses the song title from the ID3 tag rather than the file name.

**Comment by Tzahi12345** [comment]
Good idea! I see there's already a [node library](https://www.npmjs.com/package/node-id3) that supports this. I'll see if I can get it included in the next update.

**Comment by Tzahi12345** [comment]
This feature has been implemented and merged into the master branch! The next update will have automatic tagging functionality for mp3s.

Check out the associated PR [here](https://github.com/Tzahi12345/YoutubeDL-Material/pull/35/)

**Comment by LukasK13** [comment]
Awesome, thank you very much for your great work.
