### ISSUE TITLE
'public mode' for YoutubeDL-Material

### ISSUE THREAD

**Issue by theRAGEhero** [Tzahi12345/YoutubeDL-Material#240]
Hello!
I'd like to embed YoutubeDL-Material into my website. Is it a way to let people download without doing any login? 
I know that is possbile if you don't create the Admin user...
Could you please help me? 

Thank you in advance,
Alessandro

**Comment by Tzahi12345** [comment]
Hi!

This should be possible, but it does require you to disable multi-user mode. If you want the app to behave like most public youtube downloaders, you can disable the file manager and enable download only mode in the _Extra_ tab in the settings. Hope this helps!
