### ISSUE TITLE
Ability to blacklist video title word combinations

### ISSUE THREAD

**Issue by jonathanm-ur** [Tzahi12345/YoutubeDL-Material#242]
I would like the ability to never download videos that contain a specific string in the title while still downloading all the other videos in a subscription or playlist.

Global or playlist / sub specific would work fine for my needs, but per subscription would be better overall in my opinion.

The specific example is a video that never changes content, but the title is changed every time the like counter is changed. That means every time that subscription is scraped it detects the new video and downloads it again, wasting bandwidth, storage, and hits on the site.

**Comment by Tzahi12345** [comment]
Should be relatively easy to do! Edit the subscription (or you can do this when you subscribe), and head down to the Custom args option. Just add the `--reject-title REGEX` arg, replacing REGEX with a regex expression that matches the titles you want to ignore. For example, if the videos have the string `[COUNTER]` at the beginning of the title, `--reject-title [COUNTER]` should ignore those videos. I think, unless they want you to match the whole line, in which case `--reject-title .*[COUNTER].*` will work too.

Let me know if this works! You can also do this globally in the settings as well if you need that for whatever reason.

**Comment by jonathanm-ur** [comment]
This has started showing up in my logs.
`
youtube-dl: error: no such option: --reject-title`

**Comment by Tzahi12345** [comment]
Make sure you put double commas between the regex expression and the arg title itself, the "custom arg" field should look like this: `--reject-title,,REGEX`. Sorry for the confusion, should've made that clear!

**Comment by Tzahi12345** [comment]
I'm gonna go ahead and close this issue unless you're still facing this problem, let me know if it still persists!

**Comment by jonathanm-ur** [comment]
After getting the error message, I can no longer get any custom arg to save, so I don't know if it's working or not.

To be clear, I added the arg, --reject-title [This Video Has]
and started getting the error. I read up on regex, and determined (maybe falsely?) that the square brackets are NOT a delimiter, rather they are interpreted literally, so I removed the custom arg and tried to correct it, but what I put in originally wouldn't stay gone. I finally removed it manually from the db.json file, but now I can't add any custom arg at all, the field accepts my input, and clicking save appears to do something, in that it changes to an inactive button after a few seconds, but when I go out and back in to the sub, the custom arg field is blank again.

**Comment by Tzahi12345** [comment]
Looks like you found a nasty bug there with editing the subscription! I've gone ahead and fixed it, the latest `nightly` should include this fix (should be uploaded about 10 mins after I send this comment).

Just found this out, but it looks like you should also surround the regex with a single quotation mark ([see example here](https://stackoverflow.com/a/59906533/8088021))

Square brackets look like they're a [special character](https://sc1.checkpoint.com/documents/R76/CP_R76_IPS_AdminGuide/12885.htm) in regex. Regex confuses me too, I use [this helpful tool](https://regex101.com/) to test expressions and get a better handle on it. You can "escape" the special characters by adding a backslash before it, like so: `--reject-title,,'\[This Video Has\]'`. Don't forget the double commas ;) You can take the easier approach and just reject titles that have `This Video Has` like so: `--reject-title,,'This Video Has'`

**Comment by jonathanm-ur** [comment]
The custom arg (--reject-title,,'This Video Has') is properly in place, both in the GUI and db.json.

However, the videos continue to be downloaded, pretty much every few hours.
This Video Has 59,459 Likes (That's 1,697,839 Fewer Than Tom's!)
This Video Has 59,459 Likes (That's 1,698,712 Fewer Than Tom's!)
This Video Has 59,460 Likes (That's 1,699,604 Fewer Than Tom's!)
