### ISSUE TITLE
Downloaded videos not showing in UI 

### ISSUE THREAD

**Issue by brandonjones24** [Tzahi12345/YoutubeDL-Material#243]
I've added two subscriptions and the videos downloaded to /app/subscriptions and the respective subscription folders. However, nothing is visible in the web interface. It doesn't seem that I am getting permissions errors from docker, but I am getting an error in my logs below.

I wonder if the file is being downloaded and moved to an unexpected location?

![image](https://content.screencast.com/users/BrandonJones7998/folders/Snagit/media/6a8a9a1c-075f-40e6-be68-5667460b024d/2020-11-06_16-26-50.png)

![image](https://content.screencast.com/users/BrandonJones7998/folders/Snagit/media/869f9d81-d01d-4d04-b6f8-363490e13cf6/2020-11-06_16-31-10.png)

Docker compose snippet:
```
  ytdl_material:
    environment:
        ALLOW_CONFIG_MUTATIONS: 'true'
    restart: always
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/New_York
    volumes:
        - /Volumes/docker/youtubedl-material/appdata:/app/appdata
        - /Volumes/docker/youtubedl-material/audio:/app/audio
        - /Volumes/docker/youtubedl-material/video:/app/video
        - /Volumes/docker/youtubedl-material/subscriptions:/app/subscriptions
        - /Volumes/docker/youtubedl-material/users:/app/users
    ports:
        - "8998:17442"
    image: tzahi12345/youtubedl-material:latest
    networks:
      - t2_proxy
```

```
2020-11-06T20:12:46.599Z ERROR: WARNING: Cannot update utime of file
ERROR: [Errno 2] No such file or directory
ERROR: unable to rename file: [Errno 2] No such file or directory
ERROR: unable to rename file: [Errno 2] No such file or directory
ERROR: unable to rename file: [Errno 2] No such file or directory
WARNING: Cannot update utime of file
ERROR: [Errno 2] No such file or directory
ERROR: unable to rename file: [Errno 2] No such file or directory
ERROR: unable to rename file: [Errno 2] No such file or directory
ERROR: [Errno 2] No such file or directory
ERROR: unable to rename file: [Errno 2] No such file or directory
WARNING: Cannot update utime of file
ERROR: [Errno 2] No such file or directory
ERROR: unable to rename file: [Errno 2] No such file or directory
ERROR: [Errno 2] No such file or directory: 'subscriptions/channels/[Redacted]/[Redacted]
2020-11-06T20:12:46.634Z ERROR: ERROR: unable to rename file: [Errno 2] No such file or directory
ERROR: unable to rename file: [Errno 2] No such file or directory
ERROR: [Errno 2] No such file or directory
WARNING: Cannot update utime of file
ERROR: [Errno 2] No such file or directory
2020-11-06T20:12:46.786Z ERROR: ERROR: unable to rename file: [Errno 2] No such file or directory
WARNING: Cannot update utime of file
ERROR: [Errno 2] No such file or directory
2020-11-06T20:12:46.876Z ERROR: ERROR: unable to rename file: [Errno 2] No such file or directory

2020-11-06T20:58:00.014Z ERROR: ERROR: S6YTMCWTTGg: YouTube said: Unable to extract video data
2020-11-06T21:27:15.401Z ERROR: ERROR: S6YTMCWTTGg: YouTube said: Unable to extract video data

```

**Comment by brandonjones24** [comment]
I was able to replicate this in Synology docker as well with the latest image and a fresh install.

**Comment by Tzahi12345** [comment]
Interesting, can you go into the settings and see if youtube-dl or youtube-dlc is being used? Try using the one you're not currently using and see if that helps.

I've seen these errors come up over the last few weeks since the DMCA. If you restart the server, though, the files should be automatically found and added. Is that not happening?

**Comment by brandonjones24** [comment]
Sorry for the delay. I am on v4.1 and I am struggling to find this option in settings. I'm sure I am just missing this. Can you point me in the right direction?

Thanks!
Brandon

**Comment by Tzahi12345** [comment]
Ah no problem! I should have mentioned you have to be on the `nightly` tag as that option was added after v4.1 was released. Once you pull the latest nightly, go into the advanced tab in the settings and you should see the option there!

**Comment by brandonjones24** [comment]
Awesome thanks! I will pull the nightly and report back.

On November 15, 2020, zdarin <notifications@github.com> wrote:
> Ah no problem! I should have mentioned you have to be on the nightly

> tag as that option was added after v4.1 was released. Once you pull
> the latest nightly, go into the advanced tab in the settings and you

> should see the option there!
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Tzahi12345/YoutubeDL-
Material/issues/243#issuecomment-727591331>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABOPDRHMFTWJYRWUOCJGCJDSP72EVANCNFSM4TNFHSHQ>.

**Comment by davidnewhall** [comment]
I switched from `latest` to `nightly` today because there are several videos I can't download - was hoping for a fix. When I switched, all my videos went missing. Just nothing in the interface. When I go to downloads it shows lots of UUIDs, but there are no videos. Switched back to `latest` and all the videos re-appeared. This may be related. I'm highly technical, so if you can point me at what to look for I can probably help figure it out.

**Comment by Tzahi12345** [comment]
@davidnewhall since you offered :) the UI retrieves the list of videos from the server in a request called getAllFiles (this is new, in the past getMp3s and getMp4s was used). You can view the response from the server by right clicking->inspect element->network tab and looking for the request (see attached image for reference).

Can you paste what comes up in that response on the `nightly` tag? Also, if you can paste the response for getMp3s and getMp4s that might be helpful too (those requests are still sent, the info is just not used on the home page anymore). Let me know if you need help doing this!

![image](https://user-images.githubusercontent.com/707413/99491668-275a3f80-293a-11eb-9528-12accfa5f3ae.png)

**Comment by davidnewhall** [comment]
You pointed me in the right direction and my issue is probably unrelated to this thread. I have this behind nginx and I manually "found and added" all the api paths to make it work on the root of my domain with other apps that use the `/api` URI. I had to add two new paths: `/api/getAllFiles` and `/api/getAllCategories`. Sorry about the noise. 

Is there a way to make this app serve these files/paths on a sub folder? ie `/ytdl/api/getThings`

This is a snippet of my relevant nginx config now, for reference:
```
location ~ ^/api/(config|isPenSet|auth/(admin|login|jwtAuth)|getMp[34]s|getFile|video|setConfig|getUsers|getRoles|logs|downloads|clearDownloads|tomp4|getVideoInfos|download|createPlaylist|setPin|isPinSet|checkPin|getAllCategories|getAllFiles) {
  proxy_pass $ytdl;
}
```

Nightly seems OK for now. Thank you!

**Comment by brandonjones24** [comment]
To follow up on this issue, using the Nightly with Youtube-DLC seems to

be working. I have another issue of some thumbnails not showing up, but

I will open a separate issue if needed. 

Thanks for your help!

On November 18, 2020, zdarin <notifications@github.com> wrote:
> You pointed me in the right direction and my issue is probably
> unrelated to this thread. I have this behind nginx and I manually
> "found and added" all the api paths to make it work on the root of my

> domain with other apps that use the /api URI. I had to add two new
> paths: /api/getAllFiles and /api/getAllCategories. Sorry about the
> noise.
>
> Is there a way to make this app serve these files/paths on a sub
> folder? ie /ytdl/api/getThings
>
> This is a snippet of my relevant nginx config now, for reference:
>
> location ~
> ^/api/(config|isPenSet|auth/(admin|login|jwtAuth)|getMp[34]s|getFile|video|setConfig|getUsers|getRoles|logs|downloads|clearDownloads|tomp4|getVideoInfos|download|createPlaylist|setPin|isPinSet|checkPin|getAllCategories|getAllFiles)
> { proxy_pass $ytdl; }
> Nightly seems OK for now. Thank you!
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Tzahi12345/YoutubeDL-
Material/issues/243#issuecomment-729458889>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABOPDRGGZOX3MIJ322H45ALSQNRWJANCNFSM4TNFHSHQ>.

**Comment by BasWeg** [comment]
Hi,
after the latest 2 nightly releases I'm facing the same issue. The videos from subscriptions do not show up in their subscription tab. 
They were still there last week ;)
But the videos are shown at the main tab from youtubedl-material and are accessible.

**Comment by Tzahi12345** [comment]
@BasWeg Interesting, can you inspect element->network tab and reload the subscription's page? Look for a request called getSubscription and paste the response. Or if that's a bit much, you can email me your instance login info (IsaacMGrynsztein@gmail.com) and I can try to find out what went wrong.

**Comment by BasWeg** [comment]
@Tzahi12345 Do you mean the json response?

**Comment by Tzahi12345** [comment]
@BasWeg Yup, should be an object that has to properties, "files" and "subscription"

**Comment by BasWeg** [comment]
@Tzahi12345 
![grafik](https://user-images.githubusercontent.com/56368122/102264757-5acac280-3f16-11eb-87e9-b50edcb47272.png)
For example the respose for the one playlist/subscription is following:
`{
	"subscription": {
		"name": "DocSwim-Trockentraining",
		"url": "https://www.youtube.com/playlist?list=PL90mCdov3Ow-LgofCrCarIbMiTSeRwooE",
		"id": "850b3500-d14e-4a01-9297-611d7b0c9610",
		"streamingOnly": false,
		"user_uid": null,
		"type": "video",
		"isPlaylist": true,
		"videos": [
			{
				"id": "SCHWIMMERSCHULTER - 6 EFFEKTIVE ÜBUNGEN _ PLAN #106",
				"title": "SCHWIMMERSCHULTER: 6 EFFEKTIVE ÜBUNGEN | PLAN #106",
				"thumbnailURL": "https://i.ytimg.com/vi/hfBHt_kGk_E/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCYKLqXgVlX9-GlENKNbXeKvUoLTg",
				"isAudio": false,
				"duration": 650,
				"url": "https://www.youtube.com/watch?v=hfBHt_kGk_E",
				"uploader": "DOCSWIM",
				"size": 242827550,
				"path": "subscriptions/playlists/DocSwim-Trockentraining/SCHWIMMERSCHULTER - 6 EFFEKTIVE ÜBUNGEN _ PLAN #106.mp4",
				"upload_date": "2019-10-13",
				"thumbnailPath": null,
				"uid": "8c6728f3-8085-4e66-bced-2199c87446c7",
				"registered": 1608061115565
			},
			{
				"id": "RUMPFSTABILITÄT für Schwimmer & Triathleten _ PLAN #102",
				"title": "RUMPFSTABILITÄT für Schwimmer & Triathleten | PLAN #102",
				"thumbnailURL": "https://i.ytimg.com/vi/IqOlhjpUihA/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAjKqvGUs5QdDFE2lKRmwHELhJC_Q",
				"isAudio": false,
				"duration": 896,
				"url": "https://www.youtube.com/watch?v=IqOlhjpUihA",
				"uploader": "DOCSWIM",
				"size": 230910690,
				"path": "subscriptions/playlists/DocSwim-Trockentraining/RUMPFSTABILITÄT für Schwimmer & Triathleten _ PLAN #102.mp4",
				"upload_date": "2019-09-15",
				"thumbnailPath": null,
				"uid": "18305d7c-350e-4fec-a2e8-3a3fe59c4dc0",
				"registered": 1608061115570
			},
			{
				"id": "BEWEGLICHKEIT für Schwimmer & Triathleten _ PLAN #103",
				"title": "BEWEGLICHKEIT für Schwimmer & Triathleten | PLAN #103",
				"thumbnailURL": "https://i.ytimg.com/vi/MuDymWPYw0U/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBfrvpV7hov9rNXhw03jYw5XV0vUA",
				"isAudio": false,
				"duration": 798,
				"url": "https://www.youtube.com/watch?v=MuDymWPYw0U",
				"uploader": "DOCSWIM",
				"size": 230341917,
				"path": "subscriptions/playlists/DocSwim-Trockentraining/BEWEGLICHKEIT für Schwimmer & Triathleten _ PLAN #103.mp4",
				"upload_date": "2019-09-22",
				"thumbnailPath": null,
				"uid": "0cc1c98d-507b-41bb-a06d-a3e17d4065f9",
				"registered": 1608061115578
			},
			{
				"id": "MOVEMENT PREP für Schwimmer & Triathleten _ PLAN #104",
				"title": "MOVEMENT PREP für Schwimmer & Triathleten | PLAN #104",
				"thumbnailURL": "https://i.ytimg.com/vi/bTDFA6dZDdA/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAZaylIPsHPjo2yB3fF0pfgBN9wGQ",
				"isAudio": false,
				"duration": 873,
				"url": "https://www.youtube.com/watch?v=bTDFA6dZDdA",
				"uploader": "DOCSWIM",
				"size": 218317759,
				"path": "subscriptions/playlists/DocSwim-Trockentraining/MOVEMENT PREP für Schwimmer & Triathleten _ PLAN #104.mp4",
				"upload_date": "2019-09-30",
				"thumbnailPath": null,
				"uid": "22b570bd-1c3b-48c1-83d3-ad0eb255a797",
				"registered": 1608061115587
			},
			{
				"id": "FULL-BODY-WARM-UP in 4_30 MINUTEN _ PLAN #105",
				"title": "FULL-BODY-WARM-UP in 4:30 MINUTEN | PLAN #105",
				"thumbnailURL": "https://i.ytimg.com/vi/NrrntA3yAIo/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBHZ5TH3ceClQWdt7szsNQzkzWBDA",
				"isAudio": false,
				"duration": 469,
				"url": "https://www.youtube.com/watch?v=NrrntA3yAIo",
				"uploader": "DOCSWIM",
				"size": 217790969,
				"path": "subscriptions/playlists/DocSwim-Trockentraining/FULL-BODY-WARM-UP in 4_30 MINUTEN _ PLAN #105.mp4",
				"upload_date": "2019-10-07",
				"thumbnailPath": null,
				"uid": "9bd278c5-0694-43bf-8c7b-f344e90095e4",
				"registered": 1608061115593
			}
		],
		"archive": "/app/subscriptions/archives/DocSwim-Trockentraining"
	},
	"files": [
		{
			"id": "SCHWIMMERSCHULTER - 6 EFFEKTIVE ÜBUNGEN _ PLAN #106",
			"title": "SCHWIMMERSCHULTER: 6 EFFEKTIVE ÜBUNGEN | PLAN #106",
			"thumbnailURL": "https://i.ytimg.com/vi/hfBHt_kGk_E/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLCYKLqXgVlX9-GlENKNbXeKvUoLTg",
			"isAudio": false,
			"duration": 650,
			"url": "https://www.youtube.com/watch?v=hfBHt_kGk_E",
			"uploader": "DOCSWIM",
			"size": 242827550,
			"path": "subscriptions/playlists/DocSwim-Trockentraining/SCHWIMMERSCHULTER - 6 EFFEKTIVE ÜBUNGEN _ PLAN #106.mp4",
			"upload_date": "2019-10-13",
			"thumbnailPath": null,
			"uid": "8c6728f3-8085-4e66-bced-2199c87446c7",
			"registered": 1608061115565
		},
		{
			"id": "RUMPFSTABILITÄT für Schwimmer & Triathleten _ PLAN #102",
			"title": "RUMPFSTABILITÄT für Schwimmer & Triathleten | PLAN #102",
			"thumbnailURL": "https://i.ytimg.com/vi/IqOlhjpUihA/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAjKqvGUs5QdDFE2lKRmwHELhJC_Q",
			"isAudio": false,
			"duration": 896,
			"url": "https://www.youtube.com/watch?v=IqOlhjpUihA",
			"uploader": "DOCSWIM",
			"size": 230910690,
			"path": "subscriptions/playlists/DocSwim-Trockentraining/RUMPFSTABILITÄT für Schwimmer & Triathleten _ PLAN #102.mp4",
			"upload_date": "2019-09-15",
			"thumbnailPath": null,
			"uid": "18305d7c-350e-4fec-a2e8-3a3fe59c4dc0",
			"registered": 1608061115570
		},
		{
			"id": "BEWEGLICHKEIT für Schwimmer & Triathleten _ PLAN #103",
			"title": "BEWEGLICHKEIT für Schwimmer & Triathleten | PLAN #103",
			"thumbnailURL": "https://i.ytimg.com/vi/MuDymWPYw0U/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBfrvpV7hov9rNXhw03jYw5XV0vUA",
			"isAudio": false,
			"duration": 798,
			"url": "https://www.youtube.com/watch?v=MuDymWPYw0U",
			"uploader": "DOCSWIM",
			"size": 230341917,
			"path": "subscriptions/playlists/DocSwim-Trockentraining/BEWEGLICHKEIT für Schwimmer & Triathleten _ PLAN #103.mp4",
			"upload_date": "2019-09-22",
			"thumbnailPath": null,
			"uid": "0cc1c98d-507b-41bb-a06d-a3e17d4065f9",
			"registered": 1608061115578
		},
		{
			"id": "MOVEMENT PREP für Schwimmer & Triathleten _ PLAN #104",
			"title": "MOVEMENT PREP für Schwimmer & Triathleten | PLAN #104",
			"thumbnailURL": "https://i.ytimg.com/vi/bTDFA6dZDdA/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLAZaylIPsHPjo2yB3fF0pfgBN9wGQ",
			"isAudio": false,
			"duration": 873,
			"url": "https://www.youtube.com/watch?v=bTDFA6dZDdA",
			"uploader": "DOCSWIM",
			"size": 218317759,
			"path": "subscriptions/playlists/DocSwim-Trockentraining/MOVEMENT PREP für Schwimmer & Triathleten _ PLAN #104.mp4",
			"upload_date": "2019-09-30",
			"thumbnailPath": null,
			"uid": "22b570bd-1c3b-48c1-83d3-ad0eb255a797",
			"registered": 1608061115587
		},
		{
			"id": "FULL-BODY-WARM-UP in 4_30 MINUTEN _ PLAN #105",
			"title": "FULL-BODY-WARM-UP in 4:30 MINUTEN | PLAN #105",
			"thumbnailURL": "https://i.ytimg.com/vi/NrrntA3yAIo/hqdefault.jpg?sqp=-oaymwEZCNACELwBSFXyq4qpAwsIARUAAIhCGAFwAQ==&rs=AOn4CLBHZ5TH3ceClQWdt7szsNQzkzWBDA",
			"isAudio": false,
			"duration": 469,
			"url": "https://www.youtube.com/watch?v=NrrntA3yAIo",
			"uploader": "DOCSWIM",
			"size": 217790969,
			"path": "subscriptions/playlists/DocSwim-Trockentraining/FULL-BODY-WARM-UP in 4_30 MINUTEN _ PLAN #105.mp4",
			"upload_date": "2019-10-07",
			"thumbnailPath": null,
			"uid": "9bd278c5-0694-43bf-8c7b-f344e90095e4",
			"registered": 1608061115593
		}
	]
}`

**Comment by BasWeg** [comment]
@Tzahi12345 mybe its due to the Angular update. The Inspector->Console shows errors:
`ERROR TypeError: oi.a.merge is not a function
    t subscription-file-card.component.ts:32
    fac subscription-file-card.component.ts:89
    Angular 4
    qk subscription.component.html:40
    Angular 35
    RxJS 5
    Angular 9`

Even the mainpage shows errors:
`ERROR Error: Uncaught (in promise): TypeError: jS.Observable is undefined
.......
http://192.168.21.35:17442/polyfills-es2015.3d6d29cecba919db447b.js:1:56687
`

**Comment by Tzahi12345** [comment]
@BasWeg I think I fixed it! You can see the [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/43b0c2fb9e1b0c119510db2eb9f60071ae583082), I guess the jump to rxjs 6 broke Observable.merge, which was thankfully only actively used there.

The nightly should take an hour to build and push, let me know if it's fixed!

**Comment by BasWeg** [comment]
@Tzahi12345 Until now the Unraid-Docker tab does not recognize that there is a new version. As soon as an update is available I'm going to let you know if this is fixed.
Thank you!

**Comment by BasWeg** [comment]
@Tzahi12345 Thanks for the fix! The videos are shown in the subscription tab, too.

There is one minor inaccuracy, in the subscription tab the thumbnails are shown with the video-length as header. It would be great to have the Upload/download-date instead. In the main the duration of a video is shown in the video picture.
![Bildschirmfoto von 2020-12-16 13-26-43](https://user-images.githubusercontent.com/56368122/102348878-c8bccb80-3fa2-11eb-978c-daf74381d3e3.png)

And on the main-tab the actual date (12/16/20) is shown for all videos from a subscription instead of the upload or download date. The "not subscripted" videos shows the download date.
![Bildschirmfoto von 2020-12-16 13-39-36](https://user-images.githubusercontent.com/56368122/102349852-46cda200-3fa4-11eb-8b8f-3ec2ad1bf641.png)

Sorry for the circumstances.

**Comment by tyzbit** [comment]
I had this bug in a previous build (within the last 2 months) and I recently wiped everything out and recreated from `nightly` (I'm guessing commit addd54fefd062382b65efe33d9bacb0ee3b80182) and the videos showed up as they were downloaded from the subscriptions for me.  I would leave this open for more positive reports but so far it looks good for me.

**Comment by Tzahi12345** [comment]
You're right @tyzbit, I actually implemented this feature in [this commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/1f0153b17edae9000cb0b0f58d12d082853b8291), just haven't gotten around to cleaning up the issues list. I'll go ahead and close this one as it should be resolved! To be clear you have to be on the latest `nightly` or wait for the next release.

@BasWeg the inconsistency you saw with the subscription page file cards should be fixed in a future release once I transfer them to the new component seen in the home page!
