### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by hwalker928** [Tzahi12345/YoutubeDL-Material#245]
Hey there, I get this error when running npm start.

npm ERR! Linux 3.10.0-1127.19.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! backend@1.0.0 start: `nodemon -q app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backend@1.0.0 start script 'nodemon -q app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the backend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon -q app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs backend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls backend
npm ERR! There is likely additional logging output above.

Kind regards.

**Comment by Tzahi12345** [comment]
Can you try running `node app.js` instead of npm start? It may be an issue with nodemon, but it's hard to tell right now. Perhaps you'll get an error message that gives some more info.

Also, if you have Docker installed, it will provide a much more straightforward path to installing! But I know that option is not available to all users.

**Comment by hwalker928** [comment]
Hey there,

I have tried with docker as well and I get a different error, and I'll go
grab you those logs now.

With node app.js, I also get a different error.

Kind regards, and I'll reply with them soon.

**Comment by Tzahi12345** [comment]
Thanks! I'll investigate once you send those my way

**Comment by hwalker928** [comment]
node app.js error

https://paste.harrydev.me/eyutizabiv.typescript

docker-compose pull error 

https://paste.harrydev.me/osikinezaq.sql

**Comment by Tzahi12345** [comment]
Hm I don't quite understand the issue with the docker-compose, do you mind sharing your docker-compose.yml file?

Regarding the node app.js error, it sounds like your node.js [may be outdated](https://stackoverflow.com/questions/37815790/syntaxerror-unexpected-token-function-async-await-nodejs). If you can update to node v12, it should work without issue. Let me know how it goes!

**Comment by hwalker928** [comment]
Ah - updating nodejs seems to have resolved the error, but I cannot access the website

**Comment by Tzahi12345** [comment]
Interesting, do you get any errors at that point? Your browser console might give more insight (right click->inspect element->console).  Normally once the app is up and running it should be accessible from the same host on localhost:17443

Just a quick question in case this is the problem: did you download the app from the releases page or did you do a git pull? If you do a git pull, you actually need to build the frontend first (`ng build --prod` from the root folder), normally users just download the latest release (v4.1), though that's getting a bit outdated at this point.

**Comment by hwalker928** [comment]
I just downloaded it from releases as the ng build command doesnt exist

**Comment by Tzahi12345** [comment]
I'm still confused as to why nothing shows up when you try to access the app. Does anything pop up in the browser console?

You can still try the build-from-source route, it just takes a couple extra steps (if you're down for that):

1. Run `npm install -g @angular/cli`
2. Run `git clone https://github.com/Tzahi12345/YoutubeDL-Material.git` and then `cd YoutubeDL-Material`
3. Run 'npm install' (installs dependencies for the frontend)
3. Run `ng build --prod` (forgot to mention about that this requires Angular, the first command installs it)
4. Run `cd backend` to enter the backend directory
5. Run `npm install` (installs dependences for the backend)
6. Finally, run `node app.js`

**Comment by hwalker928** [comment]
pm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@8.5.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@8.5.3 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/ytdbuild/YoutubeDL-Material/npm-debug.log

But ive already updated node?
This is during step 3

**Comment by hwalker928** [comment]
Also btw, do you have discord? I would just find it easier to communicate than issues

**Comment by Tzahi12345** [comment]
Yup! Here's my code: Tzahi#8672

I can't get in a call now since it's fairly late but I agree, it'll be easier to chat there (only downside is if someone else faces this issue, but in that case I'll post an update here summarizing the fix)

**Comment by hwalker928** [comment]
Sent FR.

**Comment by Tzahi12345** [comment]
We were able to get this fixed last night -- the main problem listed here is that Node.js was outdated (and even when updating, centos used the old version). ffmpeg is also not installed by default on centos, so that had to be done as well. @hwalker928 added instructions in the README for centos users to avoid any installation problems in the future. Thanks for the contribution!

**Comment by battlezone** [comment]
I am getting the exact same error but with different versions:
````
> backend@1.0.0 start /home/battlezone/youtubedl-material
> nodemon -q app.js

sh: 1: nodemon: not found

npm ERR! Linux 4.15.18-30-pve
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! backend@1.0.0 start: `nodemon -q app.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the backend@1.0.0 start script 'nodemon -q app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the backend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodemon -q app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs backend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls backend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/battlezone/youtubedl-material/npm-debug.log
````

Running `node app.js` gives me the following error:
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'uuidv4'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/battlezone/youtubedl-material/app.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

This is on a fresh Ubuntu 18.04 release with the dependencies installed. I had to install NPM separately though. Everything seems up to date.

**Comment by hwalker928** [comment]
Do `node -v`

**Comment by battlezone** [comment]
````
node -v
v8.10.0
````

**Comment by hwalker928** [comment]
Update to node 12

**Comment by battlezone** [comment]
Thanks, that did the trick.
