### ISSUE TITLE
Bookmarklet (and maybe Firefox extension?)

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#25]
A Chrome extension is fine and dandy, but what about users whose main browser is Firefox or basically every mobile user? Bookmarklets are universal and resource-friendly. If I had extensions for all the bookmarklets I use I'd have some of the bloated browsers out there. :D

In the case of Firefox extensions you'd get the added benefit of having the Android version (at least the OG Firefox for Android, the new generation of Firefox is still rebuilding extension support) support the extension as well.

**Comment by Tzahi12345** [comment]
Looks relatively simple to implement. For the bookmarklet though, I'm not sure how to let it know what the YoutubeDL-Material URL is. From a first glance, I'm not sure a settings menu is possible like it is for Firefox or Chrome extensions.

**Comment by GlassedSilver** [comment]
The URL could be passed as an environment variable by Docker I guess? Not sure how other applications are handling this, but that's my intuition. I can look into it if you like. :)

Regarding the Firefox extension: will you sign it and upload the signed .xpi extension not only to github but also the Firefox add-ons repo? (addons.mozilla.org/)

**Comment by Tzahi12345** [comment]
I can perhaps make a bookmarklet generator in-app (maybe in settings), so it can just grab the URL from there.

With regards to the Firefox extension: beat ya to it. It's still under review. The Chrome extension funnily enough got rejected. Not surprised Google wouldn't want something like this up in their app store.

I'm 12/18 in line to get reviewed, so it should be done sometime soon.

![](https://i.imgur.com/uxq2mIH_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by Tzahi12345** [comment]
It's approved! Check out the Firefox extension [here](https://addons.mozilla.org/en-US/firefox/addon/youtubedl-material/)

**Comment by GlassedSilver** [comment]
> It's approved! Check out the Firefox extension [here](https://addons.mozilla.org/en-US/firefox/addon/youtubedl-material/)

Man, you're on top of the game! Next time I'm on my desktop I will try it out.

Remember to link to this extension in an eventual "About this application" view. :)

At some point a good chunk of the user base won't come from github, however when I publish the CA I will mention the extensions and bookmarklet, since it's one of the differentiators. :)

**Comment by Tzahi12345** [comment]
>Remember to link to this extension in an eventual "About this application" view. :)

Good idea, I'll see about adding an About page in the next update, it'll probably do good for spreading the word about this project too.

I'm still building out the features I want for the next update so it might be a couple weeks until we get 3.5, bookmarklet and extension included :)

**Comment by GlassedSilver** [comment]
> 
> 
> > Remember to link to this extension in an eventual "About this application" view. :)
> 
> Good idea, I'll see about adding an About page in the next update, it'll probably do good for spreading the word about this project too.
> 
> I'm still building out the features I want for the next update so it might be a couple weeks until we get 3.5, bookmarklet and extension included :)

Not only that, but it would allow the end-user to conveniently check the application's version. :3 

Couple of weeks definitely sounds promising. (:

**Comment by Tzahi12345** [comment]
v3.5 is out, with a dedicated Extensions section included! Bookmarklet can be found in the Extension section of the settings (will think about moving it to the About dialog), along with info on the Firefox and Chrome extensions. Check it out! :)

**Comment by BeecherNetworks** [comment]
Is there a flag I can add to the URL to put the download into audio mode? Or perhaps an alternative for the browser addon? (Currently using the bookmarklet for video and the addon for audio, but I would prefer the bookmarklet if possible.)

Great app thanks.

**Comment by Tzahi12345** [comment]
> Is there a flag I can add to the URL to put the download into audio mode? Or perhaps an alternative for the browser addon? (Currently using the bookmarklet for video and the addon for audio, but I would prefer the bookmarklet if possible.)
> 
> Great app thanks.

There is, it is `;audioOnly=true` (the semicolon is required to escape from the URL flag). The underlying bookmarklet would look something like this: 

`javascript:(function()%7Bwindow.open('http://example.com:17442/#/home;url=' + encodeURIComponent(window.location) + ';audioOnly=true')%7D)()`

But this should be easier to do than having to manually modify the bookmarklet code. I have added a checkbox to the bookmarklet generator, so you can set this flag through the UI quite easily! 
[Here's the relevant code changes](https://github.com/Tzahi12345/YoutubeDL-Material/commit/7ef6c78612927b19238a5fa4bb16e2695c7934df#diff-786d0e4edfe525fae03ae989639e4678). See screenshot below:

<img src="https://i.imgur.com/xfRvK9h.png" width="600">

You'll be able to use it in the next update, along with a [settings menu redesign](https://github.com/Tzahi12345/YoutubeDL-Material/pull/47).

Thanks for the suggestion! Feel free to open up an issue if you have any other ideas/issues.

**Comment by BeecherNetworks** [comment]
Brilliant, thanks for both.
