### ISSUE TITLE
Private-d YT videos stalling subscriptions.

### ISSUE THREAD

**Issue by heyyceejayy** [Tzahi12345/YoutubeDL-Material#250]
So I rebuilt the database and decided to re-add subscriptions to channels. There are a couple of videos that were either taken down or marked as private and I'm running into an issue where, even though the videos are there and up to date, subscription check will stall and say "the last check has not completed". Later on, it will finally finish subscription check and show:

2020-11-19T08:48:28.655Z ERROR: ERROR: dAVfeFXbIEE: YouTube said: Unable to extract video data
ERROR: bGu-9Cim1xM: YouTube said: Unable to extract video data
ERROR: CLmXlXDEEXM: YouTube said: Unable to extract video data
ERROR: XKlCtmWkC0A: YouTube said: Unable to extract video data

**Comment by Tzahi12345** [comment]
If they're private and you have access to them, you need to upload your youtube cookies in the Advanced tab in the settings. [Here's info on how to do that](https://apple.stackexchange.com/a/349759). The videos should download without issue with your cookies.

Does the stalling prevent the videos from getting registered (that is, do you see them show up in the UI)?

**Comment by heyyceejayy** [comment]
They seem to be videos that have been previously private but have been put on private to the general public. After messing around, I seemed to have solved the issue by modifying the subscription url.

When adding subscriptions, is there a difference between linking directly to a channels URL vs the videos page?

Example:
https://www.youtube.com/c/ChilledCow vs https://www.youtube.com/c/ChilledCow/videos

using the URL with videos appended to the URL seemed to fix the issue for me.
