### ISSUE TITLE
Docker 

### ISSUE THREAD

**Issue by next2non** [Tzahi12345/YoutubeDL-Material#251]
Hi,

I installed youtubedl-material using docker, but it won’t download the link. The npm way worked but the docker doesn’t. When I paste the link it tries to find the video, but after few seconds nothing happens. Using the npm method used to give me options of video quality, but with docker it doesn’t.

**Comment by Tzahi12345** [comment]
Interesting, do you see any errors in the browser console? It sounds like the UI isn't loading properly for some reason

**Comment by next2non** [comment]
No errors in the browser console, it’s as you say the UI isn’t loading properly. Made a small video if it helps

https://drive.google.com/file/d/1t1fDfDYlxn7u1uGYXiCXLDoWq0cRnJMS/view?usp=drivesdk

**Comment by next2non** [comment]
This is the error i get

An error has occurred:
Failed pre-check for video info: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -o video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail http://www.youtube.com/watch?v=_30qQeMvZuA
Download start: Nov 24, 2020, 6:03:25 PM

**Comment by Tzahi12345** [comment]
Sorry for the late reply, does this still occur on v4.2?

**Comment by next2non** [comment]
Hi,

it seems to be working now, thanks for the fix

**Comment by Tzahi12345** [comment]
Awesome, great to hear!
