### ISSUE TITLE
What is multi-download mode?

### ISSUE THREAD

**Issue by jo-me** [Tzahi12345/YoutubeDL-Material#252]
Hi,

couldn't find it in the API docs (or in the code) what this flag does.
What does it do?

Thanks!

**Comment by Tzahi12345** [comment]
Good question, it just allows you to download multiple videos at a time without a redirect to the video player. It's an old feature, and sometimes it's a bit finnicky. In the future I want to implement a good system for controlling downloads (like a queue), so it'll likely be deprecated at that point. Hope this makes sense!

**Comment by jo-me** [comment]
Ah okay, thanks for pointing that out. It does make sense to have this option, though.
You could rename it to "Preview after download" or something similar to make it more clear.
