### ISSUE TITLE
Top title does not match html head title

### ISSUE THREAD

**Issue by jo-me** [Tzahi12345/YoutubeDL-Material#253]
Changing the page title via Settings > Extra > Top Title changes the title visible in the UI, but it does not change it in the browser tab :

![image](https://user-images.githubusercontent.com/10351272/99845338-c0749a80-2b74-11eb-98a5-64e976391dd7.png)

**Comment by Tzahi12345** [comment]
While this wasn't the original intention of the feature, but last week I actually had the same idea! I've gone ahead and updated it so now the tab title should reflect the top title set in the Extra tab. Pull the latest `nightly` and you should be able to see this, thanks for the suggestion!

[Relevant commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/b32fdb2445dc464013755b7cc743fe398ae5618e)

**Comment by jo-me** [comment]
Cool that was quick :) thanks!
