### ISSUE TITLE
Audio playlist cannot be played

### ISSUE THREAD

**Issue by jo-me** [Tzahi12345/YoutubeDL-Material#256]
I've created an audio playlist and added some audio files to it.
However, none of the playlist items can be played.

There are errors in the dev console like this:
`Error: ENOENT: no such file or directory, stat 'video/Kinderlieder - das Lied über die Tiere..mp3'
`
So, apparently the songs are prepended with "video/" instead of "audio/"..  The filename itself is ok and present in /audio.

Video playlists work as expected.

I'u sing the ":latest" version.

**Comment by Tzahi12345** [comment]
Weird, can you try using the `nightly` tag instead of latest and see if it's fixed?

**Comment by jo-me** [comment]
Oh i meant nightly...

**Comment by Tzahi12345** [comment]
Is this resolved in the latest `nightly`? There's been quite a few updates that could have fixed this.
