### ISSUE TITLE
Update youtube-dl on every start of the application/container

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#26]
So I noticed the latest release notes have some really nice and welcome notes, props to that!

However, there is one glaring issue and that is youtube-dl's version. From user feedback I've seen in regards to other applications that work as a wrapper for youtube-dl I've learnt that it's best practice to always auto-update youtube-dl constantly almost at any chance, specifically container restarts, since Youtube is an unpredictably fast moving beast on the back-end and youtube-dl will OFTEN break requiring youtube-dl to be updated. 

Relegating the **update of youtube-dl to a mere restart of the container and maybe additionally periodically when no task is running** would also move the spotlight away from you when your wrapper isn't to blame for something breaking. :)

Cheers!

**Comment by Tzahi12345** [comment]
Glad you liked the notes :)

Looked into this a bit, and there is [a way](https://github.com/przemyslawpluta/node-youtube-dl#update) to download the latest binary manually. This does not check if it's on the latest version or run, but it appears someone made a [workaround](https://github.com/przemyslawpluta/node-youtube-dl/issues/282) that does. Will play around with this a bit more, but it looks simple enough to make it into the next update.

**Comment by GlassedSilver** [comment]
Fantastic news!

**Comment by Tzahi12345** [comment]
Automatic updating has been implemented and is now merged into the master branch. The next update will have this feature included. I will note that this check only occurs on startup, so a user restart is required to update binaries if they are available. I'll look into implementing periodic checks (should require a few lines of code and perhaps a setting) before the next release.

See relevant PR [here](https://github.com/Tzahi12345/YoutubeDL-Material/pull/34). Thanks for the suggestion!

**Comment by GlassedSilver** [comment]
Man, you're really just delivering delivering delivering.

Mad props. :)
