### ISSUE TITLE
Enhancement: Allow to 'silently' download to server only

### ISSUE THREAD

**Issue by Sono-Gomorrha** [Tzahi12345/YoutubeDL-Material#263]
Hi, 

I would like to see the option to 'silently' download to the server only. Currently I can find these two options:
a) with default settings youtubedl-material saves the video to the server it is running on and then starts playing the video automatically OR
b) if I select 'Download only mode' under 'Settings -> Extra' the video will be downloaded to the server, but also automatically to my client.

Actually none of these really fits my use case. What I would like to do would be to download these only to the server (so option b) but without the download to my client. My use case is that I would like to save the video to watch it later on, like in the evening, but then be able to watch it from the server in my LAN, I don't want to watch it right away, that is why I don't like option a), but also don't want to have it on my laptop drive either.

**Comment by GlassedSilver** [comment]
I may be wrong on this one, but I think if you enable mutli-download mode it should not start playing the video right away.

At least I never have that happen for me and that setting is something I remember changing once and iirc it affected my 1-2 times of seeing this weird default behavior.

**Comment by Tzahi12345** [comment]
@GlassedSilver is correct, just enable multi-download mode on the home page and you should be set!

There was an issue where the recent videos would not get reloaded when using multi-download mode, but that's been fixed. Just pull the latest `nightly` and you should be good to go!
