### ISSUE TITLE
Set custom path in settings menu and make it global instead of cookie-based per browser

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#265]
I am a big believer in the way I store and name my downloads on disk and don't like just having the video and subscription paths as is.

I would really like to set and forget per instance instead of per browser a rule of what comes after the the video/, audio/ or subscriptions/ folder.

IMHO the options to set those folders' locations should include a second field where you define a subfolder logic and a filename logic separately.

This would make a LOT more sense over having custom paths PER download (as a quick setting so to say), because as long as everything gets yote into the same videos/ folder the utility of having custom paths per download should be limited.

**Comment by Tzahi12345** [comment]
You can basically do this already by adding a global custom arg like `-o,,[%(id)s] - %(title)s.%(ext)s`. It's not as intuitive as what you described, but it's certainly possible.

But it sounds like you think a dedicated option is the better approach, right?

**Comment by GlassedSilver** [comment]
Yes that would be really appreciated. :)

**Comment by Tzahi12345** [comment]
Done! Latest build will have this included. As always, thanks for the suggestions!

[Relevant commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/b730bc5adc1921c0fb79365ae4a80dded4c46a00)
