### ISSUE TITLE
"Download videos uploaded in the last X ..." is blank after subscribing

### ISSUE THREAD

**Issue by DarkSkyGhost** [Tzahi12345/YoutubeDL-Material#267]
After subscribing and modifying the subscription, the "day/week/month/year" setting is blank.

[screenshot](https://i.imgur.com/tPte8Jn.png)

Saving and reopening blanks it again.

**Comment by Tzahi12345** [comment]
Nice bug catch, it's fixed!

[See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/d15d262b87cdfac01a8bd3de78ff03f45b9e908b)
