### ISSUE TITLE
Ability to just "Delete" video from My videos

### ISSUE THREAD

**Issue by DarkSkyGhost** [Tzahi12345/YoutubeDL-Material#268]
Currently you can only "Delete and redownload", it would be great to have an option to just "Delete" the video.

[screenshot](https://i.imgur.com/oKsGd7e.png)

**Comment by Tzahi12345** [comment]
To explain this label a bit better, if you don't have the `Use youtube-dl archive` setting in the Downloader tab and you delete a video that is part of a subscription, it will redownload in the next check *unless* you have the "Download videos in the last X" enabled and the video won't be included. So with the option enabled the label doesn't make sense for old videos.
  * To make matters worse, we don't know the exact time a video was uploaded (just the day), so checking the upload date to see whether it would be redownloaded will not result in a 100% accurate label. If you have any suggestions for rewording, I'm all ears.

If you want to prevent it from being redownloaded in all circumstances, you can enable `Use youtube-dl archive` and you'll see an additional option called "Delete and blacklist." In this case, you can be confident that the video will not be redownloaded.

**Comment by DarkSkyGhost** [comment]
Ah, didn't know what youtube-dl archive option does.

I've enabled it and yes, the option to delete and blacklist appeared.

Will try it out.
