### ISSUE TITLE
how can I add playlist 

### ISSUE THREAD

**Issue by rmGFW** [Tzahi12345/YoutubeDL-Material#275]
how can I specify the subscription type in subscriptions page

I want add some playlist ,but it always cheat my url as Channels

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/66858140/100969167-9ad09380-356d-11eb-8fa2-e0dafde40c91.png">

**Comment by Tzahi12345** [comment]
Interesting, what's the URL are you using?
