### ISSUE TITLE
How refresh db after moving files?

### ISSUE THREAD

**Issue by jo-me** [Tzahi12345/YoutubeDL-Material#278]
Hi
I moved downloaded stuff away from the download folder and those items still appear in the frontend
![image](https://user-images.githubusercontent.com/10351272/101244208-4f50ed80-3705-11eb-86d8-22028f891e94.png)

How can I recreate the DB file? 

Thanks

**Comment by jo-me** [comment]
Deleting individually in the frontend does not work (no error in console)
I'd expect the DB to refresh on start if not periodically. As a manual fix, could there be a button in the settings maybe to update the DB?

**Comment by Tzahi12345** [comment]
If you delete it through the UI and restart the app, it should find the file again as long as it's in a folder that's being watched (`video` and `audio` folders/user folders, subfolder of those are OK too). Is it in one of these folders or in a separate one entirely?

**Comment by jo-me** [comment]
Well I just deleted / moved stuff out of the audio folder (via file system) and now I seem to have corrupted DB. 
Deleting the broken items in the UI does not work , restart does not fix it as well. 

How can I fix that? Can I delete the DB?

**Comment by Tzahi12345** [comment]
You can delete the DB, but be aware you'll have to recreate your users. Once you do that, add the videos back to their appropriate place along with their JSON files. Restart the server and they should be imported again.

Deleting outside of the app won't corrupt the DB, but the app will think those files still exist even if they don't. I should probably add some check where if the file is not found it'll delete it from the app, but there may be unintended consequences with this approach.

**Comment by jo-me** [comment]
So, I stopped the container, deleted the `db.json` file and restarted.
Now, the broken / removed downloads are gone from the UI.

Thanks!
