### ISSUE TITLE
Max quality is not max quality.

### ISSUE THREAD

**Issue by fishscene** [Tzahi12345/YoutubeDL-Material#279]
When downloading a video at max quality, it downloads the 1280x720 video (~60MB). Not the 4K HDR video, which is over 400MB.

Running the same URL through youtube-dl directly downloads the 4k HDR Video.

**Comment by Tzahi12345** [comment]
Are you using Docker? If so change your tag to `nightly` and it should work without issue!

Basically, the latest release version (4.1) had this issue but it has since been fixed.

**Comment by fishscene** [comment]
Asolutely spectacular!

This was exactly it. I switched to nightly and the video is definitely in max quality. So much so, that I'm wondering why youtubedl-material downloads a 1.1 GB file and my manual install of youtube-dl downloads a 400MB file. 

I am quite pleased at the fast response and the targeted resolution. Thank you @Tzahi12345 :)

Any word on when this will make it in to the stable channel for Docker?

**Comment by Tzahi12345** [comment]
Glad I could help! You can see a longer explanation in the Discussions, but hopefully sometime in the next 3 weeks or so.

Let me know if you need any other help!
