### ISSUE TITLE
Extension: Right click menu support

### ISSUE THREAD

**Issue by gerroon** [Tzahi12345/YoutubeDL-Material#281]
Hi

Thanks for the browser extension, very helpful. Is it possible to add it to the browser right click menu so that we can download videos from urls in the pages. Right now one has to be in aan actual Youtube vidoe page to be able to activate the downloader.

Also it would  be nice if the downloader starts right away instead if taking to the download  page.

thanks

**Comment by Tzahi12345** [comment]
While your specific request wasn't possible, I reworked the extension so it should fit this use case (and it means you can download non-YT links too!)

If you're on Firefox, update the extension 0.4, or use the zips located in the repo. See screenshot below for a preview.

![image](https://user-images.githubusercontent.com/707413/102673190-1f700400-4161-11eb-9327-758ec79539c8.png)

[Relevant commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/cd93313cfc3a26a0cd113466567f55dc4cd47a17)
