### ISSUE TITLE
Ability to download Liked Videos playlist?

### ISSUE THREAD

**Issue by darth2499** [Tzahi12345/YoutubeDL-Material#282]
Ever since YouTube made the Liked Videos playlist private it seems to be much more difficult to download them using youtube-dl. I set my cookies and can confirm that I can indeed download my private videos but no way of downloading my Liked Videos, I simply get this error.

`2020-12-12T08:44:49.260Z ERROR: ERROR: The playlist does not exist.`
`2020-12-12T08:44:49.260Z ERROR: Subscribe: Failed to get subscription info. Subscribe failed.`

The URL for the playlist just lists as `https://www.youtube.com/playlist?list=LL` so perhaphs that's the issue?

**Comment by darth2499** [comment]
I have figured it out, the URL worked and I just had to ignore the warning and eventually it started downloading them.

**Comment by Tzahi12345** [comment]
Awesome, good to hear. Not sure why the error comes up, probably has to do with it being private.
