### ISSUE TITLE
Default Arguments , Not downloading highest Res

### ISSUE THREAD

**Issue by Elwador** [Tzahi12345/YoutubeDL-Material#284]
I used this: "youtube-dl https://www.youtube.com/watch?v=hJqYc62NCKo -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 -o video/%(uploader)s [%(channel_id)s]/%(playlist_index)s - %(title)s [%(id)s].mp4 " in the YoutubeDL-Material Docker and in my Ubunut VM. But in the Material Docker i got a file size of 10mb and in my VM the file size was 180mb. 
I have no clue how to get my Docker to download the higher Res Video.

I also tried do download the video only with -f bestvideo[ext=mp4]+bestaudio[ext=m4a] but this results in the download failing and the log says "ERROR: requested format not available".
That are the formats that i got with -F in my VM:
![grafik](https://user-images.githubusercontent.com/75888166/102003564-377ef800-3d09-11eb-89b5-10a77d633175.png)

The other thing is that the default Argmuments don't get removed when i add Arguments of my own or change the Output Pattern. 
The only workaround i found for this is to use the Advanced download mode.

**Comment by Tzahi12345** [comment]
Are you on the latest nightly? If not switch your tag to `nightly` and try again, it should download the best quality video.

This was an issue in the v4.1 but it has since been fixed.

**Comment by Elwador** [comment]
I downloaded the nightly build now. But before I can really test it i have another question reagrding Permissions.
I am using Unraid and installed the Docker but all the Videos downloaded and the Folders created by the Docker are set to group/user 1000. I tried to set the PUID/PGUID 99/100 but it didn't change anything. 
And i think because of that i can't delete downloaded videos the webinterface says "Deleted sucsessful" but after reloading the page the video is back. 
Is there a option to set the permission somewhere?

**Comment by Elwador** [comment]
> 
> 
> I downloaded the nightly build now. But before I can really test it i have another question reagrding Permissions.
> I am using Unraid and installed the Docker but all the Videos downloaded and the Folders created by the Docker are set to group/user 1000. I tried to set the PUID/PGUID 99/100 but it didn't change anything.
> And i think because of that i can't delete downloaded videos the webinterface says "Deleted sucsessful" but after reloading the page the video is back.
> Is there a option to set the permission somewhere?

I figured it out had to create those 3 Variables:
![grafik](https://user-images.githubusercontent.com/75888166/102022644-7acc7b80-3d88-11eb-964f-5d79409bb9ea.png)

And for downloading i am now usign : -f bestvideo[height<=?1080][fps<=?30]+bestaudio/best --prefer-ffmpeg --merge-output-format mkv

still get mp4 files for some reason but now my Plex is able to play the files without getting an error that the formate av1 isn't supported

**Comment by Tzahi12345** [comment]
>But i noticed that it messes things up if i delete files with my data explorer instead of the delete funktion in the webinterface.

Yup, on startup the server doesn't check for deleted files, perhaps this should be done. Feel free to create an issue for this!

>And for downloading i am now usign : -f bestvideo[height<=?1080][fps<=?30]+bestaudio/best --prefer-ffmpeg --merge-output-format mkv

Not sure what's causing this, but this app only supports mp4 and mp3 files. I've attempted to make it file format agnostic and it was a bit of a task so it won't be an easy switch.
