### ISSUE TITLE
Paging control shows "of 100"

### ISSUE THREAD

**Issue by jo-me** [Tzahi12345/YoutubeDL-Material#286]
Paging reports 100 items even though there are only 30

![image](https://user-images.githubusercontent.com/10351272/102022654-815af300-3d88-11eb-81b2-abf0b090cc5c.png)

**Comment by GlassedSilver** [comment]
It also will cap out there... so if you expect pages after it... There won't be any way to get to those older pages.

**Comment by Tzahi12345** [comment]
Nice bug finds!

@jo-me In the latest nightly the `of X` will now reflect the total number of videos (or if you're searching, the number of videos that match the search)

@GlassedSilver I fixed that issue as well, though it shouldn't be a problem now regardless as the above fix will prevent you from landing on an empty page

I also moved the paginator slightly down as it felt too close to the videos. And I added some text if your search results in no videos or if you never downloaded any videos to begin with. Let me know if you run into any other issues, and thanks for the report as always! Pull the latest `nightly` for the fixes.

[Relevant commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/e39e8f3dba8f719ee3fdab89f0cb2d71ceaed629)

**Comment by GlassedSilver** [comment]
TIL I have over 30k videos already!

Well, that's a lot of safety against bitrot of videos I share and get shared with!

**Comment by Tzahi12345** [comment]
That's incredible, no wonder the home page refused to load without the pagination haha

**Comment by GlassedSilver** [comment]
The upside is that I guess I'm the scalability test group? :D
