### ISSUE TITLE
Authentication bug

### ISSUE THREAD

**Issue by dovy6** [Tzahi12345/YoutubeDL-Material#291]
#Set up youtube-dl-material with multi-user mode enabled, which, when I access it over a nginx reverse proxy requires me to log in. See 
![image](https://user-images.githubusercontent.com/76541192/103046819-94737d00-4557-11eb-9b7d-96c0753f089d.png)

However, without logging in, and with no authentication, you can go to settings: 
![image](https://user-images.githubusercontent.com/76541192/103046881-c08efe00-4557-11eb-9fb6-68e3dfcdc951.png)

unselect multi-user mode: 
![image](https://user-images.githubusercontent.com/76541192/103046910-dbfa0900-4557-11eb-82c7-383f8a3dd8b9.png)

and poof, you have full access with no authentication required:
![image](https://user-images.githubusercontent.com/76541192/103046942-f3d18d00-4557-11eb-9380-28a65a91d502.png)

Thank you very much for your work in creating this docker.

**Comment by dovy6** [comment]
Sorry, can't figure out how to edit my post, but here's the screenshot with the settings button I meant to post:
![image](https://user-images.githubusercontent.com/76541192/103047096-63477c80-4558-11eb-8d8d-0f140d6ba47e.png)

**Comment by Tzahi12345** [comment]
Are you on Docker? If so, can you try using the `nightly` tag? This should be fixed! v4.2 is dropping soon and so that will resolve it for all users on the `latest` tag or those not on Docker.

**Comment by dovy6** [comment]
Appears to have fixed it, thank you!
