### ISSUE TITLE
ERROR: Could not find associated JSON file for audio file

### ISSUE THREAD

**Issue by wardwygaerts** [Tzahi12345/YoutubeDL-Material#293]
Since this morning, I see these error in the logs for every audio file which is downloaded (every 5 minutes). The .json file is still located next to the .mp3.
The error also appears for newly downlaoded audio files.

I'm on v4.2

**Comment by Tzahi12345** [comment]
Bug squashed! It was a relatively easy one, basically in the metadata it would sometimes get the [file extension wrong](https://github.com/ytdl-org/youtube-dl/issues/17560) (it thought the mp3 was a webm file) and so when we removed the last three letters in the file name it contained a nasty extra `.`

I converted the code to remove the file extension that's a lot more reliable. You can see the [commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/dbf08e127658b58e2003e19f631892462535d5d4) I've pushed these changes the `nightly`, `4.2`, and `latest` tags, it will take an hour or so for those to get updated. Thanks for the bug report!
