### ISSUE TITLE
FR: Extension: Mobile compability

### ISSUE THREAD

**Issue by gerroon** [Tzahi12345/YoutubeDL-Material#294]
Hi

Is it possible to make the Firefox/Chrome extension installable on the mobile versions of these browsers?

thanks

**Comment by Tzahi12345** [comment]
The new version of Firefox (released around September) makes this kinda difficult, and the functionality itself is a bit clunky.

I just added some instructions on the wiki page for Firefox on Android, [see here](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Firefox-Extension#android). This is pretty much the only way to do it, as Chrome on Android doesn't let you install any extensions, and even Kiwi (a browser with extensions listed as one of its features) doesn't let you edit the settings for the extension for whatever reason.

Hope this makes sense.
