### ISSUE TITLE
FR: Set file time to the download time

### ISSUE THREAD

**Issue by gerroon** [Tzahi12345/YoutubeDL-Material#296]
Hi

Is it possible to set the date/time of the downloaded video file to the download time rather than the time that is set by Youtube? If the downloaded video is really old then the file modif date to tbe very old as well there for it won't show up properly at the top properly in  the file explorer's date sorting.

thanks

**Comment by Tzahi12345** [comment]
Hi! Where exactly are you referring to? On the home screen or the video info dialog?

**Comment by gerroon** [comment]
I mean the actual file modification date of the actual file. I do not use the frontend myself, I use a regular file browser.

**Comment by Tzahi12345** [comment]
If you go into your settings and add `--no-mtime` to your global custom args, I *think* this should fix it. Let me know if it works!

**Comment by Tzahi12345** [comment]
I don't think a dedicated option for this is necessary as the feature already exists within youtube-dl. If you have any other feature requests feel free to open an issue! I'll go ahead and close this one.
