### ISSUE TITLE
Add helm chart

### ISSUE THREAD

**Issue by koeberlue** [Tzahi12345/YoutubeDL-Material#297]
For an easy deployment option on kubernetes it would be awesome to have a helm chart in place. This would allow me to get this project up and running in no time.

Since we already have a `docker-compose.yml` we could use [Kompose](https://kompose.io/user-guide/#alternative-conversions) to generate a first version.

**Comment by Tzahi12345** [comment]
Still trying to understand how the Kubernetes stack works, would I use Kompose to create an artifact and then upload that to [ArtifactHub](https://artifacthub.io/)?

Basically what I'm asking is: what do I do with the output files from Kompose?

**Comment by koeberlue** [comment]
Disclaimer: I've never done this myself before. Some parts may be inaccurate. Also by researching the necessary steps i discovered that publishing charts is way more complicated than i thought 🙈 

Helm expects a specific folder and data structure for a chart. Kompose will generate yaml files in a this specific folder structure in a subfolder called `docker-compose`. 

Probably we would want to change some variables and rename the base folder `docker-compose` to `chart` and so on. But in general that should be enough for a first draft. Maybe add an Ingress aswell.

To get the chart published on Artifacthub we would need to host a repository. Most people seem to use github pages for this: https://helm.sh/docs/topics/chart_repository/

**Comment by Tzahi12345** [comment]
I *think* I got it uploaded, don't have an ArtifactHub link yet but here's the link to the repo:

https://tzahi12345.github.io/YoutubeDL-Material/docker-compose

Let me know if that works, I don't really have a way to test this.

**Comment by koeberlue** [comment]
Awesome! I could add the repo to helm and was able to deploy the chart.

Unfortunately the Pod was not able to start. There seems to be a problem with the volume mounts, since they are created with a hardcoded path to your local machine. 

![IMG_20201231_063551_236](https://user-images.githubusercontent.com/22097982/103396304-b01bec00-4b32-11eb-8815-53b57848924d.jpg)

For the initial version we should probably use persistent volume claims. When i tested Komlose with the docker-compose.yml it actually created those claims for me (just ignore the warnings about unsupported paths).

Is there any way i can support you with this issue? I'd be happy to donate some money so you could test this on any cloud provider. I might also create a PR with a preconfigured chart, but this could take some weeks.

**Comment by Tzahi12345** [comment]
>Unfortunately the Pod was not able to start. There seems to be a problem with the volume mounts, since they are created with a hardcoded path to your local machine.

The reason I set it up that way was because I thought the mounts wouldn't exist otherwise, and if the container was ever re-made (like during an update) it could lose all the application data. But if those mounts (I guess they're called claims?) exist anyways that works.

>For the initial version we should probably use persistent volume claims. When i tested Kompose with the docker-compose.yml it actually created those claims for me (just ignore the warnings about unsupported paths).

Ok! I went ahead and set it up that way, you can try running it again.

>Is there any way i can support you with this issue? I'd be happy to donate some money so you could test this on any cloud provider. I might also create a PR with a preconfigured chart, but this could take some weeks.

Hm I don't want to take donations, especially because I don't know how to set up kubernetes on the cloud. But if the current version doesn't work and you want to do so, you can set it up and give me credentials/instructions to play around with.

**Comment by koeberlue** [comment]
Trying it out right now. The volumes are looking good so far. I cannot test if the pod starts, because I hit the docker pull rate limit right now. Will report back again in some hours.

So quick explanation on those persistent volume claims: You basically tell kubernetes to create a persistent volume for you and then you can mount it inside your container. Whoever set up the kubernetes cluster is then responsible to provide the volumes you claimed and to make sure they are persisted between container restarts. But as a developer you don't have to care about how to create the volumes.

If you are willing to go the extra mile, you can quite easily set up a local development cluster e.g. with

**Comment by koeberlue** [comment]
Update: The pod started just fine. Great work! 

For the container to be accessible from the outside, i would suggest adding an Ingress. Short explanation (pretty simplified): Most kubernetes clusters run a reverse proxy by default. For minikube, it can be activated with `minikube addons enable ingress`. To configure this proxy, you create Ingress objects, in which you can define which service should be accessible via which URL.

If you create a new chart with `helm create` those objects come preconfigured: https://docs.bitnami.com/tutorials/create-your-first-helm-chart/
Maybe we can merge them with the files created by Kompose.

**Comment by Tzahi12345** [comment]
In the meantime I actually created a cluster on gcloud as they had a free tier and it was surprisingly easy to set up! Pod works great for me, performance is great.

>They have very generic names like ytdl-material-claim0. They could probably be easily renamed to `ytdl-material-claim-videos' or something like that. Search and replace on the original string should be sufficent

> They are all limited to 100Mi. Maybe we could provide some sane defaults like 50Gi for videos etc. This could then be a configurable option in a later version

Fixed and fixed! Making it configurable requires a [StorageClass](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/), but isn't this platform-specific? It has a field `provisioner:` which they set to `kubernetes.io/gce-pd` which only applies to gcloud it seems.

Regarding the ingress, I did this in gcloud too and it autogenerated this YAML:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\tzahi\Documents\YoutubeDL-Material\kompose.exe --file .\docker-compose.yml
      convert -c
    kompose.version: 1.21.0 (992df58d8)
    meta.helm.sh/release-name: my-youtubedl-material
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-12-31T10:11:12Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    io.kompose.service: ytdl-material
  name: ytdl-material
  namespace: default
  resourceVersion: "686"
  selfLink: /api/v1/namespaces/default/services/ytdl-material
  uid: 07d9a9da-332d-4053-ad10-96ea21eea9e4
spec:
  clusterIP: 10.8.7.16
  ports:
  - name: "8998"
    port: 8998
    protocol: TCP
    targetPort: 17442
  selector:
    io.kompose.service: ytdl-material
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

This also seems platform-specific (e.g. `clusterIP`). Is there a way to generalize this and/or the StorageClass so it can be consumed by all platforms?

**Comment by koeberlue** [comment]
> In the meantime I actually created a cluster on gcloud as they had a free tier and it was surprisingly easy to set up! Pod works great for me, performance is great.

Nice! I didn't know about the free tier. That's great for development :+1:

Let's have a look at the two open parts: Ingress and persisten volumes:

### Ingress

So you created a service of type `ClusterIP`. This means, that your Pods can only be reached from inside the cluster. This is absolutely okay, because then the reverse proxy, also running inside the cluster, can access it. But you need to tell the reverse proxy, how the service should be reachable from the outside. For this, Kubernetes uses an `Ingress`.

If you want to give the user full control over the service and ingress configuration while still having sane defaults, i'd suggest to just just the helm defaults.

I just ran `helm create test` locally to get the files needed. I will just paste those files here so you can adapt it to your solution.

First of all, you have to add some entries to `values.yaml`. These are the default values, which _can_ be overridden by every user on deployment.

<details>
  <summary>`values.yaml`</summary>
```
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```
</details>

(Note: The following snippets may contain the word `test` as this was the name of my chart. They need to be replaced by the name of your chart)

You should keep the comments to help users with their configuration.

Then there needs to be an ingress object:

<details>
  <summary>`templates/ingress.yaml`</summary>
```
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "test.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
```
</details>

So, if the user enables the ingress in his `values.yaml`, helm will create an ingress with the provided values.

Then we need to make the service configurable:


<details>
  <summary>`templates/service.yaml`</summary>
```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "test.fullname" . }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "test.selectorLabels" . | nindent 4 }}
```
</details>

Again this will deploy the service exactly like the user configured it. Note that the `targetPort` is set to `http`. So in one of your existing `yaml` files, there should be a port definition for the container. Add `name: http` to this definition.

This should be sufficent to get the ingress running.

### Persistent volume

> Making it configurable requires a StorageClass, but isn't this platform-specific? It has a field provisioner: which they set to kubernetes.io/gce-pd which only applies to gcloud it seems.

To make the size of the volume configurable, you would just need to add a value for the size to `values.yaml` and use it in `templates/ytdl-material-claim-XXX`. If you do not specify a `StorageClass`, Kubernetes will just use the storage class that was configured as the default for the cluster. If you want to make it completely configurable, there is some more work involved. Since I do not know, how your yaml files look right now, let me just point you to another helm chart: https://github.com/bitnami/charts/tree/master/bitnami/mariadb

So the default configuration can again be found in (`values.yaml`)[https://github.com/bitnami/charts/blob/c59b86919f47504bc8fd06f75a024f55e58ace77/bitnami/mariadb/values.yaml#L309]. It is then used in [`templates/primary/statefulset.yaml`](https://github.com/bitnami/charts/blob/c59b86919f47504bc8fd06f75a024f55e58ace77/bitnami/mariadb/templates/primary/statefulset.yaml#L304). You will probably not have a `StatefulSet`, so just look out for the place, where your container is defined.

**Comment by Tzahi12345** [comment]
Thanks for the configs! They were pretty helpful -- it was missing one file though which I had to add manually: _helpers.tpl. Otherwise I did experience a couple issues:

1. `targetPort: http` in service.yaml gave me the following error: `containerPort: got “string”, expected “integer”`  ([this SO question](https://stackoverflow.com/questions/56749674/kubernetes-validationerror-invalid-type-for-io-k8s-api-core-v1-containerport-con) seems related). So I made it static for now, but this isn't something that *has* to be configurable right? It's just the internal port, the .Values.service.port is really all that matters.

2. The selectorLabel logic in _helpers.tpl didn't seem to work, as when it was used in the service yaml it caused gcloud to not find the pod associated with the chart. Once I hardcoded it back to `ytdl-material` it worked fine. This may have been my fault though as I'm not super familiar with YAMLs and the way these "variables" work. It doesn't seem *super* important, but again, my limited knowledge prevents me from seeing where this could be an issue.

I went ahead and added the ingress as well, gcloud is persistent on creating its own ingresses so I'm not sure if it works lol. You can test it out yourself, and I should've given this link to you earlier but here's the repo: https://github.com/Tzahi12345/YoutubeDL-Material/tree/gh-pages/docker-compose

I also made the claim sizes configurable in the `values.yaml`. Ideally they should be expandable, I looked for the `allowVolumeExpansion` field in the example storage classes but I couldn't find it. Is it possible for users to add this themselves or once the volumes are made it can't be changed?

Also, there was a typo this morning in one of the claims, so that's fixed and the chart should work without issue now.

**Comment by koeberlue** [comment]
Alright, I installed the latest version and it was really easy to configure. It took me like three minutes on my smartphone to get everything up and running. That's incredible 👍 

There was just one _small_ issue with the ingress. Note that the ingress needs a `serviceName` and uses a variable for that. But the service has a hardcoded name `ytdl-material`. I would suggest to just hardcode it in the ingress as well.

Concerning the hardcoded values for port and service name: It probably won't matter, as long as you do not deploy ytdl-material twice in the same namespace. But currently I can't imagine a scenario where this might be useful.

The `allowVolumeExpansion` is something that the cluster provider (e.g. Google) would configure for you. So if your provider allows to resize volumes, you can do it. If not, you need a fresh redeploy or must delete videos. There is really not much we can do here. 

So from my point of view, if the ingress is fixed, this issue would be solved. There might come some different use cases which will then need to be implemented in the chart, but for a first version this looks really great.

Maybe before the release you could also do some renaming. The folder `docker-compose` should probably be called `chart`. And you might remove the `ytdl-material-` prefix from the template files.

**Comment by Tzahi12345** [comment]
Done! Files and folder are renamed, and the serviceName is hardcoded. The new repo URL is https://tzahi12345.github.io/YoutubeDL-Material/chart. 

For posterity, here's the chart on ArtifactHub: https://artifacthub.io/packages/helm/youtubedl-material/youtubedl-material

I'll go ahead and close this issue, feel free to open another one if you have additional suggestions or run into any issues. Happy new years!

**Comment by koeberlue** [comment]
I just did a fresh install with the last changes and everything went through without any problems. Thanks for your time and effort :+1: Please let me know if there is a way to drop a donation. I'd love to at least buy you a coffee ;)

Since you also published the chart on artifacthub, I assume that additionial suggestion will be coming soon ;)

**Comment by Tzahi12345** [comment]
I don't need the money :) truth is, I do this for fun, and I feel like if I got donations it would feel like a job.

Anyways the fact that I made something you *would* donate to is inspiring, thank you!

**Comment by patoarvizu** [comment]
Is the source for the chart somewhere on this repo? I'd like to inspect it and see what can be tuned before deploying it.

**Comment by Tzahi12345** [comment]
@patoarvizu Yup! You can see it [here](https://github.com/Tzahi12345/YoutubeDL-Material/tree/gh-pages/chart)

**Comment by patoarvizu** [comment]
Ah thanks! Any reason why it's only on the `gh-pages` branch?

**Comment by Tzahi12345** [comment]
I could merge it into master, but it isn't really necessary. ArtifactHub requires it to be accessible through a web server which GitHub pages does, so that's why we're using a GH pages-specific branch. Not merging it into master was a stylistic decision, as if I make any updates to the templates in `gh-pages` I'd have to merge it into master again (*and* rebase the gh-pages branch prior to making changes). Hope that makes sense.

**Comment by patoarvizu** [comment]
Yeah, I was asking precisely because if updates or contributions are made to the chart, they would have to be made on the branch and then rebase/merge up, not because I necessarily thought it's wrong.

You can always serve your GH pages off a directory in your main branch, so that way you don't have to keep merging/rebasing.

In any case, it's not immediately necessary, only a suggestion. Thanks!

**Comment by benashby** [comment]
I just opened https://github.com/Tzahi12345/YoutubeDL-Material/pull/359 to get a more robust helm chart in
