### ISSUE TITLE
Error downloading with nightly on Raspberry 4

### ISSUE THREAD

**Issue by luandro** [Tzahi12345/YoutubeDL-Material#298]
Getting this error when trying to download a video:

```
youtubedl_1  | 2021-01-01T20:10:46.583Z ERROR: Error during parsing:Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json http://www.youtube.com/watch?v=Xq8IgOcJ2qQ

youtubedl_1  | 2021-01-01T20:10:46.585Z ERROR: failed to parse for urls starting with https://www.youtube.com/watch?v=Xq8IgOcJ2qQ&ab_channel=NewenAfrobeat

youtubedl_1  | 2021-01-01T20:10:49.479Z ERROR: Error while retrieving info on video with URL https://www.youtube.com/watch?v=Xq8IgOcJ2qQ&ab_channel=NewenAfrobeat with the following message: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json -o video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail http://www.youtube.com/watch?v=Xq8IgOcJ2qQ
```

Running docker-compose nightly image on a Raspberry 4.

Any ideas what could be causing?

**Comment by Tzahi12345** [comment]
I've had this error when youtube-dl randomly stops working, can you go into the Advanced tab in the settings and switch to youtube-dlc? Let me know if that works!

**Comment by luandro** [comment]
Thanks for the quick response @Tzahi12345!

But unfortunately that didn't do the trick. Any other ideas?

**Comment by Tzahi12345** [comment]
I should have mentioned, it does require a server restart which will download the alternate binary.

Are you using any additional args? Turn on verbose debugging and share the args being used, it should show up on the console.

Other than that I'm not sure what could be causing it. I'll see if I can get it to print a more descriptive error message as error code 1 doesn't really say much

**Comment by luandro** [comment]
I had done a `docker-compose down && docker-compose up` should that be enough?

This is what versobe debugging gives me:

```
youtubedl_1  | 2021-01-01T21:52:33.387Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--write-thumbnail
youtubedl_1  | 2021-01-01T21:52:40.419Z DEBUG: URL info retrieval delay: 7.795 seconds.
youtubedl_1  | 2021-01-01T21:52:40.421Z ERROR: Error during parsing:Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json http://www.youtube.com/watch?v=Xq8IgOcJ2qQ
youtubedl_1  | 2021-01-01T21:52:40.423Z ERROR: failed to parse for urls starting with https://www.youtube.com/watch?v=Xq8IgOcJ2qQ&ab_channel=NewenAfrobeat
youtubedl_1  | 2021-01-01T21:52:41.046Z ERROR: Error while retrieving info on video with URL https://www.youtube.com/watch?v=Xq8IgOcJ2qQ&ab_channel=NewenAfrobeat with the following message: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl --dump-json -o video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail http://www.youtube.com/watch?v=Xq8IgOcJ2qQ
```

**Comment by Tzahi12345** [comment]
I went ahead and updated the latest `nightly` so that the error message includes more info, do you mind running it again and seeing what comes out?

**Comment by luandro** [comment]
Seemed to have starting working now with youtube-dlc. Might have been a combination of youtube-dl stopping and a networking problem.

Thanks for the quick responses and ajustments @Tzahi12345! This project is amazing, wish you the best!

**Comment by Tzahi12345** [comment]
Always a pleasure, let me know if you run into any other issues!
