### ISSUE TITLE
Streams instead of downloading

### ISSUE THREAD

**Issue by UltraTV** [Tzahi12345/YoutubeDL-Material#3]
When I "Download" a video or mp3 it streams it on my browser instead of directly downloading it.
(google chrome and nginx)

**Comment by Tzahi12345** [comment]
I believe this is just a feature of the browser. If you right click on the player, it should have a "save video" option, which will download it normally. Would you like a "download-only mode" to prevent this kind of behavior? Not sure if it can be done, but I can certainly look into it.

**Comment by UltraTV** [comment]
Yes, a download only mode would be great.
AllTube also somehow managed to force downloads.

**Comment by Tzahi12345** [comment]
New update just dropped which primarily adds this feature. Check it out [here](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v2.1), and feel free to open any issues if you face any. Thanks for the suggestion!
