### ISSUE TITLE
Successfully compiled - but not serving YoutubeDL-Material on the web-port

### ISSUE THREAD

**Issue by ProxyCell** [Tzahi12345/YoutubeDL-Material#300]
I recently pulled the release for 4.2 and while it appears to work in the terminal, it never actually serves up the web server on port 17442 like v4.1 is doing on the same machine.

With 4.2 I execute `npm start` and it begins compiling, starts an angular development server on port 4200 and tells me that it compiled successfully, it then rests here permanently

I feel like I'm overlooking something very simple here but I'm not super-familiar with node. I'm attaching two log files showing the different outputs when running `npm start` in both 4.1 and 4.2.

[youtubedl-material-4.1-WORKING-log.txt](https://github.com/Tzahi12345/YoutubeDL-Material/files/5761226/youtubedl-material-4.1-WORKING-log.txt)
[youtubedl-material-4.2-ERROR-log.txt](https://github.com/Tzahi12345/YoutubeDL-Material/files/5761227/youtubedl-material-4.2-ERROR-log.txt)

**Comment by ProxyCell** [comment]
pi@raspberry ~/youtubedl-material ❯ nvm ls                                                                                                                         14:13:59
->     v14.15.3

pi@raspberry ~ ❯ cat /etc/os-release                                                                                                                               14:15:25
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

**Comment by Tzahi12345** [comment]
Did you get the zip from the [releases page](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v4.2)?

All you have to do is run `npm install` and then `npm start`.

If you directly pull from GitHub (which it seems you did), you can compile it yourself with the [instructions here](https://github.com/Tzahi12345/YoutubeDL-Material#build-it-yourself), but it isn't necessary and the zip method is a lot simpler.

**Comment by ProxyCell** [comment]
> Did you get the zip from the [releases page](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v4.2)?

No, I have done something much more embarrassing instead: I've been pulling the zipped source code... my lack of familiarity with node is really bothering me now as I should have noticed the directory layout difference...

Thank you @Tzahi12345 - I feel strange now

**Comment by Tzahi12345** [comment]
No problem! Happens to the best of us :) let me know if you run into any other issues
