### ISSUE TITLE
HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by jarmery** [Tzahi12345/YoutubeDL-Material#302]
I have a number of subscriptions running, and now attempting to download any video through Material results in a download failed error. Console output repeats error:
`ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by Tzahi12345** [comment]
Since many users have had this specific error come about, I've gone ahead and made [this wiki page](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Fixing-429-errors) explaining the error and its possible solutions. Let me know if any of them work for you!

**Comment by jarmery** [comment]
Thanks, after waiting a couple days my IP is now unblocked but I'll try adding a cookies.txt if it happens again the future

**Comment by gartner2000** [comment]
Hi

I have tried --sleep-interval,,60 & --proxy & cookies.txt.
Cant get it to work.. also tried check interval to 3600.
Tried for a week.
Using docker in unraid.

**Comment by yllekz** [comment]
I got whacked by this recently too. I can't seem to shake the ban.

**Comment by Tzahi12345** [comment]
Proxy doesn't work sometimes for whatever reason, if you are on Docker can you try the [docker-compose method](https://github.com/Tzahi12345/YoutubeDL-Material/issues/177#issuecomment-722685712)?

**Comment by yllekz** [comment]
I gave that a shot but the URLs in those variables apparently don't exist. Do I need to replace them with other ones?

**Comment by Tzahi12345** [comment]
Ah yes I should have mentioned, you do need your own proxy for this (there are free ones available, just found some [here](https://spys.one/en/socks-proxy-list/))

**Comment by Tzahi12345** [comment]
Closing this issue as it's stale, but refer to #173 and #429 for improvements on this front!
