### ISSUE TITLE
Ability to reject certain codecs

### ISSUE THREAD

**Issue by ibrahimk157** [Tzahi12345/YoutubeDL-Material#303]
Hello,

I have a few issues I’d like to report along with a few suggestions:

Issues with v4.2:

1) Locking the settings under a pin seems to be gone... I looked through everywhere and I cant find it anymore!

2) https://github.com/Tzahi12345/YoutubeDL-Material/issues/28 seems to have gone unnoticed even though the issue still occurs with v4.2

Suggestions:

1) Add an option in settings to bring back the thing where Max quality downloads the best MP4, since I face issues playing other formats (such as WebM) on iOS.

2) Add an option to either never download VP9 codec videos or convert them to one of H. 264, H. 265, MPEG-4, M-JPEG as for even though apple did add the VP9 codec support to iOS, they seemed to have missed the iPhone X so VP9 videos dont play at all.

**Comment by Tzahi12345** [comment]
>Locking the settings under a pin seems to be gone... I looked through everywhere and I cant find it anymore!

The setting a pin feature was phased out after several bugs came about due to it -- ultimately it was added before multi-user mode was implemented and that serves the same purpose. You can read a bit more about [that here](https://github.com/Tzahi12345/YoutubeDL-Material/issues/147). Does this work in your use case or was the pin more convenient?

>#28 seems to have gone unnoticed even though the issue still occurs with v4.2

I've been wanting to fix this for a while since it's one of the oldest bugs in there, you're right in that I haven't given it the attention it deserves.

I have two problems when I try to solve this: first, I don't have consistent access to an iOS device, though I have used online services to emulate them and I have found this bug.

And second, it happens very inconsistently across devices and versions, so much so that I haven't found a single pattern where it doesn't work with X device prior to Y version or anything like that. Really weird stuff :/ I'll see if there's an iPhone I can snag from my parents, they probably have a couple sitting in a drawer somewhere lol

>Add an option in settings to bring back the thing where Max quality downloads the best MP4, since I face issues playing other formats (such as WebM) on iOS.

This actually sounds more like a bug because the videos should be converted to mp4 (it leverages the `--merge-output-format mp4`). Make sure you have ffmpeg installed as this could be giving you issues here.

>Add an option to either never download VP9 codec videos or convert them to one of H. 264, H. 265, MPEG-4, M-JPEG as for even though apple did add the VP9 codec support to iOS, they seemed to have missed the iPhone X so VP9 videos dont play at all.

This is definitely possible! There's a way to do this in youtube-dl and you can't really add a custom arg to fix this so it'll be a dedicated setting. But it sounds quite useful!

**Comment by ibrahimk157** [comment]
> > Locking the settings under a pin seems to be gone... I looked through everywhere and I cant find it anymore!
> 
> The setting a pin feature was phased out after several bugs came about due to it -- ultimately it was added before multi-user mode was implemented and that serves the same purpose. You can read a bit more about [that here](https://github.com/Tzahi12345/YoutubeDL-Material/issues/147). Does this work in your use case or was the pin more convenient?
> 
> > #28 seems to have gone unnoticed even though the issue still occurs with v4.2
> 
> I've been wanting to fix this for a while since it's one of the oldest bugs in there, you're right in that I haven't given it the attention it deserves.
> 
> I have two problems when I try to solve this: first, I don't have consistent access to an iOS device, though I have used online services to emulate them and I have found this bug.
> 
> And second, it happens very inconsistently across devices and versions, so much so that I haven't found a single pattern where it doesn't work with X device prior to Y version or anything like that. Really weird stuff :/ I'll see if there's an iPhone I can snag from my parents, they probably have a couple sitting in a drawer somewhere lol
> 
> > Add an option in settings to bring back the thing where Max quality downloads the best MP4, since I face issues playing other formats (such as WebM) on iOS.
> 
> This actually sounds more like a bug because the videos should be converted to mp4 (it leverages the `--merge-output-format mp4`). Make sure you have ffmpeg installed as this could be giving you issues here.
> 
> > Add an option to either never download VP9 codec videos or convert them to one of H. 264, H. 265, MPEG-4, M-JPEG as for even though apple did add the VP9 codec support to iOS, they seemed to have missed the iPhone X so VP9 videos dont play at all.
> 
> This is definitely possible! There's a way to do this in youtube-dl and you can't really add a custom arg to fix this so it'll be a dedicated setting. But it sounds quite useful!

As for the multi-user mode, I have played around with it. The reason why I haven’t found it to be suitable is because it locks the entire downloader behind the user authentication system (as in, you need to login to download videos, etc...). I want the downloader itself to be accessible without the need of having to create a user/login... and only have the settings locked up. 

I suggest bringing back the pin option BUT doing it in such a way that you can’t have both the pin and multi-user mode enabled at the same time. That way they never conflict with each other, hence (hopefully) getting rid of the bugs.

As for the safari download bug, if you manage to get ahold of an iPhone (or any iOS/iPadOS device for a matter of fact), make sure that it’s running iOS 13 or newer as that’s when apple added the download manager to safari. On previous versions of iOS, downloads still took place, just within the tab itself rather than through a download manager/queue... so no clue if that old system would behave differently with youtubedl-material.

As for files not being converted to MP4, I do have ffmpeg installed. However, now I’m not entirely sure if the videos aren’t playing due to the format, might just be the issue with the incompatible codecs I’ve mentioned earlier. I just assumed that the format might be one that’s incompatible, don’t know for sure. Can’t seem to figure out how to reproduce this either, so you can just ignore it.

As for the VP9 codec thing, great to hear that it’s possible through youtube-dl!

And as always, I appreciate all of the time and effort you put into all of this! Can’t thank you enough!

**Comment by GlassedSilver** [comment]
> This actually sounds more like a bug because the videos should be converted to mp4 (it leverages the `--merge-output-format mp4`). Make sure you have ffmpeg installed as this could be giving you issues here.

The issue is when you download best quality audio and video separately these days you'll often get webm videos and the merge into a mp4 container errors out.

An option to not merge into mp4 but basically whatever is needed should be added, since iOS support isn't relevant to every user but does limit your options in codecs and containers.

**Comment by GlassedSilver** [comment]
Ideally we would always download just what the user wants, e.g. best audio + best video -> merge into whatever container is necessary.

Then for playback transcoding can help if you're on an incompatible client.

This could be avoided by either going with best mp4 as download option or reencoding separately with ffmpeg, but forcing mp4 containers for everyone does have its limits and drawbacks.

**Comment by ibrahimk157** [comment]
> Ideally we would always download just what the user wants, e.g. best audio + best video -> merge into whatever container is necessary.
> 
> Then for playback transcoding can help if you're on an incompatible client.
> 
> This could be avoided by either going with best mp4 as download option or reencoding separately with ffmpeg, but forcing mp4 containers for everyone does have its limits and drawbacks.

Yes I do agree with you, adding an option for the user to choose is a great idea!

Also what about the issue with the pin above? Don’t you think the pin should be brought back and simply be made in a way that it can’t be enabled when multi-user mode is on? This is because multi-user made locks the entire downloader behind the authentication system, while the pin only locks the settings (which is what I need). Thanks!

**Comment by GlassedSilver** [comment]
I'm not sure having two separate authentication systems in place really helps things.

Ideally we'd have the authentication system that we do atm and then a setting to make downloads by users public or not. Ideally on a case-by-case basis. Of course, you could set user defaults and have all of your downloads public by default and whenever you download something you want to keep private you could have that set as private individually.

That way you could reap the benefits of both a public approach and a full authentication system.

I'll be honest with you though, I won't be able to work on this, at least not anytime soon. I'll ping @Tzahi12345 to invite him into this discussion, although if you don't mind that might be better off to be made an issue of its own.

Multi-issues are usually best left to track the progress of individual issues' progress and when they are closely related to another or even blocking among themselves. (i.e. one thing needs to be done to take care of another issue)

**Comment by ibrahimk157** [comment]
> I'm not sure having two separate authentication systems in place really helps things.
> 
> Ideally we'd have the authentication system that we do atm and then a setting to make downloads by users public or not. Ideally on a case-by-case basis. Of course, you could set user defaults and have all of your downloads public by default and whenever you download something you want to keep private you could have that set as private individually.
> 
> That way you could reap the benefits of both a public approach and a full authentication system.
> 
> I'll be honest with you though, I won't be able to work on this, at least not anytime soon. I'll ping @Tzahi12345 to invite him into this discussion, although if you don't mind that might be better off to be made an issue of its own.
> 
> Multi-issues are usually best left to track the progress of individual issues' progress and when they are closely related to another or even blocking among themselves. (i.e. one thing needs to be done to take care of another issue)

Good point! I appreciate all of the work you put into this! I’ll create a new issue for this.

**Comment by victor-rds** [comment]
@ibrahimk157 I was looking for something similar to block vp9, now I'm using custom args `-S +codec:av1:m4a`  or `-S +codec:av1:m4a`

**Comment by ibrahimk157** [comment]
> @ibrahimk157 I was looking for something similar to block vp9, now I'm using custom args `-S +codec:av1:m4a` or `-S +codec:av1:m4a`

Tried that and for some reason the same issue still occurs.

Here’s an example youtube video that this issue occurs with: https://youtu.be/BuFheTMljZk 
Mind checking if this specific video works fine on your end? As I just end up with this:

![8A8DA920-3777-4A20-9287-75F3409343D8](https://user-images.githubusercontent.com/17643723/209597421-8e5ed10f-855f-4d8e-bdd3-ff77b05bac68.png)
![B3516338-1BBA-4857-B049-C0A3552E05A7](https://user-images.githubusercontent.com/17643723/209597448-944be68a-9d32-4858-8bcc-c74b97417a57.png)

**Comment by ibrahimk157** [comment]
> @ibrahimk157 I was looking for something similar to block vp9, now I'm using custom args `-S +codec:av1:m4a` or `-S +codec:av1:m4a`

Tried that and for some reason the same issue still occurs.

Here’s an example youtube video that this issue occurs with: https://youtu.be/BuFheTMljZk 

Mind checking if this specific video works fine on your end? As I just end up with this:
![AA1FA2D2-D86F-4607-9D20-B140F2A793EF](https://user-images.githubusercontent.com/17643723/209597598-04f4893d-4cc1-4b61-8544-9390e9f9c926.jpeg)
![3B298B52-3C74-4F5A-9161-6E35D4ABDC2A](https://user-images.githubusercontent.com/17643723/209597603-2b941e2b-a398-4f3d-8eac-5d5be0eedfe3.png)
