### ISSUE TITLE
https (tls) support broken

### ISSUE THREAD

**Issue by GldRush98** [Tzahi12345/YoutubeDL-Material#305]
Upgraded from 4.0 to 4.2 and https no longer seems to work right.
The settings for the cert and key are also missing.

**Comment by Tzahi12345** [comment]
I decided to remove them in favor of doing it through a reverse-proxy. Does this apply in your use-case or was the old method preferable?

**Comment by GldRush98** [comment]
Ah I see. I run mine in a Docker container, so it was kind of nice to have it all inside a single standalone container. I understand if it simplifies your maintenance process though.

**Comment by Tzahi12345** [comment]
Yup, sorry about that. If you really want it back in, open up an issue and if there's others chiming in I'll gladly reimplement it :)
