### ISSUE TITLE
Video thumbnail should be downloaded as well

### ISSUE THREAD

**Issue by GldRush98** [Tzahi12345/YoutubeDL-Material#306]
It seems that video thumbnails are still linked to their original source.
If a video is deleted, then the thumbnail gets broken.
It would be nice if the thumbnail were downloaded as well as the video and saved so that it would always work regardless of the video's existence at its original source.

**Comment by Tzahi12345** [comment]
In the settings menu there's an option `Include thumbnail` in the Downloader tab. Is that option checked? If so this sounds like a bug.

**Comment by GldRush98** [comment]
Hmm, this option is checked. The one I have broken is back from May though, so if this was a recent addition, perhaps this was a video downloaded before that existed?

Yeah, so I just tried a new one and it appears the thumbnail was indeed downloaded.  Cool!

**Comment by Tzahi12345** [comment]
Awesome, yeah it was after v4.1 that it was truly fixed. I'll close the issue, let me know if you run into any other issues or have any suggestions.
