### ISSUE TITLE
Possibility to disable default json file ?

### ISSUE THREAD

**Issue by JamesDAdams** [Tzahi12345/YoutubeDL-Material#310]
is it possible to remove from the code the parameters to download the json files? because there is no parameter to deactivate it

app.js
![image](https://user-images.githubusercontent.com/20860324/104066543-e1b34800-5201-11eb-8f8f-640502c910fd.png)

**Comment by Tzahi12345** [comment]
This is currently possible! Go into the Downloader tab in the settings and you should see an option called "Include metadata", just disable that and you should be good to go.

It's not recommended as with new updates sometimes additional metadata is needed, such as in v4.2 when we added descriptions. Let me know if you have any further issues!

**Comment by JamesDAdams** [comment]
Thanks for your help, but i don't have "include metadata"

![image](https://user-images.githubusercontent.com/20860324/104092649-9c385e80-5285-11eb-80bc-4313c6de30b3.png)

**Comment by Tzahi12345** [comment]
Sounds like you're on an old version, update to v4.2 and you should see it there.

**Comment by JamesDAdams** [comment]
ok i update but doesn't work for the playlist it's normal ?

**Comment by JamesDAdams** [comment]
What are the categories for? (for the moment it does not work)

![image](https://user-images.githubusercontent.com/20860324/104104815-b46ea480-52aa-11eb-8794-4fd8f5986273.png)

**Comment by Tzahi12345** [comment]
>ok i update but doesn't work for the playlist it's normal ?

It should work in all instances. You're still seeing it downloaded for subscriptions? There may be a bug here.

>What are the categories for? (for the moment it does not work)

I went ahead and added a wiki page that explains them, as I realized the UI doesn't do an amazing job at doing so: https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Categories

**Comment by JamesDAdams** [comment]
> > ok i update but doesn't work for the playlist it's normal ?
> 
> It should work in all instances. You're still seeing it downloaded for subscriptions? There may be a bug here.
> 
> > What are the categories for? (for the moment it does not work)
> 
> I went ahead and added a wiki page that explains them, as I realized the UI doesn't do an amazing job at doing so: https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Categories

Yes there a bug for the playlist

**Comment by JamesDAdams** [comment]
I just saw the wifi for the categories it's really nice and I think that if you add the possibility of adding rules when adding a playlist it would be great!

Ex: I download all the playlists of a channel except one playlist in particular
