### ISSUE TITLE
Can't apply any rate limits in custom arg

### ISSUE THREAD

**Issue by radwiimp** [Tzahi12345/YoutubeDL-Material#313]
Hey there. Running the nightly build, great work. I think I have found another issue with spaces (similar to #285 ) however, whenever I try to add the arg "-r 6M" for example, it throws up an error in the logs and fails to download. I'd like to be able to limit bandwidth but I think the issue is that there needs to be a space in this command and it throws off the whole command for some reason.

This is my custom arg: --write-sub,,-r 6M,,--playlist-reverse,,--write-thumbnail,,--embed-subs,,--add-metadata,,--embed-thumbnail,,--write-description

Error that appears in the log: 
ERROR: Usage: youtube-dl [OPTIONS] URL [URL...]
youtube-dl: error: invalid rate limit specified

**Comment by Tzahi12345** [comment]
Can you add a double comma in-between the `-r` and `6M` and try again?

**Comment by radwiimp** [comment]
Oh, that seemed to do the trick, Didn't even think of that but it makes sense, thanks for the help.

**Comment by Tzahi12345** [comment]
Glad I could help! Feel free to open up another issue if you see anything else or have any suggestions. Still not sure what's causing that subscription's bug though...
