### ISSUE TITLE
Playlists not downloading when category matches

### ISSUE THREAD

**Issue by tigattack** [Tzahi12345/YoutubeDL-Material#314]
I'm using the YoutubeDL-Material Docker container.

I'm trying to download a playlist which includes a deleted video. Initially, this didn't work, after which I realised I need to add a custom arg of `-i`.  
I added this, but the error still stops the download. I also tried `--ignore-errors`, which has the same effect (i.e. nothing).

I have no other custom arguments, so it's not a matter of incorrect arg separation or anything.

I enabled verbose output and it seems that the `-i` flag is actually enabled by default? Please correct me if I'm wrong there. Regardless, though, I'm seeing an error cause the download to fail no matter what I try.

**Comment by tigattack** [comment]
Update: I just removed the `-i` flag from custom args (so there are now no custom args) and tried once again to download the playlist, and this time received an unhandled exception from node:

```
2021-01-12T18:31:42.932Z VERBOSE: youtube-dl args being used: -o,dl/video/%(uploader)s/%(title)s.mp4,--write-info-json,--print-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--cookies,appdata/cookies.txt,--write-thumbnail
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at applyCategoryRules (/app/categories.js:75:60)
    at Object.categorize (/app/categories.js:51:13)
    at /app/app.js:1136:45
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Since this seems to be related to categories, see below:
![image](https://user-images.githubusercontent.com/10629864/104357216-ccd9fb80-5504-11eb-9654-3fd5cbd8ce65.png)

And this is the playlist I'm trying to download: https://www.youtube.com/playlist?list=PLu7GwNMLkO8xS9b_T_bbQwlDhtX3LD00D

**Comment by Tzahi12345** [comment]
Your intuition is correct in that it's a categories issue. I didn't consider playlist downloads with categories, and so the logic is expecting an object containing the video's metadata and it instead receives an array of video metadata. I have one of two options here: apply a category to every video in a playlist download if a single video matches, or ignore categories when downloading playlists.

The reason why I can't check every video individually is that youtube-dl downloads the playlists in one go, so I can't apply the custom output to an individual video (well, I technically can by splitting up the download but I don't want to do that).

So I'm wondering, which option do you prefer here?

**Comment by tigattack** [comment]
Understood, thanks for the info.

I think, if possible, a toggle in the settings to swap between the two options (all or ignore) would be best, then each user can decide for themselves.  
Personally, I would prefer that all videos in a playlist have the category applied if one video matches.

Cheers for all your work on this, by the way. It's a great bit of software.

**Comment by Tzahi12345** [comment]
This is fixed! Check out the [latest PR](https://github.com/Tzahi12345/YoutubeDL-Material/pull/316).

There's a new setting under categories called "Allow playlist categorization" which defaults to true. It should be pushed to `nightly`, `latest`, and `4.2` in the next hour or so. Thanks for the bug report!

**Comment by tigattack** [comment]
Sweet, cheers! Working well for me.
