### ISSUE TITLE
Unable to find original video location.

### ISSUE THREAD

**Issue by CoreyVidal** [Tzahi12345/YoutubeDL-Material#315]
Hello. I feel like maybe I'm just being an idiot and not seeing it anywhere, but is there not a way to find the original video to what I downloaded?

Here's a screenshot:

![Screenshot_20210112-235729_Chrome](https://user-images.githubusercontent.com/20746389/104408428-0117e100-5532-11eb-9c75-1fd5bb9b4ab9.png)

I can mute it, full screen it, download and cast it. I can expand the description. If I click the "Share" button, it's offering for me to share it from my server...

Is clicking the title at the very bottom supposed to be a button that takes me to the original YouTube video? That's my only guess, but I'm tapping it and it doesn't do anything.

Am I not seeing something? Is something broken? Or is this not a feature of YoutubeDL-Material?

**Comment by Tzahi12345** [comment]
It's a share button for the locally-stored video, you can still access the original video URL by clicking on the 3 dots on the home page and clicking "Info".

But, you're right in that the info should be accessible from the player itself, so I went ahead and added an info button there to the latest `nightly` Docker tag, you can see the [commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/af58854f0e4e53add23a9b9ec2d401b22ad2f5ea)

This will likely find its way into the `4.2` and `latest` tags fairly soon as there's another fix coming that I'd like to merge as well. Hope this helps!
