### ISSUE TITLE
How can someone unsubscribe?

### ISSUE THREAD

**Issue by purplepandapants** [Tzahi12345/YoutubeDL-Material#319]
Hi,

I have about 20 subscriptions and when I try to unsubscribe nothing seems to happen. I have reloaded the docker install and the videos are still there and the subscriptions are still showing. What am I doing wrong here?

Sorry for the basic questions but I am not sure how to tackle this.

Thanks
P

**Comment by Tzahi12345** [comment]
That's weird, it really should. Which version are you running? Do you see any logs in your browser console or Docker output?

If you go to the subscription page you can edit it and pause it in the meantime while we figure out what went wrong.

**Comment by purplepandapants** [comment]
Hi,

I am using version 4.2 within a docker on my Unraid server. 

The latest entries in the log are the following.

> 2021-01-26T14:28:05.929Z ERROR: Command failed with Unknown system error -8: node_modules/youtube-dl/bin/youtube-dl -i -o subscriptions/playlists/Health – Vox/%(title)s.%(ext)s -ciw --write-info-json --print-json -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 --write-thumbnail https://www.youtube.com/playlist-REMOVED
> 
> spawn Unknown system error -8
> 
> 2021-01-26T14:28:23.591Z ERROR: Command failed with Unknown system error -8: node_modules/youtube-dl/bin/youtube-dl -i -o subscriptions/playlists/Climate Change – Vox/%(title)s.%(ext)s -ciw --write-info-json --print-json -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 --write-thumbnail https://www.youtube.com/playlist-REMOVED
> 
> spawn Unknown system error -8
> 
> 2021-01-26T14:28:41.234Z ERROR: Command failed with Unknown system error -8: node_modules/youtube-dl/bin/youtube-dl -i -o subscriptions/playlists/-REMOVED/%(title)s.%(ext)s -ciw --write-info-json --print-json -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 --write-thumbnail https://www.youtube.com/playlist-REMOVED
> 
> spawn Unknown system error -8
> 
> 2021-01-26T14:28:58.877Z ERROR: Command failed with Unknown system error -8: node_modules/youtube-dl/bin/youtube-dl -i -o subscriptions/playlists/-REMOVED/%(title)s.%(ext)s -ciw --write-info-json --print-json -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 --write-thumbnail https://www.youtube.com/playlist-REMOVED
> 
> spawn Unknown system error -8
> 
> 2021-01-26T14:29:16.527Z ERROR: Command failed with Unknown system error -8: node_modules/youtube-dl/bin/youtube-dl -i -o subscriptions/playlists/-REMOVED/%(title)s.%(ext)s -ciw --write-info-json --print-json -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 --write-thumbnail https://www.youtube.com/playlist-REMOVED
> 
> spawn Unknown system error -8
> 
> 2021-01-26T14:29:34.174Z ERROR: Command failed with Unknown system error -8: node_modules/youtube-dl/bin/youtube-dl -i -o subscriptions/playlists/-REMOVED/%(title)s.%(ext)s -ciw --write-info-json --print-json -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4 --write-thumbnail https://www.youtube.com/playlist-REMOVED

> PayloadTooLargeError: request entity too large
> at readStream (/app/node_modules/raw-body/index.js:155:17)
> at getRawBody (/app/node_modules/raw-body/index.js:108:12)
> at read (/app/node_modules/body-parser/lib/read.js:77:3)
> at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
> at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
> at /app/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
> at next (/app/node_modules/express/lib/router/index.js:275:10)
> at urlencodedParser (/app/node_modules/body-parser/lib/types/urlencoded.js:100:7)
> at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
> at /app/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
> at next (/app/node_modules/express/lib/router/index.js:275:10)
> at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
> PayloadTooLargeError: request entity too large
> at readStream (/app/node_modules/raw-body/index.js:155:17)
> at getRawBody (/app/node_modules/raw-body/index.js:108:12)
> at read (/app/node_modules/body-parser/lib/read.js:77:3)
> at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
> at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
> at /app/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
> at next (/app/node_modules/express/lib/router/index.js:275:10)
> at urlencodedParser (/app/node_modules/body-parser/lib/types/urlencoded.js:100:7)
> at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
> at /app/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
> at next (/app/node_modules/express/lib/router/index.js:275:10)
> at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
> PayloadTooLargeError: request entity too large
> at readStream (/app/node_modules/raw-body/index.js:155:17)
> at getRawBody (/app/node_modules/raw-body/index.js:108:12)
> at read (/app/node_modules/body-parser/lib/read.js:77:3)
> at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
> at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
> at /app/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
> at next (/app/node_modules/express/lib/router/index.js:275:10)
> at urlencodedParser (/app/node_modules/body-parser/lib/types/urlencoded.js:100:7)
> at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
> at /app/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
> at next (/app/node_modules/express/lib/router/index.js:275:10)
> at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
> PayloadTooLargeError: request entity too large
> at readStream (/app/node_modules/raw-body/index.js:155:17)
> at getRawBody (/app/node_modules/raw-body/index.js:108:12)
> at read (/app/node_modules/body-parser/lib/read.js:77:3)
> at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
> at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
> at /app/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
> at next (/app/node_modules/express/lib/router/index.js:275:10)
> at urlencodedParser (/app/node_modules/body-parser/lib/types/urlencoded.js:100:7)
> at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
> at /app/node_modules/express/lib/router/index.js:284:7
> at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
> at next (/app/node_modules/express/lib/router/index.js:275:10)
> at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
> 2021-01-26T17:40:23.842Z ERROR: ERROR: Error in output template: unsupported format character 'I' (0x49) at index 34 (encoding: 'UTF-8')
> 
> ERROR: Error in output template: unsupported format character 'I' (0x49) at index 34 (encoding: 'UTF-8')
> 
> ERROR: Error in output template: unsupported format character 'I' (0x49) at index 34 (encoding: 'UTF-8')
> 
> ERROR: Error in output template: unsupported format character 'I' (0x49) at index 34 (encoding: 'UTF-8')
> 
> 2021-01-26T17:42:51.734Z ERROR: ERROR: Join this channel to get access to members-only content like this video, and other exclusive perks.

**Comment by Tzahi12345** [comment]
Can you try pulling the latest v4.2? This was an issue before but it has been resolved.

**Comment by purplepandapants** [comment]
I stopped the docker, removed the image and then redownload it again. It seems to work now. When I unsubscribe the videos are disappearing off the shared volume.

Thank you for your help. It was a rather simple fix 😉

**Comment by Tzahi12345** [comment]
No problem! Feel free to open another issue if you find something else.
