### ISSUE TITLE
Handle 0 likes / dislikes in NFO file writing

### ISSUE THREAD

**Issue by jacksonbrink** [Tzahi12345/YoutubeDL-Material#321]
I am using the docker container for TubeSync.

When attempting to download videos with the option "WRITE NFO" checked, the NFO file will not be created if the video has a value of 0 for dislikes (and I assume likes as well), instead failing with the below error.

I tested this by adding a dislike to the videos in question and they downloaded and created the NFO files without issue.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/app/sync/tasks.py", line 335, in download_media
    write_text_file(media.nfopath, media.nfoxml)
  File "/app/sync/models.py", line 1081, in `nfoxml`
    votes.text = str(self.votes)
  File "/app/sync/models.py", line 981, in votes
    return upvotes + downvotes
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by Tzahi12345** [comment]
Looks like you landed in the wrong GitHub page, I'd open up an identical issue over at the [TubeSync issues page](https://github.com/meeb/tubesync/issues).

For a second you had me thinking "did I actually add NFO support and forget?"

We do coincidentally have an open issue regarding that (#207) but it hasn't been completed yet.

**Comment by jacksonbrink** [comment]
My fault! Sorry for the trouble.
