### ISSUE TITLE
Failed Migration from 4.1 to 4.2

### ISSUE THREAD

**Issue by Atreidae** [Tzahi12345/YoutubeDL-Material#324]
Hi Team, I've been using the container for this project for a little while with great success.

This morning I had an issue with Node.js maxing out my disks and as part of a process of elimination by stopping containers I found it to be this package.

However, after restarting it, I appear to have upset the DB migration as now all my subscriptions and downloads are missing from the UI.

See my recent logs files (You can see it discovering and adding files. then running a migration after i restart it)

2021-02-02T21:43:41.173Z VERBOSE: Added discovered file to the database: /Your Own Sky (Aviators Remix)
2021-02-02T21:43:46.876Z VERBOSE: Added discovered file to the database: /''Octavia's Extensions'' so far!!!
2021-02-02T21:48:28.403Z INFO: Beginning migration: 4.1->4.2+
2021-02-02T21:48:28.420Z INFO: 4.1->4.2+ migration complete!
2021-02-02T21:48:32.518Z INFO: youtube-dl successfully updated!
2021-02-02T21:48:32.524Z INFO: YoutubeDL-Material v4.2 started on PORT 17442

My current db.json is below and my db.json.old doesn't contain much either

{
  "playlists": [],
  "files": [],
  "configWriteFlag": false,
  "downloads": {},
  "subscriptions": [],
  "files_to_db_migration_complete": false,
  "simplified_db_migration_complete": true
}

Would forcing a rescan be as simple as changing "simplified_db_migration_complete" to false?
Or am I going to have to add all my subscriptions again? (Already had to do that once thanks to not mapping docker properly...)

Could this be related to https://github.com/Tzahi12345/YoutubeDL-Material/issues/295 ?

**Comment by Tzahi12345** [comment]
It could be related to #295, how many videos did you have downloaded? If it's in the thousands/tens of thousands, then it makes sense why the disk usage shot up, as there's a lot of writing that needs to be done for the migration. But before any of that is done, the db file is copied over.

Are you using multi-user mode? If so I would also check the `users.json.old` file which you can use to re-do the migration, I'll give the steps in case this is true:

1. Stop the container
2. Make a copy of `users.json.old` and rename it `users.json` (do the same for `db.json.old`)
3. Set "simplified_db_mgiration_complete" to false
4. Start the container

The migration should start again.

If all else fails, you can get your videos back into the UI quite easily by subscribing to the channels/playlists again and restarting the container. The server will auto-detect files and add them to the DB. If you're using multi-user mode you can do the same for users as well by recreating the users and re-subscribing to the channels, then restarting the container.

I was afraid migrating the DB would cause issues like these, it was unfortunately necessary to simplify much of the code as it was written long ago when I sucked at programming. Eventually we may move to a more efficient DB which will prevent issues like this, but it should go a lot more smoothly than this migration.

Hope this helps, if you have any questions feel free to shoot away!

**Comment by Atreidae** [comment]
Yeah I knew about the redetecting old files as I've had to do it before

As for downloads I estimate ~2500 videos (Wow, I didn't realise I was saving that many MLP videos w ~8000 files in ./subscriptions) but the disk operation would have been very slow as I'm using SMR drives (Shingled Magnetic Recording) which are GREAT for archiving and big writes. But terrible for re-writes, so if we are re-writing files over and over in small chunks (As suggested in #295) the disks get stuck. 

Not using Multi-User mode, so I'm guessing that when I did the first NAS reboot it nerfed the db.old and the container restart then nerfed the second attempt at it.

Don't ever feel embarrassed about the old code.
it's still better than no-code and it solved a problem.

Thanks for your help.

**Comment by Atreidae** [comment]
To add more to the dont worry about bad database code... one of my first apps ever was written in VB and used folders with multiple text files inside to contain properties for each tracked item (it was an anime list program)

How did I make this portable for sharing?
I'd zip the folder structure with a custom file extension...

**Comment by Tzahi12345** [comment]
It sounds like you gotta do the manual repair route, thankfully nothing needs to be redownloaded and everything should be auto discovered. Just make sure your subscriptions have the same name as before so the server can find the folders for the subscriptions properly. Hopefully that doesn't take too long.

>To add more to the dont worry about bad database code... one of my first apps ever was written in VB and used folders with multiple text files inside to contain properties for each tracked item (it was an anime list program)
>How did I make this portable for sharing?
>I'd zip the folder structure with a custom file extension...

Haha that's a good one. The pride in creating your own file extension is probably worth the insanity of that solution... This reminds me of this digitized file organization app idea I had about five years ago. I wrote it in C# and realized I needed a local DB, so instead of finding a library that did that for me I made one myself.

I thought I was a genius, creating a file format that was text-based, delimiting columns using a tilde (~). It was only years later I realized I reinvented CSV. I dug up [the code](https://bitbucket.org/Tzahi12345/doup/src/master/DoUp/LaDa.cs) for that, if only I could go back and warn myself lol, maybe I was meant to learn the hard way. Had a good laugh reading some of my comments back then: "instance variable", "{object name} constructor"

Anyways, let me know if you need any help with the migration or if you get stuck somewhere :) Always happy to help!

**Comment by Atreidae** [comment]
Hmm, Anyway I can manualy kick in the "rediscovery" part

re-added the playlists/channels and they are being added to db.json
The scanner goes through and discovers there are no new downloads to process, but doesn't add the existing videos to the JSON DB / UI.

If I add a new playlist, new files are added just fine, get added to the JSON file and showup in the UI, but just not old files.

**Comment by Atreidae** [comment]
I post this and notepad++ tells me the JSON just got updated.
Guess it's just running slow due to my disk setup.

**Comment by Atreidae** [comment]
Looks good now, this is on me anyway, no need to keep this issue open. Closing

**Comment by Tzahi12345** [comment]
Good to hear, sorry about the high disk usage issue. Should be resolved in a future update once the DB gets migrated into an actually viable solution that will hopefully lean more on RAM during runtime than this one.

**Comment by Atreidae** [comment]
Adding in an interesting comment here, I can see that for some reason despite me being on 4.2+ the container decided to "upgrade" the db to 4.2+ again at the start of the year.

I'd say likely Watchtower upgraded it and it rebooted mid *something* and corrupted the 35meg DB file.
Restoring an old copy and starting again appears to have recovered everything.
