### ISSUE TITLE
Nginx Proxy

### ISSUE THREAD

**Issue by serverfilesync** [Tzahi12345/YoutubeDL-Material#326]
Hello, how can I add this service behind a nginx proxy (I’m using SWAG)?

I read up some past example but none of them work.  Must I reverse proxy ~/api/? I’m already using this path for organizr, is there a workaround to this problem?

What should I put in the url field under settings? 

Thank you!

**Comment by Tzahi12345** [comment]
Have you checked out the [wiki page](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Reverse-Proxy-Setup)? The URL should be the URL after the reverse proxy, so that might be `https://ytdl.domain.com`

**Comment by serverfilesync** [comment]
Thank you and sorry I missed the wiki. 

I'll try the subdomain approach to avoid conflicts with organizr at location /api/ .
