### ISSUE TITLE
using it on docker+windows

### ISSUE THREAD

**Issue by Janaue** [Tzahi12345/YoutubeDL-Material#329]
I am trying to use ytdl material on windows 10 with docker, but i know nothing about this

I have installed Docker Desktop Installer.exe and then i installed ytdl material in dockers and i get this
![2021-02-06 08_20_25-Container instance](https://user-images.githubusercontent.com/10972636/107111962-5e166680-6854-11eb-83c4-564bd48055e4.jpg)

then I installed the firefox extension on firefox esr and now I dont know what to do to download a video.
I have put the port 17442 on the option of the firefox module
![2021-02-06 08_23_28-Gestionnaire de modules complémentaires](https://user-images.githubusercontent.com/10972636/107112011-bc434980-6854-11eb-9369-67a8c5442736.jpg)

and when I add a video to get the download , firefox goes to 
http://localhost:17442/#/home;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D-GALBxoPytg;audioOnly=false
and then nothing happens. Firefox says it can't open this URL

**Comment by Tzahi12345** [comment]
Sorry for the late reply, I've been moving into a new place and it's been a bit hectic.

Do you see any errors in the browser console? Do ctrl-shift-i and click console to see if anything shows up when you load up the URL.
