### ISSUE TITLE
is it download pluralsight course?

### ISSUE THREAD

**Issue by mahdisky** [Tzahi12345/YoutubeDL-Material#331]
is it download pluralsight course?
how do it?
and sub?

**Comment by Tzahi12345** [comment]
Subbing I don't know, apparently there's some [info here](https://www.reddit.com/r/DataHoarder/comments/99zia3/tutorial_download_pluralsight_videos_with/) which may be helpful. Basically you want to enable Advanced download mode in the settings, and enter your username/password in the box in the new dropdown on the home page under the URL input.

Not sure if that will be all you need, I don't have pluralsight so it's not something I can test.

**Comment by GlassedSilver** [comment]
I assume this issue has been sufficiently covered, if not, don't hesitate to comment, and we'll reopen!

Thank you for getting in touch with us!
