### ISSUE TITLE
Partial Download Support?

### ISSUE THREAD

**Issue by Casper042** [Tzahi12345/YoutubeDL-Material#332]
I was just reading this...
https://unix.stackexchange.com/questions/230481/how-to-download-portion-of-video-with-youtube-dl-command

Wondering how hard it would be to add this to the Advanced screen?
Would use Johnnie's answer perhaps with Steve's SED syntax to simplify the scripting?

Would be great if there was a way to batch this as well (Version 2 of the feature perhaps?)
So I could, for example, grab the first 10 seconds of a list of videos or all videos on a channel or future videos via subscription, etc.

I guess version 3 would be an option to convert a short clip to GIF as well?

Thanks

**Comment by Tzahi12345** [comment]
Version 1 is implemented :)

Pull the latest nightly on Docker and you should be able to use it immediately. It's still a bit buggy, in particular trying to redownload the same video without changing the title causes the shortened video to persist. I'll fix this later, though I couldn't do it now and I thought I may as well get it out and solve that edge case later.

You can see the [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/433d08e9dfdb641c111107408f8fba71fb5475ad). Just curious, what's your use case for version 2? I understand converting to gif and all (that could be used for all videos actually), is it just to skip in-video ads/sponsers?

**Comment by Tzahi12345** [comment]
I'll go ahead and close this issue as a working version has been implemented, if you'd like future improvements feel free to open another issue!
