### ISSUE TITLE
Suggestion: Add --download-archive

### ISSUE THREAD

**Issue by tyzbit** [Tzahi12345/YoutubeDL-Material#333]
I noticed my instance spewing a bunch of `WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests` messages.  I suspect this is because YTDL-Material is re-downloading the videos over and over again.

I suggest adding the `--download-archive [textfile with file list]` option to subscriptions (perhaps as a toggle, such as "Keep a running list of downloaded videos and only download new videos").

**Comment by Tzahi12345** [comment]
Have you tried enabling the `Use youtube-dl archive` in the Downloader tab in the settings? It's not a master list as every user has their own, but the app handles most of the maintenance itself (though you can edit it yourself as needed).

**Comment by tyzbit** [comment]
I enabled `Use youtube-dl archive` and got throttled again.  I grabbed some cookies and used them and got throttled as well.  I'm obviously being hit by https://github.com/ytdl-org/youtube-dl/issues/22839.  I'll close this since both archive and cookies are available in the UI.  Only recommendation I might make is to add a tooltip for the `Use youtube-dl archive`.
