### ISSUE TITLE
What player are you using

### ISSUE THREAD

**Issue by PDSCi996** [Tzahi12345/YoutubeDL-Material#341]
I have been using jellyfin for playback, but I found that the online playback function of this container is very good. I would like to ask what software is used and whether there is a separate container that can be used, I am very grateful.

**Comment by Tzahi12345** [comment]
We are using [ngx-videogular](https://github.com/videogular/ngx-videogular), it's an Angular component with tons of customization. It can't really work outside of Angular, but you can create your own web app if you know how to program to play the videos yourself.

We are serving the videos through nodejs which makes it CPU intensive, but the module itself is a glorified native HTML5 player which means it runs quite well on most browsers. Let me know if you have any other questions!
