### ISSUE TITLE
List of downloaded not updating unless restarted. 

### ISSUE THREAD

**Issue by rustjakey** [Tzahi12345/YoutubeDL-Material#346]
As requested, my discussion posted as an issue. Thank you for your work. Below is the transcript from the discussion. 

When I add a channel for example, nothing will happen, no downloads will start, or at least appear to.

I then restart the docker about 10 mins later and a few will show up.

Any ideas about this?

Tzahi12345
13 days ago
Here's the TLDR: we only know which videos were downloaded after the entire channel is checked, meaning you have to wait until it's all done for it to be registered into the UI.

When you restart the container, all files are checked to see if any of them don't exist in the DB. If they are missing they are added. So this is the behavior you are seeing.

One alternative we can do is if a channel is being downloaded/checked, we can run that logic in that folder to auto add files as they are being downloaded. Shouldn't take too long to implement, let me know if this is something that would be helpful in your use case or if waiting isn't an issue (for large channels it absolutely makes sense).

**Comment by Tzahi12345** [comment]
Just finished implementing this! If a subscription is being checked, every 5 seconds the server will check for already downloaded videos.

[See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/1f0153b17edae9000cb0b0f58d12d082853b8291)

Thanks for the suggestion! Feel free to throw any more at me :)
