### ISSUE TITLE
Docker : No volume support, so no configuration 

### ISSUE THREAD

**Issue by pinkfloydFR** [Tzahi12345/YoutubeDL-Material#348]
On docker, without volume support, the configuration/settings is useless.

Thanks by advance for this work !!

version : 
tzahi12345/youtubedl-material:nightly | 210.3 MB | 2021-02-22 21:10:13

**Comment by Tzahi12345** [comment]
It does have volume support! If you go into the docker-compose you should see it. They are mapped to folders that are in the root docker-compose directory,

**Comment by pinkfloydFR** [comment]
Ho my bad ! ( it seemed curious to me anyway ^^ )

I did see the docker-compose.xml example file, only follow the main page. Sorry !

Thanks again !
