### ISSUE TITLE
Move subscription and playlist information into users.json instead of db.json

### ISSUE THREAD

**Issue by jonathanm-ur** [Tzahi12345/YoutubeDL-Material#350]
I would like to see the list of subscribed channels and playlists moved out of db.json and into users.json, so that when the massive database of downloaded files gets corrupted and needs to be rebuilt the subscribed channels and playlists aren't lost.

**Comment by Tzahi12345** [comment]
Both are constantly being written to, do you only see db.json having the 0 byte issue? Really it should be both if you're on multi-user mode, in fact users.json is written a lot more often in that case.

**Comment by jonathanm-ur** [comment]
I'm in single user mode.

**Comment by Tzahi12345** [comment]
Should be fixed now with MongoDB support!
