### ISSUE TITLE
ERROR: Failed to update youtube-dlc - Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by quorn23** [Tzahi12345/YoutubeDL-Material#352]
`Today at 3:04 PM  2021-03-16T14:04:16.580Z INFO: Found new update for youtube-dlc. Updating binary...`
`today at 3:04 PM  2021-03-16T14:04:16.592Z ERROR: Failed to update youtube-dlc - Error: ENOSPC: System limit for number of file watchers reached, watch 'node_modules/youtube-dl/bin'`
`today at 3:04 PM  /app/app.js:1808`
`today at 3:04 PM                  watcher.close();`
`today at 3:04 PM                          ^`
`today at 3:04 PM  `
`today at 3:04 PM  TypeError: Cannot read property 'close' of undefined`
`today at 3:04 PM      at /app/app.js:1808:25`
`today at 3:04 PM      at FSReqCallback.oncomplete (fs.js:156:23)`

Swapped to the nightly tag for the docker image, seen that i had switched back to yt-dl a while back, switched to yt-dlc and getting this error. Switched back to yt-dl manually in the default.json and works again.

**Comment by Tzahi12345** [comment]
Weird! It looks like the container is reaching it's [file watch limit](https://stackoverflow.com/a/55543310/8088021), which is quite high and all we're doing is looking at a single file. You can try restarting (last resort rebuild) the container or run `docker exec -it /bin/sh` and then run `echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p.` which should solve the issue. Let me know if this works!

**Comment by quorn23** [comment]
Would love to test it, but sadly the commit for [#353 ](https://github.com/Tzahi12345/YoutubeDL-Material/issues/353) broke it further haha.

`today at 4:40 PM  > backend@1.0.0 start /app`
`today at 4:40 PM  > nodemon -q app.js`
`today at 4:40 PM  `
`today at 4:40 PM  `
`today at 4:40 PM  ┌──────────────────────────────────────────────┐`
`today at 4:40 PM  │         nodemon update check failed          │`
`today at 4:40 PM  │     Try running with sudo or get access      │`
`today at 4:40 PM  │     to the local update config store via     │`
`today at 4:40 PM  │ sudo chown -R $USER:$(id -gn $USER) /.config │`
`today at 4:40 PM  └──────────────────────────────────────────────┘`
`today at 4:40 PM  npm ERR! code ELIFECYCLE`
`today at 4:40 PM  npm ERR! errno 1`
`today at 4:40 PM  npm ERR! backend@1.0.0 start: `nodemon -q app.js` `
`today at 4:40 PM  npm ERR! Exit status 1`
`today at 4:40 PM  npm ERR! `
`today at 4:40 PM  npm ERR! Failed at the backend@1.0.0 start script.`
`today at 4:40 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
`today at 4:40 PM Container stopped`

Let me know if you want me to open a new issue for it.

**Comment by Tzahi12345** [comment]
Just pushed a commit that should fix this, let me know if it does!

[See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/4c06bc750ceb386c963c14cfe4d735ca6e1f59fe)

**Comment by quorn23** [comment]
today at 6:18 PM  > backend@1.0.0 start /app
today at 6:18 PM  > nodemon -q app.js
today at 6:18 PM  
today at 6:18 PM  npm ERR! code ELIFECYCLE
today at 6:18 PM  npm ERR! errno 1
today at 6:18 PM  npm ERR! backend@1.0.0 start: `nodemon -q app.js`
today at 6:18 PM  npm ERR! Exit status 1
today at 6:18 PM  npm ERR! 
today at 6:18 PM  npm ERR! Failed at the backend@1.0.0 start script.
today at 6:18 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Nope, sadly starts up with this ^

**Comment by Tzahi12345** [comment]
Pushed another fix which will hopefully resolve all of this, or at least give us a better error message as I think `npm start` hides some of it.

[Here's the commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/4c1f975eaed45f908096539fe9057b2d7cf522df)

Let me know if this finally fixes it!

**Comment by quorn23** [comment]
`today at 11:36 PM  /app/entrypoint.sh: exec: line 17: nodemon: not found`

Sadly fails to start up with throwing this error

**Comment by abb0r** [comment]
> `today at 11:36 PM /app/entrypoint.sh: exec: line 17: nodemon: not found`
> 
> Sadly fails to start up with throwing this error
> 
> *Edit: ooops, wrong button, i accidentally closed the issue by mistake

I have the exact same issue since I think yesterdays nightly.

**Comment by Tzahi12345** [comment]
Just fixed this! Let me know if the latest nightly works @abb0r @quorn23

**Comment by quorn23** [comment]
Hi @Tzahi12345 sadly not, new error:

today at 2:05 AM  Error: Failed to create directory /.forever:EACCES: permission denied, mkdir '/.forever'
today at 2:05 AM      at Object.tryCreateDir (/usr/lib/node_modules/forever/lib/util/config-utils.js:22:11)
today at 2:05 AM      at Object.forever.load (/usr/lib/node_modules/forever/lib/forever.js:357:15)
today at 2:05 AM      at Object.<anonymous> (/usr/lib/node_modules/forever/lib/forever.js:391:9)
today at 2:05 AM      at Module._compile (internal/modules/cjs/loader.js:999:30)
today at 2:05 AM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
today at 2:05 AM      at Module.load (internal/modules/cjs/loader.js:863:32)
today at 2:05 AM      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
today at 2:05 AM      at Module.require (internal/modules/cjs/loader.js:887:19)
today at 2:05 AM      at require (internal/modules/cjs/helpers.js:74:18)
today at 2:05 AM      at Object.<anonymous> (/usr/lib/node_modules/forever/bin/forever:3:1)

**Comment by abb0r** [comment]
> Just fixed this! Let me know if the latest nightly works @abb0r @quorn23

Yes, everything is working again for me. Thanks for the fast fix!

**Comment by quorn23** [comment]
If i try to create it from scratch (with empty config dir i get this error

today at 4:30 AM  /usr/lib/node_modules/forever/lib/util/config-utils.js:22
today at 4:30 AM      throw new Error('Failed to create directory '+dir+":" +error.message);
today at 4:30 AM      ^
today at 4:30 AM  
today at 4:30 AM  Error: Failed to create directory /.forever:EACCES: permission denied, mkdir '/.forever'
today at 4:30 AM      at Object.tryCreateDir (/usr/lib/node_modules/forever/lib/util/config-utils.js:22:11)
today at 4:30 AM      at Object.forever.load (/usr/lib/node_modules/forever/lib/forever.js:357:15)
today at 4:30 AM      at Object.<anonymous> (/usr/lib/node_modules/forever/lib/forever.js:391:9)
today at 4:30 AM      at Module._compile (internal/modules/cjs/loader.js:999:30)
today at 4:30 AM      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
today at 4:30 AM      at Module.load (internal/modules/cjs/loader.js:863:32)
today at 4:30 AM      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
today at 4:30 AM      at Module.require (internal/modules/cjs/loader.js:887:19)
today at 4:30 AM      at require (internal/modules/cjs/helpers.js:74:18)
today at 4:30 AM      at Object.<anonymous> (/usr/lib/node_modules/forever/bin/forever:3:1)
today at 4:30 AM Container stopped


For reference my docker-compose
`  youtube-dl:`
`    container_name: ytdl_material`
`    image: ${YOUTUBEDL}`
`    environment: `
`      - ALLOW_CONFIG_MUTATIONS='true'`
`      - UID=${PUID}`
`      - GID=${PGID}`
`    restart: always`
`    volumes:`
`     - ${DOCKERCONFDIR}/ytdl_material:/app/appdata`
`     - ${DOCKERDATADIR}/downloads/youtube/audio:/app/audio`
`     - ${DOCKERDATADIR}/downloads/youtube/video:/app/video`
`     - ${DOCKERDATADIR}/downloads/youtube/subscriptions:/app/subscriptions`
`     - ${DOCKERCONFDIR}/ytdl_material:/app/users`

**Comment by quorn23** [comment]
Closing this as i pulled the image fresh and can start it now. 
The restart server button says restarting failed fyi, but nothing more in the log.
I'll have a look first it's nightly

**Comment by Tzahi12345** [comment]
Awesome to hear! I thought maybe it was a permissions issue but I'm glad it fixed itself. Yeah it says failed to restart as the server restarts too quickly before it can send the success message to the client. I'll just update it to delay the restart for a second or so.

**Comment by quorn23** [comment]
Sadly it turns out, it is an issue with the permissions, opened a new issue https://github.com/Tzahi12345/YoutubeDL-Material/issues/361 (i could have sworn i have seen a commit where some perm change happened, but i can't find the commit if my life depends on it)
