### ISSUE TITLE
Enhancement: Restart YTDL-Material from the gui

### ISSUE THREAD

**Issue by quorn23** [Tzahi12345/YoutubeDL-Material#353]
I didn't find any way to restart ytdl-material from within the web ui (for example if you swap yt-dl to yt-dlc. 
Would be great to have a restart button somewhere, or a "fetch binary" button, so you can check for a new version and apply it without restarting the container.

**Comment by Tzahi12345** [comment]
Done! It will take about an hour or so for the `nightly` to be updated, but when it is you can find the button in the Advanced tab in the settings.

[See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/4643efbae04a6c00a1a29be2d96cb7e0dc12c836)
