### ISSUE TITLE
/app/entrypoint.sh: exec: line 17: nodemon: not found

### ISSUE THREAD

**Issue by BasWeg** [Tzahi12345/YoutubeDL-Material#355]
Hi,
I've made an docker update, and the docker does not start due to
/app/entrypoint.sh: exec: line 17: nodemon: not found
best regards
Bastian

**Comment by Tzahi12345** [comment]
Hi, sorry the nightly is broken unfortunately, I may need to revert a few commits but I won't get to it until late tonight. You can use the tag `latest` or `4.2` and it'll work without issue!

**Comment by BasWeg** [comment]
Ok. No hurry. 
I used nightly all the time. I will give latest or 4.2. a try

**Comment by Tzahi12345** [comment]
Yeah sorry about that! I just pushed [a commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/addd54fefd062382b65efe33d9bacb0ee3b80182) that should fix this, I'll keep an eye on it and close this issue if it does.

**Comment by Tzahi12345** [comment]
Should be fixed! Works on my end without issue (just a few extra logs I'll remove over the next couple days)
