### ISSUE TITLE
Only download new videos for subscription

### ISSUE THREAD

**Issue by colin-marshall** [Tzahi12345/YoutubeDL-Material#363]
Is there a way to add a subscription to a channel but only download future uploads? I don't want to download the entire channel but I would like to download all new uploads from the date of adding the subscription and forward. Sorry if this has been covered previously, I couldn't find anything on the subject by searching. Thanks!

**Comment by Tzahi12345** [comment]
Yup it's very possible! See [here](https://github.com/Tzahi12345/YoutubeDL-Material/discussions/340#discussioncomment-399699), I should add a wiki as it's a common question but difficult to find
