### ISSUE TITLE
MP3 quality

### ISSUE THREAD

**Issue by blackops786187** [Tzahi12345/YoutubeDL-Material#364]
Hi,

I was looking for a web gui youtube dl solution for my mobile phones and i stumbled across yours. The UI and download capability is solid.

One thing ive noticed is that the MP3 bitrate is quite low when using audio only mode. Im getting rates of 120kbps which is quite low. Can you expand on what settings you use to download the audio and convert it to mp3. It might be worth if required to set the default to a higher bitrate to preserve audio quality. 

Ideally for the best audio quality, you would want youtube-dl to first pull the highest audio quality available and then pipe the file into ffmpeg to create a high bitrate mp3. This would preserve the audio quality 

Thanks

**Comment by blackops786187** [comment]
Something like this would be preferable to prevent any audio quality loss. Hydrogen audio seems to confirm this. The default of quality level 5 isnt transparent

youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 "URL"

https://wiki.hydrogenaud.io/index.php/LAME

**Comment by Tzahi12345** [comment]
This should be resolved! Audio quality 0 is now used by default. See the [change here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/bb6503e86d16d13f26018f0f0d85a45c82cdff03#diff-57fcf3bf0ff2ec3604e842595d8ac0b6a43665dac4d20b3da0136bd02dc36cd7R1101). You can use the latest `nightly` to get this fix.
