### ISSUE TITLE
I just found a channel folder within a channel's channel folder in my subscriptions folder

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#369]
Really mighty confused about this...

No idea at all how this happened

Come to think of it... that folder is FULL of channel folders, wtf?

**Comment by Tzahi12345** [comment]
Do you remember the URL you used for the channel? Apparently [this is important](https://github.com/ytdl-org/youtube-dl/issues/29076#issuecomment-844784648). Maybe we can add a dialog to confirm that a user wants a channel or more.

**Comment by GlassedSilver** [comment]
Definitely didn't use the /videos addition, but now that I think about it... first off, yes a prompt would be good. Along with the prompt to show which sites this prompt will display for. e.g. YouTube and any other ones that need it down the road.
Why? So that the user doesn't expect to rely on this being asked on every ytdl supported site, when in fact it's a path of discovering as we figure out which sites need it. (unless ytdl maintains a list of this?)

But anyhow, I actually like this accident. It means I also downloaded a LOT of related videos in many of my subs, possibly even saved a lot of gems that since have gone down on YT itself, etc...

Happy accident as Bob Ross would say! :D

Another thing: the related videos from other channels would possibly do best in a folder called "Related Media" as a subfolder of /subscriptions.

But maybe not, not sure. Maybe this could be optional. I would absolutely hold off on implementing this alternative logic until ytdl-m has a managing utility to move entries of the DB around on the file system and link to the new location at the same time.

A bit like "re-organize library" or something like that in iTunes if you get my drift?
The same function could be called to integrate one-off downloads into subscription folders for a channel when it gets subscribed to later down the road after a bunch of one-off downloads. :)
