### ISSUE TITLE
Videos That Error Out Should be Put on a "Retry" List And Ideally We Could Inspect It

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#370]
And manually, but also automatically on a schedule issue retries.

Preferably, scan for and re-try on .PART files if they are found in the system.

**Comment by andreicociuba** [comment]
seems like a good idea.

**Comment by GlassedSilver** [comment]
I think I've thought of a rough technical design for that, I could put together a little chat for this a little later.

**Comment by GlassedSilver** [comment]
Maybe ties into https://github.com/Tzahi12345/YoutubeDL-Material/pull/420 ?

If the WIP there even means full management of subscription downloads even, that would be awesome. Although I believe that it's mostly the backend there.

In any case, this is a front-end request. Basically 2.0 of the `<ytdl-m>/#/downloads` page.

**Comment by Tzahi12345** [comment]
Errored out videos now show up in the downloads manager with an option to retry. A separate issue can be created for scheduling or it can be looped into #448.
