### ISSUE TITLE
Quality selector not working?

### ISSUE THREAD

**Issue by fdisamuel** [Tzahi12345/YoutubeDL-Material#372]
Hi!

I have recently deployed the latest version of the app (v4.2) with docker (nightly build) and I it seems the quality selector is broken for me.  Doesn't matter what video I paste in, the highest quality is always 720p. Of course I can select "max" too, but there are cases when 4k videofiles gets downloaded what I simply don't want. 

For example there is a 8k video I used for my test: https://www.youtube.com/watch?v=linlz7-Pnvw

- **On the interface the quality selection looks like this:**

![image](https://user-images.githubusercontent.com/62856267/115455512-56931680-a222-11eb-8013-96c894581d87.png)
![image](https://user-images.githubusercontent.com/62856267/115455539-5eeb5180-a222-11eb-98d0-a5e661a43867.png)

- **When I manually check from the container using the command:** 
`./youtube-dl -F 'https://www.youtube.com/watch?v=linlz7-Pnvw'`

![image](https://user-images.githubusercontent.com/62856267/115456037-ff417600-a222-11eb-85f9-15cf85f4e8ab.png)

As it can be clearly seen, the interface doesn't let me choose a quality bigger than 720p (or 8k at "max"), although 1080p can be selected using the command line. I have nothing significant in the logs nor in the browser developer console. 

Any help appreciated!

**Comment by fdisamuel** [comment]
Apparently, there is something wrong in my reverse proxy setup (I use nginxProxyManager), when I bypass the proxy and login the website with the local ip, it seems to be working...

**Comment by Tzahi12345** [comment]
Hi, apologies for the late response, the quality selector has been overhauled in the latest `nightly`.

See here:

![image](https://user-images.githubusercontent.com/707413/127597384-7635f9a6-9930-419b-9cf4-8000a8186664.png)

The video is currently downloading in 8K, though it is taking a while :)

Let me know if this is fixed on your end!

**Comment by fdisamuel** [comment]
Hi @Tzahi12345 thanks for the fix, it's working now on my end too. 😁
