### ISSUE TITLE
Can't share videos publicity when multi-user mode enabled

### ISSUE THREAD

**Issue by fdisamuel** [Tzahi12345/YoutubeDL-Material#375]
Hi!

Trying to share while using multi-user mode doesn't seem to work. It prompts you to login instead od showing the shared video. I have tested it using google chrome incognito mode. 

Expected behavior:
--> sharing out a video link lets anyone with the link to view that video without need to login.

Experienced behavior:
--> you must login first to watch a shared video.

Enviroment:
Docker image I use:  `tzahi12345/youtubedl-material:nightly` (latest version)
app is behind nginx reverse proxy, having an assigned subdomain.
sharing is enabled in settings and in the video page.
Nothing relevant in logs.

Thanks

**Comment by Xav-Pe** [comment]
Same here./

The share link asks to log in, with the message ``Login expired, please login again.``. I'm using nightly too.

**Comment by Tzahi12345** [comment]
This is currently being worked on! But yes, this is a legitimate bug, thanks for the catch!

**Comment by Tzahi12345** [comment]
Fixed with the latest merge! Let me know if you have any issues on this front, I added some unit tests that should catch any of these issues if they come up again.

**Comment by fdisamuel** [comment]
Thanks @Tzahi12345 for the fix, it seems to be working now!
