### ISSUE TITLE
Implement global speed limit

### ISSUE THREAD

**Issue by Mushin** [Tzahi12345/YoutubeDL-Material#379]
It could be a useful feature to be able to limit the total download speed used by the program. Is this feasible?

**Comment by Tzahi12345** [comment]
This is possible through youtube-dl directly, if you go into the Downloader tab in the settings, you can add the [rate limiter arg](https://stackoverflow.com/a/29999375/8088021) like so: `-r,,20K`. That would limit your downloads to 20KBps. For subscriptions, you'd have to add this to every subscription you want rate-limited.

Does this work in your case or do you want one setting that applies to everything?

**Comment by QrchackOfficial** [comment]
It would be really helpful to have an option exposed in the web UI that let you limit the download rate globally, yes.

**Comment by Tzahi12345** [comment]
Ok! So we can actually add 2 settings here to help with this:

1. A bandwidth-based rate limiter as described above
2. A minimum time between downloads of individual videos within a playlist or channel (using `--sleep-interval`) (see #410)

I think these two will help limit calls to YT. That, combined with a new and improved download manager (#65) will make things a lot better for controlling downloads.

**Comment by Tzahi12345** [comment]
Both of the above settings are implemented! [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/b1385f451bcb8219332d4e6b7868308e5667efe7).

The second setting listed above only applies to subscriptions as most downloads with multiple videos happen there.

You can find the sleep interval setting in the `Main` tab, and the rate limiter in the `Downloader` tab in the settings. Thanks for the suggestions!
