### ISSUE TITLE
[Docker] Create a default.json on first launch in appdata directory if it cannot be found

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#38]
Manually inserting it is a little cumbersome and making automated installs that aren't just re-installs or updates wonky. :)

**Comment by Tzahi12345** [comment]
Not sure why I haven't added that in yet! Easy enough to add into a minor version update

**Comment by Tzahi12345** [comment]
Successfully implemented! Was quite easy, see relevant commit [here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/0d756c4c97b09f4063c93a2e75fbae827cc0ff86). I'll release 3.5.1 in ~1 week which will include this fix issue among some others hopefully.

Thanks for the suggestion! Let me know if you think of anything else :)

**Comment by GlassedSilver** [comment]
Love you man! :D
