### ISSUE TITLE
Bug: Subscription interval changes only work after restart

### ISSUE THREAD

**Issue by Jisagi** [Tzahi12345/YoutubeDL-Material#380]
Hi, I m running ytdl-material inside a docker container and noticed, that any subscription interval change ones makes, are only applied, after a restart of the docker container (and thereofre the application). I did not test this outside a docker environment though, but I suppose this happens there as well.

**Comment by Tzahi12345** [comment]
Fixed! [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/6e084bd94a6d63ae8778aaee02296390027d3e2b).

One caveat is that the update will only take place after the initial delay has finished. For example, if your interval was 86400 (one day), and you change it to 300, the 5 minute interval will only begin when the next check has started, which can of course take up to a day.

It's the easiest approach without adding checks to the save settings functionality, a fine compromise imo. Thanks for the report!
