### ISSUE TITLE
Public API question

### ISSUE THREAD

**Issue by ibrahimk157** [Tzahi12345/YoutubeDL-Material#384]
Hi

So I've enabled the public api for the YoutubeDL-Material instance running on my server. And my goal is to use the iOS Shortcuts app to download videos to my iPhone through a shortcut by using the public api.

I've managed to get the server to download the video through the "tomp4" api call. However, I have no idea how to download that video from my server to my iPhone through the api. 

I'm guessing I need to use the "downloadFile" call, but I'm not sure how to link it to the video downloaded in the previous "tomp4" call.

What am I missing?

**Comment by Tzahi12345** [comment]
The API is horribly outdated, I'll make sure it's updated for v4.3 but the simple answer is to use /downloadFile and have this as the body:

```
{"fileNames" <insert file name here>, "type": <file type>}
```

This file name is relative to the download path, in the DB it's the property `id`. In a [soon-to-be-merged PR](https://github.com/Tzahi12345/YoutubeDL-Material/pull/378) this will change to the file uid, so if you're on the latest `nightly` look out for that change. The file type is just "audio" or "video".

**Comment by ibrahimk157** [comment]
> The API is horribly outdated, I'll make sure it's updated for v4.3 but the simple answer is to use /downloadFile and have this as the body:
> 
> ```
> {"fileNames" <insert file name here>, "type": <file type>}
> ```
> 
> This file name is relative to the download path, in the DB it's the property `id`. In a [soon-to-be-merged PR](https://github.com/Tzahi12345/YoutubeDL-Material/pull/378) this will change to the file uid, so if you're on the latest `nightly` look out for that change. The file type is just "audio" or "video".

Brilliant! Can’t thank you enough for your amazing work!
