### ISSUE TITLE
Docker container generates constant 1k calls per minute to YouTube

### ISSUE THREAD

**Issue by itsthejoker** [Tzahi12345/YoutubeDL-Material#385]
I checked my pihole today and was horrified to discover that this container is sending, on average, 17 requests per second to YouTube. See screenshot below for example, and note at the end where I turned off the container. 

![image](https://user-images.githubusercontent.com/5179553/119283414-f02b5a80-bc0a-11eb-9aaa-236fe6e3c6b1.png)

(Note: in the second graph, the teal is _just_ traffic from this container. The little bits of color at the bottom is every other device on my network.)

I will keep this turned off for now, but:

1) What is causing this?

2) How can I set the rate limit to be much more reasonable?

**Comment by itsthejoker** [comment]
@vladola This is the pihole interface for my entire network (https://pi-hole.net/). I can't visualize it for a specific container, but it does tell me which IP address is making the requests, and all of this traffic was coming from my NAS, which is my docker host. Since the last 24 hours also included over 80 million requests to YouTube, and I only have one container that relates to YouTube, so the logical assumption is that it's that container. I was able to verify that assumption by turning off the container and seeing the overall traffic from the host drop tremendously, as seen by the far right of both of those graphs where the total requests go down closer to 750 requests in a 10 minute period (much more appropriate for my normal network traffic).

**Comment by itsthejoker** [comment]
@Tzahi12345 any ideas on how to fix this? This issue is absolutely repeatable and I can't keep this container running all the time. Here's an example from today - it's fairly obvious when I started up the container.

![image](https://user-images.githubusercontent.com/5179553/122285565-e836a180-cebc-11eb-8a57-3cbcfaac3c2b.png)

Here's the config that I'm using, and as far as I know, it's essentially the original one that's created on first run.

```
{
  "YoutubeDLMaterial": {
    "Host": {
      "url": "http://example.com",
      "port": "17442"
    },
    "Downloader": {
      "path-audio": "audio/",
      "path-video": "video/",
      "default_file_output": "",
      "use_youtubedl_archive": false,
      "custom_args": "",
      "safe_download_override": false,
      "include_thumbnail": true,
      "include_metadata": true
    },
    "Extra": {
      "title_top": "YoutubeDL-Material",
      "file_manager_enabled": false,
      "allow_quality_select": true,
      "download_only_mode": false,
      "allow_multi_download_mode": true,
      "enable_downloads_manager": true,
      "allow_playlist_categorization": true
    },
    "API": {
      "use_API_key": true,
      "API_key": "[redacted]",
      "use_youtube_API": false,
      "youtube_API_key": "",
      "use_twitch_API": false,
      "twitch_API_key": "",
      "twitch_auto_download_chat": false
    },
    "Themes": {
      "default_theme": "dark",
      "allow_theme_change": true
    },
    "Subscriptions": {
      "allow_subscriptions": true,
      "subscriptions_base_path": "subscriptions/",
      "subscriptions_check_interval": "300",
      "redownload_fresh_uploads": false
    },
    "Users": {
      "base_path": "users/",
      "allow_registration": true,
      "auth_method": "internal",
      "ldap_config": {
        "url": "ldap://localhost:389",
        "bindDN": "cn=root",
        "bindCredentials": "secret",
        "searchBase": "ou=passport-ldapauth",
        "searchFilter": "(uid={{username}})"
      }
    },
    "Advanced": {
      "default_downloader": "youtube-dl",
      "use_default_downloading_agent": true,
      "custom_downloading_agent": "",
      "multi_user_mode": false,
      "allow_advanced_download": false,
      "use_cookies": false,
      "jwt_expiration": 86400,
      "logger_level": "info"
    }
  }
}
```

**Comment by alaohara** [comment]
Change the subscription check interval. I had the same problem, until I changed it to 86400. I think once a day is plenty often to check, not every five minutes.

**Comment by itsthejoker** [comment]
@alaohara That fixed it for me! Thank you so much!

**Comment by Tzahi12345** [comment]
If that's the consensus, then I'll go ahead and merge #392. Admittedly I made it 5 mins without much forethought to whether it's a good default or not. Thanks for the good work guys, I appreciate it :)
