### ISSUE TITLE
audio player UI disappears after loading

### ISSUE THREAD

**Issue by dbx10** [Tzahi12345/YoutubeDL-Material#387]
Changing the background from `transparent` to any solid color makes the player reappear.

Behavior: https://www.youtube.com/watch?v=_fD6Ku0EOuA

This is the line I changed:
`<vg-player _ngcontent-eyv-c187="" style="max-height: 75vh; background-color: transparent;">`
I put `rgb(200, 200, 200)` instead of transparent,

Pretty annoying because it reloads the player and starts the audio file from the beginning.

**Comment by Tzahi12345** [comment]
Should be fixed when #378 merges, [see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/pull/378/commits/0a2529330d5ca2222ca24beff7d242940a584a0a) which addresses this. Thanks for the bug report!
