### ISSUE TITLE
[FEATURE] RSS feed for all downloads

### ISSUE THREAD

**Issue by sebdanielsson** [Tzahi12345/YoutubeDL-Material#388]
Would it be possible to add an RSS feed that lists all downloads?

**Comment by Tzahi12345** [comment]
Definitely possible, I've looked into this before a bit but it doesn't seem like too much work!

https://www.devextent.com/xml-rss-feed-nodejs/

**Comment by aevans1987** [comment]
Ideally it would be nice to have the ability to do multiple playlists instead of just 1 big playlist!

**Comment by GlassedSilver** [comment]
> Ideally it would be nice to have the ability to do multiple playlists instead of just 1 big playlist!

Possibly based on the current filter, like:

- audio, video or both selected?
- Playlist
- Subscription
- A search
- Possibly more in the future? :)

**Comment by Tzahi12345** [comment]
Feature implemented and will be usable in v4.3.1!

Includes filtering for file type, subscriptions, text search, and more.

Only thing missing from @GlassedSilver's list is playlist filtering but I think that's ok for now.
