### ISSUE TITLE
Getting Bad Request when making a login request (/api/auth/login)

### ISSUE THREAD

**Issue by syedair** [Tzahi12345/YoutubeDL-Material#396]
Hi,

I have enabled multi-user mode, and the UI works great. However, my use-case is to use the API as well. When I use the API docs [1], I am unable to get the `/api/auth/login` request working to get the token for my user. The following is the sample cURL request that I copied from the API docs [1], but it still isn't working. I tried changing the Content-Type, to all available options, but still the same result. 

Any help will be much appreciated.

```
ubuntu@ubuntu:~$ curl --request POST   --url 'http://192.168.4.145:8080/api/auth/login?apiKey={{myapiKey}}'   --header 'Content-Type: application/x-www-form-urlencoded'   --header 'Prefer: code=200'   --data userid={{myuserid}}   --data password={{mypassword}} -v


Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.4.145:8080...
* Connected to 192.168.4.145 (192.168.4.145) port 8080 (#0)
> POST /api/auth/login?apiKey={{myapiKey}} HTTP/1.1
> Host: 192.168.4.145:8080
> User-Agent: curl/7.74.0
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Prefer: code=200
> Content-Length: 27
> 
* upload completely sent off: 27 out of 27 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< X-Powered-By: Express
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
< Access-Control-Allow-Origin: http://example.com
< Date: Mon, 12 Jul 2021 19:55:06 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
< 
* Connection #0 to host 192.168.4.145 left intact
Bad Request
```

[1] https://youtubedl-material.stoplight.io/docs/youtubedl-material/Public%20API%20v1.yaml/paths/~1api~1auth~1login/post

**Comment by syedair** [comment]
API Documentation needs to be updated... `username` needs to be passed instead of `userid`... 

https://youtubedl-material.stoplight.io/docs/youtubedl-material/Public%20API%20v1.yaml/paths/~1api~1auth~1login/post

**Comment by Tzahi12345** [comment]
Yup sorry about this, just made an issue to address it #397!
