### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by UltraTV** [Tzahi12345/YoutubeDL-Material#4]
I love this simple clean downloader.
My ideas for the future:

- Add setting to select quality (video and music quality)
- Make it possible to create translations
- Feature to not save the mp4/mp3 file on the server
- Feature to search a video in ytdl-material instead of copying and pasting a link (useful on phones)
- Feature to download a whole youtube playlist

**Comment by Tzahi12345** [comment]
Great suggestions, thank you! I've thought of some of these myself as well. Will keep them in mind -- I'll post a comment in this thread if they get implemented.

**Comment by Tzahi12345** [comment]
@UltraTV Letting you know that I've uploading an alpha version of the next major update (3.0) which will contain most of the features requested here (custom quality, auto-deleting mp3/mp4s, youtube search, and playlist support).

Check it out here: https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v3.0-alpha
Changelog has all the juicy deets.

I'll make sure translations are in the pipeline as they wouldn't be very difficult.

Anyways, let me know what you think!

**Comment by warsix4** [comment]
Hi, I also have an idea or two.

1. Scheduled downloads, or playlist monitoring, would be amazing, I think it could be the first step towards this project being the YouTube-arr of selfhosted apps. 
2. Renaming/moving. Just like Sonarr or Radarr, this could be configured to download each playlist's videos to a channel/playlist folder structure.

I know they are massive tasks, and I am not a developer by any means able to contibrute to these ideas, but I hope you consider them!

**Comment by Tzahi12345** [comment]
Great ideas!

1. Playlist and channel monitoring is actually planned for 2 updates from now. It will definitely require adding a large amount of code but it's requested enough that it's in the pipeline. I'll lyk when this is fully implemented. Scheduling downloads is a good idea too, I'll keep it in mind.

2. I implemented a custom output option in the UI for the next update which (I believe) will satisfy the suggestion above using youtube-dl's [output template](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#output-template) feature. I want to eventually make this a true setting rather than an input for further customization.

**Comment by warsix4** [comment]
Awesome stuff, thanks!

**Comment by UltraTV** [comment]
I love all these updates that are coming out recently. 
But is it possible to somehow autoupdate?

**Comment by UltraTV** [comment]
Idea: Setting to default tick "Only Audio"

**Comment by Tzahi12345** [comment]
>But is it possible to somehow autoupdate?

An updater script would be nice. I don't plan on implementing that in the next update, but it's something to consider.

Btw, if you use the Docker container (instructions [here](https://github.com/Tzahi12345/YoutubeDL-Material#Docker)), you can set up shared volumes that will persist your videos through updates. To update, change the version in `docker-compose.yml` and run `docker-compose pull`. You should be good to go. Only issue is your saved playlists might disappear with each update, unless you transfer over the db.json file. I'll think of some better solutions that will be easy to do for Docker and non-Docker users.

>Idea: Setting to default tick "Only Audio"

In recent versions (I think 3.1 and above), if you click "only audio" it will remember when you reload the page, storing it in your cookies. If you use a different browser, it will default back to false. Maybe a setting to change which is the default when no cookie is present. Sounds easy to implement!

**Comment by Tzahi12345** [comment]
@UltraTV Just wanted to let you know that translation support has been added, and the ability to select a language is implemented and will be available in the next release, v3.5.

Here's a [link to the XLIFF](https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/src/locale/messages.xlf) which you can use with a translation tool to create a translated XLIFF (example for Spanish [here](https://github.com/Tzahi12345/YoutubeDL-Material/blob/master/src/locale/messages.es.xlf)). I will document this officially once the release comes out in a couple weeks or so. Let me know if you create a translation! There's a tiny bit of work to do on my end to get each language fully implemented -- again, will be documented in the future.

I'll keep this issue open until I get all the features in here implemented, particularly the updater. Let me know if you have any other ideas!

**Comment by Tzahi12345** [comment]
I'm going to close out this issue as all the requests have been implemented except one: an updater.

I've created a separate issue for that which you can track [here](https://github.com/Tzahi12345/YoutubeDL-Material/issues/41). Feel free to create another issue if you have any other ideas!
