### ISSUE TITLE
MongoDB - "Connection failed! Error: Connection string failed."

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#400]
Cheers!

Okay so right as I'm trying to get to connect to my mongodb server I set up in unRAID (because unRAID doesn't really have docker-compose (it's a topic of its own...)) via docker I just cannot get it to connect to it.

I found out that the connection is refused...

Apparently there are no environment flags to set a password and user in ytdl-m and hence I'm running it without any initialized user or password... Sooo...

Yes I made sure I'm using the official mongo repo.
No I don't know what I'm doing, because I'm a complete novice with mongo :P
Anything else I could say? idk

So far testing the connection string always results in that message in the title of this issue, so...

What do? Oh and I did set my mongodb container to use the network host mode, so I can call it by my server's host IP.
I can ping to it sucessfully from the bash inside the ytdl-m container, so... mongodb itself must be cranky?

Yeah idk... the mongodb container log doesn't look too happy:

```
{"t":{"$date":"2021-07-22T05:52:07.041+02:00"},"s":"I", "c":"CONTROL", "id":23285, "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2021-07-22T05:52:07.044+02:00"},"s":"W", "c":"ASIO", "id":22601, "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
{"t":{"$date":"2021-07-22T05:52:07.044+02:00"},"s":"I", "c":"NETWORK", "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2021-07-22T05:52:07.045+02:00"},"s":"I", "c":"STORAGE", "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"Ahri"}}
{"t":{"$date":"2021-07-22T05:52:07.045+02:00"},"s":"I", "c":"CONTROL", "id":23403, "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.7","gitVersion":"abb6b9c2bf675e9e2aeaecba05f0f8359d99e203","openSSLVersion":"OpenSSL 1.1.1f 31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2021-07-22T05:52:07.045+02:00"},"s":"I", "c":"CONTROL", "id":51765, "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
{"t":{"$date":"2021-07-22T05:52:07.045+02:00"},"s":"I", "c":"CONTROL", "id":21951, "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
{"t":{"$date":"2021-07-22T05:52:07.050+02:00"},"s":"I", "c":"STORAGE", "id":22270, "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
{"t":{"$date":"2021-07-22T05:52:07.052+02:00"},"s":"I", "c":"STORAGE", "id":22315, "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=23614M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
{"t":{"$date":"2021-07-22T05:52:08.177+02:00"},"s":"I", "c":"STORAGE", "id":22430, "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1626925928:177828][1:0x1479a9cbccc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 1 through 2"}}
{"t":{"$date":"2021-07-22T05:52:08.480+02:00"},"s":"I", "c":"STORAGE", "id":22430, "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1626925928:480775][1:0x1479a9cbccc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 2 through 2"}}
{"t":{"$date":"2021-07-22T05:52:08.828+02:00"},"s":"I", "c":"STORAGE", "id":22430, "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1626925928:828109][1:0x1479a9cbccc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Main recovery loop: starting at 1/29696 to 2/256"}}
{"t":{"$date":"2021-07-22T05:52:09.188+02:00"},"s":"E", "c":"STORAGE", "id":22435, "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":2,"message":"[1626925929:188891][1:0x1479a9cbccc0], txn-recover: __posix_open_file, 805: /data/db/journal/WiredTigerLog.0000000001: handle-open: open: No such file or directory"}}
{"t":{"$date":"2021-07-22T05:52:09.189+02:00"},"s":"E", "c":"STORAGE", "id":22435, "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":2,"message":"[1626925929:189039][1:0x1479a9cbccc0], txn-recover: __wt_log_scan, 2428: WiredTiger is unable to read the recovery log: No such file or directory"}}
{"t":{"$date":"2021-07-22T05:52:09.189+02:00"},"s":"E", "c":"STORAGE", "id":22435, "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":2,"message":"[1626925929:189078][1:0x1479a9cbccc0], txn-recover: __wt_log_scan, 2431: This may be due to the log files being encrypted, being from an older version or due to corruption on disk: No such file or directory"}}
{"t":{"$date":"2021-07-22T05:52:09.189+02:00"},"s":"E", "c":"STORAGE", "id":22435, "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":2,"message":"[1626925929:189106][1:0x1479a9cbccc0], txn-recover: __wt_log_scan, 2434: You should confirm that you have opened the database with the correct options including all encryption and compression options: No such file or directory"}}
{"t":{"$date":"2021-07-22T05:52:09.189+02:00"},"s":"E", "c":"STORAGE", "id":22435, "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":2,"message":"[1626925929:189146][1:0x1479a9cbccc0], txn-recover: __wt_txn_recover, 1063: Recovery failed: No such file or directory"}}
{"t":{"$date":"2021-07-22T05:52:09.320+02:00"},"s":"E", "c":"STORAGE", "id":22435, "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1626925929:320199][1:0x1479a9cbccc0], connection: __wt_cache_destroy, 364: cache server: exiting with 3 pages in memory and 0 pages evicted"}}
{"t":{"$date":"2021-07-22T05:52:09.320+02:00"},"s":"E", "c":"STORAGE", "id":22435, "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1626925929:320362][1:0x1479a9cbccc0], connection: __wt_cache_destroy, 367: cache server: exiting with 18453 image bytes in memory"}}
{"t":{"$date":"2021-07-22T05:52:09.320+02:00"},"s":"E", "c":"STORAGE", "id":22435, "ctx":"initandlisten","msg":"WiredTiger error","attr":{"error":0,"message":"[1626925929:320420][1:0x1479a9cbccc0], connection: __wt_cache_destroy, 370: cache server: exiting with 19110 bytes in memory"}}
{"t":{"$date":"2021-07-22T05:52:09.413+02:00"},"s":"I", "c":"STORAGE", "id":22430, "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1626925929:413425][1:0x1479a9cbccc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global recovery timestamp: (0, 0)"}}
{"t":{"$date":"2021-07-22T05:52:09.413+02:00"},"s":"I", "c":"STORAGE", "id":22430, "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1626925929:413542][1:0x1479a9cbccc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global oldest timestamp: (0, 0)"}}
{"t":{"$date":"2021-07-22T05:52:09.441+02:00"},"s":"I", "c":"STORAGE", "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":2389}}
{"t":{"$date":"2021-07-22T05:52:09.441+02:00"},"s":"I", "c":"RECOVERY", "id":23987, "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2021-07-22T05:52:09.519+02:00"},"s":"I", "c":"STORAGE", "id":4366408, "ctx":"initandlisten","msg":"No table logging settings modifications are required for existing WiredTiger tables","attr":{"loggingEnabled":true}}
{"t":{"$date":"2021-07-22T05:52:09.520+02:00"},"s":"I", "c":"STORAGE", "id":22262, "ctx":"initandlisten","msg":"Timestamp monitor starting"}
{"t":{"$date":"2021-07-22T05:52:09.533+02:00"},"s":"W", "c":"CONTROL", "id":22120, "ctx":"initandlisten","msg":"Access control is not enabled for the database. Read and write access to data and configuration is unrestricted","tags":["startupWarnings"]}
{"t":{"$date":"2021-07-22T05:52:09.534+02:00"},"s":"W", "c":"CONTROL", "id":22167, "ctx":"initandlisten","msg":"You are running on a NUMA machine. We suggest launching mongod like this to avoid performance problems: numactl --interleave=all mongod [other options]","tags":["startupWarnings"]}
{"t":{"$date":"2021-07-22T05:52:09.534+02:00"},"s":"W", "c":"CONTROL", "id":22178, "ctx":"initandlisten","msg":"/sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'","tags":["startupWarnings"]}
{"t":{"$date":"2021-07-22T05:52:09.534+02:00"},"s":"W", "c":"CONTROL", "id":22184, "ctx":"initandlisten","msg":"Soft rlimits too low","attr":{"currentValue":40960,"recommendedMinimum":64000},"tags":["startupWarnings"]}
{"t":{"$date":"2021-07-22T05:52:09.556+02:00"},"s":"I", "c":"STORAGE", "id":20320, "ctx":"initandlisten","msg":"createCollection","attr":{"namespace":"admin.system.version","uuidDisposition":"provided","uuid":{"uuid":{"$uuid":"81952c6b-d069-4308-989e-b01467018ec7"}},"options":{"uuid":{"$uuid":"81952c6b-d069-4308-989e-b01467018ec7"}}}}
{"t":{"$date":"2021-07-22T05:52:09.595+02:00"},"s":"I", "c":"INDEX", "id":20345, "ctx":"initandlisten","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"admin.system.version","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2021-07-22T05:52:09.595+02:00"},"s":"I", "c":"COMMAND", "id":20459, "ctx":"initandlisten","msg":"Setting featureCompatibilityVersion","attr":{"newVersion":"4.4"}}
{"t":{"$date":"2021-07-22T05:52:09.601+02:00"},"s":"I", "c":"STORAGE", "id":20536, "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"}
{"t":{"$date":"2021-07-22T05:52:09.602+02:00"},"s":"I", "c":"STORAGE", "id":20320, "ctx":"initandlisten","msg":"createCollection","attr":{"namespace":"local.startup_log","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"af73741f-177d-4f16-ae08-c18acd4dbec1"}},"options":{"capped":true,"size":10485760}}}
{"t":{"$date":"2021-07-22T05:52:09.645+02:00"},"s":"I", "c":"INDEX", "id":20345, "ctx":"initandlisten","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"local.startup_log","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2021-07-22T05:52:09.645+02:00"},"s":"I", "c":"FTDC", "id":20625, "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/data/db/diagnostic.data"}}
{"t":{"$date":"2021-07-22T05:52:09.649+02:00"},"s":"I", "c":"NETWORK", "id":23015, "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
{"t":{"$date":"2021-07-22T05:52:09.649+02:00"},"s":"I", "c":"NETWORK", "id":23015, "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}
{"t":{"$date":"2021-07-22T05:52:09.649+02:00"},"s":"I", "c":"NETWORK", "id":23016, "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
{"t":{"$date":"2021-07-22T05:52:09.661+02:00"},"s":"I", "c":"CONTROL", "id":20712, "ctx":"LogicalSessionCacheReap","msg":"Sessions collection is not set up; waiting until next sessions reap interval","attr":{"error":"NamespaceNotFound: config.system.sessions does not exist"}}
{"t":{"$date":"2021-07-22T05:52:09.661+02:00"},"s":"I", "c":"STORAGE", "id":20320, "ctx":"LogicalSessionCacheRefresh","msg":"createCollection","attr":{"namespace":"config.system.sessions","uuidDisposition":"generated","uuid":{"uuid":{"$uuid":"5a2e2040-a8cc-4dc6-bcea-bad8e040bf6e"}},"options":{}}}
{"t":{"$date":"2021-07-22T05:52:09.722+02:00"},"s":"I", "c":"INDEX", "id":20345, "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"config.system.sessions","index":"_id_","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2021-07-22T05:52:09.722+02:00"},"s":"I", "c":"INDEX", "id":20345, "ctx":"LogicalSessionCacheRefresh","msg":"Index build: done building","attr":{"buildUUID":null,"namespace":"config.system.sessions","index":"lsidTTLIndex","commitTimestamp":{"$timestamp":{"t":0,"i":0}}}}
{"t":{"$date":"2021-07-22T05:53:09.529+02:00"},"s":"I", "c":"STORAGE", "id":22430, "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1626925989:529377][1:0x1479a80ad700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 34, snapshot max: 34 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0)"}}
```

**Comment by Tzahi12345** [comment]
What's the connection string you're putting in? Can you try `mongodb://localhost:27017`?

If the port isn't open and it's all local, I wouldn't worry about a username/password for now, we can take care of that once you get connected. Maybe there's more details in the logs as I believe we do log if there's an error connecting.

**Comment by GlassedSilver** [comment]
Unfortunately that's not how unRAID works. I could run both as host networked, but I'd rather leave the app as bridged and the db as host with the port exposed locally on the network (also for maintaining the db using something like a database editor if needed) and then setting password and user.

Honestly, that's how my mariadb and Postgres work wonderfully. No need to link anything or have both as host or use of container name.

In fact, that's how I got a different app to connect to the mongodb container! :)

**Comment by GlassedSilver** [comment]
Apparently ytdl_material exists in my database in mongo...
wtf...

so is this another case of no output and a lot of concurrent background tasks? Cause I cannot even get the ytdl-m GUI to display... so it's probably that...

And I restarted, fumbled with configs, etc... apparently once I made the right settings and didn't get the UI anymore after restarting the ytdl-m container I should have waited. :O

**Comment by Tzahi12345** [comment]
That's weird! What's happening on the browser as you try to connect? Anything in the browser logs?

But yeah startup takes 5-10 seconds now instead of the usual 1-3 seconds as a DB connection needs to be made/attempted. But it really shouldn't take much longer than that unless you see a migration is going through (using the same method you got the container logs earlier)

**Comment by GlassedSilver** [comment]
Well my db has 26k items and tbh... I would have loved for the transition not to silently start, but to be asked to move to it?

Now I don't know if the mongo db that is being created is all messed up because of my blind restarts of the docker and all that. o.O

Either way, when trying to open YTDL-M I get this:

```
Unable to connect

Firefox can’t establish a connection to the server at 192.168.2.107:8999.
```

So... I'm a bit puzzled now. I'll probably let it sit there and do its thing and check back later, praying it all transitioned nicely. I mean I did make backups of the thing, but what I'm always a bit unfond of is that at some point it made some successful downloads that now are not gonna be downloads, but "found files" or something idk if I were to restore from the backup I made uh... yesterday I think.

Maybe this is now the slowness of the old db rearing its ugly head for one last hoorah until mongodb will make things speedier once it's transitioned.

Would be awesome :P

**Comment by Tzahi12345** [comment]
It might be worth doing the transition to these new nightlies again, since you seem to have figured out the DB connection issue.

I noticed you're using port `8999`, is that intentional?

The reason why we don't ask before migrating stuff over is there isn't backwards compatibility to the old DB system from a few days ago. There is the ability to use a local DB, but the structure now matches MongoDB's, with records being split into "tables" which are just JSON objects like so:

```
{
  "files": [],
  "playlists": [],
  "categories": [],
  "subscriptions": [],
  "downloads": [],
  "users": [],
  "roles": []
}
```
I did this to make transitioning from a JSON-based DB to MongoDB as easy as possible, it requires just a few lines of code while still allowing users to transfer to the Local DB, make changes, and transfer back to MongoDB. If you'd like I can convert your db.json on my end and send you the local_db.json that generates after the transfer. That way you can do the following:

1. Set "use_local_db" in the config to true
2. Set "new_db_system_migration_complete" to true in your db.json
3. Place the generated local_db.json in your appdata folder
4. Start the server, go into settings, and transfer the DB to MongoDB

You should be good to go. This isn't ideal, but maybe necessary in your case since you have so many dang files :P

**Comment by jonathanm-ur** [comment]
I've been watching this with excitement, hoping for a smooth transition. My db.json file is over 50MB now, so I'm pretty sure I will run into the same issues, since I'm also running the container on Unraid. Currently I'm running a nightly updated a few days ago and holding, since I have no idea what to expect when I update to the latest nightly.

How would you recommend I proceed?
![image](https://user-images.githubusercontent.com/64561015/126656347-4b3f9407-e544-45a8-a3e3-1cb8f86eb1d7.png)

**Comment by Tzahi12345** [comment]
@jonathanm-ur If this is possible, perhaps you can copy the files over, create a new container on another port, and try the migration process on that test container. If it goes well, then there's not much to worry about.

I'm not sure where these issues are coming from, but I can probably test it out tonight with a relatively large database. In fact, if you send me your DB perhaps I can try it out on my container and see how that goes. Up to you, or I can just make a test one.

Ideally there wouldn't be any problems, but that's never happened with these DB migrations. It's just a matter of us using an old system that requires a lot of I/O, as @GlassedSilver said, hopefully this is the last of it.

**Comment by jonathanm-ur** [comment]
My bigger question is about the mongodb addition. Do I need to prepare a blank mongodb database before attempting the migration, or can I migrate to the new local flat text layout initially and then deal with exporting it to the mongodb once the local migration is complete?

The description of the upgrade process was unclear to me.

**Comment by Tzahi12345** [comment]
It can be either one, that's why I didn't really specify as it should be seamless regardless -- but if you do want to use mongodb directly, make sure to set `use_local_db` to false in the config and set your connection string. It's a bit riskier because it's hard to tell whether the connection string will work.

So if you're worried about that, use the local DB first and then transfer once you can test the connection string from the settings.

**Comment by jonathanm-ur** [comment]
The migration to the new format took about 20 minutes, and seemed to work fine.
Is the db.json used for anything in the new layout? I'd like to remove all extraneous files.

**Comment by Tzahi12345** [comment]
Good to hear! The `db.json` is still used for stuff like keeping track of migrations, but most of the stuff can be removed. I didn't want to strip the unused stuff to maintain backwards compatibility, though I do plan on cleaning it up at some point, perhaps when v4.3 is released.

You can get rid of `users.json` though if you'd like.

**Comment by GlassedSilver** [comment]
Okay, well at the moment I've helped my installation a bit again.

The connection to the db I didn't get to work again so far, the connection string in the test always errors out, not sure if just setting, migrating and forgetting would work, but I'm not gonna risk the integrity of my db as of now.

One curious thing:

Downloads (one-offs I issue manually) work, but the downloads list isn't clearable:
`2021-07-24T23:25:03.815Z ERROR: Session 5a1972f9a205c73cee7c56168a121760 has no downloads.`

Okay, BUUUUT....

![image](https://user-images.githubusercontent.com/1912133/126883215-cefeef58-5d5f-4947-ac7b-a5fb9a00af68.png)
Clicking on the individual clear buttons or the clear all doesn't do anything.

Very curious.

Also: subscriptions seem not to download anything at the moment. My personal setting for the interval is and has always been 3500 seconds. The container has been running for several hours by now. o.O (7 to name it directly)

Already though the instance with the local_db successfully migrated is snappier a little bit.

![image](https://user-images.githubusercontent.com/1912133/126883254-3f4bae4d-397b-4f2c-99ac-e12a201a7b64.png)

Really appreciate this nice little overview here as well by the way. :)

So... still trying to figure out the thing about the unclearable downloads, interrupted subs and getting the connection to mongodb back up and running.

Latest nightly by now by the way, for reference. :)

Cheers and let's see how this progresses. Definitely happy I can issue some downloads again and it's only been a few days but I'm already getting a bit uncomfortable not having immediate backups for my favorite channels. :D

**Comment by GlassedSilver** [comment]
Still got this in my db.json:

`files_to_db_migration_complete": false,`

Been in there like that for a while now. Wonder what's still dangling or if it's just gonna take forever to be set to true?

Either way, yes the alternative port is intentional, no worries about that. :P 

Also, I got `"new_db_system_migration_complete": true` now as of that one successful odd load a few days ago, so yeah, that's a plus.
Back in my instance as I posted before and now I'm gonna see how I can get MongoDB to work. :)

**Comment by Tzahi12345** [comment]
Not dangling! I should remove it at this point, but it was from before files even existed in the DB. We would just check the folder for a list of .mp4s with .jsons and gather info for them that way. 

![image](https://user-images.githubusercontent.com/707413/127080412-764b1392-2e66-4eaa-8fa1-c6c7f6f0617a.png)

You can see we just ignore it now, just assuming anyone on the newer versions isn't migrating from then. It's not wonderful design, but having to support so many permutations of upgrading and all is a bit crazy (where are they upgrading from? maybe they upgraded and then downgraded and then upgraded again?)

So basically it looks like you're fully migrated over! Now for the MongoDB thing, I'm a bit at a loss. I tried searching on unraid how people did it but info looks relatively scarce.

One thing I should add, and maybe make this clear in the settings menu: if you type out a connection string, testing it will **not** test whatever you typed if you did not save! Just looking at the screenshot you posted it looks like you edited it without saving. This should probably be changed, in fact I'll probably work on that now since it's super unclear.

-------------

On the downloads stuff.. Ugh, it's such a bad implementation, I'm not very motivated to iterate on it as it should be chucked out for a more robust system, where you can queue up downloads, actually cancel them, retry them, etc. And maybe that will be the home for your #157 suggestion, which is queued up for v4.3 regardless.

**Comment by GlassedSilver** [comment]
Ah ok, well I now saved the string, then tested and oddly enough... the fail doesn't happen right away, so it seems like it's doing SOMETHING in the background.

As for subscriptions... Well I added another sub to my ytdl-m and it did download the videos from there (I think all of them, but I honestly didn't check. It did grab a good bunch)

What I still find odd though: all the other subs are still paused. Is the sub checking routine maybe broken? Did you change something in the last 2-3 updates or something? Up until July 21 everything downloaded just fine, I had been a version or two below latest back then.

Really odd.

**Comment by Tzahi12345** [comment]
Connection string now uses whatever is typed in the text box ([commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/258d5ff495849b54938d720f057383915836de15)).

If the button isn't doing anything for a while, it's not a great sign. I'd wait for a message to come up, I think it times out within 30s. The server logs should say the error.

Regarding the subs, this may be a bug. Do you see anything in the logs about it?

**Comment by GlassedSilver** [comment]
> 
> 
> Connection string now uses whatever is typed in the text box ([commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/258d5ff495849b54938d720f057383915836de15)).
> 
> If the button isn't doing anything for a while, it's not a great sign. I'd wait for a message to come up, I think it times out within 30s. The server logs should say the error.
> 
> Regarding the subs, this may be a bug. Do you see anything in the logs about it?

If you don't mind I'll wait for my subscription I added a few hours ago to complete downloading and then quit the instance, make backups of the config folder and clear the log and restart the container, so I can show you the debug-level log from a fresh restart of the container.

Cause right now I don't spot anything sus in the logs, but maybe I missed something, because I turned on debug-level logging just a few hours ago, so hasn't caught anything possibly breaking at the start of the container.

Anything else I could submit - preferably privately?

Come to think of it, if you don't mind I could also screencast my instance to you in a Discord call or something and show you around and give you a real-world impression of it? Could possibly speed up any bug hunting, because well... real-time conversation is always better imho, but ymmv and I don't know if you've even got the time for it. You tell me. :)

**Comment by Tzahi12345** [comment]
Send me your discord over email! I'll add you and we can figure out a time, most likely this weekend would be good.

**Comment by GlassedSilver** [comment]
Weekend sounds good!
Dropping you an email in a bit. :)

**Comment by martadinata666** [comment]
So i also get this weird issue, when i checked with ```Test connection to mongoDB``` result failure, YOLO-ing transfer to DB result ```Transfer success```, click again the ```Test connection to mongoDB``` result become success. Can somebody try to replicate? Thanks.

**Comment by Tzahi12345** [comment]
@martadinata666 Do you see any errors in the logs?

**Comment by Tzahi12345** [comment]
@martadinata666 This should be fixed! [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/b03b4d173b590abb10108129b85c70f4f2066763). Note it usually takes about an hour for the `nightly` to update.

**Comment by Tzahi12345** [comment]
Closing as this should be resolved.
