### ISSUE TITLE
[FEATURE] ARG help

### ISSUE THREAD

**Issue by amuilyas** [Tzahi12345/YoutubeDL-Material#403]
First of all thank you for such a great program which I find incredibly useful for watching videos offline at my own pace and with full playback control on Kodi.

**Is your feature request related to a problem? Please describe.**
I find the documentation on adding arguments confusing.  I am definitely NOT a programmer but like to think of myself as semi-intelligent and struggled to follow the guidelines with respect to the GUI vs CLI that the docs seem to assume.

**Describe the solution you'd like**
One or two examples in the docs that show the text string within the GUI as a screenshot.  My immediate problem is wanting to add file creation/upload date at the start of the file name so I can easily sort channel downloads by date for latest videos.  I tried several permutations of arg text based on what I could google but do not get dates at start of file.

I tried below and none worked for me:
-o"%(release_date)s - %(title)s.%(ext)s"
-o "%(release_date)s - %(title)s.%(ext)s"
-o '%(release_date)s.%(title)s.%(ext)s'

**Additional context**
I am running YDL on Synology in Docker.  Picture of my failed attempts.  I know I am doing something very wrong, just need some pointers on how do it properly.  Thanks again for a great program!
![Screenshot 2021-07-24 182058](https://user-images.githubusercontent.com/77816893/126884743-52df39d3-5437-4890-ad52-09aacb3271ed.png)

**Comment by Tzahi12345** [comment]
Will convert this to a discussion as it's more of a question, but I'll answer it there!
