### ISSUE TITLE
Is server restart available from cli?

### ISSUE THREAD

**Issue by arithxp** [Tzahi12345/YoutubeDL-Material#406]
Sometimes the docker container is not responding.
Then the only solution I could do was to restart docker.

In the options, there was a button to restart the server. Is there a script to run on the cli?

And I am running Ubuntu server in a virtual machine (xcp-ng).
On the server, the youtube-dl material docker and the ftp server are mounted and running with rclone.
Therefore, there is no YouTube video on the server, and there is no reason to use a lot of capacity, but sometimes 50GB of capacity is used up.
Docker stopped showing an error after 100% of capacity was used.
I couldn't find the cause, so I created a new server and increased the capacity to 150 GB.
Has anyone had a similar experience? Please let me know if you know the cause.

Thanks for reading.
And thanks for the wonderful project.

**Comment by Tzahi12345** [comment]
You're seeing 50GB usage with no videos? Wow, haven't seen this one before. Perhaps it's a docker issue.

To answer your question, besides restarting the container you can go into settings, and I believe in the advanced tab you can restart the server. The container will still be running though. Let me know if this helps!

**Comment by arithxp** [comment]
> 
> 
> You're seeing 50GB usage with no videos? Wow, haven't seen this one before. Perhaps it's a docker issue.
> 
> To answer your question, besides restarting the container you can go into settings, and I believe in the advanced tab you can restart the server. The container will still be running though. Let me know if this helps!

Yes. In the Advanced tab, I saw the Restart Server button.
However, when a problem occurs, the web page is not displayed.
So I can't do anything on the gui.

```
Unable to connect
Firefox can't connect to server 192.168.29.190:8998
The server may be temporarily unavailable or may have too many users.  Please try again later.
If you can't open any page, check your computer's network connection.
If your computer or network is behind a firewall or proxy, make sure Firefox is allowed to access the web.
```

**Comment by Tzahi12345** [comment]
What exactly is taking up the disk space? If you run this command from the folder that contains your volumes, it lists them out with their size:

`docker inspect -f "{{.Volumes}}" <container_name> | sed 's/map\[//' | sed 's/]//' | tr ' ' '\n' | sed 's/.*://' | xargs sudo du -d 1 -h`

You can also try this which shows disk usage per container:

`docker system df`

**Comment by arithxp** [comment]
I deleted the vm that had a problem, so I can't check it now.
The new vm is now working fine.
/dev/mapper/ubuntu--vg-ubuntu--lv 147G 14G 125G 11% /
I'll post a comment if the problem recurs.
Thank you.

Oh, and how should I handle the case where two images are displayed on the same video?
Is there a way to organize them when they are the same video? 

The video file name, title, and path are all the same.
I clicked the 'Delete forever' button, but both have been deleted. 😂
How do I get the video back?
![51](https://user-images.githubusercontent.com/6009737/127337698-eeb906da-465b-4070-8fe8-3a51fc5a4716.png)
left video info
![52](https://user-images.githubusercontent.com/6009737/127337722-f75ee5d9-776a-4d71-9981-9592504a2c50.png)
right video info (same file name, same title, size...)
![53](https://user-images.githubusercontent.com/6009737/127337741-f6e55e73-e6b0-4f95-a1f5-ecdb5976bca7.png)
There was only one actual file. 
![54](https://user-images.githubusercontent.com/6009737/127337759-77be06f9-3866-4abe-9c88-ec62960c905f.png)

**Comment by Tzahi12345** [comment]
Looks like duplicate records were created for some reason. I'll have to look into that.

To allow the file to be downloaded again, go into `subscriptions/archives/archive.txt` and remove the line that contains the ID of that video (should be `TKGF...`). Let me know if this helps!

**Comment by arithxp** [comment]
> To allow the file to be downloaded again, go into `subscriptions/archives/archive.txt` and remove the line that contains the ID of that video (should be `TKGF...`). Let me know if this helps!

Thank you. I downloaded it again.
Only one is displayed this time. Maybe it's because of the live streaming, I don't know.

**Comment by arithxp** [comment]
> ```
> docker inspect -f "{{.Volumes}}" <container_name> | sed 's/map\[//' | sed 's/]//' | tr ' ' '\n' | sed 's/.*://' | xargs sudo du -d 1 -h
> ```
Is the command correct?
/dev/mapper/ubuntu--vg-ubuntu--lv  147G   57G   82G  41% /
The capacity of the root area has increased, so I entered a command, but an error occurred.
I don't know if it's a Ubuntu issue or a docker issue.
