### ISSUE TITLE
[BUG] I just lost a lot (not all!) of records in my db and I am puzzled as to what caused it. (might have an explanation)

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#408]
**Describe the bug**
I don't even know how to describe it.
Tried to sub to a japanese channel as mentioned in the previous issue and then ended up with this in the logs:

```
2021-07-28T17:23:11.784Z ERROR: ERROR: This live event will begin in 18 hours.
2021-07-28T17:23:11.790Z ERROR: Subscribe: Failed to get subscription info. Subscribe failed.
2021-07-28T17:25:33.081Z DEBUG: Removing all records from: files
2021-07-28T17:25:34.775Z DEBUG: Removed all records from files
2021-07-28T17:26:01.714Z ERROR: ERROR: This live event will begin in 18 hours.
2021-07-28T17:26:01.715Z ERROR: Subscribe: Failed to get subscription info. Subscribe failed.
2021-07-28T17:26:26.783Z DEBUG: Removing all records from: files
2021-07-28T17:26:28.278Z DEBUG: Removed all records from files
```

Yeah tried twice, anyhow...

Database tab in Settings shows:
```
Database location: Local
Records per table
categories: 0
downloads: 2
files: 0
playlists: 0
roles: 2
subscriptions: 36
users: 0 
```

Homepage still counts this many entries: `1 – 10 of 14203`

**Screenshots**
![image](https://user-images.githubusercontent.com/1912133/127372416-d656aa7c-794a-47c4-ad3e-518ce553ec25.png)

Gonna show you how my config folder looks like, notably compare local_db's current state to the latest .BKP I have of it.
Two-way merge would be nice, but also... hope that ytdl-m still wanders through the directory to re-add anything not in the db.

Since this seems to be something ytdl-m did "purposefully" I suspect this wouldn't be something fixed by the new externalized mongodb backened.

I know that I had a LOT of entries, probably around as many as are missing now, in the files table. That got cleared. Or something? 

Where are one-off's stored? Where are the subs stored?

I know the sub channels them selves are stored in the subs table, but I have videos in there as well, those seem to be still there, except for ones that were in the files table....

Was there a lot of switching around where stuff would be stored?

This is why I favor relational.
A file goes into a files table, a sub into a sub table. No nesting of files within subs and one-off that don't have subs into their own thing. Makes moving around easier as well, e.g. catching old one-offs to assign them to subs that got added after the fact.

I suspect that's what we do now and my mixed db got caught in the cross-fire.

I'll leave the container up for now, even though usually I would panick quite and wait for instructions, but I'll leave it at just making a backup of the db as it is now and then wait for you to get back.

**Environment**
- YoutubeDL-Material version
- docker nightly tag as of 3 days ago

**Comment by Tzahi12345** [comment]
Wow, this is a catastrophic bug and I can't believe I didn't catch this earlier. I'm so sorry. I really hope no one else unsubscribes from channels :(

I did push [a commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/d09b244bc21e396ca7bf29b76e98d1de84e18118) that fixes this. The good-ish news is that we have a mechanism to re-add all these files but that could take a while for someone with so many videos like you.

Apologies again, I should have tested this.

**Comment by GlassedSilver** [comment]
Ah I see, well good thing the log caught it!

I still remain a firm believer in the relational appproach, regardless off it being unrelated to this (ba-dum-tssshh), however it's nice that I caught a bug like this I guess and saved more users trouble like this hopefully.

Maybe I'll just stop the container, apply the last backup and start it up again after updating. Better to have ytdl-m re-catch everything that happened in the last few days rather than more than half of everything. :D (or more)
