### ISSUE TITLE
Create an updater for YoutubeDL-Material

### ISSUE THREAD

**Issue by Tzahi12345** [Tzahi12345/YoutubeDL-Material#41]
One missing feature that would significantly improve the updating process for users is an updater.

Most importantly, this should include the ability to update through the UI.

Additional notes:
* Need to investigate how this will affect Docker installs. The docker-compose will not be updated, so if they pull again it will presumably revert to the original version..
* A button to update the youtube-dl binary from the UI would also be nice
* To prevent errors during migration (such as new config items added), config items not found should revert to the default (stored in `backend/config.js`)

**Comment by GlassedSilver** [comment]
As for Docker, the old version will only be grabbed if the user has version-pinned their setup.

In my CA template I am actually defining the version as "latest", so it gets updated very handily that way the same any other container gets updated on my unRAID server. An updater is definitely much welcome for non-Docker setups.

As for manually triggering a youtube-dl binary: Yes, that would be nice indeed. :)

As for the third part: Good idea again! :)

**Comment by Tzahi12345** [comment]
Thanks for the info! I guess I should switch the docker-compose to use latest by default to avoid any issues.
