### ISSUE TITLE
[FEATURE] Download management

### ISSUE THREAD

**Issue by Tzahi12345** [Tzahi12345/YoutubeDL-Material#411]
Forgive me for breaking the template here, but this is more than just a single feature I'm looking to add.

The download management hasn't been overhauled since #57, and it's been a long time since then. The main issues are:
1. The GUI page is unwieldy to use
2. It does not fit nicely into our current DB system
3. There is no "order" to the downloads, they are simply split by session
4. Retries are not possible
5. Pausing is not possible
6. All downloads start as soon as they can, without a system to queue them up 
7. Download state (e.g. progress) is inconsistent and not clear (how much is downloaded in MBs? What's the ETA?)

These can be fixed with two new database tables. First, a `download_queue` which stores all info necessary to begin a download. It will keep track of the state (started or not, progress, paused or not, queue position)
* Caveat 1: how often do we want to update this? currently downloads get updated every second or so, but this may be too frequent
* Caveat 2: how do we store queue position? In the local DB, this is easy as items in a "table" is really just an array. In MongoDB, I don't believe this isn't the case. Perhaps we just store the start timestamp and sort when we pull the records.

Next, we can have a `finished_downloading` table, where we store downloads that finished or failed (with an error log). Here we can include a retry button, and an option to clear the "log" (not the file itself).

The GUI should be overhauled as well, showing first the download queue, and under it the finished downloads. This can be in a table format if space allows.

Related feature request: #379 regarding rate limiting downloads, which will almost certainly merge before this even gets worked on.

--------

Tangential to this #157 which should make the process of importing videos easier. The reason these occupy the same space in my brain is I imagine a queue system that can work for both (`unprocessed upload` -> `processed upload`, likewise `not yet downloaded` -> `downloaded`)

**Comment by GlassedSilver** [comment]
Oh nice, you're considering a full-on staging process! I VERY MUCH like this idea, because we only let into the DB (the main part) what has actually safely reached the instance. Before we push downloads to the DB we can do sanity checks as well!

Another thing, maybe the actual downloading happens to a /downloading directory which we then move files from into the actual user-set desired final location.

That way we don't end up with .part's in the folder structure where we expect to only find done and sane downloads. Everything that didn't pass the bouncer has to remain on the sidewalk until we let it in and confirm it fits the criteria. (is finished, isn't a kilobyte file because oh idk... something unexpected happened, etc... I actually don't know much about good sanity checking on media downloads, so don't take it from me, but the concept itself, you know? I guess we could also tie in something like... if we subscribe to a Twitch channel and they are live, I THINK we are pulling the stream as it's cast, right? In that case, I would say it's good to prefer the live recording over the VOD if our check confirms there are silent audio tracks in the file (muted music, because Amazon apparently is too poor to negotiate like Google did with musicians so music tracks can remain mostly unmuted))

**Comment by jonathanm-ur** [comment]
This may belong as a separate request, but it fits with the general theme of download management.

I would like a list of all videos in a channel, with the ability to refresh that list but not automatically download new videos, just offer the ability to check them off and add them to the queue. 

This could be implemented in the current GUI layout, when you browse the specific subscription or playlist it could have a refresh button that would update the list of currently available videos, show a blank thumbnail with text or download the thumbnail only and overlay a red X or something that would denote that it's not available locally yet, clicking on it would offer the ability to immediately download or add it to a queue. It would also be nice to highlight videos that are local only with no online counterpart with a distinct border or something, so you can see at a glance if one of the previous downloads is no longer available online.
 
There are some channels I watch that occasionally don't automatically download all new content, it would be nice to know if the youtubedl list isn't picking up the video, or it picked it up and couldn't download for some reason.

**Comment by GlassedSilver** [comment]
> This may belong as a separate request, but it fits with the general theme of download management.
> 
> I would like a list of all videos in a channel, with the ability to refresh that list but not automatically download new videos, just offer the ability to check them off and add them to the queue.
> 
> This could be implemented in the current GUI layout, when you browse the specific subscription or playlist it could have a refresh button that would update the list of currently available videos, show a blank thumbnail with text or download the thumbnail only and overlay a red X or something that would denote that it's not available locally yet, clicking on it would offer the ability to immediately download or add it to a queue. It would also be nice to highlight videos that are local only with no online counterpart with a distinct border or something, so you can see at a glance if one of the previous downloads is no longer available online.
> 
> There are some channels I watch that occasionally don't automatically download all new content, it would be nice to know if the youtubedl list isn't picking up the video, or it picked it up and couldn't download for some reason.

This really should be its own issue, but already here I'll let you know this is something I'd love to have as well! 

Would be hella helpful to troubleshoot older and newer failed sub downloads! :D 

Great idea!

**Comment by Tzahi12345** [comment]
@jonathanm-ur Your suggestion seems like an exact copy of #254, perhaps we can keep track of it there?

**Comment by jonathanm-ur** [comment]
> @jonathanm-ur Your suggestion seems like an exact copy of #254, perhaps we can keep track of it there?

However you want to handle it is fine. Is there still no way to get a list of prospective videos as was stated in that thread? I see many threads around the interwebs asking how to get just a list, and getting answers on syntax, but I haven't tried, so I'm guessing the functionality is broken like the reject title function is broken?

**Comment by Tzahi12345** [comment]
@jonathanm-ur It's possible to simulate a download with specific args and get a list of videos, so the functionality is definitely there. It's just a matter of implementing the backend code and a GUI to support it.

**Comment by Tzahi12345** [comment]
Backend work is mostly done! Here's the UI so far (WIP):


https://user-images.githubusercontent.com/707413/128816053-e21809c1-6923-4264-a8bc-94eee432283b.mp4

**Comment by GlassedSilver** [comment]
Rick Astley,  omg you're a meme monster. >D
