### ISSUE TITLE
[BUG] MongoDB startup

### ISSUE THREAD

**Issue by blackops786187** [Tzahi12345/YoutubeDL-Material#412]
**Describe the bug**
Using the latest nightly fails to start the youtube dl docker image with mongo db. Have to wait until it falls back to local db

**To Reproduce**
Download nightly on windows docker (WSL2 backend and launch)

**Expected behavior**
Youtube dl sucessfuly starts without having to wait for fallback 

**Screenshots**
![image](https://user-images.githubusercontent.com/66162099/127738783-0382b055-1e07-4c64-866c-15ec9068d043.png)

**Environment**
- Windows 10 21H1 - Docker with WSL2 Backend

**Comment by Tzahi12345** [comment]
Can you share your docker-compose.yml and the containers you have running? MongoDB should show up in both.

**Comment by QrchackOfficial** [comment]
I've experienced the same on my Debian-based LXC container with Docker when I tried switching to nightly yesterday.

I'm also using nginx reverse proxy, so I'm accessing youtubedl-material through ytdl.daphne.io, routed through a local DNS server that redirects ytdl.daphne.io -> daphne.io (via CNAME) -> local IP (via DNS record) on the browser side. I believe this can get the mongodb stuff confused, as I specifically removed all published ports from the container and instead route it through nginx. This means both the hostname and the IP in my browser is definitely _not_ the hostname and IP of the container, or even the server running docker that the container it's in.

That said, it is working for me on latest for some reason. Had to switch back from nightly to get it working. It seems like it has lost data in the process though (videos show up in subscriptions, but not on the homepage)

**Comment by blackops786187** [comment]
Hi Tzahi,

I'm new to docker so I'm not familiar with the intricacies of the docker system.  I pulled the image down using **"docker pull tzahi12345/youtubedl-material:nightly"** and started it through the GUI. I have no other containers running

Hope this helps

**Comment by QrchackOfficial** [comment]
You probably want to use docker-compose instead, I suspect you've spinned up just this repo and not a mongodb to go with it. Using docker-compose you should get both the app and the db.

**Comment by Tzahi12345** [comment]
I just modified the config files so MongoDB is not in by default unless specified in the docker compose.

This should fix this issue for docker installs without compose.

@QrchackOfficial a backup was made of the users.json and db.json files, if you use those it should be fixed! Also, if you want to use the nightly you still can, you just need to set use_local_db to true in the `default.json` settings, and if migration already occurred, set it to false in the `db.json`. sorry the migration didn't go well for you, but it should be a relatively simple fix!

**Comment by QrchackOfficial** [comment]
@Tzahi12345 it's back, had to manually copy over entries from the diff, but the crisis is averted.

**Comment by Tzahi12345** [comment]
Oh nice!

Well I think this issue is resolved due to the changes in the default config, I'd like confirmation from @blackops786187 though, let me know if you still need help!

**Comment by martadinata666** [comment]
@Tzahi12345 seems mongodb got some issue on latest docker image, i also encountered this and use mongodb:4 as workaround. https://github.com/docker-library/mongo/issues/485

**Comment by blackops786187** [comment]
Hi Tzahi,

Looks like its resolved now. Thanks

**Comment by Tzahi12345** [comment]
Awesome, great to hear!
