### ISSUE TITLE
Add autoplay functionality for subscriptions

### ISSUE THREAD

**Issue by Tzahi12345** [Tzahi12345/YoutubeDL-Material#419]
### Discussed in https://github.com/Tzahi12345/YoutubeDL-Material/discussions/418

<div type='discussions-op-text'>

<sup>Originally posted by **modeseven** August  7, 2021</sup>
I love this project but I want to lay in bed.. and put on a subscription and have it keep playing the next video over and over? is that supported? I can't find it anywhere.</div>

We can probably do this by adding a play all button to the subscription page. If there are thousands of videos in a subscription, we may have a scaling problem, however.

**Comment by Tzahi12345** [comment]
This has been implemented in #420!

**Comment by Tzahi12345** [comment]
This new button in the subscription page makes the subscription behave like a playlist in the video player

![image](https://user-images.githubusercontent.com/707413/133674823-086e41c3-25f4-43bc-99b4-404da3c7479e.png)

**Comment by GlassedSilver** [comment]
lovely!
