### ISSUE TITLE
[BUG] Version checker in the About Panel practically has no function atm

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#421]
**Describe the bug**
The version check is meaningless for anyone on the nightly build since it will always tell you you're on the latest version as long as no new RELEASE is made. Nightly users (which at this point hopefully is everyone :P ) are really left in the dust here, because there's no way to tell which nightly you're on.

**To Reproduce**
1. Go to 'About'
2. Check the installed version as listed in "Installation details"

**Expected behavior**
For anyone who isn't on the release, but nightly channel to actually check if you're on the latest nightly build.

It would be extremely helpful to reflect:

- which build channel are you on: e.g. RELEASE, nightly, anything else that may ever get added
- Tell which version of nightly are we on. It should have the commit ID and the date shown
- Bonus: tell the youtube-dl version (on that note, also which fork is used) and when it has last been updated by ytdl-m! :)
- Since this is called the Installation details section maybe also add a few bits of information like whether the build runs on docker and if so how much MEM, CPU and disk space are available. Also, some OS details.
This could be really helpful in telling people to "just copy the details from the Installation details section in about", since we can display whatever meaningful information we might need to troubleshoot an installation. :)

**Environment**
- YoutubeDL-Material version
- Docker tag: <tag> (optional)

Not relevant atm, because this is the case for every build so far. :) Would love to just copy pasta something in here though. :P 

**Additional context**
n/a

**Comment by Tzahi12345** [comment]
Forgot this had an actual issue associated with it, if you click on about you should see version info now! [See commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/58a0dc4afe9c5150c5ab6a3bdbf86967a05b5d22)

**Comment by GlassedSilver** [comment]
Any thoughts on possibly also adding these two aspects?

- Bonus: tell the youtube-dl version (on that note, also which fork is used) and when it has last been updated by ytdl-m! :)
- Since this is called the Installation details section maybe also add a few bits of information like whether the build runs on docker and if so how much MEM, CPU and disk space are available. Also, some OS details.
