### ISSUE TITLE
[BUG] Unable to have both checkbox enabled for custom arg and custom output

### ISSUE THREAD

**Issue by komawoyo** [Tzahi12345/YoutubeDL-Material#439]
**Describe the bug**
Unable to have both checkbox enabled for custom arg and custom output

**To Reproduce**
1. Enable "Allow Advanced Download" in Settings -> Advanced
2. On main page, set custom args and custom output and try to enable both

**Expected behavior**
Both checkbox should be allowed to be enabled. In the Settings -> Downloads, this is allowed as it should

**Screenshots**
![image](https://user-images.githubusercontent.com/18315233/132236719-4e917f50-921f-4609-8c81-298a409832dd.png)

**Environment**
- YoutubeDL-Material version
- Docker tag: latest (as of today 9/6/21)

**Comment by GlassedSilver** [comment]
Yeah this seems like something that should be possible. Can't really tell if this may however be a deliberate limitation, @Tzahi12345?

In any case, if you need a work-around (just in case you haven't tried this yourself yet) I think you should be able to copy and paste the relevant simulated command bit for your output with its parameters to the Custom args field.

In your example:
copy `-o video/s01e02.mp4` into Custom args along with the args you want to pass.

**Comment by Tzahi12345** [comment]
It actually is intentional, but I honestly had to check as it's been 2 years since that code has been touched.

Basically, custom args replaces all of the args with whatever you want. There's a good chance it won't even play nice with the UI, which is why it's hidden in the advanced tab anyways.

The reason for this restriction is that if you those custom args enabled, it'll be the only args running. Of course we can do a check to see if custom output was set and add it on, but if you're willing to put in your own args anyways, why not use the `-o` arg in the custom arg input?

I'm down to add in that check though if you'd like! If so I'll convert this into a feature request.

**Comment by GlassedSilver** [comment]
> It actually is intentional, but I honestly had to check as it's been 2 years since that code has been touched.
> 
> Basically, custom args replaces all of the args with whatever you want. There's a good chance it won't even play nice with the UI, which is why it's hidden in the advanced tab anyways.
> 
> The reason for this restriction is that if you those custom args enabled, it'll be the only args running. Of course we can do a check to see if custom output was set and add it on, but if you're willing to put in your own args anyways, why not use the `-o` arg in the custom arg input?
> 
> I'm down to add in that check though if you'd like! If so I'll convert this into a feature request.
> 
> EDIT:
> 
> Here's another thought since I saw you were kinda using the custom arg input as if it was going to add it to the normal set of args: maybe we can add a checkbox that says `replace all args` or something like that. That way you can use it to add one-off args or do a custom command.

you mean like give a choice to run the args passed ADDITIONALLY to the global ones and alternatively INSTEAD OF. Right?

That'd be awesome. Especially for testing/troubleshooting purposes.

**Comment by Tzahi12345** [comment]
Implemented! [See commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/75fc09ed99a4ffd0ecc0333eb23232db43a90d43)

I removed the logic preventing both from being enabled, the simulated output should give enough feedback so the user knows what's going on. Thanks for the feedback @komawoyo!

**Comment by GlassedSilver** [comment]
Maybe we could collission check the arguments from the simulated output. As in:

checks for double arguments as well as args that counter each other, e.g. all subs versus a defined set of subs.
or like codecs.

idk, you tell me. Probably not something that would be very high on the priority list, a bit like a late "nice to have" idea.
