### ISSUE TITLE
Translation Question

### ISSUE THREAD

**Issue by u0a** [Tzahi12345/YoutubeDL-Material#450]
Hi
I love this program so much that I translated it into Korean on the website. However, I have no idea what the picture attached below means. I have completed the translation of all parts except that, so use it if you think it's okay.
Thanks.
<img width="1054" alt="스크린샷 2021-09-17 13 09 55" src="https://user-images.githubusercontent.com/42744904/133729629-5faf0414-d1ff-430c-bd8e-7cd4ac82a90d.png">

**Comment by Tzahi12345** [comment]
Thanks for helping translate!

You can follow this syntax done in Spanish:

```
{VAR_SELECT, select, true {Cerrar} false {Cancelar} other {Otro} }
```


Basically just put the translation in the curly braces, for example `Close` in Spanish is `Cerrar`.

**Comment by u0a** [comment]
Oh, I got it and all done :)

**Comment by GlassedSilver** [comment]
Korean? That's mighty cool!! Thank you so much for that, it's truly appreciated!

Definitely one of the languages pretty high on my "want to learn" list!

감사 해요! 

PS: I admit I used Google Translate. :P

**Comment by u0a** [comment]
> Korean? That's mighty cool!! Thank you so much for that, it's truly appreciated!
> 
> Definitely one of the languages pretty high on my "want to learn" list!
> 
> 감사 해요!
> 
> PS: I admit I used Google Translate. :P

Haha, Cool!
I wanna be good at coding like you guys.
If there's anything you need to translate into Korean, just let me know anytime. :)

**Comment by Tzahi12345** [comment]
Added Korean translations! Thank you so much for the contribution, it's very appreciated :)

**Comment by u0a** [comment]
> Added Korean translations! Thank you so much for the contribution, it's very appreciated :)

Thanks a lot but I couldn't find Korean on the settings. Do I have to wait a little bit?

**Comment by Tzahi12345** [comment]
Yup! In about an hour or so you can pull the latest `nightly` and it'll show up in this dropdown:

![image](https://user-images.githubusercontent.com/707413/134453200-ae7e320f-b662-417d-826d-4b5e8ef593fe.png)

**Comment by u0a** [comment]
Thanks!
