### ISSUE TITLE
[BUG] Unable to Access the WebUI After Last Night

### ISSUE THREAD

**Issue by rockbo842** [Tzahi12345/YoutubeDL-Material#452]
I am unable to access the webUI after the lastest nightly update.

I have Unraid set to update automatically and was notified this morning that the nightly was updated.  Since then, I have not been able to get into the webUI.  I noticed that the address for the webUI changed from http://[IP]:[PORT:17442]/#/home in the previous version I had installed to http://[IP]:[PORT:17442]/.  Even so, I'm still not able to get in even when using http://[IP]:[PORT:17442]/.

Note that I am running the container through binhex-delugevpn for VPN purposes.  It worked prior to the update.  Other containers that are also running traffic through binhex-delugevpn are operating as normal.

Your thoughts?

**Environment**
- YoutubeDL-Material nightly
- Unraid 6.9.2

**Comment by jonathanm-ur** [comment]
First start after the update, same thing for me, repeating crashes never resolving. Restarted the container, all good.

What does the container log look like?

**Comment by rockbo842** [comment]
Thanks for the reply.  I tried restarting but no dice.

Here's the log:

[33mwarn[39m: --minUptime not set. Defaulting to: 1000ms
[33mwarn[39m: --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
internal/modules/cjs/loader.js:818
throw err;
^

Error: Cannot find module 'rxjs'
Require stack:
- /app/db.js
- /app/app.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/app/db.js:12:29)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/app/app.js:13:16)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/app/db.js', '/app/app.js' ]
}
error: Forever detected script exited with code: 1

**Comment by GlassedSilver** [comment]
What's your log say?

I have a STRONG suspicion you're on the second-latest nightly build which is known to not work, basically regardless of which kind of OS you run it on in Docker.

Also refer to #451 and for completion's sake #449 where we discovered this bug as well.

I'd suggest you re-pull the image. Either you check for updates and apply that update or if it's stuck not getting the latest nightly you can delete the container, check that you want to delete the image as well (don't worry, all your settings, your app data, etc will not be lost if you don't run any "Clean App Data" script between now and: the re-installation of the container.

For that scroll all the way down in your docker list and hit "Add Container". Then select YoutubeDL-Material from the list and it will auto-populate with all the settings as they were. Nothing is lost. :)

![image](https://user-images.githubusercontent.com/1912133/133854723-850b101c-dd84-4dca-8a92-935385d8b277.png)

This should not be necessary though, just try checking for updates first. :)

**Comment by rockbo842** [comment]
> 
> 
> What's your log say?
> 
> I have a STRONG suspicion you're on the second-latest nightly build which is known to not work, basically regardless of which kind of OS you run it on in Docker.
> 
> Also refer to #451 and for completion's sake #449 where we discovered this bug as well.
> 
> I'd suggest you re-pull the image. Either you check for updates and apply that update or if it's stuck not getting the latest nightly you can delete the container, check that you want to delete the image as well (don't worry, all your settings, your app data, etc will not be lost if you don't run any "Clean App Data" script between now and: the re-installation of the container.
> 
> For that scroll all the way down in your docker list and hit "Add Container". Then select YoutubeDL-Material from the list and it will auto-populate with all the settings as they were. Nothing is lost. :)
> 
> ![image](https://user-images.githubusercontent.com/1912133/133854723-850b101c-dd84-4dca-8a92-935385d8b277.png)
> 
> This should not be necessary though, just try checking for updates first. :)

Success!  I'm in=)  Thanks for the help!

**Comment by GlassedSilver** [comment]
Glad I could help! Pinned this issue and added a little bit more illustration for anyone else who might need it. :)

Enjoy the latest build. #420 really is quite the massive back-end change and so far runs beautifully on my end!

**Comment by rockbo842** [comment]
I really like the new progress window for downloads!
