### ISSUE TITLE
[BUG] Home thumbnails play different (random?) video instead of what's pictured.

### ISSUE THREAD

**Issue by jonathanm-ur** [Tzahi12345/YoutubeDL-Material#453]
**Describe the bug**
All the latest downloads on my home page are subscription based. When you click on one of them (any? tested top 5) it begins playing a seemingly random video from that subscription. Scrolling down on the player page reveals it's playing the top video in the list that is on the player page.
**To Reproduce**
1. Go to 'Home'
2. Click on 'A video downloaded from a subscription'
3. Watch it play a different video from that subscription

**Expected behavior**
Play selected video, not a random one from the channel.

**Environment**
latest nightly as of this post

Clicking on the videos in the subscription page itself works properly.

**Comment by arithxp** [comment]
same here.

**Comment by Tzahi12345** [comment]
Oh wow I thought this was for the thumbnail previews, not the actual video. That's my bad, I've gone ahead and fixed the issue ([see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/8aa354ac245c7862ebac238b974e9d245ebc6cdb)). Nightly should be updated shortly!
