### ISSUE TITLE
[BUG] Subscription arguments no longer beeing used

### ISSUE THREAD

**Issue by DonDawsy** [Tzahi12345/YoutubeDL-Material#457]
After the latest update it seems like the custom arguments for subscriptions are not being used. I have three arguments in all my subscriptions: -f bestvideo[ext=mp4][vcodec!*=av01]+bestaudio[ext=m4a], --add-metadata and --embed-thumbnail.

All of these worked perfectly up until the last day or so. I want to download in h264 1080p only, and embed thumbnail and metadata for Plex. Not sure what changed in the latest update. In the logs it checks for new videos with the arguments, but when it actually downloads the file, the default arguments are being used.

I am using the latest YouTube-dl Material version on Unraid with the “nightly” tag.

**Comment by Tzahi12345** [comment]
Oops, left out one line of code. Should be fixed now! [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/759637c1cfa53d1304dd9afd72c221509fe6a278).
