### ISSUE TITLE
[BUG] If the file name is long, the video cannot be downloaded.

### ISSUE THREAD

**Issue by arithxp** [Tzahi12345/YoutubeDL-Material#459]
**Describe the bug**
I'm not sure, but it seems that the download fails if the file name is long.

**To Reproduce**
1. manual download "https://www.youtube.com/watch?v=rGwr2WiPtm8"
2. check log. "ERROR: Cannot write video metadata to JSON file video/집들이 브이로그│이사 축하 & 구독자 30만 축하 계란한판 케이크│친구들이랑 집에서 놀기│오동통면∙야식 라면∙김치전∙미역국∙청국장∙집밥│집들이 선물_무선 방역기,소독기.info.json"

**Environment**
- nightly docker

**Additional context**
There are many failure lists in the Downloads tab. What they have in common is that the file names are long.

**Comment by GlassedSilver** [comment]
What's your host system?

**Comment by arithxp** [comment]
> 
> 
> What's your host system?

I have docker installed on ubuntu and synology mounted.

**Comment by GlassedSilver** [comment]
> 
> 
> > What's your host system?
> 
> I have docker installed on ubuntu and synology mounted.

I think this blog entry might be relevant to your issue here:

https://mach3.wwco.com/~wls/ramblings/2020/05/03/synology-filename-too-long/

I don't have a Synology NAS myself, but that page might give you valuable hints, because this strikes me as a host problem.

**Comment by arithxp** [comment]
> 
> 
> > > What's your host system?
> > 
> > 
> > I have docker installed on ubuntu and synology mounted.
> 
> I think this blog entry might be relevant to your issue here:
> 
> https://mach3.wwco.com/~wls/ramblings/2020/05/03/synology-filename-too-long/
> 
> I don't have a Synology NAS myself, but that page might give you valuable hints, because this strikes me as a host problem.

yes. synology's file name length rules are too tight. But it also causes the same problem in Ubuntu. (ubuntu server 20.04 lts)
![test11](https://user-images.githubusercontent.com/6009737/134644313-fa4c0ab0-3cf7-46d0-b078-32bde0442f3e.png)
I wish there was an option to shorten the file name if it is too long.

**Comment by GlassedSilver** [comment]
> 
> 
> > > > What's your host system?
> > > 
> > > 
> > > I have docker installed on ubuntu and synology mounted.
> > 
> > 
> > I think this blog entry might be relevant to your issue here:
> > https://mach3.wwco.com/~wls/ramblings/2020/05/03/synology-filename-too-long/
> > I don't have a Synology NAS myself, but that page might give you valuable hints, because this strikes me as a host problem.
> 
> yes. synology's file name length rules are too tight. But it also causes the same problem in Ubuntu.
> ![test11](https://user-images.githubusercontent.com/6009737/134662353-a5bd691c-6c1f-4bbc-8d6f-d34cf33b1958.png)
> I wish there was an option to shorten the file name if it is too long.

I think I found a solution for you.

This is straight from the yt-dlp docs:

> In some cases, you don't want special characters such as 中, spaces, or &, such as when transferring the downloaded filename to a Windows system or the filename through an 8bit-unsafe channel. In these cases, add the `--restrict-filenames` flag to get a shorter title

Source: https://github.com/yt-dlp/yt-dlp#output-template (still gotta scroll a bit for this part)

This may generate filenames that are undesirable, but I'm not aware of anything else you could try off the top of my head.
Maybe @Tzahi12345 can fill in, but this is what I could think of so far.

Alternatively you could consider deploying to a different host file-system.

This option is also available on classic youtube-dl (the default agent at least as of now, YoutubeDL-Material will switch the default to yt-dlp soon.)
Should also be available on yt-dlc.

**Comment by GlassedSilver** [comment]
Found more:

```
--restrict-filenames             Restrict filenames to only ASCII
                                 characters, and avoid "&" and spaces in
                                 filenames
--no-restrict-filenames          Allow Unicode characters, "&" and spaces in
                                 filenames (default)
--windows-filenames              Force filenames to be windows compatible
--no-windows-filenames           Make filenames windows compatible only if
                                 using windows (default)
--trim-filenames LENGTH          Limit the filename length (excluding
                                 extension) to the specified number of
                                 characters
```

Source: https://github.com/yt-dlp/yt-dlp#filesystem-options

**Comment by arithxp** [comment]
> --trim-filenames

thank you for the information. 👍 
I'll try the trim option. If it works, I'll close the issue.

**Comment by arithxp** [comment]
'--trim-filenames'
It works fine.
I don't know if it's an emoji or Unicode problem, but I had to limit it to 60 characters.

**Comment by GlassedSilver** [comment]
Since you use this parameter, I want to ask for your experience with this.

If you use the trim option, does it truncate the title of the video title only or anything else that you append to the filename as well?

For example, I use a logic like this:

`date - video title - video ID`

Would it truncate the video title only or will the video ID fall victim first? I know I could try, but I don't have a test environment set up atm and don't want to add clutter to my library :P

**Comment by GlassedSilver** [comment]
I think I found a better solution now, I've set up a subscription with notoriously long title names for their videos using this logic **now**:
`%(uploader)s [%(channel_id)s]/%(upload_date)s - %(title)200s [%(id)s]`

**before** I used the title tag without the number like so:
`%(uploader)s [%(channel_id)s]/%(upload_date)s - %(title)s [%(id)s]`

Found this suggestion in here:
https://github.com/yt-dlp/yt-dlp/issues/1837#issuecomment-981907118

This should make sure that the relevant bit is truncated to this length, not sure if this is fully unicode aware, but I'll see. If it's not then I guess I'll just truncate the Japanese channels that rely on Unicode with harsher limits and keep the Western channels at a higher limit. :)
