### ISSUE TITLE
Startup messages

### ISSUE THREAD

**Issue by jonathanm-ur** [Tzahi12345/YoutubeDL-Material#462]
Is this normal for now? I see this every time the container starts.
```
(node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
```

**Comment by dejan995** [comment]
I saw those in my logs too.
Here is what I found on [StackOverflow](https://stackoverflow.com/questions/64713565/accessing-non-existent-property-padlevels-of-module-exports-inside-circular-de/65805503).

Here is a little excrept from the link above:

> exports inside circular dependency

> 👆 This phrase gave hint to solve the same issue for me, it seems that newer NodeJS versions no longer allows circular dependencies.

> Eg - There are two files - FileA.js, FileB.js

> Where FileA.js has
const FileB = require("FileB");

> and FileB.js has
const FileA = require("FileA");

> After removing one of these circular dependencies by modifying either FileA.js or FileB.js, it was solved!

I'm using the Docker Version and can confirm that it has NodeJS v14.17.6.
If you are running the standalone version you just need to roll back to NodeJS v12 and the errors should dissapear.
If you are on Docker, like me, you will need to build the Docker image yourself. You need to replace the alpine image that is used for the FROM command, from latest to v.3.12. This is the latest alpine version that has NodeJS v12.

**Comment by Tzahi12345** [comment]
So I did look into this and @dejan995 you are right in that it's a node.js issue, but it only happens when using Winston (the logging module we use) and ForeverJS (we used this to auto start the server with the restart button in the UI).

The solution I came up with is to switch from ForeverJS to PM2 as the former has been deprecated in favor of the latter.

I'm still doing some testing on the code I have written so far but it's looking good. In the meantime it is a harmless message that doesn't affect functionality, thankfully.

**Comment by dejan995** [comment]
@Tzahi12345 This lines up with the second answer from the StackOverflow post:

> After I updated my node from version 12 to version 14, I also faced the same warning. In my case, this warning was coming due to an older version of surge. after updating surge, the warning was gone.

Looks like NodeJS v14 throws this error when using old versions of a software and in our case also deprecated.

Anyway, I went ahead and build the Docker Image using Alpine v3.12, out of curiosity 😁.
The error message is gone, so this definetly confirms that it is a issue with NodeJS.

@jonathanm-ur Please don't do this. You will be effectivly running old software that most likely has bugs that were patched in newer versions of NodeJS.
Best bet is to wait for the official switch from ForeverJS to PM2. As @Tzahi12345 said, this error does not break the app, feel free to ignore it.
