### ISSUE TITLE
[BUG] (node:19) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'users/admin/subscriptions/playlists/[playlist]/archives/archive_video.txt'

### ISSUE THREAD

**Issue by tyzbit** [Tzahi12345/YoutubeDL-Material#463]
**Describe the bug**
When downloading videos from a playlist, this error is thrown:

```
(node:19) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'users/admin/subscriptions/playlists/Skate 3 Compilations/archives/archive_video.txt'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1524:35)
    at Object.appendFileSync (fs.js:1563:6)
    at /app/downloader.js:350:24
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

Checking that folder only a `merged_video.txt` exists (with some content), but no `archive_video.txt` file exists.

**To Reproduce**
1. Enable archive functionality
2. Save a playlist
3. Observe the error

**Expected behavior**
Youtube-DL Material downloads the videos from the playlist without error

**Screenshots**
N/A 

**Environment**
- YoutubeDL-Material version:  `nightly`
- Docker tag: `latest` (optional)

**Additional context**
I doubt it specific to one playlist, but this is the playlist I was using:
https://www.youtube.com/playlist?list=PL2Ub1rILTl2pkRKXv4_f75mggWw_Fe-we

**Comment by Tzahi12345** [comment]
This should be fixed in the latest nightly!

I couldn't replicate the error but the logic for determining the path was done twice, but slightly differently. I combined it so this shouldn't happen again.

[See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/5dd48035fbfac1752aa0d577194b49cfbddbb41a). Thanks for the bug report!

**Comment by tyzbit** [comment]
Confirmed, the error is no longer seen with the latest nightly.  Thanks a lot for your hard work @Tzahi12345!
