### ISSUE TITLE
[BUG] Weblate locked.

### ISSUE THREAD

**Issue by u0a** [Tzahi12345/YoutubeDL-Material#464]
Hello.
I tried to modify some strange things in my translation, but the weblate was locked due to some code thing's error.
It seems like there is a problem in the Korean side, I don't know what's happening, can you fix it?
<img width="1440" alt="스크린샷 2021-09-27 14 53 11" src="https://user-images.githubusercontent.com/42744904/134853086-214a55ee-53f9-4554-8627-c3eb9a13b178.png">

**Comment by Tzahi12345** [comment]
My bad didn't realize it got locked, it's unlocked now!
