### ISSUE TITLE
Docker CLI Support

### ISSUE THREAD

**Issue by micpro7** [Tzahi12345/YoutubeDL-Material#465]
is it possible for you to included regular Docker Command line support and not just Docker Compose. the platform im using doesn't support installation of docker compose 

thanks

**Comment by martadinata666** [comment]
```docker run -d
--name=ytdl_material
--env ALLOW_CONFIG_MUTATIONS: 'true'
-v ./appdata:/app/appdata
-v ./audio:/app/audio
-v ./video:/app/video
-v ./subscriptions:/app/subscriptions
-v ./users:/app/users
-p 8998:17442
--restart unless-stopped
tzahi12345/youtubedl-material:latest```

**Comment by dejan995** [comment]
A slightly different approach from me.
Run it like this:
```bash
docker run -d \
--name=ytdl_material \
-p 8998:17442 \
-e UID=1000 \
-e GID=1000 \
-v /full/path/to/appdata:/app/appdata \
-v /full/path/to/audio:/app/audio \
-v /full/path/to/video:/app/video \
-v /full/path/to/subscriptions:/app/subscriptions \
-v /full/path/to/users:/app/users \
--restart unless-stopped \
tzahi12345/youtubedl-material:nightly
```
Not sure what ALLOW_CONFIG_MUTATIONS does, but I'm running my instance without it for about 3-4 months. No issues.
@Tzahi12345 Maybe you can tell us what this variable does? There is nothing about it in the README.

@micpro7 Both UID and GID have to be setup properly to avoid any file permission errors.
By default they are set to 1000, same as the example provided.
Your values are most likelly the same, but just in case you can check with this command: ``id username``. You need to replace username with the username on the Docker Host that you are using. You should get something like this:

``uid=1000(dejan) gid=1000(dejan) groups=1000(dejan),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lxd)``

If you get different values you will need to change them before running the ``docker run`` command.

For the volumes I would suggest using full paths because in my experience ``docker run`` is a bit stupid when dealing with variable paths, like the ones starting with **"./"**.

Also, I added the ``nightly`` tag to the image, per the instuctions on the README page.

> NOTE: It is currently recommended that you use the nightly tag on Docker. To do so, simply update the docker-compose.yml image field so that it points to tzahi12345/youtubedl-material:nightly.

**Comment by Tzahi12345** [comment]
>Not sure what ALLOW_CONFIG_MUTATIONS does, but I'm running my instance without it for about 3-4 months. No issues.
@Tzahi12345 Maybe you can tell us what this variable does? There is nothing about it in the README.

This led me to a two hour tangent where I created a wiki for environment variables, but I realized I also needed to make one for the config as well. So thank you for giving me the motivation :)

You can find the explanation here:

https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Environment-Variables

But you're right in that it's probably not needed, I don't use it in my local dev instance. Apparently not having it caused issues 2 years ago when I first tested Docker support.

**Comment by micpro7** [comment]
thanks for your suggestions guys 


the container is up and running but when I paste in url's and click download it fails 

what am I doing wrong ?

docker run -d \
--name=ytdl_material \
-e UID=1000 \
-e GID=1000 \
-v /overlay/upper/home/mike/Config/Youtube:/app/appdata \
-v /overlay/upper/home/mike/Youtube:/app/audio \
-v /overlay/upper/home/mike/Youtube:/app/video \
-v /overlay/upper/home/mike/Config/Youtube:/app/subscriptions \
-v /overlay/upper/home/mike/Config/Youtube:/app/users \
-p 8998:17442 \
--restart unless-stopped \
tzahi12345/youtubedl-material:nightly


I have changed ownership to mike user

I paste in urls like http/https/www 
I have gone to advanced and tried all 3 downloaders with a server restart
also created and inserted my API Key in
all seem to fail

**Comment by Tzahi12345** [comment]
@micpro7 do you have logs you can post with the error? May help track down what's going on

**Comment by micpro7** [comment]
2021-09-28T15:35:19.974Z ERROR: Error while retrieving info on video with URL https://www.youtube.com/watch?v=ASlVCJVmJ3Y with the following message: Error: Command failed with exit code 1: /app/node_modules/youtube-dl/bin/youtube-dl -o video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail --dump-json http://www.youtube.com/watch?v=ASlVCJVmJ3Y
WARNING: Unable to download webpage: <urlopen error [Errno 99] Address not available>
ERROR: Unable to download API page: <urlopen error [Errno 111] Connection refused> (caused by URLError(error(111, 'Connection refused'),))

**Comment by dejan995** [comment]
@micpro7 This error usually suggest a internet connection problem, which I have no idea how it might have happend.
I have added ```--network="bridge"```, to make sure the container gets attached to the network and also switched the port to be the same as inside the container, though I doubt the port has anything to do with this.

Clear out the ```/overlay/upper/home/mike/Config/Youtube``` folder before you try this, just to get a fresh install and not cause any conflicts.

```bash
docker run -d
--name=ytdl_material
-e UID=1000
-e GID=1000
-v /overlay/upper/home/mike/Config/Youtube:/app/appdata
-v /overlay/upper/home/mike/Youtube:/app/audio
-v /overlay/upper/home/mike/Youtube:/app/video
-v /overlay/upper/home/mike/Config/Youtube:/app/subscriptions
-v /overlay/upper/home/mike/Config/Youtube:/app/users
-p 17442:17442
--restart unless-stopped
tzahi12345/youtubedl-material:nightly```

**Comment by GlassedSilver** [comment]
I take it this is not an issue anymore or rather not a specific Docker CLI issue. (feel free to correct me if I'm wrong, re-opening this at any point can be done :) )

If it's not a Docker CLI issue feel free to open a new issue (make if you run into more issues to check it hasn't been submitted already. Even closed issues may be relevant again, then we re-open that issue instead)
