### ISSUE TITLE
[BUG] Error message when downloading from the homepage

### ISSUE THREAD

**Issue by dejan995** [Tzahi12345/YoutubeDL-Material#470]
Error Message when downloading from the homepage.
It doesn't break the download. The download is sucessfull.
It only happens when you have a different quality selected, other then the MAX option.
The error does not appear when MAX is selected.

```
2021-09-29T21:15:59.754Z VERBOSE: youtube-dl args being used: -o,video/%(title)s.mp4,--write-info-json,--print-json,-f,400+140,--merge-output-format,mp4,--write-thumbnail,
2021-09-29T21:16:15.827Z VERBOSE: Downloading 1d7c98f1-e836-4595-929a-813dba69def9,
TypeError: Cannot read property 'id' of undefined,
    at processTicksAndRejections (internal/process/task_queues.js:95:5),
    at /app/app.js:1759:89
```
This is probably due to some leftover code after [this](https://github.com/Tzahi12345/YoutubeDL-Material/commit/84fa425a993577ccbe6c3b05c8187500d87a7ef8) commit, to fix issue #438.

**Comment by Tzahi12345** [comment]
Can you provide the URL and resolution you chose? I'm having trouble reproducing this.

**Comment by dejan995** [comment]
[https://www.youtube.com/watch?v=ykkRcmAZAzo](url)
Resoluion is 1440p.
I will clear out the appdata folder and try again with a fresh install.

**Comment by Tzahi12345** [comment]
Ok I'll go ahead and close it but if it appears again let me know and I'll reopen!
