### ISSUE TITLE
[BUG] Cannot select language.

### ISSUE THREAD

**Issue by u0a** [Tzahi12345/YoutubeDL-Material#472]
I'm currently using nightly.
I can only see English, British English, Norsk bokmål in that dropdown.
<img width="1440" alt="스크린샷 2021-09-30 13 56 01" src="https://user-images.githubusercontent.com/42744904/135390007-c22bf343-de47-4593-91b6-f79f0c5811cd.png">

**Comment by Tzahi12345** [comment]
Oops, there was a bug in a recent update I did where translations got processed at build time. It's fixed now, [see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/a7f1f1eb8ecce1e0f145c9a6353b1f9c6d622428).
