### ISSUE TITLE
[BUG] pm2 haven't write permissions in docker 

### ISSUE THREAD

**Issue by ferboiar** [Tzahi12345/YoutubeDL-Material#474]
**Describe the bug**
Although UID and GID env variables are set correctly pm2 doesn't have permission to write since yesterday:
```
2021-09-30T08: 14: 27.733653307Z Error: EACCES: permission denied, mkdir '/.pm2/logs'
2021-09-30T08: 14: 27.857756953Z Error: EACCES: permission denied, mkdir '/.pm2/pids'
2021-09-30T08: 14: 27.858136100Z Error: ENOENT: no such file or directory, open '/.pm2/module_conf.json'
2021-09-30T08: 14: 27.858469020Z Error: EACCES: permission denied, mkdir '/.pm2/modules'
```
and so on. 

So the app doesn't work.

**To Reproduce**
Start the container

**Expected behavior**
A working youtube-dl-material container.

**Screenshots**
here you can see UID and GID env vars:
![imagen](https://user-images.githubusercontent.com/30288888/135423342-0fe39662-ab21-482c-b8af-8c8bab9b5626.png)

and from container shell:
```
/app # env
USER=youtube
NO_UPDATE_NOTIFIER=true
HOSTNAME=youtubedl
SHLVL=1
HOME=/root
PGID=100
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GID=100
UID=1026
PUID=1026
ALLOW_CONFIG_MUTATIONS=true
PWD=/app
```

```
/app # ps
PID   USER     TIME  COMMAND
    1 1026     36:05 node /usr/local/bin/pm2-runtime pm2.config.js
```
**Environment**
- YoutubeDL-Material version: 
```
     ID:  | sha256:b7f3308cfb5250bdb0460700b93e932bcf5145fa3e1b8cd02909183b35d08641
     Size: 319.9 MB
     Created: 2021-09-29 08:50:11
     Build: Docker on linux, amd64
```
```
/app # more version.json 
{"type": "docker", "tag": "nightly", "commit": "f0c3837", "date": "2021-09-29"}/app #
```
- Docker tag: <tag> (optional)

**Additional context**

**Comment by dejan995** [comment]
Can you run this command on the Docker Host machine, not inside the container.

```bash
id username
```

Replace username with the username you are using on the Docker Host.

This is the response I got:

```bash
uid=1000(dejan) gid=1000(dejan) groups=1000(dejan),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lxd)
```

So my enviornment variables in Portainer are set as:
```yaml
UID: 1000
GID: 1000
```

**The values put as variables must match the values of the user on the Docker Host macnine, NOT the values of the user inside the container.**

Think of this as mapping a docker volume. Docker is essentially connecting the user on the host and the user in the container, so that when the container user interacts with the host filesystem, the host will think that the host user is doing the changes and won't cause issues like the one you got.

**Comment by ferboiar** [comment]
uid 1026 is my root user:
```
ferboiar@nas:~$ id ferboiar
uid=1026(ferboiar) gid=100(users) groups=100(users),101(administrators)
```

**Comment by dejan995** [comment]
What system are you using? That is a wierd output for that command.

Can you also, inside the container, go to the /home/youtube folder and do a ``ls -la`` on it.
You should see something like this:
```bash
/home/youtube # ls -la
total 20
drwxr-sr-x    1 youtube  youtube       4096 Sep 30 08:59 .
drwxr-xr-x    1 root     root          4096 Sep 30 05:30 ..
drwxr-sr-x    3 youtube  youtube       4096 Sep 30 08:59 .cache
drwxr-sr-x    5 youtube  youtube       4096 Sep 30 10:07 .pm2
```

We need to clear up if Docker is doing something stupid or the app needs a fix.

**Comment by ferboiar** [comment]
> 
> What system are you using? That is a wierd output for that command.

Synology NAS

> 
> Can you also, inside the container, go to the /home/youtube folder and do a `ls -la` on it. You should see something like this:
> 
> ```shell
> /home/youtube # ls -la
> total 20
> drwxr-sr-x    1 youtube  youtube       4096 Sep 30 08:59 .
> drwxr-xr-x    1 root     root          4096 Sep 30 05:30 ..
> drwxr-sr-x    3 youtube  youtube       4096 Sep 30 08:59 .cache
> drwxr-sr-x    5 youtube  youtube       4096 Sep 30 10:07 .pm2
> ```
> 
> We need to clear up if Docker is doing something stupid or the app needs a fix.
```
/home/youtube # ls -la
total 0
drwxr-sr-x    1 youtube  youtube          0 Sep 30 05:30 .
drwxr-xr-x    1 root     root            14 Sep 30 05:30 ..
/home/youtube # 
```
I don't know where the app is trying to write, but according to the error log:
```
Error: EACCES: permission denied, mkdir '/.pm2/logs'
```
it seems that it is trying to write to /.pm2/ instead of /home/youtube/.pm2/ 
> 
> **EDIT:** Can you also try removing the PUID and PGID variables from the container in Portainer. The app needs only UID and GID. It may be that having both causes conflicts, not 100% sure though.

done:
```
/app # env
USER=youtube
NO_UPDATE_NOTIFIER=true
HOSTNAME=youtubedl
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GID=100
UID=1026
PWD=/app
```

**Comment by Tzahi12345** [comment]
Currently on my phone but what I suspect is happening is PM2 uses the `HOME` environment variable for the path to logs and Docker isn't happy that it's trying to write to the root directory. Can you try setting the `PM2_HOME` environment variable to `/app/pm2` or something like that? Looking thru the source code for pm2 that seems to take priority over `HOME`

**Comment by ferboiar** [comment]
solved! Thank you @Tzahi12345. `PM2_HOME` env var do the trick:
```
/app # env
USER=youtube
NO_UPDATE_NOTIFIER=true
HOSTNAME=youtubedl01
SHLVL=1
HOME=/root
PM2_HOME=/app/.pm2
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GID=100
UID=1026
PWD=/app
/app # ls -la /app/.pm2
total 12
drwxr-xr-x    1 1026     users          118 Oct  1 06:47 .
drwxr-xr-x    1 1026     users          570 Oct  1 06:47 ..
drwxr-xr-x    1 1026     users            0 Oct  1 06:47 logs
-rw-r--r--    1 1026     users            2 Oct  1 06:47 module_conf.json
drwxr-xr-x    1 1026     users            0 Oct  1 06:47 modules
drwxr-xr-x    1 1026     users           48 Oct  1 06:47 pids
-rw-r--r--    1 1026     users            1 Oct  1 06:47 pm2.pid
srwxrwxr-x    1 1026     users            0 Oct  1 06:47 pub.sock
srwxrwxr-x    1 1026     users            0 Oct  1 06:47 rpc.sock
-rw-r--r--    1 1026     users           13 Oct  1 06:47 touch
/app #
```

**Comment by Tzahi12345** [comment]
Cool! I updated the Docker file so this shouldn't happen again, [see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/45be270b6f3d85c75b52f30ea6c7f0cee068c4f8).
