### ISSUE TITLE
[BUG] --emdeb-thumbnail gets auto-removed for video files

### ISSUE THREAD

**Issue by pngmn** [Tzahi12345/YoutubeDL-Material#482]
**Describe the bug**
When using custom args with --embed-thumbnail the argument gets automatically removed. When checking 'only audio' the arg stays.

**To Reproduce**
1. Click advanced and check 'Use custom args'
2. Add --embed-thumbnail to custom args
3. The argument doesn't show up in the command preview
4. Click 'only audio'
5. The argument is shown in the command preview

**Expected behavior**
Argument should not be removed.

**Environment**
Installation type: docker  
Docker tag: nightly  
Commit hash: 88cc8d0  
Build date: 2021-10-01

**Comment by GlassedSilver** [comment]
> I guess this is the reason why it behaves like that
> 
> https://github.com/Tzahi12345/YoutubeDL-Material/blob/84fa425a993577ccbe6c3b05c8187500d87a7ef8/backend/downloader.js#L572
> 
> Is there a reason why it is audio only?

If I'm not mistaken embedding the thumbnail has been very finicky on ytdl. Not sure if the yt-dlp backend can handle this better, feel free to check their docs and their issue tracker for this. YTDL-M is basically bound to the same limitations and workflow limits with embedding stuff into the video file as the ytdl binary used itself. We don't do additional magic in this regard. :)
