### ISSUE TITLE
[BUG] Initiate download from CLI

### ISSUE THREAD

**Issue by G-R-A-F-F** [Tzahi12345/YoutubeDL-Material#485]
Hi,

I am unable to start download via curl.

**To Reproduce**
### Attempt 1
Steps to reproduce the behaviour:
1. Start docker image with this:
```
mkdir -p /home/$USER/docker/YoutubeDL-Material/

docker run -d \
--name=ytdl_material \
-e UID=1000 \
-e GID=1000 \
-v /home/$USER/docker/YoutubeDL-Material/appdata:/app/appdata \
-v /home/$USER/docker/YoutubeDL-Material/audio:/app/audio \
-v /home/$USER/docker/YoutubeDL-Material/video:/app/video \
-v /home/$USER/docker/YoutubeDL-Material/subscriptions:/app/subscriptions \
-v /home/$USER/docker/YoutubeDL-Material/users:/app/users \
-p 17442:17442 \
--restart unless-stopped \
tzahi12345/youtubedl-material:nightly`
```
Enable API, generate token and save settings.

2. In terminal:
```
curl -XPOST -H "Content-type: application/json" -H "Authorization: 2f5b6197-2704-4ae9-aa59-1ba758fa10ec" -d '{"url": "https://www.youtube.com/watch?v=XXXXXXXXXXX"}' 'http://localhost:17442/api/tomp4'
```

3. CURL response:

> curl: (52) Empty reply from server

4. URL is not added to the download queue in the WebUI

### Attempt 2 - different curl command syntax
1. Start docker image - same as above.
2. In terminal
```
curl --request POST   --url 'http://localhost:17442/api/downloadFile?apiKey=2f5b6197-2704-4ae9-aa59-1ba758fa10ec'   --data '{"url":"https://www.youtube.com/watch?v=XXXXXXXXXXX"}'
```
3. CURL response:
> {"download":{"title":"","user_uid":null,"sub_id":null,"sub_name":null,"options":{},"uid":"1478a54e-8c76-4f6c-a4d4-3b0f53a18c61","step_index":0,"paused":false,"running":false,"finished_step":true,"error":null,"percent_complete":null,"finished":false,"timestamp_start":1634212414080}}

4. URL as added to the queue, however, download is not happening.
5. Docker log output:
> TypeError: Cannot read property 'includes' of undefined
>     at Object.exports.generateArgs (/app/downloader.js:408:28)
>     at collectInfo (/app/downloader.js:194:30)
>     at runNextTicks (internal/process/task_queues.js:60:5)
>     at listOnTimeout (internal/timers.js:526:9)
>     at processTimers (internal/timers.js:500:7)

**Environment**
- Docker version 19.03.11, build 42e35e61f3
- Docker tag: tzahi12345/youtubedl-material:nightly

**Note**
Links added manually to the WebUI work without any issues.

**Comment by GlassedSilver** [comment]
Not sure I can help here, @Tzahi12345 is pretty busy lately it seems, so a reply may take some time to arrive.

I'm sorry I can't really help here like with (happily!) increasingly more other issues, but I hope you enjoy the app so far anyhow!

**Comment by Tzahi12345** [comment]
Thanks for all the details! I think I see the issue, you need to use the Content-Type header as well like so:

```
curl --request POST --url 'http://localhost:17442/api/downloadFile?apiKey=ba3467da-40c8-4bd0-8357-11f2d2f89b95' --header 'Content-Type: application/json' --data '{"url": "https://www.youtube.com/watch?v=vWAPu98Mfwk"}'
```

When I left it out I saw the same problem you were seeing. Hope this helps!

If you want to test out some more of your HTTP requests (really for any project) I recommend [Insomnia](https://insomnia.rest/download). Lightweight, open-source, can't really ask for more.
