### ISSUE TITLE
[BUG] Mp3 downloaded to the computer is only 200 Bytes.

### ISSUE THREAD

**Issue by 2ndMessiah** [Tzahi12345/YoutubeDL-Material#486]
**Firstly, thank the author for the devotion to YTDLM!!**

**Describe the bug**

Deployed the official docker image via the nightly branch. Launch logs look perfect without errors.

Then I randomly tried downloading some audio-only items. The downloading process on the server-side is pretty normal, and the audio downloaded could be played on the front UI.

But then I click download, the file I got is only around 200 Bytes.

Audio I tried (Any youtube link, no success): https://www.youtube.com/watch?v=Gx4JEBwVlXo

**Screenshots**

![image](https://user-images.githubusercontent.com/22229188/137582973-360922ac-0a0f-4f92-8fc3-925d84370e49.png)
![image](https://user-images.githubusercontent.com/22229188/137582978-373bc489-cdea-4d2d-b733-26ae16ae0823.png)
It indicates the file size is 282B.

**Environment**

Installed version: v4.2 - done  You are up to date.
Installation type: docker
Docker tag: nightly
Commit hash: 88cc8d0
Build date: 2021-10-01
browser: Chrome\edge latest stable.

**Comment by gerroon** [comment]
I think that Google is blocking or slowing down youtube-dl downloads I just got "ERROR: unable to download video data: HTTP Error 403: Forbidden
"

**Comment by svw-ataibma** [comment]
I have the same problem.

The download is a JSON object rather than the underlying file.

```
{"download":{"title":"","user_uid":null,"sub_id":null,"sub_name":null,"options":{},"uid":"xxx-xxx-xxx","step_index":0,"paused":false,"running":false,"finished_step":true,"error":null,"percent_complete":null,"finished":false,"timestamp_start":12345}}%
```

If you try to play the audio through the web interface everything works and the downloaded files exist locally.

**Fails on:**
Installation type: docker
Docker tag: nightly
Commit hash: 88cc8d0
Build date: 2021-10-01
Docker image: 2a10ec631763

**Works on**
Installation type: docker
Date: 9 months old...
Docker tag: latest
Docker image: d599d76ad855

**Comment by 2ndMessiah** [comment]
> I have the same problem.
> 
> The download is a JSON object rather than the underlying file.
> 
> ```
> {"download":{"title":"","user_uid":null,"sub_id":null,"sub_name":null,"options":{},"uid":"xxx-xxx-xxx","step_index":0,"paused":false,"running":false,"finished_step":true,"error":null,"percent_complete":null,"finished":false,"timestamp_start":12345}}%
> ```
> 
> If you try to play the audio through the web interface everything works and the downloaded files exist locally.
> 
> **Fails on:** Installation type: docker Docker tag: nightly Commit hash: [88cc8d0](https://github.com/Tzahi12345/YoutubeDL-Material/commit/88cc8d0e811e197f8c3795003542c3366082ceb3) Build date: 2021-10-01 Docker image: 2a10ec631763
> 
> **Works on** Installation type: docker Date: 9 months old... Docker tag: latest Docker image: d599d76ad855

Yeah, playback works normally.

So are there any functionality and stability differences on the "latest" tag? I'm thinking about switching to this channel.

**Comment by 2ndMessiah** [comment]
> I have the same problem.
> 
> The download is a JSON object rather than the underlying file.
> 
> ```
> {"download":{"title":"","user_uid":null,"sub_id":null,"sub_name":null,"options":{},"uid":"xxx-xxx-xxx","step_index":0,"paused":false,"running":false,"finished_step":true,"error":null,"percent_complete":null,"finished":false,"timestamp_start":12345}}%
> ```
> 
> If you try to play the audio through the web interface everything works and the downloaded files exist locally.
> 
> **Fails on:** Installation type: docker Docker tag: nightly Commit hash: [88cc8d0](https://github.com/Tzahi12345/YoutubeDL-Material/commit/88cc8d0e811e197f8c3795003542c3366082ceb3) Build date: 2021-10-01 Docker image: 2a10ec631763
> 
> **Works on** Installation type: docker Date: 9 months old... Docker tag: latest Docker image: d599d76ad855

I've found the reason possibly.
The docker-compose.yml download link in the introduction section directs to the docker-compose.yml solely for the latest branch. The right docker-compose file for the nightly is https://raw.githubusercontent.com/Tzahi12345/YoutubeDL-Material/master/docker-compose.yml .  However, I got multiple exceptions launching it up...

**Comment by Migushthe2nd** [comment]
> I have the same problem.
> 
> The download is a JSON object rather than the underlying file.
> 
> ```
> {"download":{"title":"","user_uid":null,"sub_id":null,"sub_name":null,"options":{},"uid":"xxx-xxx-xxx","step_index":0,"paused":false,"running":false,"finished_step":true,"error":null,"percent_complete":null,"finished":false,"timestamp_start":12345}}%
> ```

It seems this is the case for all files. I also notice that the mp4 files stored on the server are actually also corrupted. Before the audio and video are combined they play fine, but once they are combined, the video file is corrupt (the file is a normal size though).

**Comment by Quinten0508** [comment]
+1 on docker w/ the nightly build with this showing under portainer's log section every time I download the file:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at collectInfo (/app/downloader.js:190:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

**Comment by 2ndMessiah** [comment]
dev has discardedthis project. I stopped using it as well.

**Comment by rockbo842** [comment]
> 

Are you using another youtubedl project now?  If so, which one?
