### ISSUE TITLE
[FEATURE] Passwordlock the settings?

### ISSUE THREAD

**Issue by NotErikUden** [Tzahi12345/YoutubeDL-Material#489]
**Is your feature request related to a problem? Please describe.**
Well, sort of: I'd like to have this amazing site accessed by many people, some I may not know. It would be nice if some of the settings that could break the entire page couldn't be accessed by anyone but me, the admin.

I suggest there is an admin-code or something of that kind (_possibly even an admin user account_) one had to enter before being allowed to edit any settings whatsoever!

I do think most people are genuinely nice and won't damage anything - but the Internet is the Internet, so I'd like for there to be any sort of protection! Possibly even that some settings can only be changed when accessed by the local IP? Thanks for reading!

**Comment by GlassedSilver** [comment]
This is something we used to have, it got replaced by multi-user mode, which does (afaik) differentiate between users and admin. I don't use multi-user mode myself, so take my words with a grain of salt. @Tzahi12345 will be able to fill in better.

**Comment by GlassedSilver** [comment]
Relevant ticket where this got discussed: #147

**Comment by NotErikUden** [comment]
Is there a way to have a public user? Like, I want anyone to be able to use the site without having to sign up, I just don't want everyone to be able to change settings that could potentially kill the site.

Thank you for the ticket, however! I did enable multi-user mode!

**Comment by Tzahi12345** [comment]
@NotErikUden Looks like this discussion got moved over to #545, but yes I do love the idea and allowing a "public" user seems like the best approach where logins can be optional thereafter.
