### ISSUE TITLE
[BUG] Slow video download speed

### ISSUE THREAD

**Issue by excodex** [Tzahi12345/YoutubeDL-Material#491]
**Describe the bug**
Download is extremely slow on my self-hosted home server. Around 80kb/s instead of 8-10Mb/s.

**To Reproduce**
Download any video.

**Expected behavior**
Download with full speed, I have 100mbps dl / 100mbps up connection.

**Environment**
- YoutubeDL-Material version: v4.2
- Docker tag: tzahi12345/youtubedl-material:latest - 6bf09629a3bb - amd64

**Additional context**
youdube-dl is having issue, see: 
* https://github.com/ytdl-org/youtube-dl/issues/30173
* https://github.com/ytdl-org/youtube-dl/issues/29326

Can you add support for this fork? https://github.com/yt-dlp/yt-dlp

Thanks!

**Comment by Dominik-1980** [comment]
Same here. I have installed it yesterday.
The download is so slow, you can't really use it.
Google says one way is to select yt-dlp as downloader, but I can only select yt-dl or yt-dlc...

**Comment by USRGH** [comment]
same here. Installed some minutes ago, downloading is extremely slow. Tried youtube-dl, youtube-dlc, yt-dlp. Same result.
I'm trying to install video in 720p25. If I leave Max Quality, it's downloading a little bit faster.
Have gigabit but it's downloading 1-2MB/s

**Comment by GlassedSilver** [comment]
> same here. Installed some minutes ago, downloading is extremely slow. Tried youtube-dl, youtube-dlc, yt-dlp. Same result. I'm trying to install video in 720p25. If I leave Max Quality, it's downloading a little bit faster. Have gigabit but it's downloading 1-2MB/s

In cases like these it might be that you're rate-throttled. Usually fixed by getting a new IP/waiting some hours/days (I have dynamic IP so I can't really give you that good experience guidance on this), restarting the container or a combination of both.
