### ISSUE TITLE
[BUG] Playlist won't download if there is an unavailable video in it.

### ISSUE THREAD

**Issue by deadlycfx** [Tzahi12345/YoutubeDL-Material#493]
**Describe the bug**
Playlist won't download if there is an unavailable video in it.  It doesn't skip the unavailable video and won't download anything.

**To Reproduce**
Just download a playlist with and unavailable video.

**Expected behavior**
Skip the unavailable video and download the rest of the videos.

**Environment**
- YoutubeDL-Material 4.2
- Docker tag: nightly

**Comment by cyberskycat** [comment]
you could try add  the custom args 
```
 -i, --ignore-errors
              Continue on download errors, for example to skip unavailable videos in a playlist
```

**Comment by GlassedSilver** [comment]
Which fork of yt-dl are you using in your setup? And can you possibly provide logs?

Sorry that I can't get back to you with more than the usual initial trouble-shooting keypoints here and that I reply this late. :/

**Comment by sleepymatto** [comment]
Having the same issue trying to download a playlist with a video in the playlist that is unavailable. Using the latest nightly build (4.2). Tried both youtube-dl and youtube-dlp

https://www.youtube.com/playlist?list=PLZWD78nR1R0nxp-rSjsdtK2J1HErSmOQA

**Comment by GlassedSilver** [comment]
Pinning this issue now for visibility. I don't really have an idea how to fix this atm and googling this for feedback in regard to yt-dlp and how you'd possibly handle the error there directly with args... I come up empty.

So if anyone smarter than me knows something I'd appreciate pointers or even better a PR. :)

Thank you for reporting the bug you two!

**Comment by GlassedSilver** [comment]
yt-dlp's README says that you can use this flag to not abort on errors:


```
--no-abort-on-error              Continue with next video on download
                                 errors; e.g. to skip unavailable videos in
                                 a playlist (default)
```

This might help, but it could be that YT-DLM may abort this on its own, not sure. Can you check with yt-dlp and passing this?

**Comment by GlassedSilver** [comment]
I think I hastily applied the response-needed label here and had it auto-close when I in fact believe we should at least consider including the `--no-abort-on-error` arg to the defaults for one-off downloads. Thoughts, @Tzahi12345?

**Comment by Tzahi12345** [comment]
Hi @mikepaxton @deadlycfx, this appears to be a yt-dlp issue. Btw `--no-abort-on-error` is yt-dlp specific and on by default, but in all youtube-dl forks there's the `--ignore-errors` are (or `-i` for short) which we already use.

My guess is that in yt-dlp, `--dump-json` and `--ignore-errors` cannot be used in conjunction, that is: errors will be thrown anyways. The good news is that the necessary info to continue the download exists, just in a slightly different place (in err.stdout for those interested).

I updated #657 to include the following commit: https://github.com/Tzahi12345/YoutubeDL-Material/pull/657/commits/d225e84a0380c25bfa8ca902ffea78b32728aeaa

Should be fixed shortly when that PR closes. Thanks @mikepaxton @sleepymatto @deadlycfx for the report & info!!
