### ISSUE TITLE
[FEATURE] List public videos in user accounts and add a way in a multi-user context to download videos as public

### ISSUE THREAD

**Issue by Volyz** [Tzahi12345/YoutubeDL-Material#494]
First of all i'd like to thank you for your amazing work !

**Is your feature request related to a problem? Please describe.**
I've put a docker container of YoutubeDL-Material on my synology NAS and everything worked well ! I downloaded some videos and subscribed to some channels then began to mess with the settings.

I activated the multi user setting, created the admin account and my account. And here is the problem : videos, subscriptions and audio files downloaded previously on a non multi-user install are not browsable/viewable. They do not appear anywhere unless i reverse the settings to the non multi-user install. I thought that the multi-user adds accounts on top of the already existing architectures for each user videos + the rest. What is then the purpose of video/audio/subscription if multi-user bypass them ?

**Describe the solution you'd like**
Add some new features to the app

Like Youtube or any other viedo website, make the assets found in video/audio/subscription available/browsable/vieable on a non logged homepage if the multi-user setting is activated. They are "public" assets, viewable by anyone logged in or not.

If the user log in, add the videos/audios/subscriptions to the user list of videos/audios/subscriptions in the WebUI.

For the downloads :

In the non logged homepage => dowloads are public and they go to viedo/audio/subscription  folder

In the logged homepage => we choose if our downloads are ours (user) or public (video/audio/subscription)

**Comment by GlassedSilver** [comment]
#545 Extends on this, basically not making everything public on every instance, however enabling to set up an instance like that. If you want you can join the discussion there and chime in if my suggestion there seems plausible for you.
