### ISSUE TITLE
-f '(mp4)[height=1080' ERROR: requested format not available

### ISSUE THREAD

**Issue by QrchackOfficial** [Tzahi12345/YoutubeDL-Material#497]
Built in resolution setting (Max quality) probably has a typo, at least for subscriptions:
![image](https://user-images.githubusercontent.com/3584315/146524621-f4633569-0fdb-4400-b596-f2023a508d08.png)

The issue appeared yesterday after I pulled the nightly Docker image to update my copy

Sample:
```
Error while retrieving info on video with URL https://www.youtube.com/watch?v=4ucN1ETDXTE with the following message:
Error: Command failed with exit code 1:
/app/node_modules/youtube-dl/bin/youtube-dl -o subscriptions/channels/w2aew/%(title)s.%(ext)s
--write-info-json --print-json -f '(mp4)[height=1080'
--cookies appdata/cookies.txt --write-thumbnail --embed-subs
--mark-watched --write-auto-sub --sub-lang en -r 50K --embed-subs
 --mark-watched --write-auto-sub --sub-lang en --dump-json http://www.youtube.com/watch?v=4ucN1ETDXTE
ERROR: requested format not available
```

Note the lack of closing bracket near `-f '(mp4)[height=1080'`. So far I've worked around this by setting Max quality to best and adding a global custom arg, but this is probably a bug so I'm reporting here.

**Comment by zerojay** [comment]
I'm having this same issue and the same cause when using lower resolutions as well.

**Comment by a1ad** [comment]
Same here, I can't download any video of my subscriptions. @QrchackOfficial what custom arg do I need to add?

**Comment by QrchackOfficial** [comment]
At the moment I'm using yt-dlp downloader and added this as my global custom args:
```
--embed-subs,,--mark-watched,,--write-auto-sub,,--sub-lang,,en,,-f,,best[height<=1440][ext=mp4]/best[height<=1440]/best[ext=mp4]/best,,-r,,50K
```

All subscriptions are set to "Best" Max quality with no custom arguments.

**Comment by GlassedSilver** [comment]
Please restart your YoutubeDL-Material container. (and consider pulling the latest nightly of the docker container as well)

That will trigger an update of yt-dlp (if you use that, which I recommend!). A new release of yt-dlp dropped yesterday and it helped **a LOT** with my downloads succeeding! :)

Alternatively you can bash into your YTDL-M container and update the yt-dl fork binary like so (regardless of which binary you selected by the, but again, yt-dlp is the recommended one):

`./app/node_modules/youtube-dl/bin/youtube-dl -U`

**Comment by GlassedSilver** [comment]
Blocked by #544 as far as I can tell. Progress on this will be tracked there from now on. Feel free to discuss there.
