### ISSUE TITLE
[BUG] ERROR: No video formats found

### ISSUE THREAD

**Issue by almulder** [Tzahi12345/YoutubeDL-Material#498]
**Describe the bug**
Getting following error message in logs and unable to download anything, been working fine until the 12/15, Need possible new version released?

ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
WARNING: Unable to download webpage: HTTP Error 429: Too Many Requests

**Comment by QrchackOfficial** [comment]
The error here is `Error 429: Too Many Requests`. This is Google realizing you're trying to watch way too much. You can set up cookies to get around this.

**Comment by GlassedSilver** [comment]
Using yt-dlp can also greatly help. Restarting the container/app, waiting a little bit, etc...

Error 429 is a datahoarder's classic issue on YT, but there are ways to work around it/temporarily fix it. :)

Even more info here: https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Fixing-429-errors
