### ISSUE TITLE
Recognize Parent folder in Default file Output

### ISSUE THREAD

**Issue by wschlotter** [Tzahi12345/YoutubeDL-Material#500]
Setup:
docker-compose running nightly

I use Plex Media Server for my media at home. I want to be able to integrate youtube videos into my media server by using [Youtube-Agent](https://www.youtube.com/watch?v=69AnRyRgOVo).

One of the requirements to use the agent is to place the videos into folders. (ie /../CHANNEL NAME [CHANNEL ID]/TITLE [VIDEO ID].mp4)

I noticed that when using the global _Default file Output_ and identifying a  hierarchical path in the argument (ie. `%(channel)s [%(channel_id)s]/%(title)s [%(id)s].%(ext)s`) it does not show the % of download and shows an error in the log:

TypeError: Cannot read property 'files_to_check_for_progress' of null
today at 4:11:33 PM     at checkDownloadPercent (/app/downloader.js:587:49)
today at 4:11:33 PM     at runMicrotasks (<anonymous>)
today at 4:11:33 PM     at processTicksAndRejections (internal/process/task_queues.js:95:5)

The file does download just fine, and everything works how it's supposed to. You just can't see that status of the video as it's downloaded within the webGUI

If i am missing something or need more clarification let me know.

**Comment by Tzahi12345** [comment]
Nice catch! Looks like we couldn't use the glob method for searching for files based on a pattern when it was dealing with a subdirectory. It's definitely possible somehow but I decided to just use `fs.readdir()` instead and filter out files in JS. [See commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/21507ee36dc560064129505f4b78c64a360a2c77). Should be fixed now!
