### ISSUE TITLE
[BUG] 4.2 No yt-dlp in settings->Advanced->select downloader

### ISSUE THREAD

**Issue by kunajk** [Tzahi12345/YoutubeDL-Material#506]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7194122/149406703-9271e1fa-8d7f-4bc0-a443-9ef136ebcbcd.png)

**Environment**
- YoutubeDL-Material version
- Docker tag: <tag> (optional)

**Additional context**
Add any other context about the problem here. For example, a YouTube link.

**Comment by projx** [comment]
Do earlier versions have yt-dlp?

**Comment by GldRush98** [comment]
No, but yt-dlc hasn't been updated in over a year at this point.  yt-dlc should probably just be replaced with yt-dlp at this point considering yt-dlp is the only active fork that actually works right with youtube right now. https://github.com/yt-dlp/yt-dlp

**Comment by GlassedSilver** [comment]
Please switch to the nightly branch, "latest"  on the release channel is over a year old and misses a LOT of stuff.

You will be able to select yt-dlp there. So depending on how you deployed YoutubeDL-Material you want to switch accordingly. If you're on a docker build, just append `:nightly` as tag.

If you need further help, let us know! 👍
