### ISSUE TITLE
[BUG] transfer to a mongodb with authorization/authentication

### ISSUE THREAD

**Issue by toniexly** [Tzahi12345/YoutubeDL-Material#508]
**cannot transfer to a mongodb with authorization/authentication**
tried to transfer to mongodb, but the process stopped halfway. the log writes "codeName: 'Unauthorized'".

**Description of the issue**
I'm using this string to connect: "mongodb://192.168.2.111:27017/?compressors=zlib". the connection tests fine but the transfer fails halfway. 

Do i need to put mongodb's username and password somewhere in the connection string? but I don't know how to. it's difficult enough for me just to set up a MongoDB database...

Or, it's some other problem causing this?...

**----art of the log----**
codeName: 'Unauthorized'
 code: 13,
ok: 0,
at processTicksAndRejections (internal/process/task_queues.js:82:21) {
 
at endReadableNT (internal/streams/readable.js:1317:12)
 
at Inflate.emit (events.js:400:28)
 
at Inflate.zlibBufferOnEnd (zlib.js:159:10)
 
at Inflate.cb   (/app/node_modules/mongodb/lib/cmap/message_stream.js:183:12)
 
at MessageStream.emit (events.js:400:28)
 
at MessageStream.messageHandler   (/app/node_modules/mongodb/lib/cmap/connection.js:272:20)
 
MongoError: command find requires   authentication
 
}

**Comment by toniexly** [comment]
problem sloved.

The standard URI connection scheme has the form:
mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]

**Comment by GlassedSilver** [comment]
> problem sloved.
> 
> The standard URI connection scheme has the form: mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]

Sorry for the late reply, but thank you a lot for providing the solution that worked for you so others can reference this if they run into the same problem.

Aftercare for your own issues by sharing the solution with the community is legendary. You're an everyday hero, thank you! :)

Hope you keep enjoying YoutubeDL-Material! :)
