### ISSUE TITLE
[BUG] ERROR: Sign in to confirm your age

### ISSUE THREAD

**Issue by yves-chevallier** [Tzahi12345/YoutubeDL-Material#512]
**Describe the bug**

For any videos I get this error: 

 ```
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
WARNING: unable to download video info webpage: HTTP Error 410: Gone
```

**To Reproduce**

1. Put this link : https://www.youtube.com/watch?v=tNOZtZ4_GFo&list=FLEPX_wbuVQhwkb0qZ-UR4RA&index=1
2. Click download

**Comment by GlassedSilver** [comment]
You need to use a session cookie from your browser when you're logged into Youtube.

That way YTDL-M can act as that session and access the same stuff your account can. This also applies to stuff like videos that aren't public but visible to you.

`Settings > Advanced > Cookies > Use Cookies`

TICK to true and select a cookie to use

As for how to export the session cookie based on your browser please refer to Google. It's a bit different for every browser.

**Comment by GlassedSilver** [comment]
Also, yt-dlp recently added new workarounds for age-gated content, that may help as well.

Use yt-dlp as your ytdl binary, it has the best support cycle atm from my observations and is actively maintained.

`Settings > Advanced > Select a downloader`

If the issue cannot be remedied using yt-dlp on the latest YT-DLM nightly feel free to comment, and I will re-open the issue. :)
