### ISSUE TITLE
[BUG] Global 'File output format' is not being applied to the output file

### ISSUE THREAD

**Issue by jeffward01** [Tzahi12345/YoutubeDL-Material#519]
**Describe the bug**
I am experiencing (2) main bugs.  The minor bug which is a sub-note of the main bug is that when I click 'kill all downloads`, the downloads to not stop at all.  It has downloaded an additional 75MB and counting... since I have clicked 'kill all downloads`.

**Now the Main Bug:**

 I would like each video to have its own directory, rather than a mega-dump within the `<channel-name>` directory.  

According to the `YouTube-dl` documentation, the string:  `%(title) - %(upload_date)/%(channel)-%(title)-%(timestamp)` is supposed to create a new folder in the output directory and adapt the output format.

I started with a brand-new clean installation of `YoutubeDL-Material`, and then applied the above output format (as seen in the screenshot below), I added a new subscription, and waited for a download to start.

When a download started, as you can see, it did not apply any of the output formats which I configured.

**To Reproduce**
1. Start with clean docker image of `YoutubeDL-Material`
2. Go to the global configuration in the GUI as seen in the screenshot, apply the output format as: `%(title) - %(upload_date)/%(channel)-%(title)-%(timestamp)`
3. Go to the subscription area, add a YouTube channel. (`https://www.youtube.com/channel/UC5vXBfxN7rxKeJHJxS8dNDw/videos`) is the channel which I added. _(Side-note: Great history content which makes you question our history that we have been told, its a great channel)_
4. Wait for the download to begin, watch your output directory (as seen in my screenshot) then see your download in the download output directory (see my screenshot) **THIS IS THE MAIN BUG**
5. (minor bug), click 'kill all downloads`, then the download will not stop. **This is the minor bug.**

**Expected behavior**
I expect the output to generated as directed: `%(title) - %(upload_date)/%(channel)-%(title)-%(timestamp)`

`/subscriptions/channels/<channel-name>/<title>-<upload_date>/<channel-name>-<title-of-video>-<timestamp-of-video-upload-time>.ext`

According to the `YouTube-dl` documentation, the string: : `%(title) - %(upload_date)/%(channel)-%(title)-%(timestamp)` is supposed to create a new folder in the output directory and adapt the output format.

In summary, I would like each video to have its own directory, rather than a mega-dump within the `<channel-name>` directory.

**Screenshots**
![image](https://user-images.githubusercontent.com/12589359/153799069-95f33761-fada-4339-8794-bfe74e985b0e.png)

**Environment**
- YoutubeDL-Material version: 4.2 (latest stable)
- Unraid Docker (Unraid version: `6.10.0-rc2`
 
**Additional context**
Add any other context about the problem here. For example, a YouTube link.

* **Output format as defined in YouTube-DL docs:** `%(title) - %(upload_date)/%(channel)-%(title)-%(timestamp)` _(the extension is not included as instructed by the GUI of the YoutubeDL-Material application)._ 
* **YouTube Link to channel:** `https://www.youtube.com/channel/UC5vXBfxN7rxKeJHJxS8dNDw/videos` 

---

**My Goal is:** I would like each video to have its own directory, rather than a mega-dump within the <channel-name> directory.

**Comment by jeffward01** [comment]
Fixed it 👍 , I just had to add the `s` at the end of each `%(title)s` or other tag.

Still the minor bug where `kill all` does not _kill all..._ exists

**Comment by GlassedSilver** [comment]
The global output setting is for one-off downloads.

Subscriptions have their separate root folder (usually /subscriptions, unless you configured it to something else) which then appends a separately set path logic.

It's not a bug, but a poorly worded UI issue. I'll provide a fix for that during my next commit to the repo, thank you for reporting this!

**Comment by GlassedSilver** [comment]
Also, yt-dlp had a new release today, make sure to restart your YTDL-M instance to have it pull the latest binary for it so your downloads work better again. (I've had a lot fail on me recently, the latest yt-dlp fixed this and I've arrived at home after updating it to find SEVERAL of my subscriptions to successfully download again!)
