### ISSUE TITLE
[FEATURE] Move Video When Download Completed?

### ISSUE THREAD

**Issue by pshankland** [Tzahi12345/YoutubeDL-Material#522]
Just started to use YoutubeDL-Material and can't seem to find an option to allow either manual or automatic moving of files once the download has been completed. I know there is an option for the file output to be modified in settings but this is relative to the /audio or /video paths rather than something else. For example I have a CIFS mount to a Synology which I would like to use for my output.

Thanks.

**Comment by QrchackOfficial** [comment]
For a workaround, you can easily symlink to a CIFS mount, or map to it if it's running in Docker

**Comment by GlassedSilver** [comment]
I don't know about Synology in particular, but Docker does let you mount network shares as volumes for containers.

https://www.youtube.com/watch?v=eKAQiYu4NyI

That video MIGHT be helpful for you. I personally don't have a Synology NAS to test any possible deployment approaches with, but maybe that helps you. If I can be of any other help with this let me know.

**Comment by GlassedSilver** [comment]
> For a workaround, you can easily symlink to a CIFS mount, or map to it if it's running in Docker

If Synology lets you directly map to it that'd be sweet. Can you give us an update how this works out for you, @pshankland?

Thank you in advance and thank you for your interest in YTDL-M. :)

**Comment by GlassedSilver** [comment]
Been a month, I consider this resolved. If it's not, please don't hesitate to ask for help to set it up. :)
