### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'permissions')

### ISSUE THREAD

**Issue by Xosten** [Tzahi12345/YoutubeDL-Material#561]
**Describe the bug**
When activating for the first time the multi-user feature. It's asking to create an admin password. When confirming, it disconnects the user and brings it to the login page. When writing the same password, it keeps loading and `docker logs <container>` gives the following error : 

```
TypeError: Cannot read properties of null (reading 'permissions')
    at Object.exports.userPermissions (/app/authentication/auth.js:349:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.returnAuthResponse (/app/authentication/auth.js:189:18)
```

**To Reproduce**
1. Create a fresh container
2. Transfer from localdb to mongodb
3. Activate multi-user
4. Write admin password
5. Try to connect with _admin_ and your password
6. Check the container logs

**Expected behavior**
Kinda obvious, it should not give the error and let the user log-in

**Environment**
Installed version: v4.2 -   You are up to date.
Installation type: docker
Docker tag: nightly
Commit hash: 0bc2193
Build date: 2022-04-24

**Additional context**
- The instance on which it's running is an Oracle Cloud ARM Free tier
- It's running behind a reverse proxy, Traefik
Here's the users.json file after defining the admin password:
```
{
  "jwt_secret": "REDACTED",
  "users": [],
  "roles": {
    "admin": {
      "permissions": [
        "filemanager",
        "settings",
        "subscriptions",
        "sharing",
        "advanced_download",
        "downloads_manager"
      ]
    },
    "user": {
      "permissions": [
        "filemanager",
        "subscriptions",
        "sharing"
      ]
    }
  }
}
```

If you need any additional information, please let me know.
Thanks in advance for helping!

**Comment by Tzahi12345** [comment]
Thanks for the detailed info! Should be fixed now, [see commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/d5c1361e64a207973ff82e92811c884d1fa3ed7c). In about an hour the nightly should be updated and you should be good to go!

**Comment by Xosten** [comment]
Thanks! I'll let you know once I've tested it :)

**Comment by Xosten** [comment]
@Tzahi12345 I confirm it works. Thanks for having fixed it so quickly!

**Comment by Tzahi12345** [comment]
No problem! Thanks for the report :)
