### ISSUE TITLE
[RELIABILITY/UX] Make yt-dlp the default for new installations

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#575]
I think it's fair to say that is has become the best fork yet and fixes a lot of yt-dl's and yt-dlc's shortcomings.

**Comment by Tzahi12345** [comment]
I agree. Even on download speed alone yt-dlp is miles ahead.

[The support is great too](https://github.com/yt-dlp/yt-dlp/issues/42#issuecomment-802106910)!
