### ISSUE TITLE
[DISTRIBUTION] Automated Weekly Docker Builds

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#576]
Create weekly Nightly builds (at least if there hasn't been manual merging during the past n days.
This is helpful in keeping the base OS YTDL-M runs on and its dependencies up to date. (Linuxserver.io-style)
Consider using the exact same publish time as Linuxserver.io as well, because it's likely that folks will pull the same image layers through them as well, saving on download time and data.

**Comment by Tzahi12345** [comment]
Looks trivially easy: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
