### ISSUE TITLE
EmbedThumbnailPPError: AtomicParsley was not found. Please install

### ISSUE THREAD

**Issue by vveerar1** [Tzahi12345/YoutubeDL-Material#58]
Hi, AtomicParsley is required to perform postprocessing on the downloaded videos. I tried installing it manually, however, I am still getting the same error "EmbedThumbnailPPError: AtomicParsley was not found. Please install". Perhaps, I am not installing it in the correct directory. Could anyone please help me where exactly I should install AtomicParsley?

Post-processing commands used: 
--embed-thumbnail
--add-metadata
-v
--postprocessor-args "-id3v2_version 3"

Thank you in advance!

**Comment by Tzahi12345** [comment]
I've had a similar error complaining about no AtomicParsley before, and I believe it's related to the `--embed-thumbnail` argument.

If you're on Windows, you can get Atomic Parsley [here](http://atomicparsley.sourceforge.net/). If you're running on a Debian-based Linux distro like Ubuntu, then this command should suffice:

`sudo apt-get install atomicparsley`

I believe download it *does* fix the issue, let me know if it does! If so, I'll just update the README to note that thumbnail args require AtomicParsley installed.

**Comment by Roxedus** [comment]
It should be added to the container regardless

**Comment by Tzahi12345** [comment]
>It should be added to the container regardless

True! I just wanted confirmation it would solve the issue, no point in adding a dependency unnecessarily :)

I was planning on testing & adding this for the next update (at least on Docker), but it might be a couple weeks until that happens. In the meantime, I'll keep this issue open until I do a couple things:

1. Verify AtomicParsley is needed/works for thumbnails and add it as an optional dependency in the README
2. Add it as a dependency to the Dockerfile

**Comment by Roxedus** [comment]
Well, it is related to the `--embed-thumbnail` argument, I added it to my own YTDL container to be able to use that argument.

https://github.com/Roxedus/Arkiverer/blob/master/amd64.Dockerfile#L15

**Comment by Tzahi12345** [comment]
Awesome, thanks for the confirmation! I'll get those changes done for the next update, hopefully no more thumbnail issues after that lol

**Comment by Tzahi12345** [comment]
Quick update!

README is updated and so is the Dockerfile. Thanks @vveerar1 for bringing up the issue, and thanks @Roxedus for the implementation, it was super helpful.

Alright, closing the issue, the nightly builds should have AtomicParsley included and the next update will have it as well. Thanks again guys
