### ISSUE TITLE
Docker image build is failing

### ISSUE THREAD

**Issue by samcro1967** [Tzahi12345/YoutubeDL-Material#585]
This just started today.

Build hangs asking for time=zone input
```
Setting up libassuan0:amd64 (2.5.3-7ubuntu2) ...
Setting up libgomp1:amd64 (10.3.0-1ubuntu1~20.04) ...
Setting up libldap-common (2.4.49+dfsg-2ubuntu1.8) ...
Setting up libfakeroot:amd64 (1.24-1) ...
Setting up libsasl2-modules-db:amd64 (2.1.27+dfsg-2ubuntu0.1) ...
Setting up tzdata (2022a-0ubuntu0.20.04) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------

Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.

  1. Africa        6. Asia            11. System V timezones
  2. America       7. Atlantic Ocean  12. US
  3. Antarctica    8. Europe          13. None of the above
  4. Australia     9. Indian Ocean
  5. Arctic Ocean  10. Pacific Ocean
```

**Comment by GlassedSilver** [comment]
It should pass now, I'll observe the build process and if it's not fixed I'll investigate further.

**Comment by samcro1967** [comment]
Failing in a different place now...
```
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/js.1.gz because associated file /usr/share/man/man1/nodejs.1.gz (of link group js) doesn't exist
Setting up python3-cliapp (1.20180812.1-3build1) ...
Setting up python3-packaging (20.3-1) ...
Setting up python3-markdown (3.1.1-3) ...
Setting up cmdtest (0.32.14.gcdfe14e-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
Processing triggers for ca-certificates (20210119~20.04.2) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
/bin/sh: 1: npm: not found
The command '/bin/sh -c apt-get update && apt-get --no-install-recommends -y install   wget   curl   gnupg &&   curl -sL https://deb.nodesource.com/setup_12.x  | bash - &&   apt-get -y install   nodejs   yarn &&   apt-get install -f &&   npm install -g @angular/cli' returned a non-zero code: 127
exit status 127
```

**Comment by dejan995** [comment]
I think that this command is confusing it somehow:

``curl -sL https://deb.nodesource.com/setup_12.x  | bash -``

The error 127 is given when the shell can't execute something.
@GlassedSilver Can you try putting this as a seperate RUN command and see if it passes?

**Comment by dejan995** [comment]
> I think that this command is confusing it somehow:
> 
> `curl -sL https://deb.nodesource.com/setup_12.x | bash -`
> 
> The error 127 is given when the shell can't execute something. @GlassedSilver Can you try putting this as a seperate RUN command and see if it passes?

It is not this. I just went through the logs and it says that npm is not installed:
``#27 85.05 /bin/sh: 1: npm: not found``

Isn't Yarn suppose to install npm. That is why I did not put the `--no-install-recommends` flag in the command where Yarn is installed.

**Comment by GlassedSilver** [comment]
Yes indeed it should, when running the commands in a Ubuntu 20.04 docker I also don‘t get npm. It did not fail at that stage before, which is really weird.

**Comment by GlassedSilver** [comment]
I reverted the change to not install recommends in all steps.

Build is currently going on and not failing straight after 3-5 mins. So looks like a good sign. :)

**Comment by dejan995** [comment]
It failed again unfortunatly.
But I think @Tzahi12345  approach, #587, should take care of this.

**Comment by samcro1967** [comment]
Build just worked for me and app works as expected.
