### ISSUE TITLE
API Not Working

### ISSUE THREAD

**Issue by hernandito** [Tzahi12345/YoutubeDL-Material#59]
Hello,

When sending an API **video** download command from within my own network, tnothing happens.

I am using the Docker version. When I type the below directly in my browser, I get a blank response and nothing is downloaded.

> http://192.168.0.201:17442/api/tomp4?apiKey=692-xxx59df57b&url=https://www.youtube.com/watch?v=i82528KGDdo
*the above API is edited for security.

I can properly access the Web GUI at:
`http://192.168.0.201:17442/#/home`

Am I missing something? Is the API not yet implemented?

Thank you.

H.

**Comment by Tzahi12345** [comment]
Hi!

The API is implemented, you can view [examples here](https://github.com/Tzahi12345/YoutubeDL-Material/wiki/API), and all available routes at the [official docs](https://stoplight.io/p/docs/gh/tzahi12345/youtubedl-material?group=master&utm_campaign=publish_dialog&utm_source=studio).

You *almost* got it right. Basically, the /API/tomp4 route is a POST request, so you have to do 2 things:

1. Send the request using curl or postman, you can't send it through a browser
2. Include the video URL as a body parameter, not a query parameter

This might seem confusing, but the API key must be kept as a query parameter (so you did that part right). The reason for this is not all requests have a body (like GET requests), so it rides along with the request URL instead for consistency.

Here's an example of what that would look like:

    curl -XPOST -H "Content-type: application/json" -d '{"url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"}' 'http://192.168.0.201:17442/api/tomp4?apiKey=692-xxx59df57b'

The "url" parameter is moved to the body, while the apiKey stays as a query param. If you have curl installed (most systems do), you can type this into your command line and it should work.

**Comment by hernandito** [comment]
Thank you!

I am so used to API web requests, I thought that was how it was meant to work. I am off to learn about how to invoke a curl request in my php/javascript code.

Thanks again.

Love the app!

**Comment by Tzahi12345** [comment]
Glad you like it! :) Happy to help, don't hesitate to open up any more issues if you come across a problem/suggestion.

Apparently PHP does have a [curl library](https://stackoverflow.com/a/16920588), though JS and PHP can send POST requests natively as well (i.e. w/o a library). Anyways, I'll close out this issue, but if you run into any problems sending the API requests you can comment here and I'll be happy to help.
