### ISSUE TITLE
[BUG] Unable to transfer DB to Mongo when auth is enabled

### ISSUE THREAD

**Issue by tehniemer** [Tzahi12345/YoutubeDL-Material#594]
**Describe the bug**
I'm trying to migrate my db to Mongo with auth enabled and it's failing to send the data, however connection tests are successful.

**To Reproduce**
Create a MongoDB instance with authentication enabled, then follow steps here https://github.com/Tzahi12345/YoutubeDL-Material/wiki/Setting-a-MongoDB-backend-to-use-as-database-provider-for-YTDL-M

**Expected behavior**
The database is migrated

**Screenshots/Logs**
Docker logs
```
{ MongoError: command find requires authentication
    at MessageStream.messageHandler (/app/node_modules/mongodb/lib/cmap/connection.js:299:20)
    at MessageStream.emit (events.js:198:13)
    at Inflate.decompress [as cb] (/app/node_modules/mongodb/lib/cmap/message_stream.js:183:12)
    at Inflate.zlibBufferOnEnd (zlib.js:133:10)
    at Inflate.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) ok: 0, code: 13, codeName: 'Unauthorized', name: 'MongoError' }
```
![image](https://user-images.githubusercontent.com/11021632/166231475-e166f484-3677-4cd3-87a3-e6579847fb9d.png)

![image](https://user-images.githubusercontent.com/11021632/166231686-fd66e66a-04f7-4a68-81ad-fd90cfc38031.png)

![image](https://user-images.githubusercontent.com/11021632/166231773-2f61a33e-a0b4-40bd-a930-5c32be9e8928.png)

**Environment**
Installation details:
Installed version: v4.2 -   You are up to date.
Installation type: docker
Docker tag: nightly
Commit hash: 5e3eb68
Build date: 2022-04-30

**Comment by tehniemer** [comment]
I stumbled across #508 which helped me solve this issue, by changing my string to `mongodb://user:pass@host:port/` I had to drop off the `?compressors=zlib` at the end as that gave me a connection error.

**Comment by GlassedSilver** [comment]
Glad you got it working now! :)

**Comment by tehniemer** [comment]
You may want to update the wiki with these examples.

**Comment by GlassedSilver** [comment]
Not a bad idea, I'll add the meta-label update docs, so I can track adding this as troubleshooting step eventually when I get around to rewriting the docs. :)
(possibly around 4.4-ish, but I don't know for certain)
