### ISSUE TITLE
[BUG] Unable start `TypeError: Cannot read properties of null (reading 'includes')`

### ISSUE THREAD

**Issue by martadinata666** [Tzahi12345/YoutubeDL-Material#603]
**Describe the bug**
Can`t start youtubedl-m due error includes null
```
2022-05-05T08:58:55.945Z INFO: Config items set using ENV variables.
/home/debian/youtubedl-material/youtube-dl.js:93
    if (!is_windows && details_json && details_json['path'].includes('.exe')) {
                                                            ^

TypeError: Cannot read properties of null (reading 'includes')
    at Object.exports.verifyBinaryExistsLinux (/home/debian/youtubedl-material/youtube-dl.js:93:61)
    at startYoutubeDL (/home/debian/youtubedl-material/app.js:671:19)
    at loadConfig (/home/debian/youtubedl-material/app.js:514:11)
    at async setAndLoadConfig (/home/debian/youtubedl-material/app.js:483:5)

```

I see the PR about checking binary of `youtube-dl`,  seems it solve some weird behaviour thinking run windows? and no `.exe` extension here. Full path will be `node_modules/youtube-dl/bin/youtube-dl`

**To Reproduce**
1. Follow install guide
2. node ./app.js

**Expected behavior**
Application should start

**Screenshots**

**Environment**
- YoutubeDL-Material git master
- Dockerized nodejs 16 self build

**Youtube-dl version**
Youtube-dl itself installed by NPM correctly with version `2021.12.17`

**Comment by GlassedSilver** [comment]
This project uses node.js version 12.
#593 will clarify this in the README. :)

**Comment by martadinata666** [comment]
I see, the node 12 accept null thing, as node 16 dont. I disabled verifybincheck thing, it work again. 

Thank for making the project moving again, good luck. 👍🏼

**Comment by GlassedSilver** [comment]
So you‘re saying it works on Node.js 16 if you disable that verification? That‘s really interesting.

If you don’t mind, you can help us bring this project to Node.js 16 then possibly, since we need to step up the version eventually anyhow due to its nearing EOL. At least with Ubuntu 22.04 (our new Docker base) we get security patches still.

**Comment by martadinata666** [comment]
Technically, yes it works. But can't really tell specific situation like #601 , as i myself build for my arm64 and not encountering something like that. Maybe some node 12 quirk. I will send PR to test nodejs upgrade.

**Comment by Tzahi12345** [comment]
Not sure what caused the path field to not exists in `details`, it really should. I put up a PR (#607) that will solve this crash but I'd like to learn more if possible.

If you can get it to crash again, can you go into `node_modules/youtube-dl/bin/details` and paste what's in that file here?

**Comment by martadinata666** [comment]
this is the `details`
`
debian@4fb044620224:~/youtubedl-material/node_modules/youtube-dl/bin$ cat details 
{"version":"2022.04.08","path":null,"exec":"youtube-dl","downloader":"yt-dlp"}
debian@4fb044620224:~/youtubedl-material/node_modules/youtube-dl/bin$ 
`

**Comment by Tzahi12345** [comment]
@GlassedSilver no need to overcomplicate it! We can just check if the path is null and handle that case. More ideally we should check all necessary fields to make sure they're set properly.

I actually expected the details file to be more mangled than this. The hotfix will prevent the error from coming up but I'll make a more permanent solution that handles more edge cases. Thanks for the info @martadinata666!
