### ISSUE TITLE
Subscriptions dissappear after page refresh.

### ISSUE THREAD

**Issue by Mattyfaz** [Tzahi12345/YoutubeDL-Material#62]
When adding a Channel or Playlist to your Subscriptions it is initially listed on the page. However after any page refresh (or going into the added channel/playlist) it dissappears from your Subscriptions page.

Running this in a Docker Container on UnRaid. GIF of the behavior below:

![Screen-Recording-2020-04-29-at-9 41 30-am](https://user-images.githubusercontent.com/10377148/80548258-dd415900-89fd-11ea-8996-d28336459294.gif)

**Comment by Tzahi12345** [comment]
Hm, that is definitely weird. Is this happening for all channels/playlists?

Also, can you check the logs for any errors? It's likely a server-side problem, so if an error was logged it would be found in `appdata/logs/combined.txt`.

I'm guessing that the playlist info was retrieved correctly (the name pops up and all), but the downloads for the videos within it failed for some reason. Still doesn't explain it disappearing, though...

**Comment by Mattyfaz** [comment]
@Tzahi12345 thanks for the quick response!

I can confirm it is happening for all Playlists and Channels I've tried, I commented on the UnRaid forums and another user confirmed the same: https://forums.unraid.net/topic/87798-support-selfhostersnets-template-repository/?do=findComment&comment=850354

Unfortunately the logs don't show much at all. 
`appdata/logs/error.log` is completely empty. 
`appdata/logs/combined.log` doesn't show much at all, just this:

```
2020-04-28T02:35:48.440Z INFO: Beginning migration: 3.5->3.6+
2020-04-28T02:35:48.452Z INFO: 3.5->3.6+ migration complete!
2020-04-28T02:35:48.453Z INFO: YoutubeDL-Material v3.6 started on PORT 17442
2020-04-28T02:51:37.329Z INFO: Beginning migration: 3.5->3.6+
2020-04-28T02:51:37.345Z INFO: 3.5->3.6+ migration complete!
2020-04-28T02:51:37.346Z INFO: YoutubeDL-Material v3.6 started on PORT 17442
```

However in UnRaid you can click the container and view container logs, and in that window I am getting a bit more information:

```
at Object.mkdirSync (fs.js:823:3)
at /app/subscriptions.js:90:32
at done (/app/node_modules/youtube-dl/lib/youtube-dl.js:25:12)
at /app/node_modules/youtube-dl/node_modules/universalify/index.js:23:46
at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by Tzahi12345** [comment]
The container logs are quite helpful! It seems like it's failing at line 90 in the subscriptions.js file, at this line of code:

    fs.ensureFileSync(archive_path);

Basically, it's making sure that the archive text file exists, which gets used if the archiving functionality is turned on. When the server realizes the parent directory doesn't exist (`subscriptions/archives/{subscription_name}`) and it can't create it with mkdir, it fails.

I assume you have a volume mapped to the subscriptions folder, can you make sure you have write access without sudo? Maybe you can run `chmod -R 777 subscriptions` it and see if that changes anything (just so we can track down what's wrong, it's not a permanent solution).

If you see any other errors in the container logs, let me know. It might give us another hint as to what's going awry.

**Comment by Mattyfaz** [comment]
@Tzahi12345 permissions I believe are okay:

![Screen Shot 2020-04-29 at 11 54 50 am](https://user-images.githubusercontent.com/10377148/80554362-3d40fb00-8a10-11ea-83ce-be919e54cd8b.png)

I do have `app/subscriptions/` mapped like so:

![Screen Shot 2020-04-29 at 11 39 15 am](https://user-images.githubusercontent.com/10377148/80554392-50ec6180-8a10-11ea-8bd1-0df24f2c211b.png)

It appears to be creating the directory in subscriptions correctly (using playlist name as the folder name), then an archive.txt file inside it (although archive.txt is blank).

![Screen Shot 2020-04-29 at 11 56 49 am](https://user-images.githubusercontent.com/10377148/80554478-a88acd00-8a10-11ea-8789-26c4555d7d7b.png)

Before testing this all again I restarted the container, logs aren't showing any errors but same behavior is occurring. Add the channel or playlist, refresh, and it's gone.

Let me know if you need anything else!

**Comment by Tzahi12345** [comment]
Hm this is getting interesting. Maybe the archive stuff was a red herring? With the subscription disappearing still, this might be a database issue. Hard to tell at this point, but can you share your `appdata/db.json` file? The subscriptions would appear here if they still existed. If they're not, maybe something is deleting or overriding it.

**Comment by Mattyfaz** [comment]
@Tzahi12345 Ooo the `appdata/db.json` file is definitely doing something funny!

When I download a single video, I can see the `db.json` file populating. However as soon as I save a playlist or channel, `db.json` is wiped. If I go back and try and add another single video it is restored, but `"subscriptions": []` is empty, and trying to add any always clears it.

Recording below:

![Screen-Recording-2020-04-29-at-1 14 43-pm](https://user-images.githubusercontent.com/10377148/80557870-aed27680-8a1b-11ea-8a5a-8ed5b20bd5f0.gif)

**Comment by Tzahi12345** [comment]
Awesome detective work! I thought about it a bit more, and I think it's a bug that's quite easy to fix. Basically, I import the database twice (once in `app.js`, and another in `subscriptions.js`), which I don't think is the correct way to do it. I should instead import it once and pass variable wherever I need to use a database. It seems like the two imports are interfering with each other (maybe trying to write/read at the same time), and that's why it's behaving this way.

Not sure why it only happens on some platforms. I've dealt with inconsistencies in the past with the double imports, but I assumed because they dealt with entirely different parts of the database, it would be fine.

Having all the database calls be under one umbrella *should* resolve this issue. I'll leave this issue open until that gets done.

**Comment by saponace** [comment]
I had the same issue as @Mattyfaz. Indeed fixed in the latest nightly.

Thank you very much for your amazing work @Tzahi12345 by the way :D

**Comment by Tzahi12345** [comment]
Great to hear! It's a pleasure, thank *you* for the confirmation :)

@Mattyfaz @saponace Closing issue now, thanks for all the help!
