### ISSUE TITLE
Changing where the thumbnailURL are located

### ISSUE THREAD

**Issue by sergio45012** [Tzahi12345/YoutubeDL-Material#620]
Dear,

I'm unable to find any option to find an approach to save the thumbnail to the MongoDB or to the files system and therefore use this as source of the web intefrace thumbnails, instead of going to https://i.ytimg.com.

Is it possible to changed this thumbnail creation from https://i.ytimg.com to be create it locally (file system or MongoDB)?

Let's imagine a 5000 video library, for each of them has to connect to https://i.ytimg.com and download the thumbnail, I think would be much more efective to be located at the MondoDB itself (without dependencies on third party webs).

Thanks.

**Comment by GlassedSilver** [comment]
https://github.com/yt-dlp/yt-dlp#thumbnail-options

That's all that's needed :) It will download and use the thumbnail accordingly. The thumbnail URL will remain the same, however YTDL-M will, if present at the time of downloading, using any local assets.

I do agree though that thumbnail downloading should become a default argument., in fact it's in my personal notes to discuss with @Tzahi12345. :)
