### ISSUE TITLE
[FEATURE] Progress and status of downloads

### ISSUE THREAD

**Issue by Bastians-Bits** [Tzahi12345/YoutubeDL-Material#621]
**Is your feature request related to a problem? Please describe.**
It is hard to figure out if a video is currently downloading or if there are problems. Often the log won't print anything or not enough and won't print to which download the messages are related.

**Describe the solution you'd like**
A pages which shows the current downloads (if possible with progress bar, though I can imagine that can be tricky if the source won't provide a total file size) and a history of previous download and errors if they failed.

**Additional context**

**Comment by GlassedSilver** [comment]
Use nightly build, you‘re obviously on latest or you would have the Download manager page.

See PR #420

**Comment by GlassedSilver** [comment]
Duplicate of #411
