### ISSUE TITLE
Container version (unraid) does not contain database configuration

### ISSUE THREAD

**Issue by jxbolt** [Tzahi12345/YoutubeDL-Material#629]
I have tried installing from CA, Docker, and Docker CLI on my unraid box and in all scenarios the database options as noted in the documentation (https://github.com/Tzahi12345/YoutubeDL-Material/wiki/unRAID) is not available in the 'settings' of the UI. 

I tried to add the configuration using variables in the Unraid Docker configuration for the container but the settings are never picked up so the json database is used still. 

Is this a bug in the build is the containers only or am I missing a step?

**Comment by GlassedSilver** [comment]
You're probably not using the nightly tag, could that be?

**Comment by jxbolt** [comment]
That was exactly the issue. I missed the "USAGE OF THE NIGHTLY BUILDS IS HIGHLY RECOMMENDED." headline about 50 times. Thank you for helping!
