### ISSUE TITLE
[Feature Request] Specify subdirectory at download time

### ISSUE THREAD

**Issue by spruceb** [Tzahi12345/YoutubeDL-Material#63]
It'd be very convenient for me to be able to specify a subdirectory I'd like videos to be downloaded to at download time. This would greatly help keeping the download directories somewhat organized. Especially useful for channel and playlist downloads (which seem to explode everywhere, unless I've missed a setting).

**Comment by Tzahi12345** [comment]
This is already possible, but with the limitation that it is relative to the download directories in the settings (`audio/` and `video/`). 

If you enable `Allow advanced download` in the `Advanced` tab in the settings, you'll see a new panel show up in the home screen with a `Custom output` option. 

So if you want a channels videos to go into `video/CHANNEL_NAME` folder with the video title as the file name, your custom output would be `%(uploader)s/%(title)s`. Note that the file extension is also skipped.

If you're looking for it to be truly customizable (as in *not* having the limitation I described above), it isn't currently possible. If the current setup doesn't work, I can look into adding that as a feature in the next couple updates.

Hope this helps!

**Comment by spruceb** [comment]
Yup that's great, pretty much exactly what I was looking for! I'd looked through the settings, I just didn't realize "advanced downloads" would let me do this. Thanks!

**Comment by Tzahi12345** [comment]
Awesome, glad I could help!
