### ISSUE TITLE
[BUG] Unable to download

### ISSUE THREAD

**Issue by Akinevz** [Tzahi12345/YoutubeDL-Material#634]
**Describe the bug**
Unable to download video/audio on TrueNAS (FreeBSD). No previews. Tried 4.2, and 4.1.

**To Reproduce**
1. Install on TrueNAS
2. npm install
3. create rc.d service (optional)
4. run npm start

**Expected behavior**
A UI shows video download / error message. Error message in the log

**Screenshots**
![image](https://user-images.githubusercontent.com/1402632/171750029-4fc03638-5532-4fa1-b693-20c47cf1dd31.png)

**Environment**
- YoutubeDL-Material v4.1 pictured above
- TrueNAS 13

**Additional context**
Used to work on a previous version 3.x. After reinstalling wont download anything. Timeouts after a few seconds saying that video can't be downloaded. On version 4.1 it shows an error in the log. On version 4.2 it reports nothing

**Comment by Akinevz** [comment]
`youtube_dl ${video_file}` works perfectly fine in the terminal

**Comment by Akinevz** [comment]
![image](https://user-images.githubusercontent.com/1402632/171751158-ef01bb00-ced6-4f29-ba55-5fb60dc73026.png)
hangs on this screen until an "error occured" popup appears

**Comment by Akinevz** [comment]
![image](https://user-images.githubusercontent.com/1402632/171754606-6ebd9067-b28b-42ee-935a-8c1bbb0ac8f2.png)

**Comment by Akinevz** [comment]
Download starts 
![image](https://user-images.githubusercontent.com/1402632/171756200-eb2e2122-4256-4927-969f-93a7226fa937.png)

but errors out after a few megabyes

**Comment by bfg-coding** [comment]
This issue is also happening on Raspberry PI setup from the docker image.  I'm getting an `ERROR: ` with no details on the issue in the logs

**Comment by miguelarios** [comment]
I am also unable to download any videos with latest update on UnRAID.

**Comment by GlassedSilver** [comment]
> I am also unable to download any videos with latest update on UnRAID.

The CA template that is out there assumes `latest` tag to be the one to go for afaik. Please switch to nightly instead for now at least, until 4.3 releases.

**Comment by Akinevz** [comment]
Ah I see, so to fix the issue, just download the repo instead of the release?

**Comment by Akinevz** [comment]
Would you mind if I made a pull request on the documentation to outline that once I have a successful install?

**Comment by Tzahi12345** [comment]
If you're not using Docker you'll have to follow the steps listed in the [build it yourself](https://github.com/Tzahi12345/YoutubeDL-Material#build-it-yourself) section of the README, not sure if this would work with TrueNAS.

Give me a second I'll try for locate a zip file that might work for you...
