### ISSUE TITLE
File creation umask

### ISSUE THREAD

**Issue by chimlm** [Tzahi12345/YoutubeDL-Material#66]
Please provide a method to change the file creation umask, preferably via an environmental variable.

I run this app in a docker container if that matters.

**Comment by Tzahi12345** [comment]
Seems like [this is possible](https://stackoverflow.com/a/34721366), and it doesn't look too difficult to implement. I will say that I'm not sure what the consequences of certain umask values would be. As long as the node process can read/write files in the directory it should be fine.

I'll look into it more, but it looks like an easy feature to add, especially as an env var. Thanks for the suggestion!

**Comment by Tzahi12345** [comment]
Just wanted to drop in and let you know this has been implemented and you'll be able to use it in the next update, which is dropping in a few days. Alternatively, you can use the `nightly` tag on Docker to test it out now.

The environment variable is YTDL_UMASK, and you have to set it to the umask in decimal form (usually it's an octal). I haven't been able to properly test it as I develop on Windows, so let me know if you run into any issues with the umask.

Here's the [relevant commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/26ad1955976b6aab73909e9c81d66e1e9f2be2bf).
