### ISSUE TITLE
[FEATURE] Using npm start 

### ISSUE THREAD

**Issue by martadinata666** [Tzahi12345/YoutubeDL-Material#662]
**Is your feature request related to a problem? Please describe.**
By default the youtubedl-m use PM2 runtime, that need installed manually `npm install -g pm2` that need use root permission. By using `npm start` in package.json. We can include pm2 in backend dependencies and set npm start to `pm2-runtime --raw pm2.config.js` then dropping the need install pm2-runtime with root permission.

Looking from https://github.com/Tzahi12345/YoutubeDL-Material/blob/6fa4296edfbc7d3201a9722558e171d29f486537/backend/package.json#L8 seems youtubedl-m used to be using `nodemon` and `spoiler: i tried and it not working`.

**Describe the solution you'd like**
1. Change `npm start` to `pm2-runtime --raw pm2.config.js`
2. Add pm2-runtime to backend dependencies

**Additional context**
Using `npm start` will likely easier reproducible runtime, as user doesn't need to manually install pm2.

https://github.com/Tzahi12345/YoutubeDL-Material/pull/657

**Comment by Tzahi12345** [comment]
I removed all references to nodemon: https://github.com/Tzahi12345/YoutubeDL-Material/pull/657/commits/0ffd7022d0a44ac7e361652e97069e681aa4429c

I'm not an npm expert, but I'm not positive that adding pm2-runtime to `package.json` in `backend` will work (https://stackoverflow.com/a/10813149/8088021). The instructions on the [npm page](https://www.npmjs.com/package/pm2) also only say to use the -g.

Does npm start circumvent this somehow by including commands from node_modules?

**Comment by martadinata666** [comment]
I tried locally it work fine, `npm` will include command from `node_modules`.
```
debian@18fc2d8d6978:~/youtubedl-material$ cat package.json | grep start
    "start": "pm2-runtime --raw pm2.config.js",
      "restart_update.json",
      "restart_general.json"
debian@18fc2d8d6978:~/youtubedl-material$ pm2-runtime --raw pm2.config.js
bash: pm2-runtime: command not found
debian@18fc2d8d6978:~/youtubedl-material$ npm start

> backend@1.0.0 start
> pm2-runtime --raw pm2.config.js

2022-06-24T11:56:47: PM2 log: Launching in no daemon mode
2022-06-24T11:56:47: PM2 log: [Watch] Start watching YoutubeDL-Material
2022-06-24T11:56:47: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
2022-06-24T11:56:47: PM2 log: App [YoutubeDL-Material:0] online
2022-06-24T04:56:48.209Z INFO: Config items set using ENV variables.
2022-06-24T04:56:48.876Z INFO: YoutubeDL-Material v4.2 started on PORT 8080
```

The caveat is, when run the binaries directly need to use `npx`.
```
debian@18fc2d8d6978:~/youtubedl-material$ pm2 list
bash: pm2: command not found
debian@18fc2d8d6978:~/youtubedl-material$ npx pm2 list
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ YoutubeDL-Material │ fork     │ 1    │ online    │ 0%       │ 87.7mb   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
debian@18fc2d8d6978:~/youtubedl-material$ 
```
But it just preferences, as i prefer reduce usage of root installation much as possible.
