### ISSUE TITLE
[BUG] Tasks section accessible to all users

### ISSUE THREAD

**Issue by adripo** [Tzahi12345/YoutubeDL-Material#684]
**Describe the bug**
http://localhost/#/tasks is accessible to all users even it is not visible in the left-side menu.

**To Reproduce**
1. Go to 'http://localhost/#/tasks'

**Expected behavior**
Users with no Tasks permission (Download manager) should not access the section

**Screenshots**
![image](https://user-images.githubusercontent.com/26493496/176559690-d2d6142f-f0a8-4f99-b3d6-1a51f9419a41.png)

**Environment**
- YoutubeDL-Material version
- Docker tag: latest

Ideally you'd copy the info as presented on the "About" dialogue
in YoutubeDL-Material.
(for that, click on the three dots on the top right and then
check "installation details". On later versions of YoutubeDL-
Material you will find pretty much all the crucial information
here that we need in most cases!)

Installed version: v4.3 -   You are up to date.
Installation type: docker
Docker tag: latest
Commit hash: e726e99
Build date: 2022-06-27

**Comment by adripo** [comment]
I just found out that this problem also applies to the other sections, for example `settings` (localhost/#/settings)

**Comment by Tzahi12345** [comment]
Should be fixed with #687! Once this merges I'll update the release.
