### ISSUE TITLE
[BUG] download playlist (no subscription)

### ISSUE THREAD

**Issue by adripo** [Tzahi12345/YoutubeDL-Material#686]
**Describe the bug**
If I download a playlist URL the interface will only show one video/audio, but all the files will be downloaded

**To Reproduce**
1. Go to 'home'
2. Paste https://www.youtube.com/playlist?list=PLJP5_qSxMbkI7B5W8uo_FLAtmSKwhxXLt
3. (optional) click on audio only for faster results

**Expected behavior**
All videos/audios to be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/26493496/176570886-4829ab69-ed1a-40aa-a59b-491b86ba432f.png)
![image](https://user-images.githubusercontent.com/26493496/176570905-8b65fcd2-4d29-41dc-871a-56a8a66d40ff.png)
![image](https://user-images.githubusercontent.com/26493496/176570935-8c91db1e-1a6f-4c8b-8a0e-5007ebf6f790.png)
![image](https://user-images.githubusercontent.com/26493496/176570947-ba9ea9d0-b0fa-4c45-9416-80434e4b8c46.png)

**Environment**
- YoutubeDL-Material version
- Docker tag: latest (optional)

**Additional context**
If the video is deleted from the interface, the files will nnot be removed from the file system

**Comment by Tzahi12345** [comment]
Was able to reproduce, looks like in yt-dlp the `--print-json` arg is [not recommended](https://github.com/yt-dlp/yt-dlp#not-recommended) so I replaced the arg with yt-dlp's recommended ones. Looks like that fixed the issue.

See commit here: https://github.com/Tzahi12345/YoutubeDL-Material/commit/768798c6b37bcf71a02df1fa8160d81deb7da915

Thanks for the bug report!
