### ISSUE TITLE
[BUG] videos are still downloaded after removing subscription

### ISSUE THREAD

**Issue by adripo** [Tzahi12345/YoutubeDL-Material#689]
**Describe the bug**
If I add a subscription and remove it before the videos are downloaded, minutes later after the parse process completes I will find the downloaded files in the filesystem, but no reference in the ui.

**Comment by Tzahi12345** [comment]
Should be relatively simple to fix. We currently don't check if a sub still exists during any parts of the downloading process. We can add some checks periodically (i.e. at each step) and that should suffice.
