### ISSUE TITLE
Force autoplay

### ISSUE THREAD

**Issue by ibrahimk157** [Tzahi12345/YoutubeDL-Material#695]
Hi,

On previous versions of YoutubeDL-Material, when the user would input the url and hit download, it would automatically take them to the autoplay screen once the download has completed, such that they can then download the video/audio to their device from that screen. However, now with v4.3, the user first has to tick the autoplay box to get there. Would be nice if we had the option to force autoplay, such that it acts the same way it did with the previous versions. As this is the most sensible way of operating this for those of us who just want this as a youtube downloader (to download youtube videos to our devices). 

This further expands on https://github.com/Tzahi12345/YoutubeDL-Material/issues/545#issuecomment-1106021585 which is also aimed for those of us using this as a YouTube downloader to download videos to our devices (rather than the server).

Thanks!

**Comment by Tzahi12345** [comment]
Right now we have an "allow autoplay" checkbox. Having both "allow autoplay" and "force autoplay" would be a bit confusing.

The more I think of it, the more I realize "force autoplay" is a more useful setting to have.

I made [a poll](https://github.com/Tzahi12345/YoutubeDL-Material/discussions/698), if it doesn't get interest I'll do it anyways. Thanks for the suggestion!
