### ISSUE TITLE
[BUG] Error converting Facebook video to mp4

### ISSUE THREAD

**Issue by palla89** [Tzahi12345/YoutubeDL-Material#699]
**Describe the bug**
When downloading FB public video (example link: https://fb.watch/e3IVGVbLzj/ ) the download finish fine but in console it gives an error and doesn't convert the video to the expected format (mp4)

Is this something known?

**To Reproduce**
Just download a FB video

**Expected behavior**
I'd expect to have the final video in mp4 format

**Screenshots**

![Schermata 2022-07-05 alle 10 51 59](https://user-images.githubusercontent.com/12301205/177289619-961b4aba-830a-42e5-a7f2-e935b93beebd.png)

 these are the files I get in the download folder

![Schermata 2022-07-05 alle 10 52 17](https://user-images.githubusercontent.com/12301205/177289667-a30a94da-2fcb-4812-9866-0388643a9955.png)

**Environment**
- YoutubeDL-Material version: latest nightly
- Docker tag: nightly

**Comment by Tzahi12345** [comment]
Just tested it out on my own, not getting that error. Can you set log level to verbose and paste the logs?

**Comment by Tzahi12345** [comment]
At least with yt-dlp it works for me. Let me know if you're still seeing this with yt-dlp!
