### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by DorianVasco** [Tzahi12345/YoutubeDL-Material#7]
I installed and ran the app on a fresh sub domain, but the download of a converted does not work.
I checked the file names in the video/ directory and indeed they differ from the requested file name:

- file name should be: ETH Zürich - Bereit.mp4
- file name is: ETH Zürich - Bereit.f137.mp4

**Comment by Tzahi12345** [comment]
Did some testing where this issue came up. I fixed it by installing youtube-dl globally. Run

`sudo apt-get install youtube-dl` and let me know if that fixes the issue for you.

**Comment by DorianVasco** [comment]
Yep, that fixed it!

**Comment by DorianVasco** [comment]
Well, kind of: the playback on the following page does work, but the download is still broken, maybe because of the file name encoding?
- file name in video/ dir: ETH Zürich - Bereit.mp4
- requested file name: ETH%20Z%C3%BCrich%20-%20Bereit.mp4

the error on the node side is:
Error: ENOENT: no such file or directory, stat '/var/customers/webs/dorian/ytdl.dododata.de/backend/video/ETH%20Z%C3%BCrich%20-%20Bereit.mp4'

**Comment by Tzahi12345** [comment]
Tracked down the bug, thanks for the help! I've released a new update (3.2) that fixes this, and implements a few other features. Check it out [here](https://github.com/Tzahi12345/YoutubeDL-Material/releases/tag/v3.2).

Feel free to reopen if it comes back up, or open up a new issue if another bug comes around.
