### ISSUE TITLE
[FEATURE] Language selector at Personal Settings

### ISSUE THREAD

**Issue by tiagobugarin** [Tzahi12345/YoutubeDL-Material#714]
**Is your feature request related to a problem? Please describe.**
To change a language it is necessary to allow a user to access settings and after the change it may be the case that one would need to remove the settings access, so that the user would not be bothered with this extra panel.

**Describe the solution you'd like**
YoutubeLD-Material already have the "Personal Settings", a very good place to host a selector for the user preferred language.

**Additional context**
I don't think there is any additional context needed. If proven wrong I will update here.

**Comment by Tzahi12345** [comment]
This is done btw in v4.3.2!
