### ISSUE TITLE
[BUG] Subscription page only shows 10 videos

### ISSUE THREAD

**Issue by rockbo842** [Tzahi12345/YoutubeDL-Material#715]
**Describe the bug**
The subscription pages now only show 10 video thumbnails without the ability to see any of the other videos.

**To Reproduce**
1. Go to the top left hamburger menu.
2. Click on any of the playlists/subscriptions
3. Only 10 thumbnails are visible.

**Expected behavior**
The subscription page used to show the thumbnails for all of the videos downloaded for that subscription.  Now it behaves like the home page where only 10 thumbnails show up.  However, unlike the home page, there isn't an option to show more thumbnails.

**Screenshots**

**Environment**
- YoutubeDL-Material version 4.3
- Docker tag: nightly
- Unraid v6.9.2
![ytdl-issue](https://user-images.githubusercontent.com/72613909/180080777-0f8ae428-9dc4-426d-a4c2-eb66a3e5bfd7.png)

**Comment by SinisterCrayon** [comment]
I also see the same problem. There's no "browse bar" at the bottom to allow you to page through the subscriptions. I can only search, and I'd like the ability to actually browse through it as well.

**Comment by Tzahi12345** [comment]
Should be fixed in the latest nightly! See commit here: https://github.com/Tzahi12345/YoutubeDL-Material/commit/1f2c5a0238cce423da56d53612bc89f8967bbd2f
