### ISSUE TITLE
[FEATURE] Support YouTube Shorts

### ISSUE THREAD

**Issue by saschafoerster** [Tzahi12345/YoutubeDL-Material#716]
I would like to download YouTube Shorts. I think that youtube-dl does support this in a newer version. I tried it with YouTubeDL-Material 4.3 and got an error message: 

`Error while retrieving info on video with URL https://www.youtube.com/shorts/lqzur_4fWEM with the following message: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -i -o users/admin/video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail -r 200K --dump-json https://www.youtube.com/shorts/lqzur_4fWEM ERROR: Unable to extract ytInitialData; please report this issue on https://github.com/blackjack4494/yt-dlc . Make sure you are using the latest version; type youtube-dlc -U to update. Be sure to call youtube-dlc with the --verbose flag and include its complete output.`

**Comment by saschafoerster** [comment]
Same with youtube-dl (and not dlc): 

`Error while retrieving info on video with URL https://www.youtube.com/shorts/lqzur_4fWEM with the following message: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -i -o users/admin/video/%(title)s.mp4 --write-info-json --print-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail -r 200K --dump-json https://www.youtube.com/shorts/lqzur_4fWEM ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by Tzahi12345** [comment]
With yt-dlp it works!

I added the following warning for v4.3.1 if you are not using yt-dlp.

https://github.com/Tzahi12345/YoutubeDL-Material/blob/e2c68713ba577bc4a2573c112b7530ef8b1c3422/backend/downloader.js#L423-L425
