### ISSUE TITLE
How to add a password so that no one else can use it

### ISSUE THREAD

**Issue by topmask** [Tzahi12345/YoutubeDL-Material#722]
How to add a password so that no one else can use it

Where to modify the downloaded folder

**Comment by lawrencecandilas** [comment]
Simplest thing to do if you already have it behind a reverse proxy is to enable HTTP Authentication on the reverse proxy.
Instructions for Nginx: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

**Comment by Sardelka9515** [comment]
Enable multi users mode in settings, it'll ask you to create admin account, then you can disable user registration in settings

**Comment by Tzahi12345** [comment]
@Sardelka9515 is correct, you should enable multi-user mode. Let me know if you have trouble doing so.
