### ISSUE TITLE
Same path and file name flexibility for subscriptions as for regular downloads

### ISSUE THREAD

**Issue by GlassedSilver** [Tzahi12345/YoutubeDL-Material#73]
As discussed in issue #52 ([link to post](https://github.com/Tzahi12345/YoutubeDL-Material/issues/52#issuecomment-624250568))

Adding this issue for tracking and as a "memo".

**Comment by Tzahi12345** [comment]
Done! Check out the [PR here](https://github.com/Tzahi12345/YoutubeDL-Material/pull/136). Custom output uses the same setup as the custom output in the Advanced download menu: it's relative to the existing path and a file extension is not required. Pull the latest `nightly` and check it out!
