### ISSUE TITLE
Really slow download speeds

### ISSUE THREAD

**Issue by TheNighthawk99** [Tzahi12345/YoutubeDL-Material#732]
Hello,
not sure it is a real bug, but what I see currently is a very poor download speed.
The progress indicator shows about 0,02% every second or so.
This is the video I am downloading: https://www.youtube.com/watch?v=ojInWdxwlFI.
I have chosen to download at 1080p30, which should not be a super monster download size. However, I am only at 33% right now and It is about 30 minutes (or so) I have started.
I have just run a speedtest just to avoid any issue at my side and I got almost 50 Mbit/s in download. So this is not a problem of my connection.

Could it be a download cap setup by YT for who use YouTube-dl?

**Comment by Tzahi12345** [comment]
Sorry for the late response, it's likely you were using youtube-dl. The default now is yt-dlp and is highly recommended. Let me know if you're still seeing this with yt-dlp.
