### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Cyberbuy** [Tzahi12345/YoutubeDL-Material#737]
**Describe the bug**
On iPad Music play doesńt work. Please help

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/111644731/185748403-f736d1af-e13f-47e9-a85e-bf4b4a1c8949.jpeg)

**Environment**
- Installierte Version: v4.3 - done  You are up to date.

Installation type: docker 
Docker tag: latest 
Commit hash: 64b1a9e 
Build date: 2022-06-30

Ideally you'd copy the info as presented on the "About" dialogue
in YoutubeDL-Material.
(for that, click on the three dots on the top right and then
check "installation details". On later versions of YoutubeDL-
Material you will find pretty much all the crucial information
here that we need in most cases!)

**Additional context**
Add any other context about the problem here. For example, a YouTube link.

**Comment by Tzahi12345** [comment]
This could be a codec issue, can you try adding this to your custom args?

https://github.com/Tzahi12345/YoutubeDL-Material/issues/764#issuecomment-1528873752
