### ISSUE TITLE
[BUG] "mongo-db exited with code 132"

### ISSUE THREAD

**Issue by KaKi87** [Tzahi12345/YoutubeDL-Material#739]
**Describe the bug**
`docker-compose up` is stuck with an `mongo-db exited with code 132` error.

**To Reproduce**

1. `mkdir YoutubeDL-Material`
2. `cd YoutubeDL-Material`
3. `curl -L https://github.com/Tzahi12345/YoutubeDL-Material/releases/latest/download/docker-compose.yml -o docker-compose.yml`
4. `docker-compose pull`
5. `docker-compose up`

**Expected behavior**
The app starts successfully

**Screenshots**

```
Creating network "youtubedl-material_default" with the default driver
Creating mongo-db ... done
Creating youtubedl-material_ytdl_material_1 ... done
Attaching to mongo-db, youtubedl-material_ytdl_material_1
mongo-db         | WARNING: no logs are available with the 'none' log driver
mongo-db exited with code 132
```

**Environment**

- YoutubeDL-Material version: -
- Docker tag: `latest`

**Additional context**
None

---

Thanks

**Comment by MrUhu** [comment]
Based on this https://forums.docker.com/t/docker-container-exited-with-code-132/113173 I used version 4.4.9 for my mongodb, because my processor isn't supporting AVX which is required for mongodb 5+.

Try changing
  image: mongo
to
  image: mongo:4.4.9

**Comment by KaKi87** [comment]
That works, thanks !
