### ISSUE TITLE
[BUG] Bug with two videos on a specific channel with sponserblock. ".en.temp.vtt.concat: Numerical result out of range"

### ISSUE THREAD

**Issue by Glynax** [Tzahi12345/YoutubeDL-Material#744]
**Describe the bug**
I don't really understand the error. See attached. 
![image](https://user-images.githubusercontent.com/7043861/188056345-4bd7cc96-c643-49fa-9e7a-8ccf170d3127.png)
![image](https://user-images.githubusercontent.com/7043861/188056365-ae30847e-2560-4ae4-b46b-65a6dd4480e3.png)
and here's the folder with the rest of the channel, it seems to download them, both the temp video and the other work, with the temp being shorter (sponser block worked I believe)
![image](https://user-images.githubusercontent.com/7043861/188056413-b20e3757-c1fe-41b7-bb46-9475f9c1a901.png)

**To Reproduce**
1. Subscribe to https://www.youtube.com/c/NGPlusVideos with these custom args --add-metadata,,--write-info-json,,--write-thumbnail,,--all-subs,,--sponsorblock-remove,,all

**Expected behavior**
The rest of the channel seems to download fine, not sure why those two videos error.

**Screenshots**
See above

**Environment**
- YoutubeDL-Material version commit 9c0a77c
- Docker tag: nightly
![image](https://user-images.githubusercontent.com/7043861/188056606-e613c440-e3ee-49fe-9cad-2e83bbb6cd04.png)

Ideally you'd copy the info as presented on the "About" dialogue
in YoutubeDL-Material.
(for that, click on the three dots on the top right and then
check "installation details". On later versions of YoutubeDL-
Material you will find pretty much all the crucial information
here that we need in most cases!)

**Additional context**
Add any other context about the problem here. For example, a YouTube link.

**Comment by Tzahi12345** [comment]
It works on my end, maybe this was a yt-dlp bug?

I tried downloading this vid in particular (not as part of a subscription) and I didn't see this error: https://www.youtube.com/watch?v=b0o9dVmiT1E

Would you mind trying again and seeing if it works?
