### ISSUE TITLE
"Not a valid URL" when using filter

### ISSUE THREAD

**Issue by randalotto** [Tzahi12345/YoutubeDL-Material#745]
I'm trying to set up a subscription to a Youtube channel (https://www.youtube.com/c/NBCSports/videos) that will download only videos with specific keywords in the title ("premier league highlights"). 

I'm using the yt-dlp downloader.

I set up the subscription with the following custom argument: 
--match-filter,,title ~='(?i)\bpremier league highlights\b'

Everything initially runs fine and the downloader identifies videos to download, but then throws an error when it tries to actually download the video. 

It seems like an extra "--match-filter ..." is somehow being passed to the download instructions. Here are some representative log entries;

VERBOSE: Subscription: getting videos for subscription PL2 with args: --dump-json,-o,"subscriptions/channels/PL2/%(title)s.%(ext)s",-ciw,--write-info-json,--print-json,-f,bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4,--match-filter,title ~='(?i)\bpremier league highlights\b',--dateafter,now-5days,--cookies,appdata/cookies.txt,--write-thumbnail,--no-clean-info-json

VERBOSE: Collecting info for download 95489514-daeb-4af8-8869-7805cee3bd6a

VERBOSE: yt-dlp args being used: -o,subscriptions/channels/PL2/%(title)s.%(ext)s,--write-info-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--cookies,appdata/cookies.txt,--write-thumbnail,**--match-filter,title ~='(?i)\bpremier league highlights\b',title ~='(?i)\bpremier league highlights\b'**,--no-clean-info-json,-j,--no-simulate

VERBOSE: Downloading 95489514-daeb-4af8-8869-7805cee3bd6a

ERROR: ERROR: [generic] "title ~='(?i)\bpremier league highlights\b'" is not a valid URL. Set --default-search "ytsearch" (or run yt-dlp "ytsearch:title ~='(?i)\bpremier league highlights\b'" ) to search YouTube

If I go into the GUI and tell a failed download to retry, it produces this error:

Error while retrieving info on video with URL https://www.youtube.com/watch?v=eVwTAqAu9Mk with the following message: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -o subscriptions/channels/PL2/%(title)s.%(ext)s --write-info-json -f bestvideo+bestaudio --merge-output-format mp4 --cookies appdata/cookies.txt --write-thumbnail --match-filter title ~='(?i)\bpremier league highlights\b' title ~='(?i)\bpremier league highlights\b' --no-clean-info-json -j --no-simulate --dump-json http://www.youtube.com/watch?v=eVwTAqAu9Mk

ERROR: [generic] "title ~='(?i)\bpremier league highlights\b'" is not a valid URL. Set --default-search "ytsearch" (or run yt-dlp "ytsearch:title ~='(?i)\bpremier league highlights\b'" ) to search YouTube

Installation details:
Installed version: v4.3
Installation type: docker
Docker tag: nightly
Commit hash: 9c0a77c
Build date: 2022-08-30

**Comment by jvgoch** [comment]
+1 having the same issue. But for me the video does download and it throws the error at the end making YoutubeDL Material think the download has failed.

**Comment by mikeyounge** [comment]
+1 My issue has been with —min-filesize. Anytime a value is added for an argument, it gets added twice to the YouTube-dl command. The second value throws the error.

yt-dlp args being used: -o,subscriptions/channels/Cracking The Cryptic/%(uploader)s [%(channel_id)s]/%(upload_date).4s/%(uploader)s - S%(upload_date).4sE%(upload_date)s - %(title)s [%(id)s].%(ext)s,--write-info-json,-f,bestvideo+bestaudio,--merge-output-format,mp4,--download-archive,subscriptions/archives/Cracking The Cryptic/merged_video.txt,--write-thumbnail,-i,--restrict-filenames,-w,--min-filesize,5m,5m,--no-clean-info-json,-j,--no-simulate

**Comment by Tzahi12345** [comment]
Figured out what was going on, should be fixed when this PR is merged: https://github.com/Tzahi12345/YoutubeDL-Material/pull/873
