### ISSUE TITLE
unraid install?

### ISSUE THREAD

**Issue by pairofcrocs** [Tzahi12345/YoutubeDL-Material#75]
I'm probably an idiot but I figured I'd throw it here just to find out.

I'm trying to install via CA and upon finishing the install the container isn't starting and this is what my conainter spits out.

`internal/fs/utils.js:220
throw err;
^

Error: ENOENT: no such file or directory, open 'appdata/default.json'

at Object.openSync (fs.js:440:3)
at Object.readFileSync (fs.js:342:35)
at getConfigFile (/app/config.js:65:23)
at getConfigItem (/app/config.js:85:23)
at ensureConfigItemsExist (/app/config.js:20:9)
at Object.initialize (/app/config.js:13:5)
at Object.<anonymous> (/app/app.js:74:12)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load (internal/modules/cjs/loader.js:811:32)
at Function.Module._load (internal/modules/cjs/loader.js:723:14)
at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
at internal/main/run_main_module.js:17:11 {
errno: -2,
syscall: 'open',
code: 'ENOENT',
path: 'appdata/default.json'
}`

I don't have default.json in my appdata folder and I don't see install guides talking about it.

Any information would be very helpful,

Thanks!

**Comment by Tzahi12345** [comment]
It sounds like the config is missing. You can grab the default.json from [here](https://raw.githubusercontent.com/Tzahi12345/YoutubeDL-Material/master/backend/appdata/default.json). I thought I made it so the config would restore from default if not found, but maybe it only works for individual settings and not the entire file.

If you drop the config above into the `appdata` folder it should run just fine. I'll also make it so the server checks if the config file exists on start. Lmk if it helps!

**Comment by GlassedSilver** [comment]
> 
> 
> I'm probably an idiot but I figured I'd throw it here just to find out.
> 
> I'm trying to install via CA and upon finishing the install the container isn't starting and this is what my conainter spits out.
> 
> `internal/fs/utils.js:220
> throw err;
> ^
> 
> Error: ENOENT: no such file or directory, open 'appdata/default.json'
> 
> at Object.openSync (fs.js:440:3)
> at Object.readFileSync (fs.js:342:35)
> at getConfigFile (/app/config.js:65:23)
> at getConfigItem (/app/config.js:85:23)
> at ensureConfigItemsExist (/app/config.js:20:9)
> at Object.initialize (/app/config.js:13:5)
> at Object. (/app/app.js:74:12)
> at Module._compile (internal/modules/cjs/loader.js:955:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
> at Module.load (internal/modules/cjs/loader.js:811:32)
> at Function.Module._load (internal/modules/cjs/loader.js:723:14)
> at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
> at internal/main/run_main_module.js:17:11 {
> errno: -2,
> syscall: 'open',
> code: 'ENOENT',
> path: 'appdata/default.json'
> }`
> 
> I don't have default.json in my appdata folder and I don't see install guides talking about it.
> 
> Any information would be very helpful,
> 
> Thanks!

That's because the CA that has been published has been rushed to release to be very frank. I am still evaluating the unRAID environment myself and am actually running my own template that I will release eventually when the time is right. So far it isn't. I'm afraid the application may get a bad rep in the unRAID community, so that's why I won't release it until it's proven itself in this environment for a while.

**Comment by Tzahi12345** [comment]
@GlassedSilver I see what you mean. Stability is key, but as long as we keep working towards that, the good experiences will start outweighing the bad. Hopefully it doesn't leave a bad taste in too many people's mouths.

Anyways, I've added some logic to recreate the file if it is missing, you can see that [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/550013a2e7bf99da868eb28d444fa4aaab1311dd). I'll get this in a release within the next couple days, hopefully.
