### ISSUE TITLE
[BUG] removeIDFromArchive leaves duplicate entries

### ISSUE THREAD

**Issue by BillSobel** [Tzahi12345/YoutubeDL-Material#755]
At least two others posts mention issues with the download queue and the app filling all of memory until it crashes. One side effect of that I saw was the merge and archive file had thousands of duplicate entries. Some of my merge and archive files were 85mb text files while others where 1k. 

The function below needs to remove all occurrences of the id (I believe) not just the first before rewriting the file back out. I see so many repeats and I suspect it was from the ID being written, then a crash with out of memory, restart, rinse repeat as the file filled over time.

async function removeIDFromArchive(archive_path, type, id) {
    const archive_file = path.join(archive_path, `archive_${type}.txt`);
    const data = await fs.readFile(archive_file, {encoding: 'utf-8'});
    if (!data) {
        logger.error('Archive could not be found.');
        return;
    }

    let dataArray = data.split('\n'); // convert file data in an array
    const searchKeyword = id; // we are looking for a line, contains, key word id in the file
    let lastIndex = -1; // let say, we have not found the keyword

    for (let index=0; index<dataArray.length; index++) {
        if (dataArray[index].includes(searchKeyword)) { // check if a line contains the id keyword
            lastIndex = index; // found a line includes a id keyword
            break;
        }
    }

    if (lastIndex === -1) return null;

    const line = dataArray.splice(lastIndex, 1); // remove the keyword id from the data Array

    // UPDATE FILE WITH NEW DATA
    const updatedData = dataArray.join('\n');
    await fs.writeFile(archive_file, updatedData);
    if (line) return Array.isArray(line) && line.length === 1 ? line[0] : line;
}

**Comment by Tzahi12345** [comment]
This is fixed in the latest nightly as we moved onto handling archive functionality in the DB rather than in the file system! See: #809
