### ISSUE TITLE
[BUG] downloader.js should use node-file-dedup instead of merge-files

### ISSUE THREAD

**Issue by BillSobel** [Tzahi12345/YoutubeDL-Material#756]
As written, after a download error the archive file is merged into the merged file and if the system crashes can merge in entries that already exist. Instead of merging the files, they should be deduced together so only one instance of each video occurs in the file. The change is to use nodeFileDedup.dedupe() instead of mergeFiles()

This seems related to the high memory use. On my system the text based archive file with 200 items queued was 85mb in text with the same ID's repeated countless times.

if (useYoutubeDLArchive) {
            const archive_folder = getArchiveFolder(fileFolderPath, options, user_uid);
            const archive_path = path.join(archive_folder, `archive_${type}.txt`);

            await fs.ensureDir(archive_folder);
            await fs.ensureFile(archive_path);

            const blacklist_path = path.join(archive_folder, `blacklist_${type}.txt`);
            await fs.ensureFile(blacklist_path);

            const merged_path = path.join(archive_folder, `merged_${type}.txt`);
            await fs.ensureFile(merged_path);
            // merges blacklist and regular archive
            let inputPathList = [archive_path, blacklist_path];
            await mergeFiles(inputPathList, merged_path);  <----- this should likely be nodeFileDedup.dedup(inputPathList, merged_path);

            options.merged_string = await fs.readFile(merged_path, "utf8");

            downloadConfig.push('--download-archive', merged_path);
        }

**Comment by Tzahi12345** [comment]
This will be resolved in the latest update (v4.3.1) as we move away from using youtube-dl's archive system and simulate it ourselves (i.e. no race conditions should exist now).
