### ISSUE TITLE
[BUG] Pagination missing from Subscription Pages

### ISSUE THREAD

**Issue by Atreidae** [Tzahi12345/YoutubeDL-Material#763]
**Describe the bug**
On both Channel and Playlist subscription pages, the pagination bar is missing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the left Nav Bar (Over or Side, it doesn't matter)
2. Click on Subscriptions, then any subscription.
3. Scroll down to the bottom of the videos
4. Note there is no navigation bar for pages, or item counts.

**Expected behavior**
Clicking on a subscription should allow you to navigate between pages, see item counts etc.

**Screenshots**
***Actual Behaviour***
![image](https://user-images.githubusercontent.com/8736291/193482440-16f61d6d-d7a9-4f02-bf99-c3c189d75290.png)

***Expected Behaviour***
![image](https://user-images.githubusercontent.com/8736291/193482408-a222744a-3c20-4de4-a31d-3bb14a07bea8.png)

**Environment**
Installed version: v4.3 -   You are up to date.
Installation type: docker
Docker tag: latest
Commit hash: fc3c179
Build date: 2022-07-05

**Additional context**

Looks like the mat-paginator container is missing inside the app-subscription container (apologies if I'm getting terms wrong. I'm a PowerShell guy. not web standards), I've also switched between "Over" and "Side" navbars to no effect.

**Comment by Atreidae** [comment]
This appears to be a duplicate of #715

**Comment by Tzahi12345** [comment]
Should be fixed in the latest nightly! See commit here: https://github.com/Tzahi12345/YoutubeDL-Material/commit/1f2c5a0238cce423da56d53612bc89f8967bbd2f
