### ISSUE TITLE
Incompatible codecs on Apple operating systems

### ISSUE THREAD

**Issue by ibrahimk157** [Tzahi12345/YoutubeDL-Material#764]
Hi,

I’ve noticed that sometimes when using the downloader to download videos to apple devices (both iOS and MacOS) it tends to download the video in an incompatible codec which can’t be played in these devices.

For example:

https://youtu.be/BuFheTMljZk

Consistently comes up as:

![12A5EE26-270F-4F72-B338-CF26863FE7DE](https://user-images.githubusercontent.com/17643723/194006273-4ca3d916-a3ae-4c91-b021-e95a837e7d8f.jpeg)

which cannot be played in apple devices.

I tried changing the downloading agent, changing between the different forks of youtube-dl. All to no avail.

Running the latest stable v4.3

**Comment by bbilly1** [comment]
You might have to choose a compatible video and audio codec in your format string, for example: 
```
bestvideo[vcodec*=avc1]+bestaudio[acodec*=mp4a]/mp4
```
yt-dlp will default to the incompatible *vp9* video codec, while *avc* should play fine.

**Comment by ibrahimk157** [comment]
> You might have to choose a compatible video and audio codec in your format string, for example:
> 
> ```
> bestvideo[vcodec*=avc1]+bestaudio[acodec*=mp4a]/mp4
> ```
> 
> yt-dlp will default to the incompatible _vp9_ video codec, while _avc_ should play fine.

Thanks for the reply!

This might sound dumb, but where exactly do I input the format string? Can’t find any option obvious option within settings.

I’ve tried all three of yt-dl, yt-dlc and yt-dlp and they all exhibit the same behavior… so switching between them isn’t enough it seems.

**Comment by Tzahi12345** [comment]
Sorry for the late reply, you just put it into your custom args like so:

```
-f,,bestvideo[vcodec*=avc1]+bestaudio[acodec*=mp4a]/mp4
```

It will replace the default formatting

**Comment by ibrahimk157** [comment]
> Sorry for the late reply, you just put it into your custom args like so:
> 
> ```
> -f,,bestvideo[vcodec*=avc1]+bestaudio[acodec*=mp4a]/mp4
> ```
> 
> It will replace the default formatting

Works like a charm!

Thanks loads!

I will go ahead and close this now.
