### ISSUE TITLE
[BUG] Subscriptions resolution choice leads to no download at all

### ISSUE THREAD

**Issue by matleborgne** [Tzahi12345/YoutubeDL-Material#769]
**Describe the bug**
With the engine yt-dlp, set a different quality than Best in subscription leads to no download at all.
With youtube-dl and youtube-dlc, it leads to video-only download (without audio).

**To Reproduce**
With 4.3 version :
- Subscribe to any channel, and change the quality to 1080p for instance

**Expected behavior**
The video would download in 1080p max.

**Environment**
- YoutubeDL-Material version 4.3
- Architecture : virtual machines on AlmaLinux and AlpineLinux

**Additional context**
I found a workaround, but it is not a really a "normal" behavior :
- set a custom arg :  -f bestvideo[height<=?1080]+bestaudio/best
- suscribe with default "Best" quality

**Comment by Tzahi12345** [comment]
Sorry for the late reply, can you set your log level to verbose in the settings and share the args being used?
