### ISSUE TITLE
[BUG] - configured logging driver does not support reading

### ISSUE THREAD

**Issue by RichardProchadzka** [Tzahi12345/YoutubeDL-Material#771]
Output: 

> $ sudo docker-compose up
> Creating network "yotube-dl_default" with the default driver
> Creating mongo-db ... done
> Creating yotube-dl_ytdl_material_1 ... done
> Attaching to yotube-dl_ytdl_material_1
> ERROR: configured logging driver does not support reading

compose.yml:
![image](https://user-images.githubusercontent.com/97609737/197269795-7b7c53c3-1a2d-4eea-bc68-2d1267c13a7e.png)

I changed logging to "local" and after that i have got HTTP error that it took long.

**Comment by gnatbandanna** [comment]
I fixed the "too long" dns issue by adding the following to /etc/docker/daemon.json 
{
  "dns": ["8.8.8.8"],
  "dns-search": ["local"]
}

And restarting docker. Change "local" to whatever is appropriate for you.

**Comment by RichardProchadzka** [comment]
Thanks now i have bunch of more issues :D can i copy paste ? 
I do not know what to do i tried a lot of like these things ,,, I just want selfhosted youtube-dl with ffmpeg support :D
i have orangePI running with ubuntu 20

**Comment by gnatbandanna** [comment]
Yeah, I was going to ask if you were trying this on a Pi (Raspian). I had the same first two problems you did since around v4.3 of ytdl-material.

I did not switch to local logging though. I changed to Mondo v4 via this post: https://github.com/Tzahi12345/YoutubeDL-Material/issues/733 and then added the daemon.json dns config options and it's been working fine on my Pi. Could you try maybe using Mondo v4 and see if that resolves all of your issues?

You're welcome to post any continuing issues, but I can't promise I'll know how to fix. Maybe someone else will though!

**Comment by RichardProchadzka** [comment]
sorry that i made this to you :D
 
 sudo docker-compose up                                                                                                          Recreating mongo-db ... done                                                                                                                                 yotube-dl_ytdl_material_1 is up-to-date                                                                                                                      Attaching to mongo-db, yotube-dl_ytdl_material_1                                                                                                             mongo-db         |                                                                                                                                           mongo-db         | WARNING: MongoDB 5.0+ requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!                                                                                                                                                          mongo-db         |   see https://jira.mongodb.org/browse/SERVER-55178                                                                                        mongo-db         |   see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features                                                 mongo-db         |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306                                                      mongo-db         |                                                                                                                                           ytdl_material_1  |                                                                                                                                           ytdl_material_1  | > backend@1.0.0 start                                                                                                                     ytdl_material_1  | > pm2-runtime --raw pm2.config.js                                                                                                         ytdl_material_1  |                                                                                                                                           ytdl_material_1  | 2022-10-21T18:48:38: PM2 log: Launching in no daemon mode                                                                                 ytdl_material_1  | 2022-10-21T18:48:38: PM2 log: [Watch] Start watching YoutubeDL-Material                                                                   ytdl_material_1  | 2022-10-21T18:48:38: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-                                                          ytdl_material_1  | 2022-10-21T18:48:38: PM2 log: App [YoutubeDL-Material:0] online                                                                           ytdl_material_1  | 2022-10-21T18:49:45.208Z INFO: Cannot find config file. Creating one with default values...                                               ytdl_material_1  | 2022-10-21T18:49:46.201Z INFO: Config items set using ENV variables.                                                                      ytdl_material_1  | 2022-10-21T18:51:01.902Z ERROR: getaddrinfo ENOTFOUND ytdl-mongo-db                                                                       ytdl_material_1  | 2022-10-21T18:51:02.120Z WARN: MongoDB connection failed! Retrying 5 times...                                                             ytdl_material_1  | 2022-10-21T18:51:33.666Z ERROR: getaddrinfo ENOTFOUND ytdl-mongo-db                                                                       ytdl_material_1  | 2022-10-21T18:51:33.720Z WARN: Retry 1 failed, waiting 2000ms before trying again.                                                        ytdl_material_1  | 2022-10-21T18:52:06.071Z ERROR: connect EHOSTUNREACH 172.20.0.3:27017                                                                     ytdl_material_1  | 2022-10-21T18:52:11.789Z WARN: Retry 2 failed, waiting 2000ms before trying again.                                                        ytdl_material_1  | 2022-10-21T18:52:52.149Z ERROR: getaddrinfo ENOTFOUND ytdl-mongo-db                                                                       ytdl_material_1  | 2022-10-21T18:52:52.709Z WARN: Retry 3 failed, waiting 2000ms before trying again.                                                        ytdl_material_1  | 2022-10-21T18:53:32.554Z ERROR: getaddrinfo ENOTFOUND ytdl-mongo-db                                                                       ytdl_material_1  | 2022-10-21T18:53:34.867Z WARN: Retry 4 failed, waiting 2000ms before trying again.                                                        ytdl_material_1  | 2022-10-21T18:54:28.408Z ERROR: connection timed out                                                                                      ytdl_material_1  | 2022-10-21T18:54:28.733Z WARN: Retry 5 failed.                                                                                            ytdl_material_1  | 2022-10-21T18:54:30.487Z ERROR: Failed to connect to MongoDB, using Local DB as a fallback. Make sure your MongoDB instance is accessible, or set Local DB as a default through the config.                                                                                                            ytdl_material_1  | 2022-10-21T18:54:51.165Z INFO: Beginning migration: 4.1->4.2+                                                                             ytdl_material_1  | 2022-10-21T18:55:31.284Z INFO: 4.1->4.2+ migration complete!                                                                              ytdl_material_1  | 2022-10-21T18:55:31.635Z INFO: Beginning migration: 4.2->4.3+                                                                             ytdl_material_1  | 2022-10-21T18:55:40.111Z INFO: 4.2->4.3+ migration complete!                                                                              ytdl_material_1  | 2022-10-21T18:55:40.651Z INFO: Checking if tasks manager role permissions exist for admin user...                                         ytdl_material_1  | 2022-10-21T18:55:40.825Z INFO: Task manager permissions check complete!                                                                   ytdl_material_1  | 2022-10-21T18:55:41.587Z INFO: Restarting server...                                                                                       ytdl_material_1  | 2022-10-21T18:55:48: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]                                         ytdl_material_1  | 2022-10-21T18:55:49: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-                                                          ytdl_material_1  | 2022-10-21T18:55:51: PM2 log: App [YoutubeDL-Material:0] online                                                                           ytdl_material_1  | 2022-10-21T18:55:51: PM2 error: Error caught while calling pidusage                                                                       ytdl_material_1  | 2022-10-21T18:55:52: PM2 error: Error: ESRCH: no such process, read                                                                       ytdl_material_1  | 2022-10-21T18:55:52: PM2 log: 0 application online, retry = 3                                                                             ytdl_material_1  | 2022-10-21T18:58:50.736Z INFO: Config items set using ENV variables.                                                                      ytdl_material_1  | 2022-10-21T18:59:34.836Z ERROR: connect ECONNREFUSED 172.20.0.3:27017                                                                     ytdl_material_1  | 2022-10-21T18:59:37.327Z WARN: MongoDB connection failed! Retrying 5 times...                                                             ytdl_material_1  | 2022-10-21T19:01:20.244Z ERROR: connection timed out                                                                                      ytdl_material_1  | 2022-10-21T19:01:20.424Z WARN: Retry 1 failed, waiting 2000ms before trying again.                                                        ytdl_material_1  | 2022-10-21T19:01:22.605Z ERROR: Failed to get config file                                                                                 ytdl_material_1  | TypeError: Cannot use 'in' operator to search for 'YoutubeDLMaterial' in null                                                             ytdl_material_1  |     at Function.Object.byString (/app/config.js:37:15)                                                                                    ytdl_material_1  |     at Object.getConfigItem (/app/config.js:97:24)                                                                                        ytdl_material_1  |     at Object.exports._connectToDB (/app/db.js:121:56)                                                                                    ytdl_material_1  |     at Object.exports.connectToDB (/app/db.js:95:51)                                                                                      ytdl_material_1  |     at async loadConfig (/app/app.js:509:9)                                                                                               ytdl_material_1  |     at async setAndLoadConfig (/app/app.js:487:5)                                                                                         ytdl_material_1  | 2022-10-21T19:01:30: PM2 log: App [YoutubeDL-Material:0] exited with code [0] via signal [SIGINT]                                         ytdl_material_1  | 2022-10-21T19:01:30: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-                                                          ytdl_material_1  | 2022-10-21T19:01:32: PM2 log: App [YoutubeDL-Material:0] online                                                                           mongo-db exited with code 132                                                                                                                                mongo-db         |                                                                                                                                           mongo-db         | WARNING: MongoDB 5.0+ requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!                                                                                                                                                          mongo-db         |   see https://jira.mongodb.org/browse/SERVER-55178                                                                                        mongo-db         |   see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features                                                 mongo-db         |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306                                                      mongo-db         |                                                                                                                                           mongo-db         |                                                                                                                                           mongo-db         | WARNING: MongoDB 5.0+ requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!                                                                                                                                                          mongo-db         |   see https://jira.mongodb.org/browse/SERVER-55178                                                                                        mongo-db         |   see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features                                                 mongo-db         |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306                                                      mongo-db         |                                                                                                                                           mongo-db         |                                                                                                                                           mongo-db         | WARNING: MongoDB 5.0+ requires ARMv8.2-A or higher, and your current system does not appear to implement any of the common features for that!                                                                                                                                                          mongo-db         |   see https://jira.mongodb.org/browse/SERVER-55178                                                                                        mongo-db         |   see also https://en.wikichip.org/wiki/arm/armv8#ARMv8_Extensions_and_Processor_Features                                                 mongo-db         |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-970864306                                                      mongo-db         |                                                                                                                                           mongo-db exited with code 132                                                                                                                                Exception in thread Thread-6:                                                                                                                                Traceback (most recent call last):                                                                                                                             File "urllib3/connectionpool.py", line 426, in _make_request                                                                                                 File "<string>", line 3, in raise_from                                                                                                                       File "urllib3/connectionpool.py", line 421, in _make_request                                                                                                 File "http/client.py", line 1348, in getresponse                                                                                                             File "http/client.py", line 316, in begin                                                                                                                    File "http/client.py", line 277, in _read_status                                                                                                             File "socket.py", line 669, in readinto                                                                                                                    socket.timeout: timed out                                                                                                                                                                                                                                                                                                 During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                             File "requests/adapters.py", line 439, in send                                                                                                               File "urllib3/connectionpool.py", line 726, in urlopen                                                                                                       File "urllib3/util/retry.py", line 410, in increment                                                                                                         File "urllib3/packages/six.py", line 735, in reraise                                                                                                         File "urllib3/connectionpool.py", line 670, in urlopen                                                                                                       File "urllib3/connectionpool.py", line 428, in _make_request                                                                                                 File "urllib3/connectionpool.py", line 335, in _raise_timeout                                                                                              ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.                                                          If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).       urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)                                                                                                                                                                                               During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                       Traceback (most recent call last):                                                                                                                             File "threading.py", line 932, in _bootstrap_inner                                                                                                           File "threading.py", line 870, in run                                                                                                                        File "compose/cli/log_printer.py", line 202, in watch_events                                                                                                 File "compose/project.py", line 626, in yield_loop                                                                                                           File "compose/project.py", line 594, in build_container_event                                                                                                File "compose/container.py", line 44, in from_id                                                                                                             File "docker/utils/decorators.py", line 19, in wrapped                                                                                                       File "docker/api/container.py", line 774, in inspect_container                                                                                               File "docker/utils/decorators.py", line 46, in inner                                                                                                         File "docker/api/client.py", line 237, in _get                                                                                                               File "requests/sessions.py", line 543, in get                                                                                                                File "requests/sessions.py", line 530, in request                                                                                                            File "requests/sessions.py", line 643, in send                                                                                                               File "requests/adapters.py", line 529, in send                                                                                                             requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

**Comment by RichardProchadzka** [comment]
you can close it if you do not want to read that log .. it is okay i will find something to make it work thx for support

**Comment by tristanwilson111** [comment]
@RichardProchadzka, I believe the error you're seeing is the result of the command "docker-compose up".

This will start the container and start logging to your terminal, but exiting your terminal session will result in the container shutting down.

You can likely resolve this by running "docker-compose up -d", which will start the container by itself in Docker.

The logs you posted of:

```
Creating network "yotube-dl_default" with the default driver
Creating mongo-db ... done
Creating yotube-dl_ytdl_material_1 ... done
Attaching to yotube-dl_ytdl_material_1
ERROR: configured logging driver does not support reading
```
 
are all coming from Docker, not the application. The last ERROR line indicates that the "yotube-dl_ytdl_material_1" container is not configured to log to the console.
