### ISSUE TITLE
Apache reverse proxy

### ISSUE THREAD

**Issue by amenolo** [Tzahi12345/YoutubeDL-Material#772]
Latest YoutubeDL-Material docker running smoothless in LAN, not working behind Apache 2.4.54 (Debian 11) reverse proxy set as per wiki:

```
<VirtualHost *:80>

ServerName domain.ext
Redirect permanent / https://domain.ext

</VirtualHost>

<VirtualHost *:443>

ServerName domain.ext

ProxyPass / http://docker.local:8998/
ProxyPassReverse / http://docker.local:8998/

Include /etc/apache2/conf-available/ssl.conf

</VirtualHost>
```

What I get:

![immagine](https://user-images.githubusercontent.com/29974944/197296067-be65fb28-1074-4149-9652-9db6a5c28299.png)

No error in Apache log, no problem with other reverse proxy vhosts.

Any idea? Thanks!

**Comment by amenolo** [comment]
Thanks for your comments!

Meanwhile I tried with a basic Nginx Proxy Manager config (Custom locations and Advanced tabs are unedited)

![image](https://user-images.githubusercontent.com/29974944/227536125-f7e265f0-213e-40a0-8729-daddf28f1aec.png)


and it works well.

Corresponding raw config:

> vhost config

```
server {
  set $forward_scheme http;
  set $server         "x.x.x.x";
  set $port           8998;

listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;

  server_name domain.ext;

  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-10/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-10/privkey.pem;
  access_log /data/logs/proxy-host-6_access.log proxy;
  error_log /data/logs/proxy-host-6_error.log warn;

  location / {
include conf.d/include/proxy.conf;
  }
}
```

> proxy.conf

```
add_header       X-Served-By $host;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header X-Forwarded-Proto  $scheme;
proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP          $remote_addr;
proxy_pass       $forward_scheme://$server:$port$request_uri;
```

Since right now I don't feel like translating all of my apache vhosts into nginx vhosts, I guess it could worth a try finding a way to translate the latter nginx proxy config into proper apache config...any hints?

**Comment by JalenMak6** [comment]
> Thanks for your comments!
> 
> Meanwhile I tried with a basic Nginx Proxy Manager config (Custom locations and Advanced tabs are unedited)
> 
> ![image](https://user-images.githubusercontent.com/29974944/227536125-f7e265f0-213e-40a0-8729-daddf28f1aec.png)
> 
> and it works well.
> 
> Corresponding raw config:
> 
> > vhost config
> 
> ```
> server {
>   set $forward_scheme http;
>   set $server         "x.x.x.x";
>   set $port           8998;
> 
> listen 80;
> listen [::]:80;
> 
> listen 443 ssl http2;
> listen [::]:443 ssl http2;
> 
>   server_name domain.ext;
> 
>   include conf.d/include/letsencrypt-acme-challenge.conf;
>   include conf.d/include/ssl-ciphers.conf;
>   ssl_certificate /etc/letsencrypt/live/npm-10/fullchain.pem;
>   ssl_certificate_key /etc/letsencrypt/live/npm-10/privkey.pem;
>   access_log /data/logs/proxy-host-6_access.log proxy;
>   error_log /data/logs/proxy-host-6_error.log warn;
> 
>   location / {
> include conf.d/include/proxy.conf;
>   }
> }
> ```
> 
>  > proxy.conf
> 
> ```
> add_header       X-Served-By $host;
> proxy_set_header Host $host;
> proxy_set_header X-Forwarded-Scheme $scheme;
> proxy_set_header X-Forwarded-Proto  $scheme;
> proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
> proxy_set_header X-Real-IP          $remote_addr;
> proxy_pass       $forward_scheme://$server:$port$request_uri;
> ```
> 
> Since right now I don't feel like translating all of my apache vhosts into nginx vhosts, I guess it could worth a try finding a way to translate the latter nginx proxy config into proper apache config...any hints?

I also used the default setup with nginx proxy manager but it cannot render the page.

I try to set up the proxy host for the page with Nginx proxy manager along with Cloudflare DNS. I do disable the HTST nosniff feature and add the all the methods mentioned like adding header for 
X-Content-Type-Options: none

  in the open issue. but when I use Safari to access it with my subdomain, it just downloaded the whole page. On Chrome, it showed me the HTML text only.

May I know how to fix this issue?
