### ISSUE TITLE
[BUG] Download stage not progressing

### ISSUE THREAD

**Issue by deprecated-dot** [Tzahi12345/YoutubeDL-Material#774]
**Describe the bug**
Downloading with the default settings in 4.3 (yt-dlp as downloader, default downloading agent) yields "N/A" for "progress", and the stage appears stuck at "Getting info". If left alone, it will eventually download the video and process it, but there's no progress indicator at all anymore, right up until the moment the video is finished downloading. 

**To Reproduce**
1. Enter URL of video to download
2. Press "Download"
3. See "N/A" in the "Progress" field, and "Getting info" in the "Stage" field.

**Expected behavior**
Expected behavior is seeing a progress and stage indicator. 

**Environment**
YoutubeDL-Material, Docker nightly tag, though it is also present in "latest"

Installation details:
Installed version: v4.3 -   You are up to date.
Installation type: docker
Docker tag: nightly
Commit hash: 9c0a77c
Build date: 2022-10-18

**Additional context**
This issue exists for practically every YouTube video, but long videos are especially affected.

**Comment by plmcgrn** [comment]
I'm hitting this as well, for non-Youtube videos.  It's downloading successfully, but the download shows "Getting Info" until it finishes the download.

**Comment by Tzahi12345** [comment]
Can I have an example URL?

**Comment by deprecated-dot** [comment]
Every YouTube video I've tried. For example, I just tried https://www.youtube.com/watch?v=ER9nkOwwXro 

It shows the date timestamp, no title, and the stage stays on "Getting info" with progress as "N/A" until the video is done downloading, no progress indicator at all until it's complete. Watching throughput on my router, I can see that it's downloading, but again, there's no progress indicator. 

I used an older version of YoutubeDL-Material for a while without that issue, but as soon as I upgraded it started not displaying progress. I'm using the Docker version, if that helps. I've destroyed/deleted the container and paths and recreated them from scratch, so I'm not sure where the problem lies.

If I can provide any more info, please let me know. Thanks!

**Comment by Tzahi12345** [comment]
Figured out what was happening, should be fixed once this PR merges: https://github.com/Tzahi12345/YoutubeDL-Material/pull/873

**Comment by deprecated-dot** [comment]
Excellent! Just pulled the latest with docker-compose and restarted my instance. Everything works perfectly! Thanks, and great work.

**Comment by Codelica** [comment]
I think this bug may still be around.   For example links from RedBull like https://www.redbull.com/us-en/films/motive will just display "N/A" but eventually complete fine.  Some links from YT like https://www.youtube.com/watch?v=UfafIeK9sJw will progress up to "100%" (very) quickly and then sit there for a long time as fragments are still collected.  Anyone else seeing this still?

**Comment by plmcgrn** [comment]
Yeah I see it whenever the generic handler is used for the download 100% of the time.

Sent while mobile. Excuse typos.
________________________________

**Comment by deprecated-dot** [comment]
I tested both of those links, the YouTube link works fine, but the redbull video sits there with "N/A".

**Comment by Codelica** [comment]
Interesting..  For me the YouTube link initially looked like it was progressing fine, but I noticed it was going waaaay too quick for a 5 GB+ video with my connection.  Then it sat there at 100% while it loaded up the other 4+ GB.
