### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zackmuc** [Tzahi12345/YoutubeDL-Material#776]
I cannot delete videos which i downloaded via subscription, where subscription is deleted.

**To Reproduce**
1. Subscribe to youtube channel
2. start the download
3. unsubscribe after some videos are downloaded
4. videos cannot be deleted only delete and redownloaded

**Expected behavior**
Possiblity to delte video

**Comment by FunctionDJ** [comment]
Check this #366 or this #268 or this #227
