### ISSUE TITLE
BUG: "Please enter a valid URL!" ALWAYS displayed

### ISSUE THREAD

**Issue by bcurran3** [Tzahi12345/YoutubeDL-Material#78]
After pasting in a URL and hitting the Download button, I ALWAYS get a "Please enter a valid URL!" message....even though I did and it's downloading.

e.g.

![image](https://user-images.githubusercontent.com/14026600/81466146-1e670500-9184-11ea-8c63-e5226d967179.png)

**Comment by Tzahi12345** [comment]
That's definitely an easy fix! Thanks for the bug report, I'll see if I can get a quick fix in for it.

**Comment by Tzahi12345** [comment]
Good news, the error message has been removed! The latest nightly should have this fix in :)
