### ISSUE TITLE
[FEATURE] Connect with other apps for notification

### ISSUE THREAD

**Issue by mritunjaymusale** [Tzahi12345/YoutubeDL-Material#783]
**Is your feature request related to a problem? Please describe.**
After downloads are finished it would be nice if I got a notification or something (when using the docker version)

**Describe the solution you'd like**
The `*arr apps` ecosystem has feature where downloads, adding of movie/show etc will automatically send a notification using their connected apps plugin. I have currently set it up in a manner where any event happens in sonarr or radarr app i get a message on my telegram bot that way it's easier to keep track of things incase something is broken or something is ready for viewing.
So I would like to a similar freature where in settings page I provide the telegram bot api key and the chat id and when there is a new subscription video downloaded and ready for viewing  I will get a telegram message from my bot and I can start watching directly through your ui. 
**Additional context**
Here's how it currently works in Sonarr :
![Screenshot from 2022-11-13 14-33-16](https://user-images.githubusercontent.com/25117230/201514073-b6652acd-cf10-4373-8e3b-3022b55abd5f.png)
And here's how it looks in telegram :
![image](https://user-images.githubusercontent.com/25117230/201514134-1368bdd8-1b99-42b3-bd4f-fc5afa2a7481.png)

**Comment by GAS85** [comment]
#440 is in a similar direction

**Comment by Tzahi12345** [comment]
See latest PR #809. No promises I can get Telegram support working but I have already implemented Gotify and ntfy.

From a first look it doesn't look *that hard*. There's a few APIs that might be useful here:
* https://www.npmjs.com/package/node-telegram-bot-api
* https://www.npmjs.com/package/telegram

I'm hoping to add Apprise support (as mentioned in #440), but then you'd have to host another service.

**Comment by mritunjaymusale** [comment]
For telegram you don't need additional service which why I pefer that approach as compared to others that you have mentioned.
AFAIK other approaches require you to host or install some kind of additional app along with ytdl-material where as telegram-api can be bundled using the npm packages that you mentioned.

**Comment by Tzahi12345** [comment]
Added to #809! The way I have it set up now is (in the case of a download) it will send a URL of the thumbnail and then the text with more info like so:

![image](https://user-images.githubusercontent.com/707413/226493361-1f098f5b-b9a9-497a-a54e-ba650670b2a5.png)

Do we want to keep the thumbnail there? I'm trying to avoid adding a setting for "yes include a thumbnail" since it seems so minor.

**Comment by mritunjaymusale** [comment]
I think you should keep the thumbnail on by default, since it acts as a helpful indicator when downloading a playlist or a channel.
One last thing (atleast from my side), in the message where it provides the url, is it possible to add the link to the original video aswell? For referencing sake.

**Comment by Tzahi12345** [comment]
> I think you should keep the thumbnail on by default, since it acts as a helpful indicator when downloading a playlist or a channel. One last thing (atleast from my side), in the message where it provides the url, is it possible to add the link to the original video aswell? For referencing sake.

Makes sense, just added that in! https://github.com/Tzahi12345/YoutubeDL-Material/pull/809/commits/07a0ea6d180fb68110d756065e9abfb4a3fa4ee7

**Comment by mritunjaymusale** [comment]
Before this gets deployed, I came accross this another feature of telegram, where if you change the group into a supergroup you can create topics (like discord channel) so can you add another parameter which will ask for the topic / message_thread_id and the messages will land in the respective channel ?

**Comment by Tzahi12345** [comment]
It did get deployed in v4.3.1 :)

If you could create an issue for that feature request that would be helpful for tracking purposes
