### ISSUE TITLE
BUG: <s>"downloaded" videos that didn't download still show in archive</s> add default.json back to image

### ISSUE THREAD

**Issue by bcurran3** [Tzahi12345/YoutubeDL-Material#79]
DISCLAIMER: I'm having a problem right now. NOTHING will download. It's been this way for a few days. I need to double check my config and volumes but don't believe it's the problem. 

When I have YoutubeDL-Material download a video, it shows it downloading. It shows in the archive. It shows info for the video. BUT, the video doesn't exist in my download location. YET, it's displayed in the archive even though it doesn't exist. Clicking the video does nothing, it does not play. (This is why I don't think it's a configuration problem on my end. It did used to work and work very well up until a few days ago.)

e.g.
![image](https://user-images.githubusercontent.com/14026600/81466242-deece880-9184-11ea-9aea-78ddb39c0224.png)

**Comment by Tzahi12345** [comment]
Can you access the logs in the `appdata` folder? There should be a `combined.txt` file in there that will show additional errors. Not sure what's going wrong here from a first glance, hm..

**Comment by bcurran3** [comment]
No problem.

First - MAYBE related to migration?

> 2020-05-09T06:53:39.640Z INFO: Beginning migration: 3.5->3.6+
> 2020-05-09T06:53:39.649Z INFO: 3.5->3.6+ migration complete!
> 2020-05-09T06:53:39.650Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-09T06:53:40.134Z INFO: Found new update for youtube-dl. Updating binary...
> 2020-05-09T06:53:42.196Z INFO: Binary successfully updated: 2020.05.03 -> 2020.05.08

As requested:
cat combined.log

> 2020-05-04T22:05:09.883Z INFO: Beginning migration: 3.5->3.6+
> 2020-05-04T22:05:09.921Z INFO: 3.5->3.6+ migration complete!
> 2020-05-04T22:05:09.930Z INFO: YoutubeDL-Material v3.6 started on PORT 17442
> 2020-05-04T22:05:10.444Z INFO: Found new update for youtube-dl. Updating binary...
> 2020-05-04T22:05:12.889Z INFO: Binary successfully updated: 2020.03.24 -> 2020.05.03
> 2020-05-06T04:01:42.332Z INFO: YoutubeDL-Material v3.6 started on PORT 17442
> 2020-05-06T04:01:42.969Z INFO: Found new update for youtube-dl. Updating binary...
> 2020-05-06T04:01:45.077Z INFO: Binary successfully updated: 2020.03.24 -> 2020.05.03
> 2020-05-06T12:01:21.550Z WARN: Cannot find config with key 'ytdl_enable_downloads_manager'. Creating one with the default value...
> 2020-05-06T12:01:21.557Z WARN: Cannot find config with key 'ytdl_users_base_path'. Creating one with the default value...
> 2020-05-06T12:01:21.563Z WARN: Cannot find config with key 'ytdl_allow_registration'. Creating one with the default value...
> 2020-05-06T12:01:21.565Z WARN: Cannot find config with key 'ytdl_logger_level'. Creating one with the default value...
> 2020-05-06T12:01:21.741Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-07T00:42:33.544Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-07T01:15:00.853Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-07T01:50:52.094Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-07T04:56:20.864Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-07T05:35:58.703Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-07T06:06:48.072Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-07T10:58:27.548Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-07T15:17:51.480Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-08T02:59:05.071Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-08T10:04:24.905Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-08T20:06:57.091Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-08T20:06:57.535Z INFO: Found new update for youtube-dl. Updating binary...
> 2020-05-08T20:07:00.045Z INFO: Binary successfully updated: 2020.05.03 -> 2020.05.08
> 2020-05-08T21:55:06.141Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-08T21:55:06.543Z INFO: Found new update for youtube-dl. Updating binary...
> 2020-05-08T21:55:08.598Z INFO: Binary successfully updated: 2020.05.03 -> 2020.05.08
> 2020-05-09T06:13:26.001Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-09T06:18:01.107Z ERROR: Error during parsing:Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl --dump-json -- http://supernas.mrbillsabode.org:10081/#YouTubeDL-Material
> 2020-05-09T06:18:01.108Z ERROR: failed to parse for urls starting with http://supernas.mrbillsabode.org:10081/#YouTubeDL-Material
> 2020-05-09T06:25:45.375Z INFO: YoutubeDL-Material v4.0 started on PORT 17442
> 2020-05-09T06:25:45.911Z INFO: Found new update for youtube-dl. Updating binary...
> 2020-05-09T06:25:48.175Z INFO: Binary successfully updated: 2020.05.03 -> 2020.05.08

**Comment by Tzahi12345** [comment]
I don't think so, the migrations just add files to the database if they are not there already, it shouldn't interfere with video downloads.

It sounds like the video downloaded, but for some reason the file can't be accessed. Your container should have a volume mapped to the `/app/video`, which is where the videos are stored. Can you verify those video are there? Let me know if you have trouble finding them.

Also, let me know if you see any errors when you actually try clicking on the videos. It may be a UI error that's preventing you from accessing them.

**Comment by bcurran3** [comment]
I wiped my locally stored container data, the container, and reinstalled (a few times just now).

Somehow I screwed myself royally. (Sorry, it's late and I'm sure there's a user error here somewhere!)

When the container starts I'm now getting:

> 2020-05-09T07:33:20.849717968Z internal/fs/utils.js:220
> 2020-05-09T07:33:20.849763892Z     throw err;
> 2020-05-09T07:33:20.849766928Z     ^
> 2020-05-09T07:33:20.849784292Z 
> 2020-05-09T07:33:20.849786415Z Error: ENOENT: no such file or directory, open 'appdata/default.json'
> 2020-05-09T07:33:20.849788672Z     at Object.openSync (fs.js:440:3)
> 2020-05-09T07:33:20.849790778Z     at Object.readFileSync (fs.js:342:35)
> 2020-05-09T07:33:20.849805609Z     at getConfigFile (/app/config.js:65:23)
> 2020-05-09T07:33:20.849807829Z     at getConfigItem (/app/config.js:85:23)
> 2020-05-09T07:33:20.849810085Z     at ensureConfigItemsExist (/app/config.js:20:9)
> 2020-05-09T07:33:20.849812160Z     at Object.initialize (/app/config.js:13:5)
> 2020-05-09T07:33:20.849814230Z     at Object.<anonymous> (/app/app.js:74:12)
> 2020-05-09T07:33:20.849816516Z     at Module._compile (internal/modules/cjs/loader.js:955:30)
> 2020-05-09T07:33:20.849818612Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
> 2020-05-09T07:33:20.849820688Z     at Module.load (internal/modules/cjs/loader.js:811:32)
> 2020-05-09T07:33:20.849822789Z     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
> 2020-05-09T07:33:20.849824879Z     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
> 2020-05-09T07:33:20.849832841Z     at internal/main/run_main_module.js:17:11 {
> 2020-05-09T07:33:20.849834839Z   errno: -2,
> 2020-05-09T07:33:20.849836610Z   syscall: 'open',
> 2020-05-09T07:33:20.849838359Z   code: 'ENOENT',
> 2020-05-09T07:33:20.849840100Z   path: 'appdata/default.json'
> 2020-05-09T07:33:20.849841909Z }

I've chmod +777'd all the files and they also exist:
![image](https://user-images.githubusercontent.com/14026600/81467358-ff20a580-918c-11ea-825f-b0a7e2579aea.png)

My volumes (using Ansible):

>     volumes:
>       - "{{ youtubedlmaterial_data_directory }}/appdata:/app/appdata:rw"
>       - "{{ youtubedlmaterial_dl_audio_directory }}:/app/audio:rw"
>       - "{{ youtubedlmaterial_dl_video_directory }}:/app/video:rw"
>       - "{{ youtubedlmaterial_dl_subscriptions_directory }}:/app/subscriptions:rw"

I'm pretty sure the only change I just made was removing PUID and PGID env variables and now the site is refusing to connect. (Yeah, feeling pretty dumb right now since it was working fine a up until a few days ago and now it's complete kaput. That's why I want bash from inside the container. :) )

**Comment by Tzahi12345** [comment]
>Somehow I screwed myself royally. (Sorry, it's late and I'm sure there's a user error here somewhere!)

No worries! Let's see if we can solve it.

Looks like the config file is missing, this is an issue which [came up](https://github.com/Tzahi12345/YoutubeDL-Material/issues/75) a couple days ago but I've implemented a fix since then (not released yet). You can grab the latest config file [here](https://raw.githubusercontent.com/Tzahi12345/YoutubeDL-Material/master/backend/appdata/default.json) and put it in the `appdata` folder manually, that should fix the issue.

Hopefully the wipe fixed whatever the underlying error was causing issues before. Let me know if adding the config fixes it.

>To beat the bush again, thus why I want to be able to bash into the container to see wassup my self-inflicted wounds. :)

Not sure if you saw my response to your issue on that front, but it should be possible to launch if you run `/bin/sh` rather than `/bin/bash`.

**Comment by bcurran3** [comment]
Isaac, you the man.

FIXED!

Yepper depper. Needed that default.json. (Not in the current image!) See it now in my backup and didn't notice it missing. Cool. Thanks.

...........and guess what?

Downloads are now successful and going to the correct place! Yeah team!

Now I can download 1st grade educational videos from YouTube, drop them in Plex, and FORCE my kid to watch them without letting him run wild on YouTube and watch a whole bunch of Roblox and Bendy brain rotting crap. 

![](https://clipartmag.com/images/thank-you-emoticon-50.jpg)

Yes, saw your comment about using sh instead of bash.... and now that I've got a working app again I just verified it works and I'll go close the issue. Now quite reading all this congratulatory crap and fix that build. :)

**Comment by Tzahi12345** [comment]
Awesome! Glad we got it working. Thank *you* for being such a helpful debugger.

Regarding the config file in the image, I do believe it's there. I think the unraid's template has `appdata` mapped to an empty folder, hence the need for the default file creation. I think this solves the problem.

I've gone ahead and pushed the recent updates to the repo to the latest docker image (and 4.0) so that this nasty bug doesn't come up again. Anyways, thanks again for the help. Hope your kid enjoy the on-the-demand education haha

**Comment by bcurran3** [comment]
Not using UnRAID but am mapping appdata to an empty folder.

REF: https://github.com/davestephens/ansible-nas/pull/269

**Comment by Tzahi12345** [comment]
Wow, that's awesome! I've been working on integrations long-term, made an issue about [it here](https://github.com/Tzahi12345/YoutubeDL-Material/issues/50). Glad there's other people helping out, I assumed you were using unRAID as someone else put out a template for that. Cool stuff!
