### ISSUE TITLE
BUG (?) / FEATURE REQUEST (?): Can't connect to container console

### ISSUE THREAD

**Issue by bcurran3** [Tzahi12345/YoutubeDL-Material#80]
Trying to debug my recent videos-don't-save problem, I attempted to get into the YoutubeDL-Material container's console to verify my download paths were writable and some other misc on-the-fly diagnostics. When I try to connect to the console, it flashes and goes away.

I don't know if this is intentional or not. :)

Please "fix" container to allow bash access.

e.g.
![image](https://user-images.githubusercontent.com/14026600/81466329-a4378000-9185-11ea-8d08-7674f92c2fc1.png)
![image](https://user-images.githubusercontent.com/14026600/81466330-a7327080-9185-11ea-968a-a362b88e7150.png)
![image](https://user-images.githubusercontent.com/14026600/81466335-adc0e800-9185-11ea-8fa0-9f43671e01f2.png)

**Comment by Tzahi12345** [comment]
Try replacing `/bin/bash` with `/bin/sh`. That should fix it!

**Comment by bcurran3** [comment]
Hot damn!

(Not sure why I didn't try the "alternate" shells...)

Soon as I get my container to stop rebooting and working again I will be happy to verify.

**Comment by bcurran3** [comment]
Worked like a charm once I did it correctly. Thanks again Isaac!

p.s. Keep up the good work!

**Comment by Tzahi12345** [comment]
It's a pleasure! Feel free to open up any more issues if something comes up.
