### ISSUE TITLE
[BUG] pycryptodomex should be added to docker container

### ISSUE THREAD

**Issue by michaelkrieger** [Tzahi12345/YoutubeDL-Material#819]
**Describe the bug**
pycryptodomex should be added as a dependency, allowing it to decode encrypted streams.
WARNING: The stream has AES-128 encryption and pycryptodomex is not available; extraction will be delegated to ffmpeg
ERROR: ffmpeg exited with code -11

**Environment**
Installed version: v4.3 -   You are up to date.
Installation type: docker
Docker tag: nightly
Commit hash: 9c0a77c
Build date: 2023-01-10

**Comment by Tzahi12345** [comment]
Fixed! Thanks for the bug report :) will include this in v4.3.1

Commit: https://github.com/Tzahi12345/YoutubeDL-Material/commit/30c7a965401933482ac7cda7b96325a96697d63e
