### ISSUE TITLE
Anyone can register

### ISSUE THREAD

**Issue by PrzemekSkw** [Tzahi12345/YoutubeDL-Material#823]
Hello, I noticed that anyone who know my domain name can register in my instance. I think it's not secure. How can I disable it or get notification or email to deny or accept user?
Regards.

**Comment by Tzahi12345** [comment]
You can disable registration in the Users tab of the settings:

![image](https://user-images.githubusercontent.com/707413/229265635-f8bf8c55-f295-4ff5-a0fc-5e5a1b64cdb0.png)

Hope this helps!
