### ISSUE TITLE
Try using the [docker-compose method](https://github.com/Tzahi12345/YoutubeDL-Material/issues/177#issuecomment-722685712) if you're on Docker, let me know if this works!

### ISSUE THREAD

**Issue by tokyoqiang** [Tzahi12345/YoutubeDL-Material#827]
Try using the [docker-compose method](https://github.com/Tzahi12345/YoutubeDL-Material/issues/177#issuecomment-722685712) if you're on Docker, let me know if this works!

_Originally posted by @Tzahi12345 in https://github.com/Tzahi12345/YoutubeDL-Material/issues/323#issuecomment-770438910_

**Comment by tokyoqiang** [comment]
Hi Tzahi12345,

Thank you so much for developing such great efficient tool. I'm from Youtube restricted country, so can't use youtube-dl without proxy. Can you help to add 'PROXY' into environment for docker if possible, then container can use Http_Proxy? (I'm using synology docker)

**Comment by Tzahi12345** [comment]
Have you tried using the `--proxy` arg? See usage here: https://github.com/yt-dlp/yt-dlp#network-options

**Comment by Tzahi12345** [comment]
Good to hear! I'll go ahead and close this issue then
