### ISSUE TITLE
Disable write-info-json argument

### ISSUE THREAD

**Issue by Snake883** [Tzahi12345/YoutubeDL-Material#832]
How do I configure so it won't always add the "--write-info-json" argument by default?

Every download adds the "--write-info-json" argument.

I was also noticing the "Global Download Argument" appends the argument, not replace.

**Comment by Tzahi12345** [comment]
Write info json is highly recommended, without it we cannot rebuild the database in case of failure as we lose all the precious metadata. But it can be disabled, simply uncheck `Include metadata` in the `Downloader` section of the settings.

Global custom arg does append, yes. To replace args enable `Allow advanced download` in the `Advanced` tab in the settings. You'll see a new dropdown in the home page and you can run totally customized args there:

![image](https://user-images.githubusercontent.com/707413/229265471-5159bc81-64bc-48de-a044-12ea48bb901f.png)
