### ISSUE TITLE
What does "safe_download_override" do?

### ISSUE THREAD

**Issue by Snake883** [Tzahi12345/YoutubeDL-Material#833]
What does "safe_download_override" do when true/false?

**Comment by Tzahi12345** [comment]
This is a legacy setting, it doesn't do anything. Just removed it in the latest PR (v4.3.1 update): https://github.com/Tzahi12345/YoutubeDL-Material/pull/809/commits/0e15fd7193c8c539552d75a6144f86c31799340b
