### ISSUE TITLE
[FEATURE] Pre-Download File Size

### ISSUE THREAD

**Issue by Snake883** [Tzahi12345/YoutubeDL-Material#838]
I would like to know the file download size by quality before downloading.

**Comment by Tzahi12345** [comment]
Just added in the latest PR (#809) as a tooltip in the quality select menu: https://github.com/Tzahi12345/YoutubeDL-Material/pull/809/commits/a9d7f275ba67f8b86879d7f19afc6b751209c2f3

![image](https://user-images.githubusercontent.com/707413/229265290-e4a7bbab-dcf8-4e93-96df-618a4c907c57.png)
