### ISSUE TITLE
Database not working.

### ISSUE THREAD

**Issue by p6002** [Tzahi12345/YoutubeDL-Material#839]
I using your docker compose file, and something there is missing, because container cannot connect to mongo database and using local db instead.
Here is my compose file:
https://pastebin.com/PnXU2uH7
Here is portainer log:
https://pastebin.com/Ezpr12iA

I had the same problem a few months ago, which caused me to abandon the project. 
Do you know a solution, or a working alternative?

**Comment by martadinata666** [comment]
is the database starting correctly? 🤔

**Comment by p6002** [comment]
It looks like it works:
https://i.ibb.co/vhKgmZL/2023-02-25-130553.png
But when I want to see the mongo log, it shows:
```
Failure
Unable to retrieve container logs
```

**Comment by martadinata666** [comment]
remove the logdriver part in your compose, so it can output mongo log correctly.

**Comment by p6002** [comment]
Device is Synology DS220+

LOG from mongo:
   
```
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
```
I will try mongo:4

**Comment by p6002** [comment]
Still not work, can I use it without database? 
Mongo:4 returns:
https://pastebin.com/01YFr8NR

**Comment by martadinata666** [comment]
> Still not work, can I use it without database? 
> Mongo:4 returns:
> https://pastebin.com/01YFr8NR

ah syno DS220+, it uses celeron I think. then should be use mongo:4, and the log pretty much a running db.

**Comment by p6002** [comment]
Thanks! 
It works now (i think) log shows only: 
https://pastebin.com/HLbrY56Z

**Comment by martadinata666** [comment]
it like the mongo had preexist data. may try from scratch, `docker compose down -v` will wipe the volume db.

**Comment by p6002** [comment]
Thanks, recreating helps and I think it works now correctly:
Yt-material log:
https://pastebin.com/GWFrPjdB
Mongo log:
https://pastebin.com/7WBLapud

**Comment by Tzahi12345** [comment]
I decided to downgrade to mongo:4 in the docker-compose just to avoid future problems: https://github.com/Tzahi12345/YoutubeDL-Material/commit/f3a7d198dca092bacc5c6292a8b8ff2401ea998b
