### ISSUE TITLE
Subscription/playlist enhancement

### ISSUE THREAD

**Issue by Code-Slave** [Tzahi12345/YoutubeDL-Material#84]
Awesome app. Some of my playlists/subscriptions are music, id like to have an audio only switch for them when I add them. Any chance? Thanks. great app btw

**Comment by dhruvbhutani** [comment]
To add to this, is there any way to have specific parameters for individual channels? Resolution/quality.

**Comment by Tzahi12345** [comment]
@Code-Slave Definitely something which is possible, having it limited to videos is silly :)

@dhruvbhutani Letting users add youtube-dl parameters is also a good idea, but it will come with one caveat: certain params will likely break subscriptions, and it would be near impossible for me to test them all, so it'll be up to the user to figure those out.

Thanks for the suggestions! Much appreciated

**Comment by dhruvbhutani** [comment]
@Tzahi12345 Happy to help in testing out. I feel resolution should be a minimum level enhancement for subscriptions. For eg. I look keeping offline copies of concerts in full resolution but lectures not so much. Thank you for the work on this!

**Comment by Tzahi12345** [comment]
@dhruvbhutani thank *you* for being so supportive!

I'll let you know when I get these features implemented, once that is done you can use the `nightly` tag on Docker to test them out without having to wait for the next update.

**Comment by geekaroni** [comment]
Watching. Thanks!

**Comment by Code-Slave** [comment]
I horde channels so this will help enable my gf to horde hers too and stop bugging me hehe

**Comment by bodzio4749** [comment]
Am I confused, or there is no way to add video to an existing playlist?  If there is, would you mind to guide me in how to?

**Comment by Tzahi12345** [comment]
> Am I confused, or there is no way to add a video to an existing playlist? If there is, would you mind guiding me on how to?

Unfortunately it isn't. You can re-order but not add, though this would be trivial to implement. I've created a card [here](https://github.com/Tzahi12345/YoutubeDL-Material/projects/3#card-39796727), so it should be in by the next update!

**Comment by Tzahi12345** [comment]
Audio only mode for subscriptions is implemented! Check out the [PR here.](https://github.com/Tzahi12345/YoutubeDL-Material/pull/136)

@dhruvbhutani Note that for custom resolution, you have to use the new custom args option for subscriptions. You can see examples of this being done [here](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection-examples); if you have any issues doing this let me know and I can help.

Thanks everyone for the suggestions! Always appreciated.

**Comment by Tzahi12345** [comment]
@bodzio4749 Letting you know that the [latest PR](https://github.com/Tzahi12345/YoutubeDL-Material/pull/149) adds in a new dialog where you can modify existing playlists. Check it out in the latest `nightly`!
