### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheNighthawk99** [Tzahi12345/YoutubeDL-Material#840]
Hello, it is some days I cannot download any video.
I run through Docker container and I am on the “latest” build just copied a youtube video link and pasted in the URL field.
When the circle stops spinning, I cannot get any size resolution other than MAX.
I try then to download, but it results with an error:

Unable to extract uploader id

Do you have the same issue?
Thank you.

**Comment by martadinata666** [comment]
the ytdlp binary is outdated, enable ytdlp binary update at `tasks` menu

**Comment by yllekz** [comment]
My instance has been broken for weeks (downloads immediately fail). I'm hearing rumblings of upstream problems with ytdl material. Might be out of YTDLM's hands.

**Comment by noah-brod** [comment]
Yeah my downloads haven't been working right for a month or so.   Sometimes a download works fine.  Most of my playlist aren't grabbing new videos either.

 Sometimes it throws the following error in the logs:

`PermissionError: [Errno 13] Permission denied: '/.cache'
WARNING: Writing cache to '/.cache/yt-dlp/youtube-nsig/9419f2ea.json' failed: Traceback (most recent call last):
File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/cache.py", line 41, in store
os.makedirs(os.path.dirname(fn), exist_ok=True)
File "/usr/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib/python3.8/os.py", line 223, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'`

**Comment by noah-brod** [comment]
Some of my videos lately are also failing with the following error:

` os.makedirs(os.path.dirname(fn), exist_ok=True)
File "/usr/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib/python3.8/os.py", line 223, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'`

**Comment by Elmeromoto** [comment]
MIght be a different issue, but some of my videos lately are also failing with the following error:  
`
 os.makedirs(os.path.dirname(fn), exist_ok=True) File "/usr/lib/python3.8/os.py", line 213, in makedirs makedirs(head, exist_ok=exist_ok) File "/usr/lib/python3.8/os.py", line 213, in makedirs makedirs(head, exist_ok=exist_ok) File "/usr/lib/python3.8/os.py", line 223, in makedirs mkdir(name, mode) PermissionError: [Errno 13] Permission denied: '/.cache'
 `

**Comment by joestump** [comment]
I think until one of the following two things happens this app will continue to be broken:

* `youtube-dl` fixes the issue upstream: https://github.com/ytdl-org/youtube-dl/issues/31530 
* #753 gets fixed so `yt-dlp` works properly.

**Comment by Tzahi12345** [comment]
@joestump The app isn't broken, but it doesn't clearly communicate to users two things:

1. yt-dlp is basically the only downloader that works, if you are using other ones your downloads might fail (this has been fixed)
2. If you switch to yt-dlp, you have to restart your server (or update it via Tasks, see here: https://github.com/Tzahi12345/YoutubeDL-Material/issues/847#issuecomment-1484340809)

Normally this isn't an issue for new users/instances as yt-dlp is the default and on startup it will download the appropriate binary.

To make it more clear to users I added a hint making it clear a restart is required after changing the downloader: https://github.com/Tzahi12345/YoutubeDL-Material/commit/e720edf9f0ca5b93c59abad9d4bc40204fe6ebcb

Going to close this issue. Eventually we should probably just remove the option for youtube-dl.
