### ISSUE TITLE
[BUG] Download queue completely stalled

### ISSUE THREAD

**Issue by SinisterCrayon** [Tzahi12345/YoutubeDL-Material#841]
Downloads are stalled in the latest version after adding channels with the "@" identifier Youtube recently added. I know this is a bug that's been going around but it's caused a problem. Even after removing those channels, I can't clear out the Downloads queue and now the queue is completely stalled.

Is there a way to clear this queue manually? I am using MongoDB as the backend database

Using the nightly in Docker on my UnRAID box. Also of note that the task to download the latest YT-DLP is maybe not working? It says it ran but doesn't seem to make any difference.

I did try to clear the download queue through the GUI but it's hanging.

**Comment by SinisterCrayon** [comment]
For anyone else who hits this problem, I ended up just using Compass to connect to the MongoDB then went into the ytdl-material database and dropped the download_queue collection. After that the downloads seem to be working again.

Still can't tell if the "update yt-dlp" task is actually doing anything. It completes but doesn't seem to fix anything.

**Comment by Tzahi12345** [comment]
Sounds like the issue is fixed but I want to understand more how this happened. Were you able to find a way to consistently reproduce this?

Just tried with a channel that had a `@` and it still worked, I used the following URL: https://www.youtube.com/@KillaZM/videos
