### ISSUE TITLE
[FEATURE] Add ability to browse individual subscriptions

### ISSUE THREAD

**Issue by SinisterCrayon** [Tzahi12345/YoutubeDL-Material#845]
Currently the main index allows you to page through all the videos in a browsing fashion instead of having to search using the browse buttons in the bottom right. The individual subscription indexes do not allow this and force you to search... so only the most recent few videos are shown. Would like to have the same paging buttons on the individual subscription indexes so I can page through the videos.

**Comment by Tzahi12345** [comment]
This was actually a bug fixed in the latest PR (#809), check out the latest nightly!
