### ISSUE TITLE
[BUG] After updating the docker image, most videos do not display

### ISSUE THREAD

**Issue by arithxp** [Tzahi12345/YoutubeDL-Material#851]
**Describe the bug**
I updated my Docker. (Update a nightly version that is approximately 15 months old to version 4.3)
After the update, most of the videos in the subscription channel are not visible.
However, when I click the Library button, the videos are actually there.
Video is displayed on the home tab

**Screenshots**
before
![42](https://user-images.githubusercontent.com/6009737/229312528-07681f94-26a7-4a42-9783-9270a4d5fe1b.png)

after
![43](https://user-images.githubusercontent.com/6009737/229312542-fc6529c5-7374-48d6-b0ba-36a9d35326c2.png)
![43_lib](https://user-images.githubusercontent.com/6009737/229312773-e508b91b-ab28-4b3f-ab10-6942b0156706.png)
![43_home](https://user-images.githubusercontent.com/6009737/229313346-1171559a-6da4-4ef3-80b3-07ac2862d8df.png)

**Environment**
Installed version: v4.3
Installation type: docker
Docker tag: latest
Commit hash: fc3c179
Build date: 2022-07-05

**Comment by Tzahi12345** [comment]
Just fixed this issue in the latest PR (#809) thanks for bringing it up!

**Comment by arithxp** [comment]
Thanks for the quick fix
:)
