### ISSUE TITLE
[BUG] [extractor/pornhub][fix] fix changed ageverification cookie

### ISSUE THREAD

**Issue by tiritibambix** [Tzahi12345/YoutubeDL-Material#852]
**Describe the bug**
Can't download any video from pornhub

**To Reproduce**
1. Go to porhub
2. Choose a video
3. Copy the url
4. Paste in YoutubeDL-Material filed and hit download
5. Won't download

**Expected behavior**
Should download the video

**Environment**
Installed version: v4.3
Installation type: docker
Docker tag: latest
Commit hash: fc3c179
Build date: 2022-07-05 

**Additional context**
Apparently there was a fix to this bug 3 days ago : https://github.com/yt-dlp/yt-dlp/pull/6685

**Comment by Tzahi12345** [comment]
Sounds like it's not an issue on our side then? If I'm wrong then I'll re-open, otherwise there's nothing we can do about this until yt-dlp merges the fix.

**Comment by tiritibambix** [comment]
I do suffer from that bug though. That's why I was posting here, hoping the future merge to be mirrored in youtubedl-material ;)

**Comment by Tzahi12345** [comment]
I see what you're saying, thankfully once it merges we don't have to do anything on our end. Every time you restart your container, it will check for a yt-dlp update. Also you can go to the Tasks menu and manually trigger an update there. Hope this makes sense!

**Comment by tiritibambix** [comment]
Makes perfect sense. Thank you.

**Comment by tiritibambix** [comment]
While waiting for the merge, someone @yt-dlp [told me](https://github.com/yt-dlp/yt-dlp/pull/6685#issuecomment-1530002037) to `yt-dlp --update-to nightly`

How can I do that within youtubedl-material ?

**Comment by Tzahi12345** [comment]
You can try the following:

1. Open your container's shell by running `docker exec -it <container id> /bin/sh`
2. A slash should appear in your console. Now cd into where `yt-dlp` is stored: `cd /app/node_modules/youtube-dl/bin`
3. Run `./youtube-dl --update-to nightly`. The executable is called `youtube-dl`, but it's still yt-dlp. We do this for legacy reasons
4. You can confirm it's up to date by running `./youtube-dl --version` and it should show a date in May

Let me know if you have trouble doing this

**Comment by tiritibambix** [comment]
Hello again @Tzahi12345 
I've been trying to update to nightly again, but it doesn't work anymore. I get:
`ERROR: Unable to obtain version info; Please try again later or visit  https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest`

I went to the adress and tried puting the version in several ways, but I can't get it to work.
Could you help me again please ?
