### ISSUE TITLE
Database not working

### ISSUE THREAD

**Issue by Dataninja126** [Tzahi12345/YoutubeDL-Material#857]
The MongoDB instance isn't accessible
https://pastebin.com/raw/mA6S7ipJ

The setup is in Docker and videos download fine.  I went through some of the other threads to ensure 'mongodb://ytdl-mongo-db:27017' had a //.

I'm not sure how to troubleshoot the issue.

**Comment by GlassedSilver** [comment]
Make sure that both mongodb and ytdl-m are on the same (virtual) network, or even better they are configured as two services in a docker compose config file.

Please share how you set up your instance.

**Comment by Dataninja126** [comment]
Thanks for the quick reply. They are both in the same docker compose file
and in the same virtual network.

**Comment by Dataninja126** [comment]
Should this portion of the docker compose :
`'mongodb://ytdl-mongo-db:27017'`

Match anything from this section of the docker compose? 
`    ytdl-mongo-db:
        image: mongo
        logging:
            driver: "none"          
        container_name: mongo-db
        restart: always
        volumes:
            - ./db/:/data/db
`

**Comment by martadinata666** [comment]
remove driver logging part, and ensure your system support mongo 5, else use mongo 4. There is docs about this maybe 'ot obvious enough

**Comment by martadinata666** [comment]
it generally, mongo:5 need cpu feauures that may not available in many system usually embedded one like NAS, raspberry pi, etc. So workaround is using mongo:4, just replace it in your compose and clean up the pre exist data.

**Comment by Dataninja126** [comment]
> it generally, mongo:5 need cpu feauures that may not available in many system usually embedded one like NAS, raspberry pi, etc. So workaround is using mongo:4, just replace it in your compose and clean up the pre exist data.

I appreciate the help and I'm a little newer to this, but the docker compose doesn't really indicate where I would change it to mongo 4 vs 5 because the name reference are all mongodb

**Comment by Tzahi12345** [comment]
Here's an example on how to do it: https://github.com/Tzahi12345/YoutubeDL-Material/issues/733#issuecomment-1214611966

**Comment by Dataninja126** [comment]
> Here's an example on how to do it: [#733 (comment)](https://github.com/Tzahi12345/YoutubeDL-Material/issues/733#issuecomment-1214611966)

Thank you! This solved it. Appreciate it.
