### ISSUE TITLE
Failed to update youtube-dl on first run - ENOSPC error

### ISSUE THREAD

**Issue by adan89lion** [Tzahi12345/YoutubeDL-Material#86]
I grabbed the v4.0 image from Docker Hub, set the arguments and ran for the first time, but facing the following error message which caused force quit.

`2020-05-18T09:11:10.114Z ERROR: Failed to update youtube-dl - Error: ENOSPC: System limit for number of file watchers reached, watch 'node_modules/youtube-dl/bin'`

This is the combined log generated in the `appdata` directory
[combined.log](https://github.com/Tzahi12345/YoutubeDL-Material/files/4643215/combined.log)

**Comment by Tzahi12345** [comment]
Hm, can you try to using this command? I think you'll need to do it from Docker's own shell, so you'll have to run this first:

`docker exec -it <container name> /bin/sh`

This command *should* fix the issue:

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

**Comment by adan89lion** [comment]
Thank you for your reply. However, it (in the container) doesn't recognise `sudo` command so I removed them in your command but then it returned this:
`sysctl: error setting key 'fs.inotify.max_user_watches': Read-only file system`
I think I will build it manually and see if the issue still exist.

**Comment by Tzahi12345** [comment]
Ok, feel free to re-open if it persists! May be a bug hidden somewhere there.
