### ISSUE TITLE
[BUG] Have to restart the server for a download to succeed. [Synology] [docker]

### ISSUE THREAD

**Issue by Bidonh** [Tzahi12345/YoutubeDL-Material#863]
**Describe the bug**
On Synology 220+ docker container nightly-2023-04-16. Ran the "Update yt-dlp" task.

I can only download one or two videos from youtube, all the others subsequently fail even with "retry".
I have to restart the server for the download to succeed again.

**To Reproduce**
1. Try to DL https://www.youtube.com/watch?v=l8RqB5RBQ0A

Simulated command:  yt-dlp https://www.youtube.com/watch?v=l8RqB5RBQ0A -o video/%(webpage_url_domain)s/-%(channel)s/-%(title)s-%(id)s.%(ext)s.mp4 --write-info-json -f 22 --merge-output-format mp4 --cookies appdata/cookies.txt --write-thumbnail --no-clean-info-json -j --no-simulate

2. Click on Download, DL fail

3. See Error
Error for https://www.youtube.com/watch?v=l8RqB5RBQ0A
Error while retrieving info on video with URL https://www.youtube.com/watch?v=l8RqB5RBQ0A with the following message: Error: Command failed with exit code 1: node_modules/youtube-dl/bin/youtube-dl -o video/%(webpage_url_domain)s/-%(channel)s/-%(title)s-%(id)s.%(ext)s.mp4 --write-info-json -f 22 --merge-output-format mp4 --cookies appdata/cookies.txt --write-thumbnail --no-clean-info-json -j --no-simulate --dump-json http://www.youtube.com/watch?v=l8RqB5RBQ0A ERROR: [download] Got error: <urlopen error [Errno 99] Cannot assign requested address>. Giving up after 10 retries

4. From MongoDB Notification table
{
    _id: ObjectId('643c04884fcaa9014f4eb4e5'),
    type: 'download_error',
    actions: [
        'view_download_error',
        'retry_download'
    ],
    data: {
        download_uid: '6b438fad-a304-4e61-8c02-d3b3dea5a85f',
        download_url: 'https://www.youtube.com/watch?v=l8RqB5RBQ0A',
        download_error_type: null
    },
    user_uid: null,
    uid: '8d818631-4f42-4ec3-9a05-f23bbd4f5780',
    read: false,
    timestamp: 1681654920.316
}

5. After restarting server, start another download on the same video url https://www.youtube.com/watch?v=l8RqB5RBQ0A
Success.
From MongoDB Notification table
{
    _id: ObjectId('643c056af8631e01a12a0368'),
    type: 'download_complete',
    actions: [
        'play'
    ],
    data: {
        file_uid: 'ef6f7779-1c07-44cc-b35f-c0e8b1ab7169',
        file_title: 'Macross Plus Information High - HD AMV / MAD',
        file_thumbnail: 'https://i.ytimg.com/vi_webp/l8RqB5RBQ0A/maxresdefault.webp',
        original_url: 'https://www.youtube.com/watch?v=l8RqB5RBQ0A'
    },
    user_uid: null,
    uid: 'ff706bd0-56a2-4c0f-ad42-6d4547aa5879',
    read: false,
    timestamp: 1681655146.612
}

**Expected behavior**
To be able to download several videos without having to restart the server.
Whereas Download station or Jdownloader (in a container) simply download the videos or playlists in one go.

**Environment**
- YoutubeDL-Material 4.3
- On Synology 220+ docker container nightly-2023-04-16

- Container Log showed: 
  TypeError: Cannot read properties of undefined (reading 'uid')
    at /app/app.js:2034:27

Installation details:
Installed version: v4.3.1 -   [Update available - v4.3](https://github.com/Tzahi12345/YoutubeDL-Material/releases/latest). You can update from the settings menu.
Installation type: docker
Docker tag: nightly
Commit hash: c7bf1d0
Build date: 2023-04-16

[_ytdl_material_logs (1).txt](https://github.com/Tzahi12345/YoutubeDL-Material/files/11242563/_ytdl_material_logs.1.txt)
[_ytdl_material_logs.txt](https://github.com/Tzahi12345/YoutubeDL-Material/files/11242564/_ytdl_material_logs.txt)

**Comment by GlassedSilver** [comment]
We're aware that YTDL-M duplicates issue exists, and it's something that is being worked on, but due to the way download queuing got done in the past we have some high technical mortgage to pay, where we also want to consider safe and data integrity protecting ways of offering good and reliable solutions for already duplicates-loaded instances.

Thank you for your investigation and time.

**Comment by Bidonh** [comment]
> We're aware that YTDL-M duplicates issue exists
>download queuing

I may have poorly explained myself.
1. I try to start a download from a YT URL that fails.
2. I retry the DL that fails again.
3. I restart the server.
4. I start a download with the same YT URL that succeeds.

**Comment by Tzahi12345** [comment]
If I'd have to guess it would be a network issue on your end (seems that way based on this issue: https://github.com/yt-dlp/yt-dlp/issues/6771).

Some ideas/questions:
* Try adding `--socket-timeout,,60` to your custom args (https://github.com/yt-dlp/yt-dlp/issues/2969)
* This site suggests you may have both a wired and wireless connection active: https://www.linuxbabe.com/desktop-linux/install-youtube-dl-linux-use
* Did you set your local IP as the host? https://forums.sabnzbd.org/viewtopic.php?t=19050
* What sort of firewall settings do you have set up?
* Is your synology on an ARM device by chance?
* Did it also give the same error without cookies?

That's pretty much all I can think of from looking up this error on Google. I do think it's an error on your end, but I could be wrong.

Sorry about the CPU usage btw. It's a known issue (#122) and there's no easy way around it. Subscriptions are usually the culprit. On my windows PC (without Docker) it uses about 3-5% of my CPU usage, but I do have a beefy CPU.

I'll go ahead and close this unless we get other reports, let me know if you find out more info!
