### ISSUE TITLE
[BUG] Downloading videos below channel's max resolution

### ISSUE THREAD

**Issue by Collcroc123** [Tzahi12345/YoutubeDL-Material#869]
**Describe the bug**
All videos downloaded are at 720p, despite the max resolution being set to 1080p for the channel.

**To Reproduce**
1. Go to Subscriptions and add a subscription
2. Set Max Quality to 1080p
3. Wait for videos to download
4. Check video resolution and see it's 720p

**Expected behavior**
Should download the videos at 1080p 

**Screenshots**
N/A

**Environment**
- YoutubeDL-Material version v4.3
- Docker tag: latest

**Additional context**
I know that the videos I'm downloading support 1080p so I'm unsure why it's instead doing 720p

**Comment by Tzahi12345** [comment]
This was actually fixed, it'll be resolved in v4.3.1. In the meantime you can use the latest `nightly`.

Commit here: https://github.com/Tzahi12345/YoutubeDL-Material/commit/61973510f764326b0da7beaa721f88c8b0155993
