### ISSUE TITLE
Run error standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by LoYungSum** [Tzahi12345/YoutubeDL-Material#87]
When I follow the tutorial of https://nashosted.com/youtubedl-material-a-self-hosted-youtube-video-downloader/ , and install with the command
```
$ docker run -d --name YouTubeDL-Material \
              -v /your/appdata/location:/app/appdata \
              -v /your/audio/location:/app/audio \
              -v /your/video/location:/app/video \
              -v /your/subscriptions/location:/app/subscriptions \
              -v /your/users/location:/app/users \
              -p 8998:17442 \
              tzahi12345/youtubedl-material:latest
```
I got an error `standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by Tzahi12345** [comment]
Apparently this might happen if someone is running on anything that's not x86. Are you running this on a raspberry pi like device, or is this on a regular computer?

**Comment by LoYungSum** [comment]
Yeah, I'm running on raspberry pi 3B+

**Comment by Tzahi12345** [comment]
I see. Basically, ARM isn't supported by this project. The good news is, someone made a fork and built that support!

Actually, two people did:

@dee-oh-double-gee's: https://github.com/dee-oh-double-gee/YoutubeDL-Material

@volcan96's: https://github.com/volcan96/YoutubeDL-Material

@dee-oh-double-gee's is the most up to date, but it doesn't have the 4.0 features merged in yet. @volcan96's gets updated more often, but it's a tiny bit more behind. No guarantee either of these will work with your setup, but I hope this helps!

**Comment by LoYungSum** [comment]
Thanks, I'll check out those fork

**Comment by volcan96** [comment]
Sorry to re-open this. Just a head's up that at least for my docker images, they are hit and miss. I build them for fun/learning. 

That being said, I've found that it's better to run youtubedl-material on a non arm architecture. There are quirks with how arm handle passing of values and variables that make some of the core features of YTDL-material fail (e.g. downloading a playlist).

Just my 2 cents.

**Comment by Tzahi12345** [comment]
>I build them for fun/learning.

Why else would we program :P

Just wanted to provide *some* solution to people trying to run on ARM. I think I may have a Pi somewhere around, so maybe I'll get the chance to actually play around with your setup and see exactly how it breaks and if it could be fixed.

**Comment by LoYungSum** [comment]
Thanks, I’ll wait for the response 👍👍

**Comment by Tzahi12345** [comment]
There's an official ARM build up! Use the tag `nightly-arm` on Docker and you'll be set :)

**Comment by volcan96** [comment]
Got around to testing the image today. So far so good:
1) it booted
2) able to download a video in non-multi download mode
2a) able to download multiple video files in multi-download mode
3) able to download multiple audio-only files in multi-download mode
3a) able to download single audio only files in non-multi download mode
4) haven't fully tested downloading YT playlists
