### ISSUE TITLE
[FEATURE] Manually download videos from subscription.

### ISSUE THREAD

**Issue by Snake883** [Tzahi12345/YoutubeDL-Material#871]
I would like the ability to manually download videos from a subscription.
I want to see a list of videos from the subscription, and select which videos I want to download.

Currently, subscriptions automatically download new videos (even if there's no checkmark in "Download all uploads").

**Comment by enigmanet** [comment]
I also want this, as I'm subscribing to a channel and never triggers or takes forever to load. 
I'd buy the person coffee every morning for entire week.
