### ISSUE TITLE
[BUG]:  Error: Cannot find module '@sindresorhus/is'

### ISSUE THREAD

**Issue by samcro1967** [Tzahi12345/YoutubeDL-Material#877]
Container fails to start after last update to nightly.

```
04/24/2023 3:10:58 PM
04/24/2023 3:10:58 PM
> backend@1.0.0 start
04/24/2023 3:10:58 PM
> pm2-runtime --raw pm2.config.js
04/24/2023 3:10:58 PM
04/24/2023 3:10:59 PM
2023-04-24T20:10:59: PM2 log: Launching in no daemon mode
04/24/2023 3:10:59 PM
2023-04-24T20:10:59: PM2 log: [Watch] Start watching YoutubeDL-Material
04/24/2023 3:10:59 PM
2023-04-24T20:10:59: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
04/24/2023 3:10:59 PM
2023-04-24T20:10:59: PM2 log: App [YoutubeDL-Material:0] online
04/24/2023 3:10:59 PM
Error: Cannot find module '@sindresorhus/is'
04/24/2023 3:10:59 PM
Require stack:
04/24/2023 3:10:59 PM
- /app/node_modules/got/dist/source/create.js
04/24/2023 3:10:59 PM
- /app/node_modules/got/dist/source/index.js
04/24/2023 3:10:59 PM
- /app/node_modules/gotify/dist/gotify.js
04/24/2023 3:10:59 PM
- /app/node_modules/gotify/dist/index.js
04/24/2023 3:10:59 PM
- /app/notifications.js
04/24/2023 3:10:59 PM
- /app/downloader.js
04/24/2023 3:10:59 PM
- /app/app.js
04/24/2023 3:10:59 PM
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
04/24/2023 3:10:59 PM
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:81:25)
04/24/2023 3:10:59 PM
    at require (node:internal/modules/cjs/helpers:102:18)
04/24/2023 3:10:59 PM
    at Object.<anonymous> (/app/node_modules/got/dist/source/create.js:3:14)
04/24/2023 3:10:59 PM
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
04/24/2023 3:10:59 PM
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
04/24/2023 3:10:59 PM
    at Module.load (node:internal/modules/cjs/loader:981:32)
04/24/2023 3:10:59 PM
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
04/24/2023 3:10:59 PM
    at Module.require (node:internal/modules/cjs/loader:1005:19)
04/24/2023 3:10:59 PM
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
04/24/2023 3:10:59 PM
    at require (node:internal/modules/cjs/helpers:102:18)
04/24/2023 3:10:59 PM
    at Object.<anonymous> (/app/node_modules/got/dist/source/index.js:7:18)
04/24/2023 3:10:59 PM
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
04/24/2023 3:10:59 PM
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
04/24/2023 3:10:59 PM
    at Module.load (node:internal/modules/cjs/loader:981:32)
04/24/2023 3:10:59 PM
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
04/24/2023 3:10:59 PM
  code: 'MODULE_NOT_FOUND',
04/24/2023 3:10:59 PM
  requireStack: [
04/24/2023 3:10:59 PM
    '/app/node_modules/got/dist/source/create.js',
04/24/2023 3:10:59 PM
    '/app/node_modules/got/dist/source/index.js',
04/24/2023 3:10:59 PM
    '/app/node_modules/gotify/dist/gotify.js',
04/24/2023 3:10:59 PM
    '/app/node_modules/gotify/dist/index.js',
04/24/2023 3:10:59 PM
    '/app/notifications.js',
04/24/2023 3:10:59 PM
    '/app/downloader.js',
04/24/2023 3:10:59 PM
    '/app/app.js'
04/24/2023 3:10:59 PM
  ]
04/24/2023 3:10:59 PM
}
```

**Comment by sixshooterz** [comment]
Not sure why but I had to run `npm install @sindresorhus/is` to fix. I followed it up with `npm update`, not sure if needed or not. The interface seems to be working after those. Now I'm getting separate errors when downloading a video. Log file [here](https://pastebin.com/k05y6WHC).

**Comment by Tzahi12345** [comment]
Seems like the npm install may have mangled the youtube-dl dependency directory, can you try recreating the container?

I see where the original error is happening, just not sure why... I'll investigate

**Comment by sixshooterz** [comment]
I've tried recreating and get the same error as the OP. The interface is down until running the npm install and update commands (I did not run npm audit fix or anything else).

**Comment by Tzahi12345** [comment]
I think I fixed the issue. For some reason the package-lock.json was stale, hence that dependency was missed. Commit: https://github.com/Tzahi12345/YoutubeDL-Material/commit/5a379a6a2b57810c3faa798694e47071bc039893

Are you still seeing the other errors in your log file though @sixshooterz?

**Comment by sixshooterz** [comment]
After running the npm commands, yes, it still gives the other errors I posted to Pastebin.

**Comment by Tzahi12345** [comment]
Oh, that's because you ran `npm update`, yes that will break things :)

You only need to run the following:

1. `npm install gotify`
2. `npm install` (for good measure)

Either way the nightly should be updated in 45 mins or so

**Comment by sixshooterz** [comment]
Excellent! I'll give it a go tomorrow afternoon. Thanks for the quick turnaround!

**Comment by sixshooterz** [comment]
Decided to give it a go tonight. I ran the two npm commands you listed above. When I tried to download a video it showed this in the docker logs:

> 2023-04-24T23:53:58.934Z INFO: Config items set using ENV variables.
> 2023-04-24T23:53:59.094Z INFO: Restarting server...
> 2023-04-24T19:53:59: PM2 log: App [YoutubeDL-Material:0] exited with code [1] via signal [SIGINT]
> 2023-04-24T19:53:59: PM2 log: App [YoutubeDL-Material:0] starting in -fork mode-
> 2023-04-24T19:53:59: PM2 log: App [YoutubeDL-Material:0] online
> 2023-04-24T23:54:00.932Z INFO: Config items set using ENV variables.
> 2023-04-24T23:54:01.676Z INFO: YoutubeDL-Material v4.3.1 started on PORT 17442
> (node:1755) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> TypeError: Cannot read properties of null (reading 'name')
>     at collectInfo (/app/downloader.js:251:46)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> TypeError: Cannot read properties of null (reading 'name')
>     at collectInfo (/app/downloader.js:251:46)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Tzahi12345** [comment]
My bad, not sure how that slipped through testing. Should be fixed now: https://github.com/Tzahi12345/YoutubeDL-Material/commit/f973426bd2f89580c8944683977c37635c1d4b63

**Comment by Tzahi12345** [comment]
This is fixed, closing
