### ISSUE TITLE
[BUG] File manager in Web UI shows the files even if they get deleted from server

### ISSUE THREAD

**Issue by vah4827** [Tzahi12345/YoutubeDL-Material#878]
**Describe the bug**
When Source file is removed, web ui file manager still shows the file 

**To Reproduce**
1. Delete or move the downloaded file from Audio/Video folder
2. Refresh the Web UI
3. Web UI  still shows the file unless clock on that and choose delete from web file manager

**Expected behavior**
The server periodically checks the download folders and updates DB or web UI file manager accordingly

**Comment by Tzahi12345** [comment]
You can set this up, here's how:

1. Go to Tasks
2. Under `Missing files check`, click the schedule icon and set your desired schedule
3. Optionally, click the settings icon and select `Do not ask for confirmation`, this will avoid you having to confirm to delete the files from the file manager
4. All done!

If you don't see the settings icon you may need to update to the latest nightly. Let me know if you need more help on this front!
