### ISSUE TITLE
[FEATURE] Notification through Discord webhook

### ISSUE THREAD

**Issue by arithxp** [Tzahi12345/YoutubeDL-Material#879]
**Is your feature request related to a problem? Please describe.**
I wish the notification function could also work with Discord's webhooks.

Additionaly, I'm leaving a message while considering whether to open an issue.
How can I add --extractor-args "youtube:lang=ko,en" in custom args?
I've tried using the following methods, but they don't seem to work:
--extractor-args,"youtube:lang=ko,en"
--extractor-args,,"youtube:lang=ko,en"
--extractor-args "youtube:lang=ko,en"
'--extractor-args "youtube:lang=ko,en"'"

**Comment by Tzahi12345** [comment]
Just added this to the latest PR (#873). Here's a screenshot:

![image](https://user-images.githubusercontent.com/707413/234449133-dcc733db-7b4f-4212-90f2-dfe3319e35a4.png)

I slightly updated the formatting but it's largely the same. Let me know if you'd like style improvements.

For the extractor args, can you give me an example URL? I'm guessing ko is Korean but if you have a video on hand that would be helpful for testing. Generally you want double commas between args, so the second one you listed looks *most* correct, I'm not sure you need the quotes.

**Comment by arithxp** [comment]
Thank you for adding the Discord webhooks feature.


An example url is here. I should have told you earlier, sorry.
https://www.youtube.com/watch?v=nSMoINh3WIk
yt-dlp -s -e https://www.youtube.com/watch?v=nSMoINh3WIk --extractor-args youtube:lang=ko,en
ko : ASMR 리얼한 모닥불 불멍 10시간🔥😌 (고음질, 현장감, 장작타는, 캠프파이어)
en : ASMR Make You Warm🔥😌 (Realistic Fire Sounds 10H, Campfire, Hi-Fi Binaural)
If there is an English title and a Korean title, I want to download it as a Korean title, and if there is no Korean title, I want to download it as an English title.

https://www.youtube.com/watch?v=FhTEoQBXr38
yt-dlp -s -e https://www.youtube.com/watch?v=FhTEoQBXr38 --extractor-args youtube:lang=en,ja
en : Eating Giant Sea Urchins Full of Poisonous Spines
ja : 全身毒針に包まれた巨大ウニを食べてみると。。。
