### ISSUE TITLE
Can't download videos from reddit.

### ISSUE THREAD

**Issue by xGigaa** [Tzahi12345/YoutubeDL-Material#89]
I seems to be unable to download reddit videos. This works fine on the normal youtube-dl application but fails with this when I use YoutubeDL-Material:

`2020-05-18T20:08:47.896Z ERROR: Command failed with exit code 1: /home/youtubedl/youtubedl-material/node_modules/youtube-dl/bin/youtube-dl --dump-json -f best -o video/%(title)s.mp4 -f best[ext=mp4] --write-info-json --print-json -- https://www.reddit.com/r/HalfLife/comments/glsy0t/ive_never_had_issues_with_marines_and_grenades/`

Inspect element doesn't seem to give me any useful debug information sadly.

**Comment by Tzahi12345** [comment]
Nice catch! I've gone ahead and implemented a fix, you can view the [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/0816cb70468fd8f10880ce0c24d16fae5a8bdc18).

You can use the `nightly` tag on the Docker image to get this fix now, or wait until the next update. Thanks for the bug report!
