### ISSUE TITLE
Download failed 

### ISSUE THREAD

**Issue by hjyoung1** [Tzahi12345/YoutubeDL-Material#9]
I'm unable to setup this on my server. 
![Screenshot_20200228-211743~01](https://user-images.githubusercontent.com/45882061/75565374-d6d14800-5a73-11ea-8ed5-903da862e253.jpg)
![Screenshot_20200228-215039](https://user-images.githubusercontent.com/45882061/75565703-7098f500-5a74-11ea-8667-c52c148bd7f7.jpg)

If I'm hosting on server what values should i change for backend and frontend url? 
Tried 

> My server ip 
localhost
0.0.0.0
127.0.0.1

But still it's not working. 
I'm using docker-compose with nginx proxy (to assign hostname https://github.com/jwilder/nginx-proxy) to deploy.

**Comment by Tzahi12345** [comment]
The frontend URL is the URL you will use in a browser to access YTDL-Material. From what I understand, you are using Docker w/ a reverse-proxy. In this instance, I believe the frontend URL will be whatever path the reverse-proxy is pointing to.

Example:

Imagine your hostname is example.com and the reverse-proxy uses the path /ytdl. The frontend URL will be http://example.com/ytdl

The backend URL (if hosted on the same server) will be http://example.com:17442/

Let me know if these settings work alright for you! I'm not too familiar with how Docker and nginx-proxy work so I may be wrong on these configuration items. BTW: any other errors other than the "could not load formats"? That error in particular is not breaking, it simply means that quality formats (like 1080p, 720p) could not be found. There must be some other error happening.

**Comment by hjyoung1** [comment]
> The frontend URL is the URL you will use in a browser to access YTDL-Material. From what I understand, you are using Docker w/ a reverse-proxy. In this instance, I believe the frontend URL will be whatever path the reverse-proxy is pointing to.
> 
> Example:
> 
> Imagine your hostname is example.com and the reverse-proxy uses the path /ytdl. The frontend URL will be http://example.com/ytdl
> 
> The backend URL (if hosted on the same server) will be http://example.com:17442/
> 
> Let me know if these settings work alright for you! I'm not too familiar with how Docker and nginx-proxy work so I may be wrong on these configuration items. BTW: any other errors other than the "could not load formats"? That error in particular is not breaking, it simply means that quality formats (like 1080p, 720p) could not be found. There must be some other error happening.

Still same error. 
 using reverse proxy for
ytdl.example.com

frontend : http://ytdl.example.com
backend : http://ytdl.example.com:17442/ (tried without ytdl too)
But still same issue.
![Screenshot_20200229-135629](https://user-images.githubusercontent.com/45882061/75604297-1e4fe680-5afd-11ea-9db9-55337afdc511.jpg)

I also tried deploying this normally without docker. But still facing similar issues :/

**Comment by hjyoung1** [comment]
I tried latest 3.3 docker image and it's working fine now.
But i have some suggestions specially for mobile users 
![Screenshot_20200229-222503__01](https://user-images.githubusercontent.com/45882061/75611703-eff4fa00-5b42-11ea-87b9-7326fb04b917.jpg)
As you see delete button and title is completely visible. It would be great if you change 2 tiles for such cases.

**Comment by Tzahi12345** [comment]
Ok cool, great to hear the new version is working for you. It's an experimental build, and I'll be coming out with a slightly updated one within the next few days.

Thanks for the UI suggestions btw, I'll take a look at why they're getting cut off and get that in the new update.

Let me know if there are any more issues!
