### ISSUE TITLE
[Enhancement] Add ldap and oauth2 authentication capabilites

### ISSUE THREAD

**Issue by UnlimitedCookies** [Tzahi12345/YoutubeDL-Material#90]
Hi!

I know this might be a hard task to implement, but in order to not have to remember a new password this could eliminate the need to carry another password.

What's your take on this?

Thanks.

**Comment by Tzahi12345** [comment]
Apparently, using the library that's already being used, this is *relatively* [easy to implement](http://www.passportjs.org/docs/oauth2-api/). I can't say it'll be priority number 1, but it's a good idea so I'll see what I can do.

In general, I want to continue to add integrations from both ends (adding YoutubeDL-Material to platforms and vice versa), so it's very much in line with the development strategy over the next few months.

**Comment by UnlimitedCookies** [comment]
If you need something to test LDAP with: https://github.com/rroemhild/docker-test-openldap

**Comment by Tzahi12345** [comment]
This is done! Check out the [latest PR](https://github.com/Tzahi12345/YoutubeDL-Material/pull/205). If you want to use LDAP, jump on the latest `nightly` and head into the `Users` tab in the settings, you'll see a new `Auth method` select. For more details check out the PR, and as always, thanks for the great suggestion!
