### ISSUE TITLE
[BUG] YTDL-Material Returns ERROR: ffmpeg exited with code -11 when recording livestreams

### ISSUE THREAD

**Issue by Wado729** [Tzahi12345/YoutubeDL-Material#903]
**Describe the bug**
When trying to download a URL for a livestream, like twitch, the site returns this "ERROR: ffmpeg exited with code -11".  Prior to 4.3.1 it recorded fine and created a .mp4 when the stream was over.

**To Reproduce**
1. Go to 'localhost:8998'
2. Enter the URL in the URL field
3. Click on 'Download'

**Expected behavior**
Stream recorded and a mp4 file created.

**Screenshots**
here is the verbose error:
[debug] Command-line config: ['-o', 'video/%(title)s.mp4', '--write-info-json', '--verbose', '--no-clean-info-json', '-j', '--no-simulate', '--', 'https://www.twitch.tv/aztecross'] [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI) [debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip) [debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-6.1.0-0.deb11.6-amd64-x86_64-with-glibc2.29 (OpenSSL 1.1.1f 31 Mar 2020, glibc 2.31) [debug] exe versions: ffmpeg N-65014-g7c130d6911-static (setts), ffprobe N-65014-g7c130d6911-static [debug] Optional libraries: Cryptodome-3.17, sqlite3-2.6.0 [debug] Proxy map: {} [debug] Loaded 1786 extractors [twitch:stream] Extracting URL: https://www.twitch.tv/aztecross [twitch:stream] aztecross: Downloading stream GraphQL [twitch:stream] aztecross: Downloading stream access token GraphQL [twitch:stream] 41334800473: Downloading m3u8 information [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id [debug] Default format spec: best/bestvideo+bestaudio [info] 41334800473: Downloading 1 format(s): 1080p60__source_ [info] Writing video metadata as JSON to: video/Aztecross (live) 2023-05-09 18_21.info.json [debug] Invoking ffmpeg downloader on "https://video-weaver.atl01.hls.ttvnw.net/v1/playlist/CrgEJAbZNVMneZYLHn8Qy0M_TNACrdhWJijgKkrQFL4LM_A_afmzqw30DjrQMkbZ5ubABvsd513VjrxHTDzOmq_LezPFq8DdVC98-vU95nYEV-y3lLPeFypAwfC75KgfoI1WSB7tqMgfuyV72FlZ7AYsQRzuuhviv1XAWcvbeI7EqLUM3dfcJzhu1e5Z9n1S8UoOnu0TPPRr5bd_2b1aFpgIXKiOZ1D99vbUkqTbrUErEqxTufHhONpDadZWhFue80uUE2uVfum2mz_N8Q_mGIW1wH2jrKme1Qu_lV7pkrq6j7Ut5GGTYfImkImgsy6K5T9DOZt4cvhGiXf9xVh1jl9IWSSATgtEB3HxTCxo7S8ezf4EYAYB4ia6ClKMLiw2m85fxoQZGbDEQU3tlk5HglgU239J3zsPdHFm-SaNHKdNWMMBmOm3Of91In_9iY59njkJoRT37v3wg3UtOw6ILSMSpxA2ief_e8KzJG9UXi5kxKonQPgFDh_kDUHSbZawysmuB6FL5GZ8L1pdnDUlSLSBi-jzuGfE-N4hFshsUklN3jTk9Vdau52wm1u_TrdI1Ipo-tcVTtuYW_qrxNw7iTJ0uxNVGYZBtqPbvW1YLEZUgDWldtp8KTs9eF9SokL915iy3BbCMFuSePwiX5tgLBNoyMq9u-o0y_nLZM9x1-8-Hg83ef2LmUFIZn0sRZ5Q-6RKJwp6ifdqez788wR9MEf6qI6mkb93gyovIRXiEPHtQQkRBj6w_padsRoMau4Y31bj8q-SEGduIAEqCXVzLWVhc3QtMTD4BA.m3u8" [download] Destination: video/Aztecross (live) 2023-05-09 18_21.mp4 [debug] ffmpeg command line: ffmpeg -y -loglevel quiet -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-us,en;q=0.5 Sec-Fetch-Mode: navigate ' -i https://video-weaver.atl01.hls.ttvnw.net/v1/playlist/CrgEJAbZNVMneZYLHn8Qy0M_TNACrdhWJijgKkrQFL4LM_A_afmzqw30DjrQMkbZ5ubABvsd513VjrxHTDzOmq_LezPFq8DdVC98-vU95nYEV-y3lLPeFypAwfC75KgfoI1WSB7tqMgfuyV72FlZ7AYsQRzuuhviv1XAWcvbeI7EqLUM3dfcJzhu1e5Z9n1S8UoOnu0TPPRr5bd_2b1aFpgIXKiOZ1D99vbUkqTbrUErEqxTufHhONpDadZWhFue80uUE2uVfum2mz_N8Q_mGIW1wH2jrKme1Qu_lV7pkrq6j7Ut5GGTYfImkImgsy6K5T9DOZt4cvhGiXf9xVh1jl9IWSSATgtEB3HxTCxo7S8ezf4EYAYB4ia6ClKMLiw2m85fxoQZGbDEQU3tlk5HglgU239J3zsPdHFm-SaNHKdNWMMBmOm3Of91In_9iY59njkJoRT37v3wg3UtOw6ILSMSpxA2ief_e8KzJG9UXi5kxKonQPgFDh_kDUHSbZawysmuB6FL5GZ8L1pdnDUlSLSBi-jzuGfE-N4hFshsUklN3jTk9Vdau52wm1u_TrdI1Ipo-tcVTtuYW_qrxNw7iTJ0uxNVGYZBtqPbvW1YLEZUgDWldtp8KTs9eF9SokL915iy3BbCMFuSePwiX5tgLBNoyMq9u-o0y_nLZM9x1-8-Hg83ef2LmUFIZn0sRZ5Q-6RKJwp6ifdqez788wR9MEf6qI6mkb93gyovIRXiEPHtQQkRBj6w_padsRoMau4Y31bj8q-SEGduIAEqCXVzLWVhc3QtMTD4BA.m3u8 -c copy -f mpegts 'file:video/Aztecross (live) 2023-05-09 18_21.mp4.part' ERROR: ffmpeg exited with code -11 File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "node_modules/youtube-dl/bin/youtube-dl/__main__.py", line 17, in <module> yt_dlp.main() File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/__init__.py", line 967, in main _exit(*variadic(_real_main(argv))) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/__init__.py", line 957, in _real_main return ydl.download(all_urls) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 3369, in download self.__download_wrapper(self.extract_info)( File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 3344, in wrapper res = func(*args, **kwargs) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1507, in extract_info return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1518, in wrapper return func(self, *args, **kwargs) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1615, in __extract_info return self.process_ie_result(ie_result, download, extra_info) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result ie_result = self.process_video_result(ie_result, download=download) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 2779, in process_video_result self.process_info(new_info) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 3247, in process_info success, real_download = self.dl(temp_filename, info_dict) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 2970, in dl return fd.download(name, new_info, subtitle) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/downloader/common.py", line 444, in download ret = self.real_download(filename, info_dict) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/downloader/external.py", line 76, in real_download self.report_error('%s exited with code %d' % ( File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1015, in report_error self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs) File "node_modules/youtube-dl/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 944, in trouble tb_data = traceback.format_list(traceback.extract_stack())

**Environment**
Installation details:
Installed version: v4.3.1 -   You are up to date.
Installation type: docker
Docker tag: latest
Commit hash: 658a76d
Build date: 2023-05-09

Found a bug or have a suggestion? Click here to create an issue!

**Additional context**
https://www.twitch.tv/aztecross
or any twitch or livestream URL

**Comment by Tzahi12345** [comment]
I was able to reproduce this in docker. I believe it's actually an ffmpeg version issue. Will continue testing today.

Maybe we should have a menu to manage youtube-dl and ffmpeg versions which would make this easier to test

**Comment by Tzahi12345** [comment]
Just confirmed this is an issue with ffmpeg 6.0 specifically. Just put up #908, once that merges I'll update the latest and 4.3.1 tags

**Comment by ragregory42** [comment]
Same for me

**Comment by Erik262** [comment]
Same here as well

**Comment by truthsword** [comment]
Still here
ffmpeg exited with code -11
