### ISSUE TITLE
Video files manager displays title in ID field

### ISSUE THREAD

**Issue by CountParadox** [Tzahi12345/YoutubeDL-Material#91]
https://i.imgur.com/yEqhWNN.png

in the downloaded video manager area, the video title displays as a hyperlink correctly, but under that is the 'ID' field, which ALSO shows the title, rather than the video ID.

This doesnt bother me but looks like a bug?

**Comment by CountParadox** [comment]
![image](https://user-images.githubusercontent.com/6279380/82266829-168e3880-99ae-11ea-9633-754b484bbd4e.png)

**Comment by Tzahi12345** [comment]
This is actually vestigial information from back when the ID used to be the title. I'm actually quite inconsistent with this:

1. In the downloads manager, the ID is (for YT videos) the youtube ID, i.e. the one you see in the URL
2. In the file manager, the ID is the file name
3. In the database there is also a file UID which is a randomly generated string

The third discrepancy isn't too bad, and this issue has more to do with 1 & 2. I'm still left asking what the ID should be, or if I should move it off the file card entirely to avoid any confusion. I'll put more thought into this, lmk if you have any thoughts yourself.

**Comment by CountParadox** [comment]
So my thought is having the video ID from its website of source is very handy, as it would let you find the original video if you need to.

For example. if you have:


Title: AVideo
ID: n39nw4bwk4fjb


then you could google search for "n39nw4bwk4fjb" and likely find the original video.

Maybe it would be handy to list the source website too?

**Comment by Tzahi12345** [comment]
Agreed, I'll probably go with youtube's ID, and then randomly generate one when an ID isn't available (some non-youtube videos may not include it).

>Maybe it would be handy to list the source website too?

If you click the 3 dots and then info, you can see the URL there. I don't think it will fit on the file card as it stands.

**Comment by CountParadox** [comment]
> If you click the 3 dots and then info, you can see the URL there. I don't think it will fit on the file card as it stands.


oh cool!  I had seen this I just forgot

**Comment by Tzahi12345** [comment]
Bug fixed! Check out the [commit here.](https://github.com/Tzahi12345/YoutubeDL-Material/commit/57a9434b3c50bb8d42be863dcaa8ff1094daaad8)

Thanks for pointing this out! Always appreciated :)
