### ISSUE TITLE
[BUG] Cannot interact with local user accounts if LDAP is enabled.

### ISSUE THREAD

**Issue by dbusse-wcr7** [Tzahi12345/YoutubeDL-Material#912]
**Describe the bug**
If auth is switched to LDAP, local users are not show in the WebUI and cannot be modified or deleted.

**To Reproduce**
1. Enable Multiuser mode
2. go to users, create a secondary user other than admin to test with
3. enable ldap and log in with an ldap user
4. logout of ldap use
5. log in with admin user
6. go to users in settings.
7. can no longer see list of users, and cannot delete user setup for testing.

**Expected behavior**
Should be able to see list of existing local users to modify or delte.

**Screenshots**
![image](https://github.com/Tzahi12345/YoutubeDL-Material/assets/75992694/c89c8581-8680-498b-850e-42276e4e280e)

**Environment**
Installed version: v4.3.1 -   You are up to date.
Installation type: docker
Docker tag: latest

**Comment by Tzahi12345** [comment]
Having a hard time replicating this, can you check the browser or server logs to see if anything shows up there?

**Comment by dbusse-wcr7** [comment]
Here is what I am seeing in the browser console

![image](https://github.com/Tzahi12345/YoutubeDL-Material/assets/75992694/791c5318-ad28-4c10-a648-137edfd98546)

**Comment by Tzahi12345** [comment]
There's something weird going on in the `users` table in the database, would you mind copying that into here? Remember to remove the passhash field!

**Comment by dbusse-wcr7** [comment]
There are Two entries in the ytdl_material db in the "users" Collection

```
{ "_id" : ObjectId("[REDACTED]"), "name" : "admin", "uid" : "admin", "passhash" : "[REDACTED]", "files" : [ ], "playlists" : [ ], "subscriptions" : [ ], "created" : 1683825539888, "role" : "admin", "permissions" : [ ], "permission_overrides" : [ ], "auth_method" : "internal" }

{ "_id" : ObjectId("[REDACTED]"), "name" : null, "uid" : null, "passhash" : null, "files" : [ ], "playlists" : [ ], "subscriptions" : [ ], "created" : 1683825587710, "role" : "user", "permissions" : [ ], "permission_overrides" : [ ], "auth_method" : "ldap" }
```

I'm not super familiar with mongodb, so let me know if this isn't the info you needed. to get this I did the following
Connect to MongoDB Container shell
`show databases`
`use ytdl_material;`
`show collections`
`db.users.find()`

**Comment by Tzahi12345** [comment]
If you delete the second entry it should work just fine. Basically the UI isn't able to properly handle users that are mangled and have invalid (null) name or uid fields.

I am not able to reproduce what caused this issue but in the latest PR (#929) I added a fix to prevent this from happening in the future. If you see an error pop up that says registration failed due to invalid username/userid, then we can re-evaluate and see what's causing that to happen.
