### ISSUE TITLE
[BUG] Title filtering does not appear to work on channel subscriptions

### ISSUE THREAD

**Issue by n1nj4888** [Tzahi12345/YoutubeDL-Material#913]
I have configured a channel subscription with the following settings but no videos are downloaded even though there are videos in the CHANNEL which have the word MATCHPHRASE in the title

URL: https://www.youtube.com/c/CHANNEL/videos
Download: Last 14 days
Max Quality: 1080p
Custom args: `-f,,bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best,,--match-title,,'MATCHPHRASE'`

If I docker exec into the container and run the following equivalent CLI command directly, this seems to work and the matching videos are downloaded as expected:

```
cd /app/node_modules/youtube-dl/bin
./youtube-dl -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best --match-title 'MATCHPRASE' --dateafter 20230501 https://www.youtube.com/c/CHANNEL/videos
```

**Comment by Tzahi12345** [comment]
I think the issue here is the quotes. Try like this:

```
-f,,bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best,,--match-title,,MATCHPHRASE
```

It works for me

**Comment by n1nj4888** [comment]
Thanks @Tzahi12345 ! That solved the issue. 

Out of interest, this works now with MATCHPHRASE as a single word but is there any guidance about how the value should be formatted if MATCHPHRASE contains spaces/special characters?
