### ISSUE TITLE
[BUG] Pull fails on RPI4 aarch64

### ISSUE THREAD

**Issue by monokinetic** [Tzahi12345/YoutubeDL-Material#915]
**Describe the bug**
Trying to update my 4.3 version to 4.3.1 always fails with:

no matching manifest for linux/arm/v8 in the manifest list entries

AFAIK I'm running 64 bit:
Linux KodiBox 6.1.19 #1 SMP Sat Mar 18 20:58:05 UTC 2023 aarch64 GNU/Linux

and I see there's an arm64 version up on Dockerhub.

I'm running Docker on libreelec 11.01:
Docker version 23.0.4, build f480fb1e374b16c8a1419e84f465f2562456145e

**To Reproduce**
1. Pull this repo.
2. Try to run the docker-compose.yaml file included.
3. It fails with the error above.

Seems kind of weird because I've had 4.3 running fine for ages.

**Expected behavior**
To be able to pull version 4.3.1 on a Raspberry Pi4

**Comment by monokinetic** [comment]
Sorry my bad, it seems like actually libreelec 11 isn't fully 64 bit. I assume that's why it's not working. Still seems a bit odd as I have 4.3 installed and running fine! Closing for now.

**Comment by Tzahi12345** [comment]
Basically we stopped supporting 32 bit arm temporarily because the CI/CD pipeline got way too complicated. It will be supported again when #890 merges. Sorry for the confusion!
