### ISSUE TITLE
After enabling multi-user, the previous default users subscriptions continue to run

### ISSUE THREAD

**Issue by CountParadox** [Tzahi12345/YoutubeDL-Material#92]
This causes the logs to fill up with any missing videos, and i suspect many thousands of unrequired API calls to go through.

Currently as a work around you can disable multi-user, reload the page, remove the subscription and re-enable it. User accounts appear to persist.

**Comment by Tzahi12345** [comment]
Interesting, definitely a bug as the intention is that it seamlessly switches to user subscriptions.

Does restarting the container solve the problem as well? At least as a workaround until I get a chance to fix it.

**Comment by CountParadox** [comment]
I feel like disabling multi user and removing them is simple enough for now.
Ideally a user wanting multi-user would enable it at the start rather than playing with it a bit first ;)

**Comment by Tzahi12345** [comment]
[Latest commit](https://github.com/Tzahi12345/YoutubeDL-Material/commit/efdc471ccf51ce5c52e7ac792b047dd7dba5f171) should fix it, thanks for the bug report!
