### ISSUE TITLE
[BUG] Fails to download any youtube video on Synology NAS

### ISSUE THREAD

**Issue by ch4ndu** [Tzahi12345/YoutubeDL-Material#926]
**Describe the bug**
Not able to download any videos. Here is the log for the error
Error while retrieving info on video with URL https://www.youtube.com/watch?v=jprhe-cWKGs with the following message: Error: Command failed with exit code 2: node_modules/youtube-dl/bin/youtube-dl -o video/%(title)s.mp4 --write-info-json -S res:2160 --merge-output-format mp4 --write-thumbnail --no-clean-info-json -j --dump-json http://www.youtube.com/watch?v=jprhe-cWKGs Usage: youtube-dl [OPTIONS] URL [URL...] youtube-dl: error: no such option: -S

**Environment**
- YoutubeDL-Material version:4.3.1

Installation type: docker
Docker tag: latest
Commit hash: 80b41af
Build date: 2023-05-19

**Additional context**
Add any other context about the problem here. For example, a YouTube link.

**Comment by Tzahi12345** [comment]
Verify that you're using yt-dlp. If you switched to it you need to restart your container

**Comment by ch4ndu** [comment]
thanks for the help...works now
