### ISSUE TITLE
Cant download from non-youtube websites

### ISSUE THREAD

**Issue by CountParadox** [Tzahi12345/YoutubeDL-Material#93]
It appears I am unable to download from non-youtube websites.

Attempting to do so results in:

![image](https://user-images.githubusercontent.com/6279380/82267529-ffe8e100-99af-11ea-8bc1-46f759dad710.png)

![image](https://user-images.githubusercontent.com/6279380/82267564-1bec8280-99b0-11ea-9922-012a49e0613f.png)

This is unfortunate as youtube-dl supports *many* websites and it would be very handy.

The application should attempt to gather video info, and if successful continue as normal, but if unsuccessful it would be nice if it tries to download it with youtube-dl and if THAT succeeds then generate a thumbnail from the resulting video file using ffmpeg or similar, and use the filename as the video title in the web UI.

for testing, I tried downloading videos from:

pornhub.com
91porn.com
dailymotion.com
niconico.jp

**Comment by Tzahi12345** [comment]
I've been adding workarounds for each site individually, but I was thinking of this a second ago and I should do it the other way around:

Any video that's not youtube will use the workaround. I've gone ahead and implemented this, you can see the relevant [commit here](https://github.com/Tzahi12345/YoutubeDL-Material/commit/05d962328be1f6c3e2b5ba716b01ba45e1080295). You can use the `nightly` tag on Docker to test this out, the next update will also have this fix included. Thanks for the bug report!

**Comment by CountParadox** [comment]
91porn.com actually isnt working I just tried it again :(
