### ISSUE TITLE
[BUG]about YouTubeDL-Material can't find file

### ISSUE THREAD

**Issue by natsuki012** [Tzahi12345/YoutubeDL-Material#930]
I installed YouTubeDL-Material on my 720+ NAS using Docker. After downloading videos, I cannot see the downloaded files in the NAS folder. What should I do?

**Comment by Tzahi12345** [comment]
Can you provide more details?

* Are the videos playable?
* Are you using multi-user mode? If so check in the `users` directory

**Comment by natsuki012** [comment]
Can you provide more details?

Are the videos playable?
### 
YES on web can playble

Are you using multi-user mode? If so check in the users directory
### 
i use admin also can't find download file on my disk

**Comment by Tzahi12345** [comment]
If you're using Docker, it should be in the volumes that it auto generates. It will be in the `users/admin/video` folder

**Comment by natsuki012** [comment]
Thank you
1. then if I need to update the version, do I have to remove the whole DOCKER and reinstall it again?
2. Is it possible to add the option to change the download location in future updates?
Thank you for your reply!

**Comment by Tzahi12345** [comment]
I don't know your current setup, if you're not using Docker then it would be in the extracted zip you downloaded. Mind sharing some screenshots of how you installed? It's still a bit unclear to me

It also is possible to change the location of videos, it's in the settings and not something I've tested in a bit but it sounds like you just can't find the folder in the file system. If you can view the videos you downloaded, they are there, it's just a matter of figuring out where if that makes sense

**Comment by by275** [comment]
I also have a similar issue with following log lines:

```log
Error: ENOENT: no such file or directory, stat 'users/admin/video/REDACTED_FILENAME.mp4'
    at Object.statSync (node:fs:1538:3)
    at Object.statSync (/app/node_modules/graceful-fs/polyfills.js:308:16)
    at generateFileObject (/app/files.js:66:22)
    at Object.exports.registerFileDB (/app/files.js:12:37)
    at /app/downloader.js:389:54
    at done (/app/node_modules/youtube-dl/lib/youtube-dl.js:25:12)
    at /app/node_modules/youtube-dl/node_modules/universalify/index.js:23:46
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'users/admin/video/REDACTED_FILENAME.mp4'
}
```

It might be a permission issue but I am not sure and don't know how to solve it. Any thoughts?

**Comment by Tzahi12345** [comment]
@by275 what version are you on? There were some permissions issues with v4.3.1 that were resolved with v4.3.2

**Comment by by275** [comment]
I am using v4.3.2. It was okay with v4.3.1.

**Comment by Tzahi12345** [comment]
If you look in the directory does the file exist? Are there any fragments or ones other than the mp4 extension?

Also wondering if this happens with all videos or just some

**Comment by natsuki012** [comment]
> 我不知道您當前的設置，如果您不使用 Docker，那麼它將位於您下載的解壓 zip 中。介意分享一些您如何安裝的屏幕截圖嗎？我還是有點不清楚
> 
> 也可以更改視頻的位置，它在設置中，而不是我測試過的東西，但聽起來你只是無法在文件系統中找到該文件夾。如果你可以查看你下載的視頻，它們就在那裡，只是找出哪裡有意義的問題

Thank you
I have successfully completed the setup
I think the file is missing because I didn't specify the shared volume.

**Comment by Tzahi12345** [comment]
Gotcha yeah that's needed, they're supposed to be created by default but that depends on your docker-compose file. I'll go ahead and close the issue

**Comment by by275** [comment]
Just want to share how I resolve the problem.

I was using my own docker build but incomplete ffmpeg binary was installed causing `No such file` error for yt-dlp to merge downloaded video+audio. It would be safer if you could add an option `-f` to raise error in case of failure due to timed out.

https://github.com/Tzahi12345/YoutubeDL-Material/blob/d3cb957991bad5a5daa30c3b9b53f7662d44daca/docker-utils/ffmpeg-fetch.sh#L27

Thank you!
