### ISSUE TITLE
[BUG] Failed to start container when starting from Synology NAS

### ISSUE THREAD

**Issue by dogederp** [Tzahi12345/YoutubeDL-Material#943]
**Describe the bug**
I am not able to start a container using the latest image using the standard Docker service from synology. This is the error that's registered in the log file:

`Start container youtubedl-material failed: {"message":"OCI runtime create failed: container_linux.go:367: starting container process caused: exec: \"/app/entrypoint.sh\": stat /app/entrypoint.sh: no such file or directory: unknown"}.`

This is coming from a fresh download from Dockerhub. I have also tried running from a local Docker compose without success.
The weird thing is that when I download the image and start the container on Portainer, everything works. But this is not what I am looking for as I can't find a way to mount a volume from the NAS to the outputs (can't access /@docker/volumes without SSH). Am I doing something wrong or is this a bug?

**To Reproduce**
1. Go to 'register' in the synology docker tab and download the latest image (v4.3.2)
2. Once downloaded, start a new container and set these settings:

- Bridge for the network
- No changes for cpu and memory etc.
- Local port 8084, container port 17442
- Set volume to /docker/youtubedl-material
- Complete setup and start container

**Expected behavior**
The container should start normally.

**Environment**
- YoutubeDL-Material version 4.3.2
- Docker tag: latest

Thanks in advance for your time!

**Comment by judas1995** [comment]
U can try this
At least it's working for me.

Set volume like this

1.create one new folder and name youtubedl  in docker.( /volume1/docker/youtubedl )
2.and create some sub dir in youtubedl .(appdata, audio, subscriptions, users, video)
3.mapping storage it like this
![image](https://github.com/Tzahi12345/YoutubeDL-Material/assets/64163704/0ce99da4-58ac-4b1c-bdb0-b885a686204b)

**Comment by dogederp** [comment]
This works for me too! Thank you!
