### ISSUE TITLE
[BUG] Cannot use yt-dlp

### ISSUE THREAD

**Issue by MinaHany** [Tzahi12345/YoutubeDL-Material#945]
**Describe the bug**
Trying to download audio-only of [link ](https://www.youtube.com/watch?v=tn49-Ui4Cfc) while passing the custom args: `--parse-metadata "Paschal Canon: %(title)s"`.
I get an error message indicating that youtube-dl is being used instead of yt-dlp:

```
Error while retrieving info on video with URL https://www.youtube.com/watch?v=tn49-Ui4Cfc with the following message: Error: Command failed with exit code 2: node_modules/youtube-dl/bin/youtube-dl -o /out/%(album)s/%(title)s.%(ext)s --write-info-json --audio-quality 0 -x --audio-format mp3 --parse-metadata "Paschal Canon: %(title)s" --no-clean-info-json -j --dump-json http://www.youtube.com/watch?v=tn49-Ui4Cfc Usage: youtube-dl [OPTIONS] URL [URL...] youtube-dl: error: no such option: --parse-metadata "Paschal Canon: %(title)s"
```

I have triple checked that I have yt-dlp selected under Settings->Advanced, and I have restarted the docker container (and clicked on the Restart button in the settings) multiple times.

When I run the Task `Update yt-dlp` I get a notification saying `Task finished: Update youtube-dl`. It seems yt-dlp is indeed not being used for some reason.

**Environment (from About dialogue)**
Installed version: v4.3.2 -   You are up to date.
Installation type: docker
Docker tag: latest
Commit hash: 13a03a7
Build date: 2023-05-27

**Comment by sanyer** [comment]
I'm facing the same problem.
No matter what I do with docker-compose.yaml or settings file, ytdl-material still uses `node_modules/youtube-dl/bin/youtube-dl`

**Comment by morfismo** [comment]
another instance:

`Error while retrieving info on video with URL https://www.youtube.com/watch?v=x_E0zJU9hFY with the following message: Error: Command failed with exit code 2: node_modules/youtube-dl/bin/youtube-dl -o users/admin/video/%(title)s.mp4 --write-info-json -f bestvideo+bestaudio --merge-output-format mp4 --write-thumbnail --write-subs --write-auto-subs --sub-format srt --sub-lang en --no-clean-info-json -j --dump-json http://www.youtube.com/watch?v=x_E0zJU9hFY Usage: youtube-dl [OPTIONS] URL [URL...] youtube-dl: error: no such option: --sub-format srt `

the error it's becaouse youtube-dl has no such option. however on settings, it's clearly selecting "yt-dlp" as downloader. But it's using youtube-dl

**Comment by sanyer** [comment]
@morfismo yes, indeed, I found that out the hard way 😂 forgot to update here
