### ISSUE TITLE
Issue downloading via docker on Synology

### ISSUE THREAD

**Issue by soopercow** [Tzahi12345/YoutubeDL-Material#95]
My log is attached, I'm not 100% sure which error is the critical one

[Youtubedl-material.txt](https://github.com/Tzahi12345/YoutubeDL-Material/files/4659198/Youtubedl-material.txt)

**Comment by Tzahi12345** [comment]
[This issue](https://github.com/ytdl-org/youtube-dl/issues/7586#issuecomment-158613513) for youtube-dl is all I could find regarding that error. No solution is mentioned, but it seems to be a network problem. Can you try accessing youtube.com from where the server is hosted, maybe that video specifically?

**Comment by soopercow** [comment]
It's in docker on my NAS so it's a bit difficult, just knowing it's probably a network issue is good though I'll look into it. 

I couldn't find anything useful at all

**Comment by Tzahi12345** [comment]
You can potentially try pinging youtube.com if you get to the NAS's console

**Comment by tghdev** [comment]
> It's in docker on my NAS so it's a bit difficult, just knowing it's probably a network issue is good though I'll look into it. 
> I couldn't find anything useful at all

I guess you have blocked the docker network subnet in your Synology firewall settings. Add a new rule to allow your docker subnet (e.g. 172.17.0.0 - 255.255.255.0) at the very beginning of all rules.

**Comment by GlassedSilver** [comment]
I highly sus this will be solved by #574.

Issue will be tracked there from now on, if the issue does persist once v4.4 releases, don't hesitate to raise your hand and I'll reopen the issue! :)

**Comment by Tanjohnson99** [comment]
Hi, Issue persist on 4.3. Don0t know how to solve the issue of Download Fail.
