### ISSUE TITLE
which records need to be edited to switch subscriptions from one user to another?

### ISSUE THREAD

**Issue by mintknife** [Tzahi12345/YoutubeDL-Material#950]
I have enabled multi-user, but I can't change the subscriptions of the original user to the new user. In the subscriptions table, I changed the user_uid field with the name of the new user, now I see the subscriptions in the menu, but I can't see the videos in the interface. How can I do it?

**Comment by Tzahi12345** [comment]
The videos themselves for the subs would need to be for that sub. What you could do is delete the subscriptions from the DB (dont unsubscribe!), transfer the subscription directories into the directory for the new user (i think its `users/subscriptions/channel`), then go into Tasks and click rebuild database. It will find the sub and the videos and reimport them.

Let me know if you need any help doing this

**Comment by mintknife** [comment]
Thank you for your support, I will close this issue 👍
