### ISSUE TITLE
[BUG] Interface not working correctly behind reverse proxy

### ISSUE THREAD

**Issue by AndreaPro** [Tzahi12345/YoutubeDL-Material#983]
Hello, in the about section of my Youtube-DL-Material webpage I have the following info:

Installed version: v4.3.2 -   You are up to date.
Installation type: docker
Docker tag: nightly
Commit hash: 99c5cf5
Build date: 2023-08-01

If I access the web address of the container locally it works fine, if I try to access it through a reverse proxy it fails to load the webpage and it throws only html code that you can see [here](https://pastebin.com/WcN9E6Zj): 
I am using Linuxserver swag as proxy and [these are my settings](https://pastebin.com/281xALeV)
Any ideas?

**Comment by D34DC3N73R** [comment]
it's not the best practice, but you can set 
`X-Content-Type-Options: none`
and the page will render. This project seems to have a problem with `X-Content-Type-Options: nosniff`
