### ISSUE TITLE
Problem with some special characters ?

### ISSUE THREAD

**Issue by CountParadox** [Tzahi12345/YoutubeDL-Material#99]
Another one for you!

It appears some videos fail to download, potentially due to special characters in the title. 

See screenshot

![Screenshot_20200523-164540_Chrome](https://user-images.githubusercontent.com/6279380/82723881-10cd8580-9d15-11ea-879f-5d60f618f091.jpg)

Also seen is an unrelated issue

**Comment by Tzahi12345** [comment]
Interesting, can you go into your settings and add this to your global args: `--restrict-filenames`. Basically, this will limit the file name of your downloads to just ASCII characters. Let me know if this helps!

**Comment by CountParadox** [comment]
@Tzahi12345 works after adding that !
it stripped ALL the kanji from the filename haha

**Comment by Tzahi12345** [comment]
Awesome, good to hear. Closing issue.
