### ISSUE TITLE
[FEATURE] Add the ability to 'check now' the subscriptions

### ISSUE THREAD

**Issue by mintknife** [Tzahi12345/YoutubeDL-Material#990]
**Is your feature request related to a problem? Please describe.**
Sometimes is useful to have the ability to check if there are new videos in a subscription manually. The only option looks to be to decrease the seconds in _main -> Check interval._ .

**Describe the solution you'd like**
I'd like to have a button, on the channel page, that checks for new video and start downloading it right away

**Comment by sky4055** [comment]
I vote for this much-needed improvement!

**Comment by Tzahi12345** [comment]
It's added now with #956!
